### ISSUE TITLE
serviceAddress is not retained or displayed after using the Universal Dataplane Wizard

### ISSUE THREAD

**Issue by bloqhead** [kumahq/kuma#1002]
### Summary

When using the Universal Dataplane Wizard in the GUI, `networking.inbound.serviceAddress` is not retained and does not appear anywhere when fetching dataplanes from the API either via `kumactl get dataplanes` or when viewing the output in the GUI's Dataplanes view.

### Steps To Reproduce

~~**Make sure to run the GUI externally from [this PR](https://github.com/kumahq/kuma-gui/pull/63) on the GUI repository. This PR includes the addition of `serviceAddress` as well as some other fixes and improvements to the wizards.**~~

_Edit:_ The above PR is now merged and you can run the GUI from its [master](https://github.com/kumahq/kuma-gui/) branch.

1. Run Kuma in Universal mode (macOS)
2. Create a Dataplane with the GUI's Dataplane Wizard and make sure to enter a `serviceAddress` (or leave it as is since it defaults to 127.0.0.1)
3. After creating it, fetch the DP with something like `kumactl get dataplanes -o yaml`
4. Compare the output to the command the GUI generates and see that `servicePort` is present but not `serviceAddress`

### Additional Details & Logs

- Kuma version 0.7.1-15-g5343876f
- Universal running on macOS

I'm using the [Dataplane Specification section](https://kuma.io/docs/0.7.1/documentation/dps-and-data-model/#dataplane-specification) from the documentation as a reference point.

**Here is a command generated by the GUI that runs successfully and creates the Dataplane:**

```sh
echo "type: Dataplane
mesh: default
name: test-service-l32yus
networking: 
  address: 192.168.0.2
  inbound: 
    - port: 1234
      servicePort: 5678
      serviceAddress: 192.168.0.1
      tags: 
        kuma.io/service: test-service
        kuma.io/protocol: tcp" | kumactl apply -f -
```

**And here is the output from `kumactl` afterwards:**

```yaml
type: Dataplane
mesh: default
name: test-service-l32yus
networking: 
  address: 192.168.0.2
  inbound: 
    - port: 1234
      servicePort: 5678
      tags: 
        kuma.io/protocol: tcp
        kuma.io/service: test-service
```
