### ISSUE TITLE
re-encryption of traffic between envoy and the application

### ISSUE THREAD

**Issue by sudeeptoroy** [kumahq/kuma#1006]
In universal mode where envoy is sitting next to the application, the traffic between envoy and the application are not encrypted. In cases where the data in flight has to be strictly encrypted this pattern is not usable. For such scenario, data can be re-encrypted. Thus the ask is to support re-encryption between envoy and the application so that data in flight is always encrypted.

**Comment by jakubdyszkiewicz** [comment]
Hey, the usual pattern is that you bind your application to `127.0.0.1` therefore it cannot be accessible to the outside. The scope of trust is your VM. 

What vector of attack are you worried about? Someone ssh into your VM and do a TCP dump of requests between Envoy and app? Even if we encrypt the traffic, the attacker with root access (which is required to do TCP dump) can mess around with Envoy config to not encrypt the traffic 

Thanks!

**Comment by sudeeptoroy** [comment]
Hi @jakubdyszkiewicz , thanks for your quick reply. 
In an enterprise every components are bound by certain governing rules. Lets say the tomcat is configured only to accept https traffic by policy. In that case http between the application and envoy will not the workable even though we consider the VM to be trusted. 
There are other cases where a VM may be hosting multiple applications. Newer kernel supports multiple application listening on the same port. Kubernetes makes these constrains super easy but on universal we have challenges.

**Comment by jakubdyszkiewicz** [comment]
One of the strong points of introducing Service Mesh is that offload TLS implementations from your apps to a sidecar and you have a consistent way of dealing with secure connections across all microservices.

With that in mind, I see your point. What certificates would you expect to see being used in Tomcat's HTTPS server? What component would generate those certificates and how the validation would look like?

> There are other cases where a VM may be hosting multiple applications

In such case I would lean towards using network namespaces (#336 related issue).

**Comment by sudeeptoroy** [comment]
> One of the strong points of introducing Service Mesh is that offload TLS implementations from your apps to a sidecar and you have a consistent way of dealing with secure connections across all microservices.

I agree with you, Thanks for your consideration.

>With that in mind, I see your point. What certificates would you expect to see being used in Tomcat's HTTPS server? What component would generate those certificates and how the validation would look like?

envoy is capable of upgrading the connection and it does not verify server cert. Can you enable upgrading the connection to the https backend via annotation on dataplane configuration. 
For reference please have a look at the following annotation used by contour in k8s: **_projectcontour.io/upstream-protocol.{protocol}_**
https://github.com/projectcontour/contour/blob/2e80af0f34bf674ac488e0d05ce4c3128c09bd23/site/docs/v1.7.0/annotations.md#contour-specific-service-annotations

**Comment by jakubdyszkiewicz** [comment]
It's definitely something that we could do, but right now we don't have time to do it.

Would you have time to contribute? :)

**Comment by sudeeptoroy** [comment]
Sure, should this be a special tag or an annotation on the outbound interface definition of the Data plane.

**Comment by jakubdyszkiewicz** [comment]
Let's figure out what additional envoy config is required for this to work and then think how to expose it to users.

**Comment by sudeeptoroy** [comment]
I think it will be inbound interface and not outbound.

can it be done via proxy template definition?
What is the naming convention of the cluster name used for programming envoy? we can patch it with this configuration for testing. 

```
  clusters:
  - name: <cluster name>
    connect_timeout: 0.25s
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: <cluster name>
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: localhost
                port_value: <inbound servicePort >
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
        sni: localhost
```

**Comment by jakubdyszkiewicz** [comment]
Yeah, you can absolutely try it with proxy template modification. Try this
```
type: ProxyTemplate
mesh: default
name: custom-template-1
selectors:
  - match:
      kuma.io/service: "*"
conf:
  imports:
    - default-proxy
  modifications:
    - cluster:
        operation: patch
        match:
          origin: inbound
        value: |
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.api.v2.auth.UpstreamTlsContext
              sni: localhost
```
this way you can patch all inbound listeners with transport socket of TLS
