### ISSUE TITLE
Otel Metrics Not Received

### ISSUE THREAD

**Issue by stephen-galea-weavr** [kumahq/kuma#10070]
### What happened?

I am using Grafana Agent as an otel collector and is working for other otel sources. However when I set a MeshMetric based on (https://kuma.io/docs/2.7.x/guides/otel-metrics/) I am not receiving any metrics. 

This is my config:

```

apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
  name: otel-metrics
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Mesh
  default:
    # sidecar:
    #   profiles:
    #     appendProfiles:
    #     - name: None
    #     include:
    #     - type: Regex
    #       match: envoy_cluster_external_upstream_rq_.*
    backends:
      - type: OpenTelemetry
        openTelemetry:
          endpoint: grafana-agent-alloy.grafana.svc:4317
``` 

I can also confirm that the sidecar is being configured to send metrics 
```
2024-04-24T15:52:48.293Z	INFO	mesh-metric-config-fetcher	Starting OpenTelemetry exporter	{"backend": "grafana-agent-alloy.grafana.svc-4317"}
```
