### ISSUE TITLE
Kuma control plane pod crashed

### ISSUE THREAD

**Issue by Icarus9913** [kumahq/kuma#10072]
### What happened?

I followed the Kuma documentation to get a try with builtin gateway feature but found the kuma-control-plane pod crashed.

Reproduce steps:
1. follow the quickstart to deploy kuma on k8s(k3d)
https://kuma.io/docs/2.7.x/quickstart/kubernetes-demo/
2. create MeshGatewayInstance (https://kuma.io/docs/2.7.x/using-mesh/managing-ingress-traffic/builtin/)
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: edge-gateway
  namespace: default
spec:
  replicas: 1
  serviceType: LoadBalancer
```
3. create MeshGateway (https://kuma.io/docs/2.7.x/using-mesh/managing-ingress-traffic/builtin-listeners/)
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
mesh: default
metadata:
  name: edge-gateway
spec:
  selectors:
    - match:
        kuma.io/service: edge-gateway_default_svc
  conf:
    listeners:
      - port: 8080
        protocol: HTTP
        tags:
          port: http/8080
```
4. Delete the MeshGateway
```sh
kubectl delete MeshGateway edge-gateway
```

After deleting the `MeshGateway`, the `Kuma-control-plane` pod crashed:
```text
2024-04-25T02:29:33.144Z	INFO	intercp.catalog.writer	replacing a leader in the catalog
2024-04-25T02:29:33.251Z	INFO	controllers.Service	annotating service which is part of the mesh	{"service": {"name":"demo-app","namespace":"kuma-demo"}, "annotation": "ingress.kubernetes.io/service-upstream=true"}
2024-04-25T02:29:33.252Z	INFO	kube-manager	Starting workers	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "worker count": 10}
2024-04-25T02:29:33.256Z	INFO	kube-manager	Observed a panic in reconciler: assignment to entry in nil map	{"controller": "pod", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"edge-gateway-75778f5c87-wbjsd","namespace":"default"}, "namespace": "default", "name": "edge-gateway-75778f5c87-wbjsd", "reconcileID": "8f4f428d-747b-420d-bd45-71b442f50995"}
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 1579 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:116 +0x1a4
panic({0x24efea0?, 0x3138320?})
	runtime/panic.go:914 +0x218
github.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers.(*PodConverter).BuiltinGatewayDataplane(...)
	github.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers/gateway_converter.go:88
github.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers.(*PodReconciler).createorUpdateBuiltinGatewayDataplane(0x4000c23d40, {0x318f228, 0x400176a210}, 0x4001da1b00, 0x4001f86b68?)
	github.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers/gateway_converter.go:47 +0x174
github.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers.(*PodReconciler).reconcileBuiltinGatewayDataplane(0x4000c23d40, {0x318f228, 0x400176a210}, 0x4001da1b00, {{0x3194be8?, 0x400176a240?}, 0x0?})
	github.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers/pod_controller.go:180 +0x178
github.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers.(*PodReconciler).Reconcile(0x4000c23d40, {0x318f228, 0x400176a210}, {{{0x400105e1d0, 0x7}, {0x400099f060, 0x1d}}})
	github.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers/pod_controller.go:90 +0x3a8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x3194be8?, {0x318f228?, 0x400176a210?}, {{{0x400105e1d0?, 0xb?}, {0x400099f060?, 0x0?}}})
	sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:119 +0x8c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x40002ecd20, {0x318f260, 0x4000bd5a90}, {0x26abd40?, 0x4000b07100?})
	sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:316 +0x2e8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x40002ecd20, {0x318f260, 0x4000bd5a90})
	sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:266 +0x16c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:227 +0x74
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 1470
	sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:223 +0x43c
```
