### ISSUE TITLE
MeshHttpRoute Not Being Applied

### ISSUE THREAD

**Issue by stephen-galea-weavr** [kumahq/kuma#10204]
### What happened?

I would like to mirror calls between two services using the MeshHttpRoute policy but it is not being applied. 

This is my sample config:

```apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: mirror-ehi
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshService
    name: backend-xx-caddy_qa_svc_5555
  to:
    - targetRef:
        kind: MeshService
        name: backend-yy_qa_svc_8281
      rules:
        - matches:
           - headers:
              - type: Exact
                name: mirror-this-request
                value: "true"
          default:
            filters:
              - type: RequestMirror
                requestMirror:
                  percentage: 100
                  backendRef:
                    kind: MeshService
                    name: pn-zzz_qa_svc_8000
            backendRefs:
              - kind: MeshService
                name: backend-yy_qa_svc_8281
```

I have even tried to apply a traffic split policy but again it seems to be ignored.

```
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: ehi-route
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshService
    name: backend-xxx-caddy_qa_svc_5555
  to:
    - targetRef:
        kind: MeshService
        name: backend-yyy_qa_svc_8281
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /ehi
          default:
            backendRefs:
              - kind: MeshService
                name: backend-yyy_qa_svc_8281
                weight: 50
              - kind: MeshService
                name: pn-zzzqa_svc_8000
                weight: 50
```

**Comment by stephen-galea-weavr** [comment]
It seems the mirror is now working, however I had to restart the control plane for it to apply correctly.

**Comment by jakubdyszkiewicz** [comment]
> Triage: do you applied this on Global CP with a multizone deployment or did you apply this on Zone CP?
>
> What is the version of Kuma?
> Thanks!

**Comment by stephen-galea-weavr** [comment]
Single Zone CP. I was running 2.7.1 and then updated to 2.7.2 which reset the CP of course and then started working.

**Comment by lukidzi** [comment]
Hi. I've tried reproducing it with Kuma 2.7.1, but it works for me. I did no restarts, I've checked the request and it works.

```
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: mirror-ehi
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshService
    name: frontend_kuma-demo_svc_8080
  to:
    - targetRef:
        kind: MeshService
        name: backend_kuma-demo_svc_3001
      rules:
        - matches:
           - headers:
              - type: Exact
                name: mirror-this-request
                value: "true"
          default:
            filters:
              - type: RequestMirror
                requestMirror:
                  percentage: 100
                  backendRef:
                    kind: MeshServiceSubset
                    name: backend_kuma-demo_svc_3001
                    tags:
                      version: v1
            backendRefs:
              - kind: MeshService
                name: backend_kuma-demo_svc_3001
```

Do you have maybe any logs from control-plane, sidecar or can you see that policy affects this dataplane in the GUI?
