### ISSUE TITLE
Add readOnlyRootFilesystem and seccompProfile security context attributes onto the injected "kuma-validation" container

### ISSUE THREAD

**Issue by jijiechen** [kumahq/kuma#10366]
### What happened?

The current "securityContext" on the injected "kuma-validation" container lacks of some commonly used attributes. 
This makes the injected pod to not run on certain restricted environments when the cluster limit the security context when running pods.

So let's add these:
```yaml
securityContext:
  runAsUser: 5678
  runAsGroup: 5678
  capabilities: 
    drop:
    - ALL

  # these are new to be introduced
  readOnlyRootFilesystem: true
  seccompProfile:
     type: RuntimeDefault
```
