### ISSUE TITLE
MeshTCPRoute is not working as expected

### ISSUE THREAD

**Issue by adarsh-padhi** [kumahq/kuma#10492]
### What happened?

Hii Team , 

I am trying to implement the new targetRef Policies from existing `traffic permission` & ` trafficroute` policies  in one demo applications where the traffic is directly reaching to the application from the standard nginx gateway using ingress.

When I am using the `MeshTCPRoute` , the policies is getting applied successfully but  I'm not able to connect to the application.

kuma version - **2.5.2**

Kindly help me to point out , what I'm missing here?

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTCPRoute
metadata:
  name: allow-nginx-to-demo-app1
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
   kind: MeshSubset
   tags:
      kuma.io/service: nginx-sm-ingress-nginx-controller_kuma-gateway_svc_80
      kuma.io/zone: mesh-northeurope-01
  to:
    - targetRef:
        kind: MeshService
        name: demo-app1_kuma-backend_svc_8080
      rules:
        - default:
            backendRefs:
              - kind: MeshServiceSubset
                name: demo-app1_kuma-backend_svc_8080
                tags:
                  kuma.io/zone: mesh-northeurope-01
```
