### ISSUE TITLE
MeshExternalService: cluster is marked as TCP when there are two endpoints.

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#10560]
### What happened?

e.g.

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshExternalService
metadata:
  name: mes-http
  namespace: kong-mesh-system
  labels:
    kuma.io/mesh: default
spec:
  match:
    type: HostnameGenerator
    port: 80
    protocol: http
  endpoints:
    - address: httpbin.org
      port: 80
    - address: 1.1.1.1
      port: 443
```
