### ISSUE TITLE
Gateway resource is not created in Global Control Plane

### ISSUE THREAD

**Issue by manju-rn** [kumahq/kuma#10736]
### What happened?

Looks like the Gateway resource is not created in Global Control plane. This would be valid requirement, since Global-control plane service is ClusterIP and making it LoadBalancer and opening the firewall port for 5681 to access the GUI may not be possible. Hence, why not allow the Gateway resource to be created have http route defined to access the Global CP GUI

1.Installed the Kuma Global Control plane
```
kumactl install control-plane \
  --set "controlPlane.mode=global" \
  | kubectl apply -f -
```
2. Created this manifest
```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kuma
spec:
  controllerName: gateways.kuma.io/controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kuma-gl-gateway
  namespace: kuma-system
spec:
  gatewayClassName: kuma
  listeners:
  - name: proxy
    port: 80
    protocol: HTTP
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:  # This needs to be specified so that the Routes in different namespaces can be attached to this gateway
        from: Selector
        selector:
          matchLabels:
            gateway-access: "true"
```
4. The pods and gateway status. No gateway pod and gateway Programmed status is Unknown
```
manju@gk:~$ k get pods -A
NAMESPACE     NAME                                     READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-77bd7c5b-bvbx7   1/1     Running   0          5m2s
kube-system   calico-node-6pgkk                        1/1     Running   0          5m2s
kube-system   coredns-864597b5fd-4q5zf                 1/1     Running   0          5m2s
kuma-system   kuma-control-plane-665ddd5685-h7m7g      1/1     Running   0          3m23s
manju@gk:~$ k get gateway -A
NAMESPACE     NAME              CLASS   ADDRESS   PROGRAMMED   AGE
kuma-system   kuma-gl-gateway   kuma              Unknown      2m34s
```
