### ISSUE TITLE
Is there a way to avoid using the port 80 when calling the mesh services?

### ISSUE THREAD

**Issue by manju-rn** [kumahq/kuma#10741]
### What happened?

I have a multizone setup and is working properly
1. I have this DB hosted in a Zone2 - appears as `jp-pg-svc_db-ns_svc_5432.mesh:80` in the Kuma UI
2. I also have 2 UI for DB - adminer and pgadmin in Zone1
 - In pgadmin  -  there is no issue when I give db host name as `jp-pg-svc_db-ns_svc_5432.mesh:80` it connects fine
 - In adminer - there is a restriction on using port 80 (as it considers it priviedge port), hence `jp-pg-svc_db-ns_svc_5432.mesh:80` fails - see snapshot.  
Q1:  So is there a way for Mesh service to have other port and not 80 by default?
Q2:  Is there an alternative where I could create a dummy service (similar to how istio allows it)  in Zone1 and have it redirect to  `jp-pg-svc_db-ns_svc_5432.mesh:80` which is in Zone1.  So that in adminer UI, i could give this service name instead of `...mesh:80` ?

Snapshot from adminer
![image](https://github.com/kumahq/kuma/assets/26291847/298f74a5-c426-453b-aef9-fa3a29801701)
 
Kuma UI
![image](https://github.com/kumahq/kuma/assets/26291847/c434f65f-bd0a-4c1e-8fc3-b621d2a53ca8)

**Comment by lahabana** [comment]
Hey!

3 ways to go around this:

1. The old way [virtual-outbound](https://kuma.io/docs/2.8.x/policies/virtual-outbound/)
2. An ok workaround for you: set the env var `KUMA_DNS_SERVICE_SERVICE_VIP_PORT` to another non privilege port (like 8080) and then you'll be able to use 8080 instead of 80 everywhere
3. The new way (still beta) [meshservice and hostname generator](https://kuma.io/docs/2.8.x/networking/meshservice/)

**Comment by manju-rn** [comment]
> 3\. The new way (still beta) [meshservice and hostname generator](https://kuma.io/docs/2.8.x/networking/meshservice/)
Thanks, I was trying the 3rd way, i gave the following 
```
apiVersion: kuma.io/v1alpha1
kind: MeshService
metadata:
  name: pg-jp-svc
  namespace: db-ns
  labels:
    kuma.io/mesh: mesh2
spec:
  selector:
    dataplaneTags:
      app: jp-pg
      k8s.kuma.io/namespace: db-ns
  ports:
  - port: 5432
    targetPort: 5432
    appProtocol: tcp
```

```
apiVersion: kuma.io/v1alpha1
kind: HostnameGenerator
metadata:
  name: all
  namespace: kuma-system
  labels:
    kuma.io/mesh: mesh2
    kuma.io/origin: zone
spec:
  selector:
    meshService:
      matchLabels:
        k8s.kuma.io/namespace: db-ns
  template: "{{ .DisplayName }}.{{ .Namespace }}.mesh"
```

In Kuma GUI, I have the following 
![image](https://github.com/kumahq/kuma/assets/26291847/46f096e7-397d-4aa8-97f6-e8aba4398ce5)

But when I try using the adminer (or pgadmin). It is not able connect
![image](https://github.com/kumahq/kuma/assets/26291847/e88c5da1-555a-480f-887d-8af26994f710)

Note that the "normal" k8s service is still existing and hence pgadmin is still able to connect via `jp-pg-svc_db-ns_svc_5432.mesh:80`. Both this as well as the above MeshService should be pointing to same dataplane proxies, is it not?
![image](https://github.com/kumahq/kuma/assets/26291847/68b3eca1-36e9-4d41-abc7-285463b98951)
