### ISSUE TITLE
Do not require a hostname to generate outbound for MeshExternalService

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#10877]
### What happened?

In a case where you have a MeshEexternalService that you only want to expose via Mesh*Route. You don’t need a hostname.

Edit: check the situation for MeshService

**Comment by lukidzi** [comment]
> Let's make it not required

**Comment by lobkovilya** [comment]
In case users do a "redirect", i.e.
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: http-split
  namespace: kuma-demo
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshSubset
    tags:
      app: frontend
  to:
  - targetRef:
      kind: MeshService
      name: backend
      namespace: kuma-demo
      sectionName: http
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: "/"
      default:
        backendRefs:
        - kind: MeshService
          name: backend-v1
          namespace: kuma-demo
          port: 3001
          weight: 90
        - kind: MeshExternalService
          name: mes-1
          weight: 10
```
we don't need to generate hostnames for `backend-v1` and `backend-v2`.
