### ISSUE TITLE
`kuma.io/transparent-proxying-ip-family-mode` not applied on a per-pod basis

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#10903]
### What happened?

I observed today that when specifying `kuma.io/transparent-proxying-ip-family-mode` annotation on a per-pod basis, it doesn't work as expected

### Steps to Reproduce

1. Install `kuma` and some demo workloads:
    ```sh
    kumactl install control-plane | kubectl apply -f-
    kumactl install demo | kubectl apply -f-
    ```
   
2. Add the following annotation to a workload:
    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    # ...
    spec:
      template:
        metadata:
          annotations:
            kuma.io/transparent-proxying-ip-family-mode: ipv4
    ```

3. Observe the resulting pod's annotations:
    ```yaml
    apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        kuma.io/transparent-proxying-ip-family-mode: dualstack
    # ...
    ```

### Additional Observations

When setting the global environment variable for the control plane:
```sh
kumactl install control-plane --set controlPlane.envVars.KUMA_RUNTIME_KUBERNETES_INJECTOR_SIDECAR_CONTAINER_IP_FAMILY_MODE=ipv4 | kubectl apply -f-
```
the value changes as expected.
