### ISSUE TITLE
MeshFaultInjection validation error message should be more specific

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#10907]
### Description

```
apiVersion: kuma.io/v1alpha1
kind: MeshFaultInjection
metadata:
  name: default
  namespace: kong-mesh-system
  labels:
    kuma.io/mesh: default # optional, defaults to `default` if it isn't configured
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: MeshService
        name: httpbin
      default:
        http:
          - abort:
              httpStatus: 500
              percentage: 50
```

```
kubectl apply -f mfi.yaml
The MeshFaultInjection "default" is invalid: spec.from: must not be defined
```

the core question here is: why?

the answer is in the code: https://github.com/kumahq/kuma/blob/cf056262652a58535baedceeb91f2409d826ecbd/pkg/plugins/policies/meshfaultinjection/api/v1alpha1/validator.go#L48 it also targets gateways but just from the error code we don't know :(
