### ISSUE TITLE
Improve kuma-dp probe

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#11034]
### Description

Kuma DP probe is on `<POD-IP>:9901/ready` which is listener that we generate. For plaintext traffic it responds only on ready. The request is passed to Envoy Admin. Envoy Admin is executed in the same `main_thread` as xDS processing. When we generate many xDS changes, `main_thread` may not respond on the probe even though Envoy is fine.

Of the solution is to change the probe to give static response. Here is a MeshProxyPatch
```
apiVersion: kuma.io/v1alpha1
kind: MeshProxyPatch
metadata:
  name: admin-static-response
  namespace: kuma-system
spec:
  targetRef:
    kind: Mesh
  default:
    appendModifications:
      - listener:
          operation: Patch
          match:
            name: "kuma:envoy:admin"
          jsonPatches:
            - op: remove
              path: /filterChains/0/filters/0/typedConfig/routeConfig/virtualHosts/0/routes/0/route
            - op: add
              path: /filterChains/0/filters/0/typedConfig/routeConfig/virtualHosts/0/routes/0/direct_response
              value: {"status": 200, "body": {"inline_string": "LIVE"}}
```

Envoy will receive this listener only when it successfully connects to the CP and receives config. Additionally, we can change the cluster to EDS so that we will only make it healthy when we actually receive LDS/CDS/EDS.
The response for `/ready` endpoint is then handled on the worker threads.

It seems ok to always respond with LIVE. When Pod is terminating, we remove the endpoint from all the clients.

Things to check
1) Currently, when kuma-dp receives SIGSTOP it goes into DRAINING state. Check what HC responds in this scenario. We might need to handle it with stats probe so that outside of Kubernetes, the scheduler can also immediately remove endpoint by checking HC.
2) Check when other values can occur. It's hot restart which we don't support, but is there anything else?
