### ISSUE TITLE
Design `from` policies with `spec.targetRef` selecting whole proxies

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#11078]
### Description

From [MADR](https://github.com/kumahq/kuma/pull/10858/files#diff-95c559a0f6155d986d45f294106f1a5a789e99bd0c0c93dae4405724efc76f3cR11-R13): 

> We want to iterate over policy design and move `Mesh*Route` to `spec.to[].targetRef` section follow model where `spec.targetRef`
selects whole proxies

From slack (focusing on `2`):

> 1. we've just rewrote `to` policies to make it so that we always ID a set of proxies. Putting MES in top level reverts this. Which is playing wack a mole
> 2. There's a more general problem with from policies with top level targetRef. Because atm it uses top level mesh service which is: a) against what is said in (1) b) what happens when a proxy port is backed by 2 services?

example that breaks this rule now: https://github.com/kumahq/kuma/blob/871dc55592952583a3aea7acd75bafa3af5ba3e4/test/e2e_env/kubernetes/meshtrafficpermission/api.go#L44-L71

example for `what happens when a proxy port is backed by 2 services?`:

Is it - having 2 MS:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshService
metadata:
  name: redis-1
spec:
  selector:
    dataplaneTags:
      app: redis
  ports:
  - port: 6739
    targetPort: 6739
    appProtocol: tcp
```

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshService
metadata:
  name: redis-2
spec:
  selector:
    dataplaneTags:
      app: redis
      version: v1
  ports:
  - port: 6739
    targetPort: 6739
    appProtocol: tcp
```

`redis-2` is a subset of `redis-1` and creating a MTP like this:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: allow-redis-1
spec:
  targetRef:
    kind: MeshService
    name: redis-1
  from:
    - targetRef:
        kind: Mesh
      default: # 3
        action: Allow
```

would allow `redis-2` as well and we don't want that.
