### ISSUE TITLE
unknown namespace for the cache error while working with some namespaces

### ISSUE THREAD

**Issue by mhkarimi1383** [kumahq/kuma#11085]
### What happened?

When I want to work with `cert-manager` namespace I'm getting
```
failed to upgrade cert-manager@cert-manager: admission webhook "secret.validator.kuma-admission.kuma.io" denied the request: unable to get: cert-manager/sh.helm.release.v1.cert-manager.v1 because of unknown namespace for the cache
```

**Comment by mhkarimi1383** [comment]
ReInstalling Kuma fixes the problem, But why?

**Comment by slonka** [comment]
> triage: please post steps to reproduce this issue

**Comment by mhkarimi1383** [comment]
@slonka 
I will provide my configurations but this problem happens by chance :(

**Comment by mhkarimi1383** [comment]
Here is my Helm values:

```yaml
cni:
  enabled: true
  chained: true
  logLevel: debug
  netDir: /etc/cni/net.d
  binDir: /opt/cni/bin
  confName: 05-cilium.conflist

egress:
  enabled: true
ingress:
  enabled: true
  service:
    type: NodePort ## Route It on FW if needed.
controlPlane:
  zone: example-01
  mode: zone
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5

    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
  ## TODO: Enable this when we have Kong available ;)
  ingress:
    enabled: false
    ingressClassName: kong
    hostname: ""
    annotations: {}
  globalZoneSyncService:
    type: NodePort ## Route It on FW if needed.
kubectl:
  image:
    tag: 1.29.5 ## NOTE: Same as K8s version.
experimental:
  ebpf:
    enabled: false # NOTE: https://github.com/kumahq/kuma/issues/9846
```

After reinstalling Kuma I got the same error After a while

**Comment by mhkarimi1383** [comment]
Also here is my `cert-manager` namespace manifest

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    kuma.io/system-namespace: "true"
```
