### ISSUE TITLE
Support for ServiceMap with Deligated GW

### ISSUE THREAD

**Issue by mhkarimi1383** [kumahq/kuma#11088]
### Description

I have setup Kuma with Kong in my cluster and It's working great But I set setup grafana I notice that the provided dashboard is empty since they are working with envoy specific metrics

**Comment by slonka** [comment]
> triage: is that the Kong is not showing up in the Service Map or are you expecting something else to show up in the metrics?

**Comment by mhkarimi1383** [comment]
@slonka ServiceMap is empty

**Comment by lukidzi** [comment]
> Triage: Could you provide steps to reproduce? Also, could you post policies that you've applied?

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's check on our side. Just a simple deployment with MeshMetrics.

**Comment by slonka** [comment]
Could not reproduce with 2.8.3:

![image](https://github.com/user-attachments/assets/641e7ee7-82c8-4228-a74f-9ce804045f4b)

Steps:
1. Install kuma

```
kumactl install control-plane | kubectl apply -f -
```

2. Install observability 

```
kumactl install observability | kubectl apply -f -
```

3. Add traces and metrics:

```
echo 'apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
  name: metrics-default
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Mesh
  default:
    sidecar:
      includeUnused: true
      profiles:
        appendProfiles:
        - name: Basic
    backends:
    - type: Prometheus
      prometheus:
        port: 5670
        path: "/metrics"
' | kubectl apply -f -
```

```
apiVersion: kuma.io/v1alpha1
kind: MeshTrace
metadata:
  name: default
  namespace: kuma-system
  labels:
    kuma.io/mesh: default # optional, defaults to `default` if unset
spec:
  targetRef:
    kind: Mesh
  default:
    backends:
      - type: Zipkin
        zipkin:
          url: http://jaeger-collector.mesh-observability:9411/api/v2/spans
```
