### ISSUE TITLE
Kuma DP + Envoy version in Dataplane Insights

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#1112]
### Summary

We would like to collect info about Kuma DP + Envoy version and present it in the GUI. This information help us improve upgrade UX and other.

To do this, we need to collect this info and store in DataplaneInsights, so the steps are
1) Extend DataplaneInsight with a new field (this should be on DiscoverySubscription because one data plane of the same name can reconnect with a different Kuma DP / Envoy version)
```
message Version {
  message KumaDpVersion {
    string version = 1;
    string gitTag = 2;
    string gitCommit = 3;
    string buildDate = 4;
  }
  KumaDpVersion dpVersion = 1;

  message EnvoyVersion {
    string version = 1; // ex. 1.15.0
    string build = 2; // ex. 50ef0945fa2c5da4bff7627c3abf41fdd3b7cffd/1.15.0/clean-getenvoy-2aa564b-envoy/RELEASE/BoringSSL
  }
  EnvoyVersion envoy = 2;
}
```
2) Send this info in BootstrapRequest
To send envoy version you need to extract this via `envoy --version` and parse it.
3) Generate Bootstrap config that puts this information into metadata (pkg/bootstrap/template.go)
```
node:
  metadata:
    version:
      kumaDp:
        version:
        gitTag:
        gitCommit:
        buildDate:
      envoy:
        version:
        build:
```
4) Fill the info from `envoy.DiscoveryRequest` in `DataplaneStatusTracker`

5*) Given this info, we can now present version in `kumactl inspect dataplanes` or Kuma GUI.
