### ISSUE TITLE
MeshAccessLogs: Multiple lines of logs are consumed as single line by Dynatrace

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#11143]
### What happened?

Dynatrace requires `[timestamp] [logLevel] {json_data}` to correlate data as a single log. Because JSON format produced by `Envoy` is a full json string without these prefixes, logs are not properly indexed by Dynatrace. It would be nice to support this format or HTTP backend

```yaml
type: MeshAccessLog
name: accesslogs
mesh: default
spec:
 targetRef:
   kind: Mesh
 from:
   - targetRef:
       kind: Mesh
     default:
       backends:
         - type: File
           file:
             path: /dev/stdout
             format:
               type: Json
                 json:
                   - key: "start_time"
                      value: "%START_TIME%"
                   - key: "bytes_received"
                      value: "%BYTES_RECEIVED%"
```
