### ISSUE TITLE
MeshExternalService should aggregate different services into one

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#11221]
### Description

Let's say we have Redis instances in zone-a (K8s), zone-b (K8s), and zone-c (universal). If we want to aggregate all these Redis instances from different zones, we can't achieve this with the current MeshExternalService. Once added on global, specific MeshExternalService will work on k8s but not universal. Allowing users to aggregate many different MeshExternalServices into one would be nice.  

Use case:
* MeshLoadbalancingStrategy and fallback to a specific zone

```yaml
type: MeshExternalService
name: redis
mesh: default
spec:
  match:
    type: HostnameGenerator
    port: 6379
    protocol: tcp
  endpoints:
    - address: redis.db.svc.cluster.local
```

Ideas:
* MeshMultiZoneExternalService?
