### ISSUE TITLE
Unable to make MeshLoadBalancingStrategy & MeshMultiZoneService work with counter demo

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#11343]
### What happened?

We had a live testing session and we tried to apply the following resources:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshMultiZoneService
metadata:
  name: redis-mz
  namespace: kong-mesh-system
  labels:
    kuma.io/mesh: default
spec:
  ports:
  - port: 6379
    appProtocol: tcp
  selector:
    meshService:
      matchLabels:
        kuma.io/display-name: redis
        k8s.kuma.io/namespace: kuma-demo
---
kind: MeshLoadBalancingStrategy
apiVersion: kuma.io/v1alpha1
metadata:
  name: disable-la-to-redis
  namespace: kong-mesh-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: MeshMultiZoneService
        labels:
          kuma.io/display-name: redis-mz
      default:
        localityAwareness:
          disabled: true
```
to disable localityAware LB for redis, but it didn't work. The policy doesn't even show up in GUI in `DPP / Policies` view.
