### ISSUE TITLE
Non-federated zone CP doesn't add `kuma.io/zone` label on policies

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#11373]
### What happened?

Policy without `kuma.io/zone` label can't reference MeshService with `kuma.io/zone` label. 

1. Start zone CP
2. Create MeshService `backend`
3. Apply MeshHTTPRoute
    ```yaml
    type: MeshHTTPRoute
    name: mesh-service-route-1
    mesh: mesh-service
    labels:
      kuma.io/origin: zone # when this is missing we don't have kuma.io/zone
    spec:
      targetRef:
        kind: MeshSubset
        tags:
          kuma.io/service: demo-client
      to:
        - targetRef:
            kind: MeshService
            name: backend
            sectionName: "80" 
          rules:
            - matches:
              - path:
                  value: /instance1
                  type: PathPrefix
              default:
                backendRefs:
                  - kind: MeshService
                    name: backend
                    port: 80
            - matches:
              - path:
                  value: /instance2
                  type: PathPrefix
              default:
                backendRefs:
                  - kind: MeshService
                    name: backendsecond
                    port: 80
    ```
