### ISSUE TITLE
Incorrect validation for MeshExternalService in `to[].targetRef` 

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#11499]
### What happened?

Should work:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: timeout
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: MeshExternalService
      labels:
        kuma.io/display-name: echo-http
    default:
      http:
        requestTimeout: 29s
```
But it doesn't:
```
The MeshTimeout "timeout" is invalid:
* spec.to[0].targetRef.name: must be set with kind MeshExternalService
* spec.to[0].targetRef.labels: must not be set with kind MeshExternalService
```
