### ISSUE TITLE
Inspect API `/_rules` to include the list of outbounds

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#11500]
### Description

Kuma GUI needs to create cross links to MS, MES, MMZS even when there are no specific rules for them.

We need to include the list of outbounds, like:
```yaml
outbounds:
- name: demo-app-2955c88v9z48dww6.kuma-demo # core name
  envoy: default_demo-app_kuma-demo_west_msvc_5000
  resourceIdentifier:
    type: MeshService
    mesh: default
    displayName: demo-app
    namespace: kuma-demo
    zone: west
    sectionName: "5000"
```

and change `toResourceRules[].resourceMeta` to `resourceIdentifier`:

```yaml
toResourceRules:
  - conf: {...}
    origins: [...]
    resourceIdentifier:
      type: MeshService
      mesh: default
      displayName: demo-app
      namespace: kuma-demo
      zone: west
      sectionName: "5000"
```

Matching between item in `outbounds` and item in `toResourceRules` should be done by using the `resourceIdentifier`. 

The only place where we have name with hash is `outbounds[].name` and it only should be used for creating cross links (until Kuma API gets endpoints that accept `resourceIdentifier`).
