### ISSUE TITLE
`to[].targetRef: Mesh` doesn't work, even though it shows up in Inspect API

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#11512]
### What happened?

I noticed in the Inspect API we build `BaseMeshContext` and it contains its own `Mesh`. But the real `MeshContext` we build for proxy doesn't contain its own mesh (we exclude it):
https://github.com/kumahq/kuma/blob/17fe0560f9b09e4049dbef4a42cd2b6bfb8a124b/pkg/xds/context/mesh_context_builder.go#L116

New ResourceRule algo treats `kind: Mesh` as a real resource and tries to look it up in the MeshContext. If it doesn't find it, there will be no rule.

Repro:
1. Apply MeshTimeout:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: timeout-all
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: Mesh
    default:
      connectionTimeout: 29s
```
2. See the value "29s" is not present in the config dump
