### ISSUE TITLE
policy with MeshSubset detected as a producer policy

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#11570]
### What happened?

That's clearly a consumer policy for a workload running in the same namespace as the main app.

```yaml
type: MeshRetry
mesh: default
name: retry-demo-app-consumer-89bdbw75z9c4xz4d
labels:
  k8s.kuma.io/namespace: kuma-demo
  kuma.io/display-name: retry-demo-app-consumer
  kuma.io/env: kubernetes
  kuma.io/mesh: default
  kuma.io/origin: zone
  kuma.io/policy-role: producer
  kuma.io/zone: west
spec:
  targetRef:
    kind: MeshSubset
    tags:
      k8s.kuma.io/service-name: redis
  to:
    - targetRef:
        kind: MeshService
        name: demo-app
        sectionName: '5000'
      default:
        http:
          numRetries: 127
```

**Comment by lahabana** [comment]
Actual this is rightly a producer policy.

What makes a producer policy is:

```
  to:
    - targetRef:
        kind: MeshService
        name: demo-app
        sectionName: '5000'
```
and the fact that it's in the same namespace.

To convert this into a consumer policy I need to do:

```
kind: MeshRetry
apiVersion: kuma.io/v1alpha1
metadata:
  name: retry-demo-app-consumer-2
  namespace: kuma-demo
spec:
  targetRef:
    kind: MeshSubset
    tags:
      k8s.kuma.io/service-name: redis
  to:
    - targetRef:
        kind: MeshService
        labels:
          kuma.io/display-name: demo-app
      default:
        http:
          numRetries: 127
```
