### ISSUE TITLE
Introduce `HealthyPanicThreshold` for MeshCircuitBreaker policy

### ISSUE THREAD

**Issue by Icarus9913** [kumahq/kuma#11704]
### Description

I noticed that there's an implementation difference between our MeshCircuitBreaker and Istio's (https://github.com/istio/istio/blob/7b2d8b9dacb7989d75b3b3d860988cadb9f5a848/pilot/pkg/networking/core/cluster_traffic_policy.go#L416-L423), 
maybe we could add one flag to disable panic threshold and it depends on the user's choice.

**Comment by lahabana** [comment]
Would that be something like:

https://kuma.io/docs/dev/policies/meshcircuitbreaker/
```yaml
      outlierDetection:
        panicDisabled: true
        interval: 5s
        baseEjectionTime: 30s
        maxEjectionPercent: 20
        splitExternalAndLocalErrors: true
```

?

Also from looking at the docs I see no mention of panic, we should talk about it.

Is there any possible workaround to set configuration in a way that will avoid entering panic?
