### ISSUE TITLE
Using on invalid targetRef leads to a failure in the validation of the targetRef not in the validation of kind

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#11735]
### What happened?

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshExternalService
metadata:
  name: datadog-trace-on-km
spec:
  endpoints:
  - address: trace-svc.datadog-agent.svc.cluster.local
    port: 8126
  match:
    port: 8126
    protocol: http
    type: HostnameGenerator
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name:  datadog-trace-test
spec:
  targetRef:
    kind: MeshExternalService
    labels:
      app: datadog-trace
  from:
    - targetRef:
        kind: Mesh
      default:
        action: Allow
```

Returns:

```
The MeshTrafficPermission "datadog-trace-test" is invalid: spec.targetRef.name: must be set with kind MeshExternalService
```

The error should just be that `kind: MES` in not supported.

I don't know if it's an error specific to MTP or more general.
