### ISSUE TITLE
Traffic lost during CP upgrade from 2.8 to 2.9 preview

### ISSUE THREAD

**Issue by jijiechen** [kumahq/kuma#11787]
### What happened?

Traffic lost during a CP upgrading from `2.8.3` to `2.9.0-preview.vd05b010b1`.
No traffic is expected to be lost during this process.

### Reproduce steps

- Deploy a single zone Kuma using 2.8.3 helm chart
- Install [the counter demo app](https://github.com/kumahq/kuma-counter-demo)
- Create these resoures/policies:
  - MeshGatewayInstance with 3 replicas
  - MeshGateway
  - MeshHTTPRoute
- Open a browser, access the gateway endpoint, and enable "Auto Increment" on the demo page
- Upgrade CP to `2.9.0-preview.vd05b010b1` using `helm upgrade`
- Keep observing CP pod creation/termination
- Keep observing network traffic, I get error "Cannot connect to: demo-app"
- Open a new browser tab and access the gateway endpoint again, I can see a notice "This is a Kuma MeshGateway. No route match this MeshGateway"
- Keep observing network traffic, traffic recovers automatically after ~2 min. When open the gateway endpoint again, it shows the counter demo app correctly.

### Resources and policies

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: edge-gateway
  namespace: kuma-demo
spec:
  replicas: 3
  serviceType: LoadBalancer

---

apiVersion: kuma.io/v1alpha1
kind: MeshGateway
mesh: default
metadata:
  name: edge-gateway
spec:
  selectors:
    - match:
        kuma.io/service: edge-gateway_kuma-demo_svc
  conf:
    listeners:
      - port: 80
        protocol: HTTP
        tags:
          port: http_8080


---

apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: edge-gateway-route
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshGateway
    name: edge-gateway
    tags:
      port: http_8080
  to:
  - targetRef:
      kind: Mesh
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: "/"
      default:
        backendRefs:
        - kind: MeshService
          name: demo-app_kuma-demo_svc_5000

```

### Screenshot

<img width="291" alt="image" src="https://github.com/user-attachments/assets/f739edcb-d734-4618-b099-7b7802da723a">
