### ISSUE TITLE
Traffic not prioritized on the zone

### ISSUE THREAD

**Issue by qjoly** [kumahq/kuma#11966]
### What happened?

Hello :wave: 

I have just deployed 2 zones (respectively “home” and “cloud”). I want my services to always prioritize exchanges with applications in the same zone.

[This documentation](https://kuma.io/docs/2.9.x/policies/meshloadbalancingstrategy/#default-behaviour) tells me that this is supposed to be enabled by default.

> Locality-aware load balancing is enabled by default, unlike its predecessor [localityAwareLoadBalancing](https://kuma.io/docs/2.9.x/policies/locality-aware). Requests are distributed across all endpoints within the local zone first unless there are not enough healthy endpoints.

But I don't have this behavior. Requests are distributed in RoundRobin mode, regardless of zone.

![image](https://github.com/user-attachments/assets/53026e30-16bf-4100-8d79-5225d18a5a54)

(The point of view above comes from the front-app in the cloud zone)
![image](https://github.com/user-attachments/assets/bcc5d371-1192-4793-922f-acd5597bbc80)

I haven't configured meshloadbalancingstrategy and mTLS is enabled, have I done something wrong? 

Thank you in advance :pray:

**Comment by bartsmykla** [comment]
> triage: it's probably not clear from the docs, but for this behavior to happen `MeshLoadBalancingStrategy` needs to exist, so you should apply something like
```
apiVersion: kuma.io/v1alpha1
kind: MeshLoadBalancingStrategy
metadata:
  name: name
spec:
  to:
  - targetRef:
      kind: Mesh
    default:
      localityAwareness: {}
```
