### ISSUE TITLE
[injector] Regression: `spec.initContainers[0].name: Required value`

### ISSUE THREAD

**Issue by voidlily** [kumahq/kuma#11993]
### What happened?

```
Warning  FailedCreate     77s                replicaset-controller  Error creating: Pod "lrtest-dashboard-6bbf859f6-p4ltc" is invalid: [spec.initContainers[0].name: Required value, spec.initContainers[0].image: Required value]
```

I don't know exactly why this is happening yet, but it started happening to me in 2.9.0. Previously I was on 2.8.3 where I was not having issues with sidecar injection. This seems to happen to me regardless if I use injection labels on the namespace, or the Deployment.

kuma values.yaml

```yaml
dataPlane:
  dnsLogging: true
controlPlane:
  autoscaling:
    enabled: true
    minReplicas: 2
  resources:
    requests:
       cpu: 200m
       memory: 512Mi
    limits:
       memory: 512Mi
  tolerations:
    - key: ondemand
      operator: Equal
      value: "true"
      effect: NoSchedule
  egress:
    enabled: true
  envVars:
    KUMA_RUNTIME_KUBERNETES_INJECTOR_IGNORED_SERVICE_SELECTOR_LABELS: rollouts-pod-template-hash
    KUMA_RUNTIME_KUBERNETES_SKIP_MESH_OWNER_REFERENCE: true
    # for kuma CNI, because eks disables ipv6 by default
    KUMA_RUNTIME_KUBERNETES_INJECTOR_SIDECAR_CONTAINER_IP_FAMILY_MODE: ipv4
    KUMA_RUNTIME_KUBERNETES_INJECTOR_CONTAINER_PATCHES: dp-resources

# https://kuma.io/docs/2.8.x/production/dp-config/cni/
cni:
  enabled: true
  chained: true
  netDir: /etc/cni/net.d
  binDir: /opt/cni/bin
  confName: 10-aws.conflist
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi
```

dp-resources patch referenced in the values.yaml

```yaml
# https://docs.konghq.com/mesh/latest/introduction/kuma-requirements/
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: dp-resources
  namespace: kuma-system
spec:
  sidecarPatch:
    - op: add
      path: /resources/requests
      value: '{
        "cpu": "50m",
        "memory": "256Mi"
      }'
    - op: add
      path: /resources/limits
      value: '{
        "memory": "256Mi"
      }'
```

I tried on 2.9.0 disabling this patch as well but it didn't make a difference.
