### ISSUE TITLE
Expose `divisor` setting in helm 

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#11991]
### Description

We set `GOMAXPROCS`and `GOMEMLIMIT` and some user might want to configure for them [`divisor`](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/).
We should expose the option to configure it

```yaml
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: control-plane
                  resource: limits.memory
                  divisor: "1"
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  containerName: control-plane
                  resource: limits.cpu
                  divisor: "1"
```

By default we should set it to 1

**Comment by voidlily** [comment]
i'm also having an issue with argocd diffing on the divisor because there's no default set for it.

```diff
                 resourceFieldRef:
                   containerName: control-plane
-                  divisor: '0'
                   resource: limits.memory
             - name: GOMAXPROCS
                 resourceFieldRef:
                   containerName: control-plane
-                  divisor: '0'
                   resource: limits.cpu
           image: >-
```

similar issue as https://github.com/cilium/cilium/issues/30634?

**Comment by voidlily** [comment]
For anyone following along, workaround in argo is like this

```
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - '.spec.template.spec.containers[0].env[]?.valueFrom.resourceFieldRef.divisor'
```
