### ISSUE TITLE
silent error when a route leads to an unknown cluster

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#12040]
### What happened?

I have meshService exclusive and define a route:

```
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: demo-app-edge-gateway
  namespace: kuma-system
spec:
  targetRef:
    kind: MeshGateway
    name: edge-gateway
  to:
  - targetRef:
      kind: Mesh
    rules:
    - default:
        backendRefs:
        - kind: MeshService
          name: demo-app
          port: 5050
      matches:
      - path:
          type: PathPrefix
          value: /
```

notice the missing `namespace` therefore the service is not found. When this happens I only have errors in the cp log

```
2024-11-14T09:16:26.220Z	INFO	xds.status-tracker	config rejected	{"proxyName": "demo-app-gateway-57db88db7f-s2hz6.kuma-demo", "mesh": "default", "streamID": 4, "type": "RouteConfiguration", "resourceVersion": "800adba1-1fe9-4ef6-9bf2-172188908a73"}
2024-11-14T09:16:26.221Z	INFO	xds.nack-backoff	config was previously rejected by Envoy. Applying backoff before resending it	{"backoff": "5s", "nodeID": "default.demo-app-gateway-57db88db7f-s2hz6.kuma-demo", "reason": "At least one of name or cluster_header need to be specified"}
```

Ideally I'd like the route to just be skipped and not the entire config to fail.
