### ISSUE TITLE
MeshPassthrough doesnt work correctly when CIDR and protocol HTTP

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#12052]
### What happened?

It seems that when a user creates a policy with CIDRs and the HTTP protocol, we don't generate the correct routes. We should address this and ensure it works properly.

```
    targetRef:
      kind: Mesh
    default:
      appendMatch:
        - type: CIDR
          value: 172.16.0.0/12
          protocol: http
          port: 8126
        - type: CIDR
          value: 192.168.0.0/16
          protocol: http
          port: 8126
        - type: CIDR
          value: 240.0.0.0/4
          protocol: http
          port: 8126
```
