### ISSUE TITLE
Add a way to identify an application

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#12095]
### Description

With the coming up of `MeshService` we have a separation between workload (pods) and service (service). This is a very good thing because that's how Kubernetes see things.

One issue we have now is that it's hard to relate services and workloads, a common way in kubernetes is to use the `app` label and its newer alternative [`app.kubernetes.io/name`](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels). 

From the top of my head I think this would be useful to:

- Get rid of kuma.io/service in Dataplane
- In dashboards be able to relate and differentiate between outbound and inbound metrics.
- Auto reachable services?
- Building a service Map
- Group multiple deployments in different zones

To me implementation should be:

- In mesh object define what labels should be used in order e.g:

```yaml
type: Mesh
name: default
spec:
  constraints:
    dataplaneProxy:
       appLabels: [app.kubernetes.io/name, app] # the order is priority (if one is set the others are ignored)
```

This would then add `kuma.io/service: app` to all entities by translating labels. 

xrefs:

- #11693
