### ISSUE TITLE
MeshLoadBalancingStrategy support for RingHash and TCP traffic

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#12110]
### Description

By [design](https://github.com/kumahq/kuma/blob/master/docs/madr/decisions/022-lb-policy.md), we chose to support `RING_HASH` routing only for HTTP traffic. However, it is also possible to configure it for TCP traffic.

Use Case:
As a user, I want all requests from a specific source IP to route to the same instance of my database consistently.

Example Envoy configuration:

```
static_resources:
  listeners:
    - name: listener_0
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: tcp_stats
                cluster: service_ring_hash
                hash_policy:
                  - source_ip: {}

  clusters:
    - name: service_ring_hash
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: RING_HASH
      load_assignment:
        cluster_name: service_ring_hash
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address: { address: 127.0.0.1, port_value: 9001 }
              - endpoint:
                  address:
                    socket_address: { address: 127.0.0.1, port_value: 9002 }
              - endpoint:
                  address:
                    socket_address: { address: 127.0.0.1, port_value: 9003 }
```
