### ISSUE TITLE
When I have multiple services I get multiple inbounds with the same port

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#12123]
### What happened?

with:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: kuma-demo
  labels:
    app: demo-app
    version: v1
spec:
  selector:
    matchLabels:
      app: demo-app
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
        version: v1
    spec:
      containers:
        - name: app
          image: ghcr.io/kumahq/kuma-counter-demo:latest
          env:
            - name: OTEL_SERVICE_NAME
              value: demo-app
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://opentelemetry-collector.mesh-observability:4317
            - name: KV_URL
              value: "http://kv.kuma-demo.svc.cluster.local:5050"
            - name: APP_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['version']
          ports:
            - name: http
              containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: kuma-demo
spec:
  selector:
    app: demo-app
  ports:
  - protocol: TCP
    appProtocol: http
    port: 5050
    targetPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-v1
  namespace: kuma-demo
spec:
  selector:
    app: demo-app
    version: v1
  ports:
    - protocol: TCP
      appProtocol: http
      port: 5050
      targetPort: 5050
```

I get:

```yaml
type: Dataplane
mesh: default
name: demo-app-6c79d867f8-wlbww.kuma-demo
labels:
  k8s.kuma.io/namespace: kuma-demo
  kuma.io/display-name: demo-app-6c79d867f8-wlbww
  kuma.io/env: kubernetes
  kuma.io/mesh: default
  kuma.io/origin: zone
  kuma.io/zone: default
networking:
  address: 10.42.0.17
  inbound:
    - port: 5050
      tags:
        app: demo-app
        k8s.kuma.io/namespace: kuma-demo
        k8s.kuma.io/service-name: demo-app
        k8s.kuma.io/service-port: '5050'
        kubernetes.io/hostname: k3d-k3s-default-server-0
        kuma.io/protocol: http
        kuma.io/service: demo-app_kuma-demo_svc_5050
        kuma.io/zone: default
        pod-template-hash: 6c79d867f8
        version: v1
      health:
        ready: true
    - port: 5050
      tags:
        app: demo-app
        k8s.kuma.io/namespace: kuma-demo
        k8s.kuma.io/service-name: demo-app-v1
        k8s.kuma.io/service-port: '5050'
        kubernetes.io/hostname: k3d-k3s-default-server-0
        kuma.io/protocol: http
        kuma.io/service: demo-app-v1_kuma-demo_svc_5050
        kuma.io/zone: default
        pod-template-hash: 6c79d867f8
        version: v1
      health:
        ready: true
  transparentProxying:
    redirectPortInbound: 15006
    redirectPortOutbound: 15001
    ipFamilyMode: DualStack
  admin:
    port: 9901
probes:
  port: 9000
```

So I have 1 inbounds with the same port. This has a couple of problems:
- Where is the traffic actually routed to?
- The underlying [xds conf](https://gist.github.com/lahabana/20be9016e5235263dc7438789df0fa7d) ends up with a single cluster and listener so there's little sense in having multiple inbounds...
