### ISSUE TITLE
Handle root `targetRef` compatibility when `kumactl` >= 2.9.x applies resources to older control planes

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#12165]
### What happened?

In Kuma 2.9, the `targetRef` field at the top level of policies became optional, and `kind: Mesh` is assumed by default if it is not provided (https://github.com/kumahq/kuma/pull/11321). However, this change can cause issues when using newer versions of `kumactl` (>= 2.9.x) with older control planes (< 2.9.0). 

For example, if a user applies the following policies on a universal zone control plane (v2.8.3):

```yaml
type: MeshAccessLog
name: all-incoming-traffic
mesh: default
spec:
 from:
 - targetRef:
     kind: Mesh
   default:
     backends:
     - type: File
       file:
         path: "/usr/local/logs/incoming.log"
---
type: MeshAccessLog
name: all-outgoing-traffic
mesh: default
spec:
 to:
 - targetRef:
     kind: Mesh
   default:
     backends:
     - type: File
       file:
         path: "/usr/local/logs/outgoing.log"
```

The policies are applied without errors (`kumactl apply` succeeds, and `kumactl get` displays them), but they do not update the Envoy configuration in the data plane proxies.

### Next steps

We need to handle this compatibility issue. Some potential ideas (I didn't spend much time on them, so there might be better solutions):
1. Update `kumactl` to detect when the control plane version is < 2.9.0 and:
   - fail if policies are missing the top-level `targetRef`, or
   - automatically add `kind: Mesh` to policies and log a warning
2. Backport the change from https://github.com/kumahq/kuma/pull/11321 to Kuma versions 2.8.x and earlier.
3. Document this behavior and the compatibility considerations in the documentation.

The first step is to determine the best approach for addressing this issue.
