### ISSUE TITLE
Question - Fronting Kuma Control-Plane GUI with Nginx Ingress

### ISSUE THREAD

**Issue by robincher** [kumahq/kuma#1219]
### Summary

Hi, i wonder if control-plane can be exposed via Ingress?

I got this error when i set it up with AWS LB and Nginx Ingress.

<img width="916" alt="Screenshot 2020-11-26 at 4 11 24 PM" src="https://user-images.githubusercontent.com/328109/100325992-53458700-3004-11eb-8f04-60b7e37136ec.png">

Alternatively, i can access the UI and API successfully locally by using portforwarding

```
kubectl port-forward svc/kuma-control-plane -n kuma-system 5681:5681
```

### Steps To Reproduce

1. Install Stand-alone Kuma  ```./kumactl install control-plane | kubectl apply -f -```
2. Create ingress to kuma-control-plane 
3. Test with a web browser

### Additional Details & Logs

- Kuma 1.0.1
- Error logs
Nginx Controller Logs

```
10.48.40.214 - - [26/Nov/2020:06:45:41 +0000] "GET /gui/favicon.png HTTP/1.1" 200 2408 "https://kuma-cp-mydomain.com/gui/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36" 662 0.001 [kuma-system-kuma-control-plane-5681] [] 10.48.41.137:5681 2408 0.004 200 4f0874b5e0c7f46ba94110c1fc08396b
10.48.40.214 - - [26/Nov/2020:06:45:42 +0000] "GET /gui/img/product-logo.5a8acea1.png HTTP/1.1" 200 12987 "https://kuma-cp-mydomain.com/gui/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36" 680 0.002 [kuma-system-kuma-control-plane-5681] [] 10.48.41.137:5681 12987 0.004 200 ec5b5956f656cd496c2a89f0832f28c6
10.48.40.214 - - [26/Nov/2020:06:45:49 +0000] "GET / HTTP/1.1" 200 96 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36" 725 0.001 [kuma-system-kuma-control-plane-5681] [] 10.48.41.137:5681 96 0.000 200 31762ad253a1501adfcddc658ebac6de
10.48.40.214 - - [26/Nov/2020:06:45:54 +0000] "GET / HTTP/1.1" 200 96 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36" 725 0.001 [kuma-system-kuma-control-plane-5681] [] 10.48.41.137:5681 96 0.004 200 9e43f797125e49ef87cc4f1379b31ffb
```

- Configuration

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuma-control-plane-ingress
  namespace: kuma-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "http"
spec:
  rules:
    - host: "kuma-cp-mydomain.com"
      http:
        paths:
          - backend:
              serviceName: kuma-control-plane 
              servicePort: 5681

```

- AWS EKS 1.16
- AWS ALB fronting EKS ingress

**Comment by jakubdyszkiewicz** [comment]
Hey, yes - some of our users expose it via Ingress. What happens if you hit `http://kuma-cp-mydomain.com/meshes`?
Do you have some additional TLS layer? I see `https` in nginx logs
What browser do you use? Can you try with other browsers?

Thanks!

**Comment by nickolaev** [comment]
I had this working with Kong like this:

```yaml
cat <<EOF | kubectl apply -f - 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuma-api
  namespace: kuma-system
  annotations:
    kubernetes.io/ingress.class: kong
    kubernetes.io/ingress.global-static-ip-name: "kong-demo-ip"
spec:
  rules:
  - host: $KUMA_PUBLIC_URL
    http:
      paths:
      - path: /
        backend:
          serviceName: kuma-control-plane
          servicePort: 5681
EOF
```
