### ISSUE TITLE
The virtual_domains not generated correctly with AUTO_REACHABLE_SERVICES and MeshTrafficPermission

### ISSUE THREAD

**Issue by Icarus9913** [kumahq/kuma#12273]
### What happened?

version: `2.9.2`

## What happened?

I eanbled the `AUTO_REACHABLE_SERVICES` feature and create 2 MTPs and found the virtual_domains was not generate correctly from the XDS configuration

## Steps to reproduce

1. create a single zone with `2.9.2`
2. enable auto_reachable_services with ENV `KUMA_EXPERIMENTAL_AUTO_REACHABLE_SERVICES`
3. Apply the following yamls:

```yaml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  meshServices:
    mode: Exclusive
  mtls:
    enabledBackend: ca-1
    backends:
    - name: ca-1
      type: builtin
---
apiVersion: kuma.io/v1alpha1
kind: HostnameGenerator
metadata:
  name: default
  namespace: kuma-system
spec:
  selector:
    meshService:
      matchLabels:
        kuma.io/origin: zone
  template: "{{ .DisplayName }}.{{ .Namespace }}.default.gg.mesh"
```

4. Create 2 applications with sidecar injected:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kuma.io/sidecar-injection: enabled
  name: kuma-demo
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kuma.io/sidecar-injection: enabled
  name: kuma-one
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-app
  namespace: kuma-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2048-app
  template:
    metadata:
      labels:
        app: 2048-app
    spec:
      containers:
      - name: 2048-app
        image: ghcr.io/daocloud/dao-2048:v1.4.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-2048-app
  namespace: kuma-demo
spec:
  type: ClusterIP
  selector:
    app: 2048-app
  ports:
    - name: http
      appProtocol: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: kuma-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
          - containerPort: 80
            name: http-web-svc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: kuma-one
spec:
  selector:
    app: nginx
  ports:
  - name: name-of-service-port
    appProtocol: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
```

5. Create the following MTPs one by one:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: mtp-allow-kuma-one
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Mesh
  from:
  - targetRef:
      kind: MeshSubset
      tags:
        k8s.kuma.io/namespace: kuma-one
    default:
      action: Allow
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: mtp-allow-kuma-other-ns-and-tag
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Mesh
  from:
  - targetRef:
      kind: MeshSubset
      tags:
        asdfasdfasdf: asdfasdfasdf
        k8s.kuma.io/namespace: kuma-other
    default:
      action: Allow
```

## Result

XDS configurations:

```text
        {
          "name": "kuma:dns",
          "active_state": {
            "version_info": "64c1c7c1-8609-40a6-b7c3-ea3949b850e1",
            "listener": {
              "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
              "name": "kuma:dns",
              "listener_filters": [
                {
                  "name": "envoy.filters.udp.dns_filter",
                  "typed_config": {
                    "@type": "type.googleapis.com/envoy.extensions.filters.udp.dns_filter.v3.DnsFilterConfig",
                    "stat_prefix": "kuma_dns",
                    "server_config": {
                      "inline_dns_table": {}
                    }
                  }
                }
              ],
```
