### ISSUE TITLE
Add kind `Dataplane` for top-level targetRefs

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#12358]
### Description

We discussed in the [madr](https://docs.google.com/document/d/1tdIOVVYObHbGKX1AFhbPH3ZQKYvpQG-2s6ShHSECaXM/edit?tab=t.0#heading=h.pauem61sn4m1) we need a new kind `Dataplane` for top-level targetRef:

```yaml
spec:
  targetRef:
    kind: Dataplane
    labels: 
      app: backend
    sectionName: http-api
```

That unblocks us to use Dataplane labels instead of inbound tags when selecting the proxy we'd like to configure. Also, it provides a way to select a single port on the DPP when configuring inbounds (by using `sectionName`).

> The field “sectionName” selects the port by name, but if name is not specified it’s possible to select the port by number passed as a string.

This issues covers only updating the API and not the matching. Make sure validation for new kind works as expected (i.e. `sectionName` can only be set for inbound policies).
