### ISSUE TITLE
Add `spec.rules` for MeshTimeout

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#12364]
### Description

We should add a `rules` list without L7 `matches` (only `rules[].default`)

```yaml
spec:
  targetRef:
    kind: Dataplane
    labels:
      app: frontend
  rules:
    - default:
        connectTimeout: 5s
```

This issue covers only API change.
