### ISSUE TITLE
Deprecate `targetRef.proxyTypes` field

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#12363]
### Description

Once https://github.com/kumahq/kuma/issues/12359 is implemented it should be possible to use `kuma.io/proxy-type` label instead of `proxyTypes` field. The field has to be deprecated.

**Comment by lobkovilya** [comment]
We don't want `spec.targetRef.kind: Dataplane` to select MeshGateway's DPPs. We're preserving `targetRef.proxyTypes` field for now to be able to use (i.e. in default policies):
```yaml
spec:
  targetRef:
    kind: Mesh
    proxyTypes: ["Gateway"]
```
