### ISSUE TITLE
Inspect API support for the new top-level targetRef kind `Dataplane`

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#12360]
### Description

In GUI we have "affected dataplanes" page that shows what DPPs are affected by the policy. We need to update Inspect API endpoint `_resources/dataplanes` to support the new kind `Dataplane`.

**Comment by lobkovilya** [comment]
the response example:
```yaml
{
 "items": [
  {
   "labels": {
    "kuma.io/env": "universal",
    "kuma.io/mesh": "default",
    "kuma.io/origin": "zone",
    "kuma.io/proxy-type": "sidecar",
    "kuma.io/zone": "zone-1"
   },
   "mesh": "default",
   "name": "example",
   "type": "Dataplane"
  }
 ],
 "total": 1
}
```
