### ISSUE TITLE
Add `spec.rules` for MeshAccessLog

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#12367]
### Description

We should add a `rules` list without L7 `matches` (only `rules[].default`)

```yaml
spec:
  targetRef:
    kind: Dataplane
    labels:
      app: frontend
  rules:
    - default: 
        backends:
          - type: File
            file:
              path: /dev/stdout
```

This issue covers only API change.
