### ISSUE TITLE
Add `spec.rules` for MeshRateLimit

### ISSUE THREAD

**Issue by Automaat** [kumahq/kuma#12370]
### Description

We should add a rules list without L7 matches (only rules[].default)

```yaml
spec:
  targetRef:
    kind: Dataplane
    labels:
      app: frontend
  rules:
    - default: ...
```

This issue covers only API change.
