### ISSUE TITLE
Add `spec.rules` for MeshFaultInjection

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#12372]
### Description

We should add a `rules` list without L7 `matches` (only `rules[].default`)

```yaml
spec:
  targetRef:
    kind: Dataplane
    labels:
      app: frontend
  rules:
    - default:
        http:
          - abort:
              httpStatus: 500
              percentage: "2.5"
```

This issue covers only API change.
