### ISSUE TITLE
Add support for targeting ZoneEgress in MeshTrafficPermission

### ISSUE THREAD

**Issue by Automaat** [kumahq/kuma#12389]
### Description

We have designed how we want to target zone proxies in [MADR](https://docs.google.com/document/d/1tdIOVVYObHbGKX1AFhbPH3ZQKYvpQG-2s6ShHSECaXM/edit?pli=1&tab=t.0#heading=h.6u1udkd4npx9).  We now need to implement possibility to configure ZoneEgress as stated in MADR. API should look like: 

```yaml
spec:
  targetRef:
    kind: ZoneEgress
  rules:
    - targetRef:
        kind: MeshExternalService
        name: my-external-service
      default:  ...
```

In targetRef inside `rules` we should be able to select:
- Mesh
- MeshService
- MeshMultizoneService
- MeshExternalService

In order to start implementation of this feature we need to have MADR in place: https://github.com/kumahq/kuma/issues/12374
