### ISSUE TITLE
Add support for targeting ZoneIngress in MeshAccessLog

### ISSUE THREAD

**Issue by Automaat** [kumahq/kuma#12390]
### Description

We have designed how we want to target zone proxies in [MADR](https://docs.google.com/document/d/1tdIOVVYObHbGKX1AFhbPH3ZQKYvpQG-2s6ShHSECaXM/edit?pli=1&tab=t.0#heading=h.6u1udkd4npx9).  We now need to implement possibility to configure ZoneIngress as stated in MADR. API should look like: 

```yaml
spec:
  targetRef:
    kind: ZoneIngress
  rules:
    - targetRef:
        kind: MeshService
        name: demo-app
      default:  ...
```

In targetRef inside `rules` we should be able to select:
- Mesh
- MeshService
- MeshMultizoneService
