### ISSUE TITLE
New top-level targetRef kind `ZoneEgress`

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#12404]
### Description

The issue covers only API change.

As we've agreed in [the design](https://docs.google.com/document/d/1tdIOVVYObHbGKX1AFhbPH3ZQKYvpQG-2s6ShHSECaXM/edit?tab=t.0#heading=h.6u1udkd4npx9) we need a new kind `ZoneEgress` to attach policies to zone egress proxy. It also supports `labels`:

```yaml
spec:
  targetRef:
    kind: ZoneEgress
    labels:
      kuma.io/zone: zone-1
```
