### ISSUE TITLE
Update dependabot to run for release branches and automate config updates

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#12493]
### Description

We should update the dependabot configuration to run for release branches for `github-actions` and `dockerfiles`, as it currently only works for `master`. This means copying the settings for each active release branch, like this:

```yaml
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
    labels:
      - "dependencies"
      - "ci/skip-test" # No need to run tests on github actions updates
    target-branch: master

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
    labels:
      - "dependencies"
      - "ci/skip-test" # No need to run tests on github actions updates
    target-branch: release-2.9
```

We also need to update the automation to keep these configurations up to date when active release branches change.
