### ISSUE TITLE
Policies with `spec.from` targeting MeshGateway should be updated to use `spec.rules`

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#12729]
### Description

If we want to deprecate `spec.from` then policies like
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: mesh-gateways-timeout-all-default
  namespace: kuma-system
spec:
  targetRef:
    kind: Mesh
    proxyTypes:
    - Gateway
  from:
  - targetRef:
      kind: Mesh
    default:
      http:
        requestHeadersTimeout: 500ms
        streamIdleTimeout: 5s
      idleTimeout: 5m0s
```

also should use `spec.rules`
