### ISSUE TITLE
kumactl install control-plane produces duplicate env vars

### ISSUE THREAD

**Issue by austince** [kumahq/kuma#1273]
### Summary

`kumactl install control-plane` does not respect user overrides of kuma env variables passed with the `--env-var` flag. This makes it difficult to customize an install past what is officially supported.

### Steps To Reproduce

1. `kumactl install control-plane --env-var KUMA_DEFAULTS_SKIP_MESH_CREATION=true`
2. See the duplicate entries for `KUMA_DEFAULTS_SKIP_MESH_CREATION` in the cp deployment

### Additional Details & Logs

- kumactl v1.0.2

**Comment by hvydya** [comment]
Hi I'd like to work on this. Can you assign it to me?

**Comment by austince** [comment]
Sure! Feel free to message in the [slack](https://chat.kuma.io/) if you'd like to talk about any of the details.

**Comment by subnetmarco** [comment]
Hi @hvydya, any progress on this issue?

**Comment by hvydya** [comment]
Yeah! The issue is coming from Helm charts apparently, while generating them. The package used for that is generating multiple entries for `env-var`s. I am assuming it's not because of a bug in Helm charts. So searching for the actual issue restricted to kuma codebase only.

**Comment by hvydya** [comment]
Hi! I need some help. I am unable to figure out the bug. I haven't used Helm before so I don't have much context regarding what is happening and what is supposed to happen. But, I've found the place where the duplicate `env-var`s get introduced.

Ref: `app/kumactl/cmd/install/render_helm_files.go` line `64`
```go
files, err = engine.RenderWithClient(chart, valuesToRender, kubeClientConfig)
```
Here files variable has the duplicate env-vars in the cp deployment. So I'm not sure why `RenderWithClient` is producing them.

**Comment by austince** [comment]
Hey @hvydya, no worries on timing, totally understand studies come first + good luck! 

As for the fix, nice find on the line that generates the duplicates, and that it ultimately is caused by the Helm chart resources. I think the below link is the section in the chart that creates the duplicates since the user-supplied `envVars` are just added to the hardcoded list. We'll need a way to merge these lists and favor the user-supplied ones.

https://github.com/kumahq/kuma/blob/7d703bce6e5583f262cb2396d3b8e45680be85f8/deployments/charts/kuma/templates/cp-deployment.yaml#L37-L97

Here's a good place to start with Helm templates:
https://helm.sh/docs/chart_template_guide/getting_started/


I should also say that if this is not something that interests you and you'd rather work on other issues, by all means, no worries just let us know!

**Comment by hvydya** [comment]
Hi @austince ! So, I looked into Helm charts and I came up with an idea. I changed the `cp-deployment.yaml` but, my changes aren't getting reflected while generating the values from the templates. So, I looked into that and I'm guessing the templates are hardcoded in a file ( `/app/kumactl/pkg/install/k8s/control-plane/helmtemplates_vfsdata.go`). 

https://github.com/kumahq/kuma/blob/b35a1a3bd543221b1fa6f874c5908d1f928d20f9/app/kumactl/pkg/install/k8s/control-plane/helmtemplates_vfsdata.go#L221-L227

What is the workaround for this? Basically I need to make it use my changes instead of this hardcoded template.

**Comment by jakubdyszkiewicz** [comment]
Hey @hvydya, run `make generate/kumactl/install/k8s/control-plane` after modyfing YAML to reflect this in vfsdata

**Comment by hvydya** [comment]
Hi! Thanks, that command worked. 👍 

The go package from helm doesn't handle merging so, my guess was to modify the template. I've looked at the template docs and didn't find any straightforward fix. The idea I had in mind was:
Maintain the `map` of envs present in `cp-deployment.yaml`, in `values.yaml`. In `cp-deployment.yaml` , we iterate through the `map` declared before and check if `envVars` (present in `values.yaml`) has that key and if it does, use it, otherwise use the default value.

The problems with this approach are:

1. There are some conditional envs (like `KUMA_MULTIZONE_REMOTE_ZONE`) which are added only when certain condition is met. Incorporating these in the above method is not possible I think. But, keeping them as is in `cp-deployment.yaml` will cause duplicates again.
2. The user might supply his custom envs which may not be present in our `map`. So they are to be added separately.

Let me know your thoughts on this. 👍 

Maybe I've overlooked something that makes it more easier to do this. Will go through the docs once again.

**Comment by austince** [comment]
Hey, I like the direction you're going with the `map` of envs! The problems you've noted make a lot of sense -- here might be some ways to get around them:

If we keep the conditional generated "kuma-defined" env map separate from the "user-defined", we might be able to then generate the final map by merging them, with precedence going to the user-defined values. The [Sprig template library](https://masterminds.github.io/sprig) (which is included by default in Helm) has some nice functions that could help with this, perhaps [`mergeOverwrite`](https://masterminds.github.io/sprig/dicts.html). Once we have the final map, we could just iterate over key-values and insert them directly. 

It might be tricky to build those maps, as it will involve parsing that generated yaml with the `fromYaml` command. You could add a helper template (in `_helpers.tpl`) (maybe called `"kuma.defaultEnv"`) that does the conditional env list generation. You might also want a helper that takes an env list and turns it into a map.


```yaml
# in _helpers.tpl
{{- define "kuma.defaultEnv" -}}
- name: KUMA_ENVIRONMENT
  value: "kubernetes"
- name: KUMA_STORE_TYPE
  value: "kubernetes"
- name: KUMA_STORE_KUBERNETES_SYSTEM_NAMESPACE
  value: {{ .Release.Namespace | quote }}
- name: KUMA_GENERAL_TLS_CERT_FILE
  value: /var/run/secrets/kuma.io/tls-cert/tls.crt
- name: KUMA_GENERAL_TLS_KEY_FILE
  value: /var/run/secrets/kuma.io/tls-cert/tls.key
{{- if eq .Values.controlPlane.mode "remote" }}
- name: KUMA_MULTIZONE_REMOTE_GLOBAL_ADDRESS
  value: {{ .Values.controlPlane.kdsGlobalAddress }}
{{- end }}
# ... etc.
{{- end }}
```

```yaml
# in cp-deployment.yaml
{{- $defaultEnvList := include "kuma.defaultEnv" . | fromYaml }}
{{- $defaultEnvMap := include "kuma.envListToMap" $defaultEnvList }}
# ... do merging into $finalEnvMap
{{- range $key, $value := $finalEnvMap }}
  - name: {{ $key | upper }}
    value: {{ $value | quote }}
{{- end }}
```

Does that make sense? What do you think of that approach?
