### ISSUE TITLE
MeshService for delegated gateway shows unavailable

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#12746]
### Kuma Version

master

### Describe the bug

I followed the [Delegated Gateway guide](https://kuma.io/docs/2.9.x/guides/gateway-delegated/) and successfully deployed a delegated gateway. However, after deployment, I checked the UI and noticed that the MeshService status is marked as Unavailable. I understand that the service does not directly communicate with the gateway, but this status is misleading and might suggest that the gateway is not deployed correctly.

traffic works:
```
~ $ curl -XPOST 172.21.3.1:80/increment
{"counter":7,"zone":"local","err":null}~ $
```

```
type: MeshService
mesh: default
name: kong-gateway-proxy.kong
labels:
  app.kubernetes.io/instance: kong
  app.kubernetes.io/managed-by: Helm
  app.kubernetes.io/name: gateway
  app.kubernetes.io/version: '3.8'
  enable-metrics: 'true'
  helm.sh/chart: gateway-2.46.0
  k8s.kuma.io/is-headless-service: 'false'
  k8s.kuma.io/namespace: kong
  k8s.kuma.io/service-name: kong-gateway-proxy
  kuma.io/display-name: kong-gateway-proxy
  kuma.io/env: kubernetes
  kuma.io/managed-by: k8s-controller
  kuma.io/mesh: default
  kuma.io/origin: zone
  kuma.io/zone: default
spec:
  state: Unavailable
  selector:
    dataplaneTags:
      app.kubernetes.io/component: app
      app.kubernetes.io/instance: kong
      app.kubernetes.io/name: gateway
      k8s.kuma.io/namespace: kong
  ports:
    - name: kong-proxy
      port: 80
      targetPort: 8000
      appProtocol: tcp
    - name: kong-proxy-tls
      port: 443
      targetPort: 8443
      appProtocol: tcp
status:
  vips:
    - ip: 10.43.99.250
  tls:
    status: Ready
  dataplaneProxies: {}
```

<img width="1797" alt="Image" src="https://github.com/user-attachments/assets/7fb1f35c-fbff-46a5-8857-7db370fbfdf3" />

### To Reproduce

Follow the guide https://kuma.io/docs/2.9.x/guides/gateway-delegated/ 

### Expected behavior

The gateway is shown as a healthy or MeshService for gateway is not generated since it should be an entry point and doesn't need to be tracked (cross mesh is not supported with MS for now)
