### ISSUE TITLE
MeshTimeout with top-level MeshGateway is not allowed by validation

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#12764]
### Description

Apply:
```yaml
type: MeshTimeout
name: mt-1
mesh: default
spec:
  targetRef:
    kind: MeshGateway
    name: gateway-proxy
  from:
    - targetRef:
        kind: Mesh
      default:
        idleTimeout: 50s
        connectionTimeout: 51s
        http:
          requestTimeout: 52s
          streamIdleTimeout: 53s
          maxStreamDuration: 54s
          maxConnectionDuration: 55s
```
Result:
```
Error: YAML contains invalid resource: spec.from: must not be defined.
```

However, the following policy works
```yaml
type: MeshTimeout
name: mt-1
mesh: default
spec:
  targetRef:
    kind: Mesh
    proxyTypes:
      - Gateway
  from:
    - targetRef:
        kind: Mesh
      default:
        idleTimeout: 50s
        connectionTimeout: 51s
        http:
          requestTimeout: 52s
          streamIdleTimeout: 53s
          maxStreamDuration: 54s
          maxConnectionDuration: 55s
```
