### ISSUE TITLE
FaultInjection excessive requirement of http protocol on "source"

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#1281]
### Summary

There is a requirement for `FailtInjection` policy's matcher to specify `kuma.io/protocol: http` for `source`. Apparently, it's not needed, because the protocol for outbound listener on the source side is infered from destinations - https://github.com/kumahq/kuma/blob/master/pkg/xds/generator/outbound_proxy_generator.go#L50.

Resource 

```yaml
type: FaultInjection
mesh: default
name: fi1
sources:
    - match:
        kuma.io/service: frontend
        version: "0.1"
        kuma.io/protocol: http # won't be mandatory anymore 
destinations:
    - match:
        kuma.io/service: backend
        kuma.io/protocol: http
conf:        
    abort:
        httpStatus: 500
        percentage: 50
    delay:
        percentage: 50.5
        value: 5s
    responseBandwidth:
        limit: 50 mbps
        percentage: 50
```
