### ISSUE TITLE
MeshPassthrough validation allows passing invalid DNS name

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#12814]
### Description

Apply:
```yaml
echo 'type: MeshPassthrough
name: allow-some-passthrough
mesh: default
spec:
  targetRef:
    kind: MeshSubset
    proxyTypes:
    - Sidecar
    tags:
      kuma.io/service: demo-app_kuma-demo_svc_5000
  default:
    passthroughMode: Matched
    appendMatch:
    - type: Domain
      value: "*.hello@world"
      protocol: tls
      port: 443' | kumactl apply -f-
```
Actual: no validation error
Expected: `*.hello@world` is not a valid wildcard domain.

The reason is we call `IsDNSName` only after checking it's not a wildcard https://github.com/kumahq/kuma/blob/d7ec0a2b1ac19208fb7dd9726309e3cf8cdc5848/pkg/plugins/policies/meshpassthrough/api/v1alpha1/validator.go#L102-L103
