### ISSUE TITLE
One invalid MeshExternalService makes makes all MES not working

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#12821]
### Kuma Version

master

### Describe the bug

If you have two MeshExternalServices, one valid and the other referencing an invalid secret, it seems to cause all MeshExternalServices to stop working. The logs show errors indicating this issue.

```yaml
unable to create MeshExternalService endpoint. Endpoint won't be included in the XDS.    {"name": "kong-1.kong-mesh-system", "mesh": "demo", "err
or": "could not load clientCert: could not load data: Resource not found: type=\"Secret\" name=\"kong-cert-1\" mesh=\"demo\"", "errorVerbose": "Resource not found: type=\"Secret\" name=\"kong-cert-1
\" mesh=\"demo\"\ncould not load data\ngithub.com/kumahq/kuma/pkg/core/datasource.(*staticLoader).Load\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/core/datasource/static.go:49\n
github.com/kumahq/kuma/pkg/xds/topology.loadBytes\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/topology/outbound.go:885\ngithub.com/kumahq/kuma/pkg/xds/topology.createMeshExt
ernalServiceEndpoint\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/topology/outbound.go:675\ngithub.com/kumahq/kuma/pkg/xds/topology.fillExternalServicesReachableFromZone\n\tg
ithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/topology/outbound.go:619\ngithub.com/kumahq/kuma/pkg/xds/topology.BuildEgressEndpointMap\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045
254-fbef9908b833/pkg/xds/topology/outbound.go:63\ngithub.com/kumahq/kuma/pkg/xds/sync.(*EgressProxyBuilder).Build\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/sync/egress_pro
xy_builder.go:75\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncEgress\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/sync/dataplane_watchdog.go:279\ngithub.com/
kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).Sync\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/sync/dataplane_watchdog.go:84\ngithub.com/kumahq/kuma/pkg/xds/sync.(*dataplane
WatchdogFactory).New.func2\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/sync/dataplane_watchdog_factory.go:44\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTi
ck\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/util/watchdog/watchdog.go:54\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start\n\tgithub.com/kumahq/kuma@v0.0.0-20
250121045254-fbef9908b833/pkg/util/watchdog/watchdog.go:22\nruntime.goexit\n\truntime/asm_amd64.s:1700\ncould not load clientCert\ngithub.com/kumahq/kuma/pkg/xds/topology.createMeshExternalServiceEn
dpoint\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/topology/outbound.go:677\ngithub.com/kumahq/kuma/pkg/xds/topology.fillExternalServicesReachableFromZone\n\tgithub.com/kuma
hq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/topology/outbound.go:619\ngithub.com/kumahq/kuma/pkg/xds/topology.BuildEgressEndpointMap\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b8
33/pkg/xds/topology/outbound.go:63\ngithub.com/kumahq/kuma/pkg/xds/sync.(*EgressProxyBuilder).Build\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/sync/egress_proxy_builder.go:
75\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncEgress\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/sync/dataplane_watchdog.go:279\ngithub.com/kumahq/kuma/pk
g/xds/sync.(*DataplaneWatchdog).Sync\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/sync/dataplane_watchdog.go:84\ngithub.com/kumahq/kuma/pkg/xds/sync.(*dataplaneWatchdogFactor
y).New.func2\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/xds/sync/dataplane_watchdog_factory.go:44\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick\n\tgithub.c
om/kumahq/kuma@v0.0.0-20250121045254-fbef9908b833/pkg/util/watchdog/watchdog.go:54\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start\n\tgithub.com/kumahq/kuma@v0.0.0-20250121045254-f
bef9908b833/pkg/util/watchdog/watchdog.go:22\nruntime.goexit\n\truntime/asm_amd64.s:1700"}
```

### To Reproduce

Create 2 MeshExternalServices where one points to not existing secret

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: kuma-cert-1
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
data:
  value: dGVzdAo=
type: system.kuma.io/secret
---
apiVersion: v1
kind: Secret
metadata:
  name: kuma-key-1
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
data:
  value: dGVzdAo=
type: system.kuma.io/secret
---
apiVersion: kuma.io/v1alpha1
kind: MeshExternalService
metadata:
 name: kuma-1
 namespace: kuma-system
 labels:
   kuma.io/mesh: default
spec:
  match:
    type: HostnameGenerator
    port: 80
    protocol: http
  endpoints:
  - address: aaa.test.dev
    port: 443
  tls:
    enabled: true
    verification:
      serverName: aaa.test.dev
      clientCert:
        secret: kuma-cert-1
      clientKey:
        secret: kuma-key-1
---
apiVersion: kuma.io/v1alpha1
kind: MeshExternalService
metadata:
 name: kuma
 namespace: kuma-system
 labels:
   kuma.io/mesh: default
spec:
  match:
    type: HostnameGenerator
    port: 80
    protocol: http
  endpoints:
  - address: aaa.test.dev
    port: 443
  tls:
    enabled: true
    verification:
      serverName: aaa.test.dev
      clientCert:
        secret: kuma-cert
      clientKey:
        secret: kuma-key
```
### Expected behavior

We should still generate a MeshExternalService for a valid service and skip the invalid ones.
