### ISSUE TITLE
MMZS allowed to have longer names than MeshService and MeshExternalService

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#12825]
### Description

MeshService and MeshExternalService names are limited to 63 characters, but MeshMutliZoneService can be 253.

**Comment by lobkovilya** [comment]
@michaelbeaumont you [added](https://github.com/kumahq/kuma/pull/10544) the validation for MS and MES probably when we didn't have MMZS. Do you know if it's needed for MMZS?

**Comment by lukidzi** [comment]
> Triage: If there is a good reason to keep 253 let's write it. If there is no reason to keep it, we should disallow creating new services MMZS with longer names than 63 and still supporting backward compatibility.

**Comment by michaelbeaumont** [comment]
No, no reason not to have 63

**Comment by lahabana** [comment]
xref #9246

**Comment by Icarus9913** [comment]
MeshMutliZoneService can be used in HostnameGenerator as part of DNS URL hostname, so we need the MMZS name to follow RFC-1035. 

We've added the Deprecation for the MMZS name in 1.20.x

Tracked in https://github.com/kumahq/kuma/issues/13054

**Comment by lobkovilya** [comment]
I’m reopening this issue. It was previously closed in favor of tracking it in #13054, which has since been closed as not planned.

I think it's important to implement it before 3.0, the suggested HostnameGenerator in our docs looks like [this](https://kuma.io/docs/2.13.x/resources/hostnamegenerator/#hostnamegenerator-for-meshmultizoneservice):
```yaml
apiVersion: kuma.io/v1alpha1
kind: HostnameGenerator
metadata:
  name: mesh-multi-zone-service
  namespace: kuma-system
spec:
  selector:
    meshMultiZoneService:
      matchLabels:
        kuma.io/origin: global
  template: "{{ .DisplayName }}.mzsvc.mesh.local"
```
it's going to generate invalid hostname if display name is longer than 253.
