### ISSUE TITLE
Feature Request: Ingress Per-Zone Advertised Addresses

### ISSUE THREAD

**Issue by rucciva** [kumahq/kuma#1297]
### Summary

In a scenario where zone A and zone B are reachable through private network (e.g. for supporting both vm and kubernetes workloads in a private network) but zone C are only reachable through public network, it would be efficient if communication between zone A and B use the private network. 

Maybe with this kind of configuration:

```yaml
#  zoneA
mesh: default
name: ingress-A-01
networking:
  ingress:
    publicAddress: 7.7.7.7
    publicPort: 10000
    advertisedAddresses:
       - zone: [ "zoneB" ]
          address: 10.0.0.2
          port: 10000

#  zoneB
mesh: default
name: ingress-B-01
networking:
  ingress:
    publicAddress: 9.9.9.9
    publicPort: 10000
    advertisedAddresses:
       - zone: [ "zoneA" ]
          address: 10.0.1.2
          port: 10000
```

### Additional Details & Logs

- Version: 1.0.3

**Comment by subnetmarco** [comment]
Perhaps routing across zones deserves a new resource in Kuma as it can get quite complex. Also for some zone-to-zone traffic we may want to use different ingresses with a round robin load balancing strategy, some other zones with least request, and so on.

**Comment by rucciva** [comment]
That could also work. In that case, we need to specify two different ingress with two different service tag, one with public ip and one with private ip. And then the resource could be similar to TrafficRoute like this

```
type: ZoneRoute
name: route-private
mesh: default
sources:
  - match:
      kuma.io/zone: 'A'
destinations:
  - match:
      kuma.io/zone: 'B'
conf:
  split:
    - weight: 100
      ingress:
        kuma.io/service: 'ingress-private'
```

```
type: ZoneRoute
name: default-route
mesh: default
sources:
  - match:
      kuma.io/zone: '*'
destinations:
  - match:
      kuma.io/zone: '*'
conf:
  split:
    - weight: 100
      ingress:
        kuma.io/service: 'ingress-public'
```
