### ISSUE TITLE
Prohibit using dot, underscore signs for Mesh, Zone, MeshService, MeshMultizoneService, MeshExternalService name

### ISSUE THREAD

**Issue by Icarus9913** [kumahq/kuma#12985]
### Description

When using HostnameGenerator, the name of the mentioned resources can be part of the **FQDN hostname**. Actually, it breaks the DNS RFC-1035 Label Names restrictions. The dot sign is used to separate DNS name labels.

> Some resource types require their names to follow the DNS label standard as defined in [RFC 1035](https://tools.ietf.org/html/rfc1035). This means the name must:
> * contain at most 63 characters
> * contain only lowercase alphanumeric characters or '-'
> * start with an alphabetic character
> * end with an alphanumeric character

Here's an example of HostnameGenerator:

```yaml
apiVersion: kuma.io/v1alpha1
kind: HostnameGenerator
...
spec:
  selector:
    meshService:
      matchLabels:
        k8s.kuma.io/namespace: kuma-demo
  template: '{{ .DisplayName }}.{{ .Namespace }}.{{ .Mesh }}.svc.icarus.mesh.local'
```
Although it doesn't impact the URL request:

```text
root@nginx-5f54549bb4-vj47j:~# curl -I aa.a.kuma-demo.default.svc.icarus.mesh.local
HTTP/1.1 200 OK
server: envoy
date: Mon, 03 Mar 2025 04:58:07 GMT
content-type: text/html
content-length: 4055
last-modified: Thu, 02 Mar 2023 10:57:12 GMT
etag: "64008108-fd7"
accept-ranges: bytes
x-envoy-upstream-service-time: 4
```

## Notice

The Kubernetes system has one first level resource creation validation that doesn't allow you to create a resource with underscore sign in name

```text
The MeshService "aa_a" is invalid: metadata.name: Invalid value: "aa_a": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

But in our Universal mode, we didn't add that restriction:

```text
root@cb35c33dd3de:~/kuma-2.9.3/bin# KUMA_MODE=zone \
           KUMA_MULTIZONE_ZONE_NAME=wk_zone_2 \
           KUMA_ENVIRONMENT=universal \
           KUMA_STORE_TYPE=memory \
           ./kuma-cp run
----------
root@cb35c33dd3de:~/kuma-2.9.3/bin# ./kumactl get zones
NAME        AGE
wk_zone_2   1m
```
