### ISSUE TITLE
Remove hash-suffix on BuiltinGateway Envoy Clusters

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#13129]
### Description

Today BuiltinGateway generates a unique Cluster for each Listener. For example, given a MeshGateway:
```yaml
type: MeshGateway
name: gateway-proxy
mesh: mesh-1
selectors:
  - match:
      kuma.io/service: gateway-proxy
conf:
  listeners:
    - port: 8080
      protocol: HTTP
      hostname: example.kuma.io
      tags:
        key1: value1
    - port: 9090
      protocol: HTTP
      hostname: test.kuma.io
      tags:
        key2: value2
```
and MeshHTTPRoute
```yaml
type: MeshHTTPRoute
name: gateway-proxy-route
mesh: mesh-1
spec:
  targetRef:
    kind: MeshGateway
    name: gateway-proxy
  to:
    - targetRef:
        kind: Mesh
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: "/"
          default:
            backendRefs:
              - kind: MeshService
                name: echo-service
                port: 80
```

Kuma is going to generate 2 clusters:
* `mesh-1_echo-service__kuma-3_msvc_80-{{hash(listeners[0].tags)}}`
* `mesh-1_echo-service__kuma-3_msvc_80-{{hash(listeners[1].tags)}}`

IIUC we needed a cluster per listener to enable old connection policies to work, i.e. users apply `connectionTimeout` on `listener[0]` but under the hood, the timeout is set on the Cluster. More context is available in the PR https://github.com/kumahq/kuma/pull/3098.

With new real-resource outbound policies, it should be easier to guarantee cluster-specific confs are applied only by using `to.targetRef.kind: MeshService`. And when targeting MeshGateway Listeners it should be possible to change only listener-specific confs, i.e:

```yaml
type: MeshTimeout
name: mt-1
mesh: mesh-1
spec:
  targetRef:
    kind: Mesh
    proxyTypes:
      - Gateway
  to:
    - targetRef:
        kind: MeshService
        name: echo-service
      default:
        idleTimeout: 50s # applied on Cluster
        connectionTimeout: 51s # applied on Cluster
        http:
          requestTimeout: 52s # ignored, potentially can improve it
---
type: MeshTimeout
name: mt-1
mesh: mesh-1
spec:
  targetRef:
    kind: MeshGateway
    name: gateway-proxy
    sectionName: "9090"
  rules:
    - default:
        idleTimeout: 50s # applied on Listener
        connectionTimeout: 51s # ignored
        http:
          requestTimeout: 52s # applied on Listener
```

After that, we can remove the `hash(listeners[i].tags)` suffix on the cluster name and make multiple listeners share the Cluster per MeshService.
