### ISSUE TITLE
High CPU usage when using multiple `to` policies

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#13149]
### Kuma Version

master

### Describe the bug

When a user has multiple `to` policies targeting a `MeshService` (old) that affect a single dataplane, along with a default `to` policy for the `Mesh`, our build rules algorithm performs excessive work by iterating over unnecessary permutations. This leads to significantly high CPU usage.

### To Reproduce

1. Deploy kuma
2. Use kuma-tools to generate 40 services
3. Create policies
```
---
apiVersion: kuma.io/v1alpha1
kind: MeshLoadBalancingStrategy
metadata:
  annotations:
    kuma.io/display-name: mesh-load-balancing-strategy-default
  labels:
    kuma.io/mesh: default
  name: mesh-load-balancing-strategy-default
  namespace: kuma-system
spec:
  targetRef:
    kind: Mesh
  to:
  - default:
      loadBalancer:
        leastRequest:
          choiceCount: 3
        type: LeastRequest # check diff with ringhash in envoy docs on absence of header
    targetRef:
      kind: Mesh
---
apiVersion: kuma.io/v1alpha1
kind: MeshLoadBalancingStrategy
metadata:
  name: srv-000-policy
  namespace: kuma-system
spec:
  targetRef:
    kind: MeshService
    name: srv-000_kuma-test_svc_80
  to:
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-005_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-004_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-003_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-002_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-001_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-007_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-029_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-028_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-027_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-026_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-025_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-024_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-023_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-022_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-021_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-020_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-019_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-018_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-017_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-016_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-015_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-014_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-013_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-012_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-011_kuma-test_svc_80
  - default:
      loadBalancer:
        ringHash:
          hashPolicies:
          - header:
              name: x-affinity
            type: Header
        type: RingHash
    targetRef:
      kind: MeshService
      name: srv-010_kuma-test_svc_80
```

4. Observe high CPU usge

### Expected behavior

CPU isn't that high
