### ISSUE TITLE
Apply multiple resources using kumactl apply

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#132]
There should be an option to apply multiple resources

```
name: backend-01
mesh: default
type: Dataplane
networking:
  inbound:
    - interface: 127.0.0.1:8080:8090
      tags:
        service: backend
        version: "1.0"
        env: production
  outbound:
    - interface: :30000
      service: postgres
      servicePort: 5432

---
name: backend-02
mesh: default
type: Dataplane
networking:
  inbound:
    - interface: 127.0.0.1:8080:8090
      tags:
        service: backend
        version: "1.0"
        env: production
  outbound:
    - interface: :30000
      service: postgres
      servicePort: 5432
```

Resources can have different types.
