### ISSUE TITLE
Define container `ports` for MeshMetric so that PodMonitor can consume them

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#13281]
### Description

`PodMonitor` requires a port to be defined so that it can be matched and configure prometheus. For sidecars we can work around this by having a container patch:

```
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: sc-container-patch
  namespace: kuma-system
spec:
  sidecarPatch:
    - op: add
      path: /ports
      value: '[{ "containerPort": 5670, "name":"metrics"}]'
```

and then the sidecar shows up:

![Image](https://github.com/user-attachments/assets/dc2e9a10-b34a-424a-883c-8a8577838172)

for `Builtin Gateway` we need to change the controller code:

https://github.com/kumahq/kuma/blob/4df8c07617f5047c1be9d26405f4180251a2751e/pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go#L251

to generate the ports based on `MeshMetric`.

A possible other solution would be to have the Container Patch also patch gateways.

I used https://github.com/prometheus-operator/kube-prometheus?tab=readme-ov-file#quickstart to install prometheus operator.

xrel: https://github.com/kumahq/kuma/issues/5180#issuecomment-1353631150
