### ISSUE TITLE
MeshRateLimit validate `local.http.onRateLimit.status` to be >= 400

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#13319]
### Description

Today, it's possible to apply:

```yaml
type: MeshRateLimit
mesh: default
name: mrl
spec:
  from:
    - default:
        local:
          http:
            requestRate:
              num: 10
              interval: 1m0s
            onRateLimit:
              status: 204
```

But Envoy is going to [default the status to 429](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/local_ratelimit/v3/local_rate_limit.proto#envoy-v3-api-field-extensions-filters-http-local-ratelimit-v3-localratelimit-status):

> If this is set to < 400, 429 will be used instead. 

We need to improve validation and disallow `status` to be less than 400.
