### ISSUE TITLE
Verify if we need kuma.io/system-namespace: "true"

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#13343]
### Description

We can notice that we use secret webhook only for secrets in system namespace. We use `kuma.io/system-namespace: "true"` label which is set by pre-install-job. Seems like it might not be required since we can use 

```yaml
namespaceSelector:
  matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values: ["kuma-system"]
```
