### ISSUE TITLE
The MeshLoadBalancingStrategy is invalid: spec.to[0].targetRef.kind: value is not supported, only Mesh is allowed if loadBalancer is set

### ISSUE THREAD

**Issue by jijiechen** [kumahq/kuma#13443]
### Kuma Version

2.10.1

### Describe the bug

Kuma complained the error described on title when I was trying to apply a MeshLoadBalancingStrategy policy based on the example on this docs page:

https://kuma.io/docs/2.10.x/policies/meshloadbalancingstrategy/#ringhash-load-balancing-from-web-to-backend

I believe there is something wrong with the validation because I did not change the `spec.to[0].targetRef.kind`. The only change I did was changing the `spec.targetRef` to a MeshGateway with name match.

The original policy content on the doc is able to be applied, but after my change, it fails.

### To Reproduce

1. Create a mesh deployment on Kubernetes, without MeshService turned on
2. Try to create the policy mentioned

### Expected behavior

The policy is created successfully

### Additional context (optional)

Policy content:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshLoadBalancingStrategy
metadata:
  name: ring-hash
  namespace: kuma-demo
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshGateway
    name: edge-gateway
  to:
  - targetRef:
      kind: MeshService
      name: backend_kuma-demo_svc_8080
    default:
      loadBalancer:
        type: RingHash
        ringHash:
          hashPolicies:
          - type: Header
            header:
              name: x-header
```
