### ISSUE TITLE
Rethink merging behaviour of MeshHTTPRoutes

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#13440]
## Today's Behaviour

When several MeshHTTPRoutes have the same list of `matches`, [their confs are merged](https://kuma.io/docs/2.10.x/policies/meshhttproute/#merging):
```yaml
# MeshHTTPRoute route-1
rules:
  - matches: 
      - path:
          type: Exact
          name: /orders
        method: GET
    default: 
      filters: FILTERS_LIST
---
# MeshHTTPRoute route-2
rules:
  - matches: # key-2
      - path:
          type: Exact
          name: /orders
        method: GET
    default: 
      backendRefs: BACKENDS_LIST
```
result in
```yaml
rules:
  - matches:
      - path:
          type: Exact
          name: /orders
        method: GET
    default: 
      filters: FILTERS_LIST
      backendRefs: BACKENDS_LIST
```

## Problem 

While implementing MeshHTTPRoute support for policies, I realised it might not be the best way to handle routes.

When a client sends `GET /orders`, the request is processed through the merged configuration, meaning contributions from both `route-1` and `route-2` affect it.
However, we currently name the route as if it came solely from one resource (e.g., `kri_mhttpr_mesh-1___route-2`), hiding the fact that `route-1` also contributed.

This becomes problematic when different policies (e.g., MeshTimeouts) are attached to each route individually:
* `timeout-1` applies to `route-1`
* `timeout-2` applies to `route-2`

Since the merged configuration is attributed only to `route-2`, we would apply only `timeout-2`, ignoring `timeout-1`.

This is surprising because the request is influenced by both original routes.

Additionally, it's not aligned with the Gateway API approach that [states](https://gateway-api.sigs.k8s.io/api-types/httproute/#merging):
> Multiple HTTPRoutes can be attached to a single Gateway resource. Importantly, only one Route rule may match each request.

## Proposal

We're not gaining much from the fact that we're merging routes, because both `filters` and `backendRefs` are arrays, so they always do a full override. We need to create an MADR considering the posibility to stop merging MeshHTTPRoutes. It should also cover the migration.
