### ISSUE TITLE
Fix ordering of namespace scoped policies

### ISSUE THREAD

**Issue by Automaat** [kumahq/kuma#13576]
### Description

Right now when me merge policies we first sort them. When sorting we take into account policy info like `role`, `origin`, `targetRef`. 

We have found an issue when multiple policies are in the same namespace, we compare them by role and ignore namespace. This leads to the situation when we have two policies in the same namespace and more broad policy targeting `Mesh` will be labelled as consumer and specific policy to MeshService or Mesh*Route will be labelled as producer, causing broader policy to override specific one.
For example:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: mesh-timeout-1
  namespace: kuma-demo
  labels:
    kuma.io/mesh: default
spec:
  to:
  - targetRef:
      kind: Mesh
    default:
      http:
        streamIdleTimeout: 999s
---
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: mesh-timeout-2
  namespace: kuma-demo
  labels:
    kuma.io/mesh: default
spec:
  to:
  - targetRef:
      kind: MeshService
      name: demo-app
    default:
      http:
        streamIdleTimeout: 444s
```
In this case, `mesh-timeout-1` will be labelled as `consumer` policy and `mesh-timeout-2` will be labelled as `producer` policy. Causing `mesh-timeout-1` to override `mesh-timeout-2` which does not make sense from user point of view

We need to change how we compare policies here: 
https://github.com/kumahq/kuma/blob/a8788ad310103113a61fcd7557c8954a2d4a6977/pkg/plugins/policies/core/matchers/dataplane.go#L413-L415
We need to compare policies by role only when they are from different namespaces.

This change will need to be described in UPGRADE.md as this is a breaking change on how we merge namespace scoped policies.
