### ISSUE TITLE
Panic in Kuma CP when using targetRef.kind Dataplane with labels in MeshTrafficPermission policy

### ISSUE THREAD

**Issue by vermdeep** [kumahq/kuma#13584]
### Kuma Version

2.10.1

### Describe the bug

Getting following panic in Kuma CP when applying MeshTrafficPermission policy mentioned below:

```
runtime error: invalid memory address or nil pointer dereference
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick.func1
    github.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:75
runtime.gopanic
    runtime/panic.go:791
runtime.panicmem
    runtime/panic.go:262
runtime.sigpanic
    runtime/signal_unix.go:917
github.com/kumahq/kuma/pkg/plugins/policies/core/matchers.isSelectedByLabels
    github.com/kumahq/kuma/pkg/plugins/policies/core/matchers/dataplane.go:261
github.com/kumahq/kuma/pkg/plugins/policies/core/matchers.dppSelectedByPolicy
    github.com/kumahq/kuma/pkg/plugins/policies/core/matchers/dataplane.go:191
github.com/kumahq/kuma/pkg/plugins/policies/core/matchers.MatchedPolicies
    github.com/kumahq/kuma/pkg/plugins/policies/core/matchers/dataplane.go:64
github.com/kumahq/kuma/pkg/plugins/policies/meshtrafficpermission/graph/util.ComputeMtpRulesForTags
    github.com/kumahq/kuma/pkg/plugins/policies/meshtrafficpermission/graph/util/rule_builder.go:40
github.com/kumahq/kuma/pkg/plugins/policies/meshtrafficpermission/graph/services.BuildRules
    github.com/kumahq/kuma/pkg/plugins/policies/meshtrafficpermission/graph/services/reachable_services_graph.go:71
github.com/kumahq/kuma/pkg/plugins/policies/meshtrafficpermission/graph.Builder
    github.com/kumahq/kuma/pkg/plugins/policies/meshtrafficpermission/graph/reachable_graph.go:66
github.com/kumahq/kuma/pkg/xds/context.(*meshContextBuilder).BuildIfChanged
    github.com/kumahq/kuma/pkg/xds/context/mesh_context_builder.go:235
github.com/kumahq/kuma/pkg/xds/cache/mesh.(*Cache).GetMeshContext.func1
    github.com/kumahq/kuma/pkg/xds/cache/mesh/cache.go:61
github.com/kumahq/kuma/pkg/xds/cache/once.RetrieverFunc.Call
    github.com/kumahq/kuma/pkg/xds/cache/once/cache.go:43
github.com/kumahq/kuma/pkg/xds/cache/once.(*Cache).GetOrRetrieve.func1
    github.com/kumahq/kuma/pkg/xds/cache/once/cache.go:67
github.com/kumahq/kuma/pkg/xds/cache/once.(*once).Do.func1
    github.com/kumahq/kuma/pkg/xds/cache/once/once.go:13
sync.(*Once).doSlow
    sync/once.go:76
sync.(*Once).Do
    sync/once.go:67
github.com/kumahq/kuma/pkg/xds/cache/once.(*once).Do
    github.com/kumahq/kuma/pkg/xds/cache/once/once.go:12
github.com/kumahq/kuma/pkg/xds/cache/once.(*Cache).GetOrRetrieve
    github.com/kumahq/kuma/pkg/xds/cache/once/cache.go:59
github.com/kumahq/kuma/pkg/xds/cache/mesh.(*Cache).GetMeshContext
    github.com/kumahq/kuma/pkg/xds/cache/mesh/cache.go:52
github.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncDataplane
    github.com/kumahq/kuma/pkg/xds/sync/dataplane_watchdog.go:116
github.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).Sync
    github.com/kumahq/kuma/pkg/xds/sync/dataplane_watchdog.go:76
github.com/kumahq/kuma/pkg/xds/sync.(*dataplaneWatchdogFactory).New.func2
    github.com/kumahq/kuma/pkg/xds/sync/dataplane_watchdog_factory.go:45
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick
    github.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:81
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start
    github.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:46
github.com/kumahq/kuma/pkg/xds/server/callbacks.(*dataplaneSyncTracker).OnProxyConnected.func1
    github.com/kumahq/kuma/pkg/xds/server/callbacks/dataplane_sync_tracker.go:57
runtime.goexit
    runtime/asm_amd64.s:1700
```

MeshTrafficPermissionPolicy:
```yaml
type: MeshTrafficPermission
name: dee-service
mesh: dev
labels:
  owner: dee
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/service: nexus-service
  from:
  - targetRef:
      kind: MeshSubset
      tags:
        kuma.io/service: dee-service
    default:
      action: Allow
```

### To Reproduce

Create the mesh using below config:
```yml
type: Mesh
name: dev
skipCreatingInitialPolicies: ['*']
routing:
   defaultForbidMeshExternalServiceAccess: true
mtls:
  enabledBackend: ca-1
  backends:
    - name: ca-1
      type: builtin
      dpCert:
        rotation:
          expiration: 1d
      conf:
        caCert:
          RSAbits: 2048
          expiration: 1y
networking:
  outbound:
    passthrough: true
meshServices:
  mode: Exclusive
```

Start 2 dataplanes with below configs:
```yml
type: Dataplane
mesh: dev
name: dee-service-xxx
networking:
  address: 192.168.3.3
  inbound:
    - port: "80"
      servicePort: "3000"
      tags:
        kuma.io/service: dee-service
        kuma.io/protocol: grpc
  admin:
    port: "9902"
  transparentProxying:
    redirectPortInbound: "15006"
    redirectPortOutbound: "15001"
labels:
  service: dee-service
```

```yml
type: Dataplane
mesh: dev
name: nexus-service-yyyy
networking:
  address: 192.168.3.5
  inbound:
    - port: "80"
      servicePort: "3000"
      tags:
        kuma.io/service: nexus-service
        kuma.io/protocol: grpc
  admin:
    port: "9902"
  transparentProxying:
    redirectPortInbound: "15006"
    redirectPortOutbound: "15001"
labels:
  region: ap-south-1
  service: nexus-service
```

Apply the MeshTrafficPermission policy.

### Expected behavior

MeshTrafficPermission policy should work after applying.

### Additional context (optional)

- Using KUMA_EXPERIMENTAL_AUTO_REACHABLE_SERVICES
- Running Kuma CP in universal mode
- Using MeshSubset value for 'targetRef.kind' works as expected
