### ISSUE TITLE
Improve policy targetRef validation

### ISSUE THREAD

**Issue by Automaat** [kumahq/kuma#13614]
### Description

When we now specify invalid kind in policy targetRef we get simple:
```
The MeshTrafficPermission "*" is invalid: spec.targetRef.kind: value is not supported
```

We could improve this and make it more verbose with values that are supported we could have something like this:

```
The MeshTrafficPermission "*" is invalid: spec.targetRef.kind: MeshExternalService is not supported. Supported Kinds: Mesh, MeshSubset, MeshService, MeshServiceSubset, Dataplane
```

**Comment by slonka** [comment]
This can be done using if/else in OAPI 3.1 https://json-schema.org/understanding-json-schema/reference/conditionals or `oneOf`

```
components:
  schemas:
    MyObject:
      oneOf:
        - properties:
            typeA:
              enum: [a1]
            typeB:
              enum: [b11, b12]
          required: [typeA, typeB]
        - properties:
            typeA:
              enum: [a2]
            typeB:
              enum: [b21, b22, b23, b24]
          required: [typeA, typeB]
```
