### ISSUE TITLE
MeshService new targetRef format doesn't work

### ISSUE THREAD

**Issue by rdavyd** [kumahq/kuma#13612]
### Kuma Version

2.10.1

### Describe the bug

Tried new targetRef format:

```yaml
  targetRef:
    kind: MeshService
    name: client-mesh
    namespace: default
    sectionName: http
```
However it didn't work neither for `.spec.targetRef` nor in `to[]` clause.

https://github.com/kumahq/kuma/blob/de16dff4b64312df4e1c112be993806311953614/pkg/plugins/policies/core/matchers/dataplane.go#L202-L205

As far as I understand this only considers `kuma.io/service` tag

### To Reproduce

<details><summary>Create custom mesh:</summary>

```yaml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: dev
spec:
  meshServices:
    mode: Everywhere
  skipCreatingInitialPolicies:
  - '*'
```
</details>
<details><summary>Create client and server:</summary>

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: client-mesh
  namespace: default
  labels:
    app: client-mesh
    kuma.io/mesh: dev
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
    appProtocol: http
  selector:
    app: client-mesh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-mesh
  namespace: default
  labels:
    app: client-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-mesh
  template:
    metadata:
      labels:
        app: client-mesh
        kuma.io/sidecar-injection: "enabled"
        kuma.io/mesh: dev
    spec:
      containers:
      - name: client
        image: curlimages/curl:latest
        command:
        - tail
        - -f
        - /dev/null
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
      securityContext:
        fsGroup: 100
        runAsUser: 100
        runAsGroup: 101
      terminationGracePeriodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: svr-mesh
  namespace: default
  labels:
    app: svr-mesh
    kuma.io/mesh: dev
spec:
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
    appProtocol: http
  selector:
    app: svr-mesh

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svr-mesh
  namespace: default
  labels:
    app: svr-mesh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svr-mesh
  template:
    metadata:
      labels:
        app: svr-mesh
        kuma.io/sidecar-injection: "enabled"
        kuma.io/mesh: dev
    spec:
      containers:
      - image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
        name: echosvr
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: cache
          mountPath: /var/cache/nginx
        - name: tmp
          mountPath: /var/tmp/nginx
        - name: certs
          mountPath: /certs
        - name: run-nginx
          mountPath: /run/nginx
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
      securityContext:
        fsGroup: 100
        runAsUser: 100
        runAsGroup: 101
      volumes:
      - name: cache
        emptyDir: {}
      - name: certs
        emptyDir: {}
      - name: run-nginx
        emptyDir: {}
      - name: tmp
        emptyDir: {}
```
</details>

<details><summary>Create test policies:</summary>

```yaml
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  namespace: kuma-system
  name: allow-svr-mesh
  labels:
    kuma.io/mesh: dev
spec:
  targetRef:
   # this works fine
    kind: MeshService
    name: svr-mesh_default_svc_8080
  from:
  - targetRef:
      kind: Mesh
    default:
      action: Allow
---
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: svr-timeout
  namespace: default
  labels:
    kuma.io/mesh: dev
spec:
  targetRef:
    kind: MeshService
    name: client-mesh
    namespace: default
    sectionName: http
  to:
  - targetRef:
      kind: MeshService
      name: svr-mesh
      namespace: default
      sectionName: http
    default:
      idleTimeout: 50s
      connectionTimeout: 12s
      http:
        requestTimeout: 13s
```
</details>

After checking xDS configs on dataplane timeout is not configured. Also checked `MeshRetry` and `MeshHTTPRoute`, they didn't work either. Also policies are not seen as applied to respective `Dataplanes` in GUI.

### Additional context (optional)

Environment:

- k8s 1.31.5 on prem
- CNI kube-router 2.5.0
- kuma CNI enabled

**Comment by Automaat** [comment]
@rdavyd yes there are a lot of examples with MeshService, but only in `spec.to[].targetRef` section of a policy. It is never used in docs in `spec.targetRef`. In `spec.targetRef` it is deprecated in favour of `Dataplane` kind.  You should see a message with this deprecation when you applied your policies. 

The issue you have referred https://github.com/kumahq/kuma/issues/13360 is just an idea, we might not implement it as now added possibility to target workloads by `Dataplane` kind. MeshService is like k8s Service and Dataplane is basically equivalent to k8s pod. We treat MeshService as destination, that is why it only can be put in `spec.to[].targetRef` section of a policy.

**Comment by rdavyd** [comment]
@Automaat Sorry for premature issue closure. Didn't have time to test.
I'm using now `Dataplane` for the `spec.targetRef` and it selects target dataplanes correctly.
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: svr-timeout
  namespace: default
  labels:
    kuma.io/mesh: dev
spec:
  targetRef:
    kind: Dataplane
    labels:
      app: client-mesh
      k8s.kuma.io/namespace: default
  to:
  - targetRef:
      kind: MeshService
      name: svr-mesh
      # tried with or without namespace and sectionName. Tried sectionName "http" or "8080"
      namespace: default
      sectionName: http
    default:
      idleTimeout: 50s
      connectionTimeout: 12s
      http:
        requestTimeout: 13s
```

However I still cannot get new matching rules for the `MeshService` in the `to` section to work. Regardless of specifying or not `namespace` and `sectionName` GUI always shows resulting matcher as `kuma.io/service: svr-mesh`

![Image](https://github.com/user-attachments/assets/9c0ca6cf-c30a-4a65-b0e8-405446555acd)

Timeout configuration is also absent in `client-mesh` xDS configuration.

<details>
<summary>MeshService svr-mesh</summary>

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshService
metadata:
  annotations:
    kuma.io/display-name: svr-mesh
  labels:
    app: svr-mesh
    k8s.kuma.io/is-headless-service: "false"
    k8s.kuma.io/namespace: default
    k8s.kuma.io/service-name: svr-mesh
    kuma.io/env: kubernetes
    kuma.io/managed-by: k8s-controller
    kuma.io/mesh: dev
    kuma.io/origin: zone
    kuma.io/zone: default
  name: svr-mesh
  namespace: default
  ownerReferences:
  - apiVersion: v1
    kind: Service
    name: svr-mesh
    uid: a6441201-13b0-44e1-af95-6453445d957a
spec:
  identities:
  - type: ServiceTag
    value: svr-mesh_default_svc_8080
  ports:
  - appProtocol: http
    name: http
    port: 8080
    targetPort: 8080
  selector:
    dataplaneTags:
      app: svr-mesh
      k8s.kuma.io/namespace: default
  state: Available
status:
  addresses:
  - hostname: svr-mesh.mesh
    hostnameGeneratorRef:
      coreName: dev-mesh-service-old.kuma-system
    origin: HostnameGenerator
  - hostname: svr-mesh.default.mesh
    hostnameGeneratorRef:
      coreName: dev-mesh-service.kuma-system
    origin: HostnameGenerator
  dataplaneProxies:
    connected: 2
    healthy: 2
    total: 2
  hostnameGenerators:
  - conditions:
    - message: ""
      reason: Generated
      status: "True"
      type: Generated
    hostnameGeneratorRef:
      coreName: dev-mesh-service-old.kuma-system
  - conditions:
    - message: ""
      reason: Generated
      status: "True"
      type: Generated
    hostnameGeneratorRef:
      coreName: dev-mesh-service.kuma-system
  tls:
    status: NotReady
  vips:
  - ip: 10.10.187.74
```

</details>

MeshService svr-mesh has label `k8s.kuma.io/service-name: svr-mesh` not `kuma.io/service`.

Also tried this:
```yaml
  to:
  - targetRef:
      kind: MeshService
      labels:
        kuma.io/display-name: svr-mesh
        k8s.kuma.io/namespace: default
        kuma.io/zone: default
```
In this case GUI showed empty matcher `kuma.io/service:` and timeout was also absent in xDS configuration.
It works only if I specify MeshService name in old style: `name: svr-mesh_default_svc_8080`

**Comment by Automaat** [comment]
hmm, I've just recreated your setup and I've applied yours policy:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: svr-timeout
  namespace: default
  labels:
    kuma.io/mesh: dev
spec:
  targetRef:
    kind: Dataplane
    labels:
      app: client-mesh
      k8s.kuma.io/namespace: default
  to:
  - targetRef:
      kind: MeshService
      name: svr-mesh
      # tried with or without namespace and sectionName. Tried sectionName "http" or "8080"
      namespace: default
      sectionName: http
    default:
      idleTimeout: 50s
      connectionTimeout: 12s
      http:
        requestTimeout: 13s
```

And it worked for me. I got proper config:

```json
{
          "version_info": "ff618e7c-638c-4dda-b9ce-82de3981626e",
          "cluster": {
            "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
            "name": "dev_svr-mesh_default_default_msvc_8080",
            "type": "EDS",
            "eds_cluster_config": {
              "eds_config": {
                "ads": {},
                "resource_api_version": "V3"
              }
            },
            "connect_timeout": "12s",
            "typed_extension_protocol_options": {
              "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
                "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
                "common_http_protocol_options": {
                  "idle_timeout": "50s",
                  "max_connection_duration": "0s",
                  "max_stream_duration": "0s"
                },
                "explicit_http_config": {
                  "http2_protocol_options": {}
                }
              }
            }
          },
```

In gui I don't see it properly. But we are in the middle of rewriting inspect api, and it should work better with MeshService in kuma 2.12

Your mesh is configured with MeshService Everywhere so it also uses `kuma.io/service` that is probably why you see it in gui. Did you try searching in your xds config values for your policy?

**Comment by rdavyd** [comment]
> Did you try searching in your xds config values for your policy?

Yes, it is absent with new matching config. But when I revert to old matching `name: svr-mesh_default_svc_8080` it appears.
How can I inspect/debug more? Maybe there is some additional zone or mesh configuration required?

```yaml
apiVersion: kuma.io/v1alpha1
kind: Zone
mesh: dev
metadata:
  name: default
spec: {}
```

**Comment by Automaat** [comment]
There is nothing you can change on zone that will influence this.

That is weird as I have the same setup as you posted in the issue, and it works properly for me. Did you change something from your basic setup you've posted? Do you have any other policies? 
Do you even have proper cluster for your destination: `dev_svr-mesh_default_default_msvc_8080`? Do you use reachable services?

**Comment by Automaat** [comment]
I just see that you are enabling sidecar injection per pod not on namespace. When you don't enable it on namespace it will be created from kuma.io/service not from Kubernetes service. That is probably why you can only target it per kuma.io/service. 

But I still don't understand why this works for me as expected

**Comment by rdavyd** [comment]
> Do you use reachable services?

<details>
<summary>My kuma CP config</summary>

```yaml
    runtime:
      kubernetes:
        injector:
          sidecarContainer:
            ipFamilyMode: ipv4
            resources:
              limits:
                  cpu: 1000m
                  memory: 256Mi
              requests:
                  cpu: 50m
                  memory: 256Mi

          sidecarTraffic:
            excludeOutboundPorts:
            - 6033
            - 27017
            - 6379
            - 3000
            - 11211
            - 8500
            - 9092
        skipMeshOwnerReference: true
    experimental:
      autoReachableServices: true
    defaults:
      skipMeshCreation: true
      createMeshRoutingResources: false
      skipHostnameGenerators: true
```

</details>

> Did you change something from your basic setup you've posted?

No

> Do you have any other policies?

<details>
<summary>Relevant policies</summary>

```yaml
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: k8s-infra:kuma.io/MeshTrafficPermission:kuma-system/mgg-default-deny-all
    kuma.io/display-name: mgg-default-deny-all
  labels:
    argocd.argoproj.io/instance: k8s-infra
    k8s.kuma.io/namespace: kuma-system
    kuma.io/mesh: dev
    kuma.io/origin: zone
    kuma.io/policy-role: system
    kuma.io/zone: default
  name: mgg-default-deny-all
  namespace: kuma-system
spec:
  from:
  - default:
      action: Deny
    targetRef:
      kind: Mesh
  targetRef:
    kind: Mesh
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  namespace: kuma-system
  name: allow-svr-mesh
  labels:
    kuma.io/mesh: dev
spec:
  targetRef:
    kind: MeshService
    name: svr-mesh_default_svc_8080
  from:
  - targetRef:
      kind: Mesh
    default:
      action: Allow
---
apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: k8s-infra:kuma.io/MeshMetric:kuma-system/metrics-mgg
    kuma.io/display-name: metrics-mgg
  labels:
    argocd.argoproj.io/instance: k8s-infra
    k8s.kuma.io/namespace: kuma-system
    kuma.io/env: kubernetes
    kuma.io/mesh: dev
    kuma.io/origin: zone
    kuma.io/policy-role: system
    kuma.io/zone: default
  name: metrics-mgg
  namespace: kuma-system
spec:
  default:
    backends:
    - prometheus:
        path: /metrics
        port: 5670
      type: Prometheus
    sidecar:
      includeUnused: true
      profiles:
        appendProfiles:
        - name: Basic
        exclude:
        - match: envoy_listener_.*
          type: Regex
        - match: envoy_cluster_upstream_cx_http.*
          type: Regex
        - match: envoy_cluster_upstream_cx_connect.*
          type: Regex
        - match: envoy_cluster_external.*
          type: Regex
  targetRef:
    kind: Mesh
---
apiVersion: kuma.io/v1alpha1
kind: MeshPassthrough
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: k8s-infra:kuma.io/MeshPassthrough:kuma-system/mgg-passthrough
    kuma.io/display-name: mgg-passthrough
  labels:
    argocd.argoproj.io/instance: k8s-infra
    k8s.kuma.io/namespace: kuma-system
    kuma.io/mesh: dev
    kuma.io/origin: zone
    kuma.io/policy-role: system
    kuma.io/zone: default
  name: mgg-passthrough
  namespace: kuma-system
spec:
  default:
    passthroughMode: All
  targetRef:
    kind: Mesh
    proxyTypes:
    - Sidecar
```

</details>

Yes, cluster is present in xDS

```json
          "cluster": {
            "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
            "name": "svr-mesh_default_svc_8080",
            "type": "EDS",
            "eds_cluster_config": {
              "eds_config": {
                "ads": {},
                "resource_api_version": "V3"
              }
            },
            "connect_timeout": "5s",
            "typed_extension_protocol_options": {
              "envoy.extensions.upstreams.http.v3.HttpProtocolOptions": {
                "@type": "type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions",
                "common_http_protocol_options": {
                  "idle_timeout": "3600s",
                  "max_connection_duration": "0s",
                  "max_stream_duration": "0s"
                },
                "explicit_http_config": {
                  "http2_protocol_options": {}
                }
              }
            }
          },
```

I'll try enabling injection on namespace level.

EDIT: added xDS cluster
