### ISSUE TITLE
Permanently failed jobs can trigger /quitquitquit on a live pod

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#13617]
### Kuma Version

2.10.1

### Describe the bug

A job that permanently failed will be laying around for some time, if in that time another pod is spawned with the same IP on a next reconciliation loop we will try to call `/quitquitquit` on that IP which could kill a healthy pod.

Possible solutions:
1. In https://github.com/kumahq/kuma/pull/4964 we remove Dataplanes that have Completed, we can do the same for a permanently errored ones (not sure how easy it is to detect this, can we check `.status.conditions` and see that it's set to `Failed`?)
2. When we reconcile the pod we need to check if it's really that pod's dataplane

Workarounds:
1. Use sidecar containers (as per [this comment](https://github.com/kumahq/kuma/blob/17b95d4221d6f658b095c0da73c1ab8d72bc3ce7/pkg/plugins/runtime/k8s/controllers/pod_status_controller.go#L27) they don't run PodStatusReconciler which calls `/quitquitquit`)
2. Use `backoffLimit: 0` and `restartPolicy: OnFailure` - seems that k8s cleans up pods like that (unlike `restartPolicy: Never`

xrel: https://github.com/kumahq/kuma/pull/4964

### To Reproduce

Create a k8s cluster with kuma.

Apply this:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: fail-job-ns
  labels:
    kuma.io/sidecar-injection: "enabled"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fail-once-job
  namespace: fail-job-ns
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: fail-container
        image: busybox
        command: ["sh", "-c", "echo 'This job will fail' && exit 1"]
      restartPolicy: Never
```

Start watching logs:

```
kubectl logs svc/kong-mesh-control-plane -n kong-mesh-system -f | grep "ERROR"
```

When it failed add another job that is successful:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: success-job
  namespace: fail-job-ns
spec:
  template:
    spec:
      containers:
      - name: success-container
        image: busybox
        command: ["sh", "-c", "echo 'Hello, world!'"]
      restartPolicy: Never
  backoffLimit: 1
```

You should see an error like this:

```
2025-05-22T13:36:16.782Z	ERROR	kube-manager	Reconciler error	{"controller": "kuma-pod-status-controller", "controllerGroup": "", "controllerKind": "Pod", "Pod": {"name":"fail-once-job-1-dqrvw","namespace":"fail-job-ns"}, "namespace": "fail-job-ns", "name": "fail-once-job-1-dqrvw", "reconcileID": "7c43b489-872f-41d0-97ef-b1f5948df68c", "error": "envoy admin client failed. Most probably the pod is already going down.: unable to send POST to quitquitquit: Post \"https://10.42.0.17:9901/quitquitquit\": dial tcp 10.42.0.17:9901: i/o timeout", "errorVerbose": "Post \"https://10.42.0.17:9901/quitquitquit\": dial tcp 10.42.0.17:9901: i/o timeout\nunable to send POST to quitquitquit\ngithub.com/kumahq/kuma/pkg/envoy/admin.(*envoyAdminClient).PostQuit\n\tgithub.com/kumahq/kuma@v0.0.0-20250317113640-fed2256136e6/pkg/envoy/admin/client.go:125\ngithub.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers.(*PodStatusReconciler).Reconcile\n\tgithub.com/kumahq/kuma@v0.0.0-20250317113640-fed2256136e6/pkg/plugins/runtime/k8s/controllers/pod_status_controller.go:68\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:328\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:288\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:249\nruntime.goexit\n\truntime/asm_arm64.s:1223\nenvoy admin client failed. Most probably the pod is already going down.\ngithub.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers.(*PodStatusReconciler).Reconcile\n\tgithub.com/kumahq/kuma@v0.0.0-20250317113640-fed2256136e6/pkg/plugins/runtime/k8s/controllers/pod_status_controller.go:69\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile\n\tsigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:328\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:288\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.20.2/pkg/internal/controller/controller.go:249\nruntime.goexit\n\truntime/asm_arm64.s:1223"}
```

You can see that there is a request failing. You'd have to have a bunch of finished pods to hit the actual problem but I think you see my point.

### Expected behavior

A healthy pod should not be killed because it shared an ip of a failed job.
