### ISSUE TITLE
Build a PoC to use Spiffe compliant certs and separate generation from CA verification

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#13660]
### Description

let's just see what breaks and what needs specific attention.

This issue can be closed once we have: a demo with: a multi zone demo app with certs that are spiffe compliant

**Comment by lahabana** [comment]
@lukidzi to add a link to his branch and then close this issue

**Comment by lukidzi** [comment]
Hacked version of Spiffe https://github.com/lukidzi/kuma/tree/poc-spiffe

and instruction:

1. k3d cluster create global --network=kind
2. k3d cluster create zone1 --network=kind
3. k3d cluster create zone2 --network=kind
4. k3d image import --cluster global kumahq/kuma-init:0.0.0-preview.vlocal-build kumahq/kuma-cp:0.0.0-preview.vlocal-build kumahq/kuma-dp:0.0.0-preview.vlocal-build
5. k3d image import --cluster zone1 kumahq/kuma-init:0.0.0-preview.vlocal-build kumahq/kuma-cp:0.0.0-preview.vlocal-build kumahq/kuma-dp:0.0.0-preview.vlocal-build
6. k3d image import --cluster zone2 kumahq/kuma-init:0.0.0-preview.vlocal-build kumahq/kuma-cp:0.0.0-preview.vlocal-build kumahq/kuma-dp:0.0.0-preview.vlocal-build
7. kumactl install control-plane \
  --set "controlPlane.mode=global" \
  | kubectl apply -f -
8. Apply
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshProxyPatch
metadata:
  name: custom-template-1
  namespace: kuma-system
spec:
  targetRef:
    kind: Mesh
  default:
    appendModifications:
      - cluster:
          operation: Add
          value: |
            name: spire
            connectTimeout: 0.25s
            http2_protocol_options: {}
            loadAssignment:	
              clusterName: spire
              endpoints:	
              - lbEndpoints:	
                - endpoint:	
                    address:	
                      pipe:	
                        path: /run/spire/sockets/spire-agent.sock
---
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  mtls:
    enabledBackend: ca-1
    backends:
      - name: ca-1
        type: builtin
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: allow-all
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  from:
  - targetRef:
      kind: Mesh
    default:
      action: Allow
```
9. Install spire on zone1 and zone2
10. expose federation between clusters
```yaml
apiVersion: v1
kind: Service
metadata:
  name: spire-federation-lb
  namespace: spire-server
  labels:
    app: spire-server
spec:
  type: LoadBalancer
  ports:
    - name: federation
      port: 8443
      protocol: TCP
  selector:
    app.kubernetes.io/instance: spire
    app.kubernetes.io/name: server
```
11. https://spiffe.io/docs/latest/spire-helm-charts-hardened-advanced/federation/
12. Create auto register in both zones
```yaml
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: demo-app-test
spec:
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}"
  workloadSelectorTemplates:
    - "k8s:ns:kuma-demo"
  federatesWith: ["default.zone2"]
```
13. Install kuma in zone1
```
kumactl install control-plane \
  --set "controlPlane.mode=zone" \
  --set "controlPlane.zone=zone1" \
  --set "ingress.enabled=true" \
  --set "controlPlane.kdsGlobalAddress=grpcs://172.20.0.2:5685" \
  --env-var "KUMA_GENERAL_TRUSTED_DOMAIN=default.zone1" \
  --set "controlPlane.tls.kdsZoneClient.skipVerify=true" \
  | kubectl apply -f -
```
14. Install kuma in zone2
```
kumactl install control-plane \
  --set "controlPlane.mode=zone" \
  --set "controlPlane.zone=zone2" \
  --set "ingress.enabled=true" \
  --set "controlPlane.kdsGlobalAddress=grpcs://172.20.0.2:5685" \
  --env-var "KUMA_GENERAL_TRUSTED_DOMAIN=default.zone2" \
  --set "controlPlane.tls.kdsZoneClient.skipVerify=true" \
  | kubectl apply -f -
```
15. Install kuma demo


My values yaml for spire instalation: 
Replace: bundleEndpointURL with address of federation endpoint
zone1

```
global:
  openshift: false
  spire:
    recommendations:
      enabled: true
    namespaces:
      create: true
    ingressControllerType: ingress-nginx
    clusterName: default.zone1
    trustDomain:  default.zone1
    bundleConfigMap: spire-bundle-a
    caSubject:
      country: US
      organization: A
      commonName:  default.zone1

spire-server:
  federation:
    enabled: true
    ingress:
      enabled: true
  controllerManager:
    identities:
      clusterSPIFFEIDs:
        default:
          federatesWith:
          - default.zone2
      clusterFederatedTrustDomains:
        default.zone2:
          bundleEndpointProfile:
            endpointSPIFFEID: spiffe://default.zone2/spire/server
            type: https_spiffe
          bundleEndpointURL: https://172.20.0.6:8443
          trustDomain: default.zone2

spiffe-oidc-discovery-provider:
  enabled: true
  tls:
    spire:
      enabled: false
  ingress:
    enabled: true
```

zone2
```
global:
  openshift: false
  spire:
    recommendations:
      enabled: true
    namespaces:
      create: true
    ingressControllerType: ingress-nginx
    clusterName: default.zone2
    trustDomain:  default.zone2
    bundleConfigMap: spire-bundle-b
    caSubject:
      country: US
      organization: b
      commonName:  default.zone2

spire-server:
  federation:
    enabled: true
    ingress:
      enabled: true
  controllerManager:
    identities:
      clusterSPIFFEIDs:
        default:
          federatesWith:
          - default.zone1
      clusterFederatedTrustDomains:
        default.zone1:
          bundleEndpointProfile:
            endpointSPIFFEID: spiffe://default.zone1/spire/server
            type: https_spiffe
          bundleEndpointURL: https://172.20.0.4:8443
          trustDomain: default.zone1

spiffe-oidc-discovery-provider:
  enabled: true
  tls:
    spire:
      enabled: false
  ingress:
    enabled: true
```
