### ISSUE TITLE
MeshHTTPRoute policy not working on universal

### ISSUE THREAD

**Issue by vermdeep** [kumahq/kuma#13668]
### Kuma Version

2.10.1

### Describe the bug

MeshHTTPRoute policies are not working when running in universal mode in multi-zone-mode with `KUMA_EXPERIMENTAL_AUTO_REACHABLE_SERVICES=true`.

<br />
I tried following MeshHTTPRoutePolicies and none of them working:

1. With  actual name of auto-generated `MeshService` as seen in GUI, (not it's kuma.io/display-name):
<details><summary>
Show
</summary> 

```yaml
type: MeshHTTPRoute
name: pool3-nexus-service
mesh: dev
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: MeshService
      # Actual name of auto-generated mesh service as seen in GUI, (not kuma.io/display-name)
      name: pool2-nexus-service-7wz797d65f2v7564  
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: "/vermdeep"
        default:
           backendRefs:
             - kind: MeshService
               name: pool3-nexus-service-74dd2b6z64cb554v
```
</details>

2. Using `kuma.io/display-name` of auto-generated `MeshService` in place of `name`.

<details><summary>
Show
</summary> 

```yaml
type: MeshHTTPRoute
name: pool3-nexus-service
mesh: dev
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: MeshService
      name: pool2-nexus-service 
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: "/vermdeep"
        default:
           backendRefs:
             - kind: MeshService
               name: pool3-nexus-service
```
</details>

### To Reproduce

Apply the following policies:

**Mesh configuration:**
<details><summary> Show </summary>

```yaml
type: Mesh
name: dev
skipCreatingInitialPolicies: ['*']
routing:
   defaultForbidMeshExternalServiceAccess: true
mtls:
  enabledBackend: ca-1
  backends:
    - name: ca-1
      type: builtin
      dpCert:
        rotation:
          expiration: 1d
      conf:
        caCert:
          RSAbits: 2048
          expiration: 10y
networking:
  outbound:
    passthrough: true
meshServices:
  mode: Exclusive
```

</details>

**Dataplanes:**
<details><summary>Source service</summary>

```yaml
type: Dataplane
mesh: dev
name: nexus-service
networking:
  address: 10.0.0.1
  inbound:
    - port: "80"
      servicePort: "3000"
      tags:
        kuma.io/service: nexus-service
        kuma.io/protocol: grpc
        application: nexus-service
      serviceProbe:
        tcp: {}
  admin:
    port: "9902"
  transparentProxying:
    redirectPortInbound: "15006"
    redirectPortOutbound: "15001"
labels:
  region: ap-south-1
  service: nexus-service
```
</details>

<details><summary>
Destination services
</summary>

```yaml
---
type: Dataplane
mesh: dev
name: pool2-nexus-service
networking:
  address: 10.0.0.2
  inbound:
    - port: "80"
      servicePort: "3000"
      tags:
        kuma.io/service: pool2-nexus-service
        kuma.io/protocol: http
        application: pool2-nexus-service
      serviceProbe:
        tcp: {}
  admin:
    port: "9902"
  transparentProxying:
    redirectPortInbound: "15006"
    redirectPortOutbound: "15001"
labels:
  region: ap-south-1
  service: pool2-nexus-service
---
type: Dataplane
mesh: dev
name: pool3-nexus-service
networking:
  address: 10.0.0.2
  inbound:
    - port: "80"
      servicePort: "3000"
      tags:
        kuma.io/service: pool3-nexus-service
        kuma.io/protocol: http
        application: pool3-nexus-service
      serviceProbe:
        tcp: {}
  admin:
    port: "9902"
  transparentProxying:
    redirectPortInbound: "15006"
    redirectPortOutbound: "15001"
labels:
  region: ap-south-1
  service: pool3-nexus-service
```
</details>

**MeshTrafficPermissionPolicies:**
<details><summary>
Show
</summary>
 
```yaml
---
type: MeshTrafficPermission
name: pool3-nexus-service
mesh: dev
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/service: pool3-nexus-service
  from:
  - targetRef:
      kind: MeshSubset
      tags:
        kuma.io/service: nexus-service
    default:
      action: Allow
---
type: MeshTrafficPermission
name: pool2-nexus-service
mesh: dev
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/service: pool2-nexus-service
  from:
  - targetRef:
      kind: MeshSubset
      tags:
        kuma.io/service: nexus-service
    default:
      action: Allow
```
</details>

### Expected behavior

After applying routing policies, rules must be visible in envoy config_dump.

### Additional context (optional)

There was nothing in Kuma CP logs. Using `KUMA_EXPERIMENTAL_AUTO_REACHABLE_SERVICES=true` for automatic discovery of reachable services, I haven't tested without it.

**Comment by lobkovilya** [comment]
> Triage: if you apply MeshHTTPRoute policy on Zone and MeshService is synced from another zone, then you have to use `targetRef` with `labels` to reference the resource:
>
> ```yaml
> type: MeshHTTPRoute
> name: pool3-nexus-service
> mesh: dev
> spec:
>   targetRef:
>     kind: Mesh
>   to:
>   - targetRef:
>       kind: MeshService
>       labels:
>         kuma.io/display-name: pool2-nexus-service
>     rules:
>       - matches:
>         - path:
>             type: PathPrefix
>             value: "/vermdeep"
>         default:
>            backendRefs:
>              - kind: MeshService
>                labels:
>                  kuma.io/display-name: pool3-nexus-service
> ```
> 
> It's never correct to use hashed name inside the policy. 
> 
> Please checkout the docs section on referencing MeshServices in the policies https://kuma.io/docs/2.10.x/policies/introduction/#using-policies-with-meshservice-meshmultizoneservice-and-meshexternalservice

**Comment by vermdeep** [comment]
@lobkovilya Thanks for the help, above policy is working when using MeshService with labels. I want to do routing based on headers using the below policy, this is not working:
```yaml
type: MeshHTTPRoute
name: pool3-nexus-service
mesh: dev
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: MeshService
      labels:
        "kuma.io/display-name": pool2-nexus-service
    rules:
      - matches:
        - headers:
          - type: Exact
            name: "kuma-route"
            value: "pool2"
        default:
          backendRefs:
          - kind: MeshService
            labels:
              "kuma.io/display-name": pool2-nexus-service
      - matches:
        - headers:
          - type: Exact
            name: "kuma-route"
            value: "pool3"
        default:
          backendRefs:
          - kind: MeshService
            labels:
              "kuma.io/display-name": pool3-nexus-service
```

Following policy is working:
```yml
type: MeshHTTPRoute
name: pool3-nexus-service
mesh: dev
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: MeshService
      labels:
        "kuma.io/display-name": pool2-nexus-service
    rules:
      - matches:
        - headers:
          - type: Exact
            name: "x-nugget-kuma-route-id"
            value: "pool2"
        default:
          backendRefs:
          - kind: MeshService
            name: pool2-nexus-service
      - matches:
        - headers:
          - type: Exact
            name: "x-nugget-kuma-route-id"
            value: "pool3"
        default:
          backendRefs:
          - kind: MeshService
            name: pool3-nexus-service
```
This is adding multiple clusters in envoy for same service:

<img width="1019" alt="Image" src="https://github.com/user-attachments/assets/f969f74c-b753-4f89-93ee-b8a9609b02ff" />

---

**Newly added clusters are missing rules from MeshCircuitBreaker policy.** 

<details>
<summary> MeshCircuitBreakerPolicy </summary>

```yaml
type: MeshCircuitBreaker
name: all
mesh: dev
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: Mesh
    default:
      connectionLimits:
        maxConnections: 1024
        maxPendingRequests: 1024
        maxRetries: 2
        maxRequests: 4096
```
</details>

There is also one side-effect with above policy. If I scale down pods of `pool2-nexus-service` to 0 then all traffic which could have gone to `pool3-nexus-service` is also affected. 

This could have been avoided if I could use same `kuma.io/service` for both pool2 and pool3 dataplanes but with different labels. Then I could filter based on labels in the above policy. But I am not able to do this because on universal, MeshService have auto-generated labels and same MeshService will be created for both pool2 and pool3 irrespective of their labels/tags.

**Comment by vermdeep** [comment]
Above policies does not work when **not using** MeshService, I tried with below mesh config:
```yaml
meshServices:
  mode: ReachableBackends
``` 

In documentation, https://kuma.io/docs/2.10.x/policies/meshhttproute/#targetref-support-matrix `to[].targetRef.kind` is only MeshService so I think MeshHTTPServices should work with MeshService only, but in code examples, we have checkbox "I am using MeshService" which suggests that it should work without MeshService.

**Comment by lobkovilya** [comment]
I think you also need to specify port in `backendRefs` (looks like we're missing mentioning of this in docs):

```yaml
type: MeshHTTPRoute
name: pool3-nexus-service
mesh: dev
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: MeshService
      labels:
        kuma.io/display-name: pool2-nexus-service
    rules:
      - matches:
        - headers:
          - type: Exact
            name: "kuma-route"
            value: "pool2"
        default:
          backendRefs:
          - kind: MeshService
            port: 80 # <- here
            labels:
              kuma.io/display-name: pool2-nexus-service
      - matches:
        - headers:
          - type: Exact
            name: "kuma-route"
            value: "pool3"
        default:
          backendRefs:
          - kind: MeshService
            port: 80 # <- here
            labels:
              kuma.io/display-name: pool3-nexus-service
```

Could you please try that? I'll make sure to update the docs

**Comment by vermdeep** [comment]
Thank you, above policy is working fine.

But if I have 2 dataplanes with distinct tags/labels but with same `kuma.io/service`, then it is not working. Since for different labels/tags a single mesh service is generated. I tried below policy:
```yaml
type: MeshHTTPRoute
name: nexus-service
mesh: dev
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: MeshService
      labels:
        kuma.io/display-name: nexus-service
    rules:
      - matches:
        - headers:
          - type: Exact
            name: "kuma-route"
            value: "pool2"
        default:
          backendRefs:
          - kind: MeshService
            port: 80
            labels:
              kuma.io/display-name: nexus-service
              pool: pool2
      - matches:
        - headers:
          - type: Exact
            name: "kuma-route"
            value: "pool3"
        default:
          backendRefs:
          - kind: MeshService
            port: 80
            labels:
              kuma.io/display-name: nexus-service
              pool: pool3
```

**Dataplane Configurations, MeshTrafficPermissions policies**:
 <details>
<summary> Show </summary>

```yml
---
type: Dataplane
mesh: dev
name: pool2-nexus-service
networking:
  address: 10.0.0.2
  inbound:
    - port: "80"
      servicePort: "3000"
      tags:
        kuma.io/service: nexus-service
        kuma.io/protocol: http
        application: nexus-service
        pool: pool2
      serviceProbe:
        tcp: {}
  admin:
    port: "9902"
  transparentProxying:
    redirectPortInbound: "15006"
    redirectPortOutbound: "15001"
labels:
  region: ap-south-1
  pool: pool2
---
type: Dataplane
mesh: dev
name: pool3-nexus-service
networking:
  address: 10.0.0.5
  inbound:
    - port: "80"
      servicePort: "3000"
      tags:
        kuma.io/service: nexus-service
        kuma.io/protocol: http
        application: nexus-service
        pool: pool3
      serviceProbe:
        tcp: {}
  admin:
    port: "9902"
  transparentProxying:
    redirectPortInbound: "15006"
    redirectPortOutbound: "15001"
labels:
  region: ap-south-1
  pool: pool3
---
type: Dataplane
mesh: dev
name: fig-service
networking:
  address: 10.0.0.15
  inbound:
    - port: "80"
      servicePort: "3000"
      tags:
        kuma.io/service: fig-service
        kuma.io/protocol: http
        application: fig-service
      serviceProbe:
        tcp: {}
  admin:
    port: "9902"
  transparentProxying:
    redirectPortInbound: "15006"
    redirectPortOutbound: "15001"
labels:
  region: ap-south-1
---
type: MeshTrafficPermission
name: nexus-service
mesh: dev
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/service: nexus-service
  from:
  - targetRef:
      kind: MeshSubset
      tags:
        kuma.io/service: fig-service
    default:
      action: Allow
---
```

</details>

We want to do this way to avoid affecting traffic to pool3-nexus-service when pool2-nexus-service is down.

**Comment by lobkovilya** [comment]
> But if I have 2 dataplanes with distinct tags/labels but with same kuma.io/service, then it is not working. Since for different labels/tags a single mesh service is generated. 

Yes, because the following backendRef
```yaml
kind: MeshService
port: 80
labels:
  kuma.io/display-name: nexus-service
  pool: pool2
```

uses MeshService's labels (not Dataplane's labels).

If you need to create a traffic split between `pool: pool2` and `pool: pool3` then you need to create 2 MeshService, see [docs](https://kuma.io/docs/2.11.x/policies/meshhttproute/#traffic-split).

> We want to do this way to avoid affecting traffic to pool3-nexus-service when pool2-nexus-service is down.

I don't think MeshHTTPRoute is going to help you with this. By default on Kubernetes if pods of `pool3-nexus-service` are failing Kuma won't sent the traffic to them. If you want to define more advanced fallback behaviour you should consider using MeshCircuitBreaker, MeshHealthCheck, MeshLoadBalancingStrategy policies.

**Comment by vermdeep** [comment]
> Yes, because the following backendRef uses MeshService's labels (not Dataplane's labels).

Is there any way to specify custom labels to MeshService on universal?


> I don't think MeshHTTPRoute is going to help you with this. By default on Kubernetes if pods of pool3-nexus-service are failing Kuma won't sent the traffic to them

I think I was not able to explain the issue clearly. Let me explain the issue what I am facing. Let's assume we apply below MeshHTTPRoute:

```yaml
type: MeshHTTPRoute
name: pool3-nexus-service
mesh: dev
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: MeshService
      labels:
        kuma.io/display-name: pool2-nexus-service
    rules:
      - matches:
        - headers:
          - type: Exact
            name: "kuma-route"
            value: "pool2"
        default:
          backendRefs:
          - kind: MeshService
            port: 80
            labels:
              kuma.io/display-name: pool2-nexus-service
      - matches:
        - headers:
          - type: Exact
            name: "kuma-route"
            value: "pool3"
        default:
          backendRefs:
          - kind: MeshService
            port: 80
            labels:
              kuma.io/display-name: pool3-nexus-service
```

Now If pods of `pool2-nexus-service` are 0, envoy will not receive the configuration for `pool2-nexus-service`, since all dataplanes of `pool2-nexus-service` are down. This will affect the traffic intended for `pool3-nexus-service` even though pool3 service is up and running.

This will not happen if I have one service `nexus-service` having dataplanes with distinct tags (pool2 and pool3). In this case, envoy will receive the configuration for `nexus-service`, since atleast one dataplane of `nexus-service `is up. Therefore, traffic to pool3 dataplanes will work even if pool2 dataplanes are down.

**Comment by lobkovilya** [comment]
> Is there any way to specify custom labels to MeshService on universal?

Yes, you can specify custom labels on MeshService resource.

> Now If pods of pool2-nexus-service are 0, envoy will not receive the configuration for pool2-nexus-service, since all dataplanes of pool2-nexus-service are down. This will affect the traffic intended for pool3-nexus-service even though pool3 service is up and running.

If I understand your case correctly, Envoy still will receive Cluster for `pool2-nexus-service` because there is MeshService `pool2-nexus-service` (even if there are 0 DPPs for the service). 

So the policy you wrote should work well for pool3 even if there a no DPPs in pool2. If the actual behaviour is different then it's probably a bug.

**Comment by vermdeep** [comment]
> > Is there any way to specify custom labels to MeshService on universal?

> Yes, you can specify custom labels on MeshService resource.

Can you share how to do this ? 

> So the policy you wrote should work well for pool3 even if there a no DPPs in pool2. If the actual behaviour is different then it's probably a bug.

I will recheck and get back on this.


Btw, following is working as expected in `meshServices.mode: ReachableBackends`.
```yaml
type: MeshHTTPRoute
mesh: dev
name: nexus-service
labels:
  kuma.io/mesh: dev
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: MeshService
        name: nexus-service
      rules:
        - matches:
            - headers:
                - type: Exact
                  name: kuma-route
                  value: pool2
          default:
            backendRefs:
              - kind: MeshServiceSubset
                name: nexus-service
                tags:
                  pool: pool2
                weight: 1
        - matches:
            - headers:
                - type: Exact
                  name: kuma-route
                  value: pool3
          default:
            backendRefs:
              - kind: MeshServiceSubset
                name: nexus-service
                tags:
                  pool: pool3
                weight: 1
```
