### ISSUE TITLE
multi-zone mode cross zone access problem

### ISSUE THREAD

**Issue by luxurine** [kumahq/kuma#1371]
### Summary

SUMMARY_GOES_HERE

I have three k8s cluster with kuma deployed in multi-zone mod, I have tried the demo in this repo(https://github.com/subnetmarco/kuma-demo). The question is it looks like I can access from one zone to another only if both zone have the service to be consumed. For example, counter svc in zone-1 need access redis svc in zone-2, only if zone-1 also have a redis svc deployed. This is the way or I misunderstand something?
![image](https://user-images.githubusercontent.com/8802090/103329395-94afd300-4a97-11eb-84e2-bf41ba97ed83.png)
![image](https://user-images.githubusercontent.com/8802090/103329438-aa24fd00-4a97-11eb-80de-c306eb98437a.png)

### Steps To Reproduce

1. three k8s cluster deployed in multi-zone mode(one global cp, two remote cp)
2. install kuma cp, ingress, gateway; turn on mtls
3. deploy demo
**zone-1:**
```
# redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kuma-demo
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: "redis"
          ports:
            - name: tcp
              containerPort: 6379
          lifecycle:
            postStart:
              exec:
                command: ["/usr/local/bin/redis-cli", "set", "zone", "kuma01"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kuma-demo
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
```

**zone-2:**
```
# redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: kuma-demo
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: "redis"
          ports:
            - name: tcp
              containerPort: 6379
          lifecycle:
            postStart:
              exec:
                command: ["/usr/local/bin/redis-cli", "set", "zone", "kuma02"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: kuma-demo
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379

# counter svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  namespace: kuma-demo
spec:
  selector:
    matchLabels:
      app: counter
  replicas: 1
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
        - name: counter
          image: "thefosk/kuma-demo"
          env:
            - name: REDIS_HOST
              value: "redis.kuma-demo.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: APP_VERSION
              value: "1.0"
            - name: APP_COLOR
              value: "#efefef"
  replicas: 1
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
        - name: counter
          image: "thefosk/kuma-demo"
          env:
            - name: REDIS_HOST
              value: "redis.kuma-demo.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: APP_VERSION
              value: "1.0"
            - name: APP_COLOR
              value: "#efefef"
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: counter
  namespace: kuma-demo
  annotations:
    5000.service.kuma.io/protocol: http
    ingress.kubernetes.io/service-upstream: "true"
spec:
  selector:
    app: counter
  ports:
  - protocol: TCP
    port: 5000
  type: ClusterIP
```

It will work ok as follow:
![image](https://user-images.githubusercontent.com/8802090/103328862-6630f880-4a95-11eb-8ce1-43720d436754.png)
![image](https://user-images.githubusercontent.com/8802090/103328855-5c0efa00-4a95-11eb-9150-60d9d0977410.png)

But if I delete redis deployment and svc in zone-2, it will fail as follow:
![image](https://user-images.githubusercontent.com/8802090/103328933-a1cbc280-4a95-11eb-9a62-43f6aced3f24.png)

### Additional Details & Logs
none

- Version: 1.0.4
- Error logs: none
- Configuration: none
- Platform and Operating System: k8s v1.20.1

**Comment by subnetmarco** [comment]
You can consume other services as long as you use the `.mesh` DNS resolver that is built-in with Kuma by making the request to `{kuma-service-name}.mesh` on default port `80` (the port will be transparently replaced with the port of the service you are trying to consume, `80` is just a placeholder): https://kuma.io/docs/1.0.4/documentation/networking/#usage

**Comment by luxurine** [comment]
> You can consume other services as long as you use the `.mesh` DNS resolver that is built-in with Kuma by making the request to `{kuma-service-name}.mesh` on default port `80` (the port will be transparently replaced with the port of the service you are trying to consume, `80` is just a placeholder): https://kuma.io/docs/1.0.4/documentation/networking/#usage

Thanks for the reply.
I change the env:
```yaml
          env:
            - name: REDIS_HOST
              value: "redis.kuma-demo.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
```
to 
```yaml
          env:
            - name: REDIS_HOST
              value: "redis_kuma-demo_svc_6379.mesh"
            - name: REDIS_PORT
              value: "80"
```

It works. Thanks!
