### ISSUE TITLE
Panic in mads server during FetchMonitoringAssignments call

### ISSUE THREAD

**Issue by vermdeep** [kumahq/kuma#13730]
### Kuma Version

2.11.0

### Describe the bug

Getting following panic whenever call is made to mads endpoint:

```
2025-06-13T10:57:29.679Z	INFO	mads-server	http: panic serving 127.0.0.1:55972: runtime error: invalid memory address or nil pointer dereference
goroutine 2456736 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1947 +0xbe
panic({0x333f680?, 0x67bbc20?})
	runtime/panic.go:792 +0x132
github.com/kumahq/kuma/pkg/util/xds/v3.(*FallBackNodeHash).ID(0xc000816df8, 0x0)
	github.com/kumahq/kuma/pkg/util/xds/v3/fallback_node_hash.go:19 +0x40
github.com/envoyproxy/go-control-plane/pkg/cache/v3.(*snapshotCache).CreateWatch(0xc000e8daa0, 0xc00205c780, {0x0, 0xc003882f60, 0xc003882ff0, 0xc003882f90, 0x1, 0x0, 0xc003882fc0}, 0xc0004788c0)
	github.com/envoyproxy/go-control-plane@v0.13.4/pkg/cache/v3/simple.go:398 +0x9d
github.com/kumahq/kuma/pkg/mads/v1/service.(*server).FetchMonitoringAssignments(0xc0003c33e0, {0x42803d0, 0xc000478770}, 0xc00205c780)
	github.com/kumahq/kuma/pkg/mads/v1/service/mads.go:44 +0x1b6
github.com/kumahq/kuma/pkg/mads/v1/service.(*service).handleDiscovery(0xc000e19880, 0xc008229e00, 0xc000478700)
	github.com/kumahq/kuma/pkg/mads/v1/service/http.go:67 +0x251
github.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter(0x47de0c?, 0xc0068876a0?, 0x4ef313?)
	github.com/emicklei/go-restful/v3@v3.12.2/filter.go:23 +0x53
github.com/kumahq/kuma/pkg/mads/server.(*muxServer).Start.MetricsHandler.func1.1()
	github.com/kumahq/kuma/pkg/util/prometheus/gorestful_middleware.go:21 +0x1f
github.com/slok/go-http-metrics/middleware.Middleware.Measure({{0x426d6a0, 0xc000816d38}, {0x0, 0x0}, 0x0, 0x0, 0x0, 0xc001590e40}, {0x0, 0x0}, ...)
	github.com/slok/go-http-metrics@v0.13.0/middleware/middleware.go:142 +0x2f9
github.com/kumahq/kuma/pkg/mads/server.(*muxServer).Start.MetricsHandler.func1(0xc008229e00, 0xc000478700, 0xc00077e370)
	github.com/kumahq/kuma/pkg/util/prometheus/gorestful_middleware.go:20 +0x118
github.com/emicklei/go-restful/v3.(*FilterChain).ProcessFilter(0xc00218c820?, 0x426d400?, 0xc005672700?)
	github.com/emicklei/go-restful/v3@v3.12.2/filter.go:21 +0x42
github.com/emicklei/go-restful/v3.(*Container).dispatch(0xc0016dc090, {0x426d400, 0xc005672700}, 0xc005440500)
	github.com/emicklei/go-restful/v3@v3.12.2/container.go:296 +0x9ac
net/http.HandlerFunc.ServeHTTP(0xc000d3c840?, {0x426d400?, 0xc005672700?}, 0x28?)
	net/http/server.go:2294 +0x29
net/http.(*ServeMux).ServeHTTP(0x3a48c75?, {0x426d400, 0xc005672700}, 0xc005440500)
	net/http/server.go:2822 +0x1c4
github.com/emicklei/go-restful/v3.(*Container).ServeHTTP(0x419ea5?, {0x426d400?, 0xc005672700?}, 0xc005672701?)
	github.com/emicklei/go-restful/v3@v3.12.2/container.go:316 +0x1cb
net/http.serverHandler.ServeHTTP({0x425f238?}, {0x426d400?, 0xc005672700?}, 0x1?)
	net/http/server.go:3301 +0x8e
net/http.(*conn).serve(0xc003984090, {0x4280328, 0xc0016e2240})
	net/http/server.go:2102 +0x625
created by net/http.(*Server).Serve in goroutine 460
	net/http/server.go:3454 +0x485
```

MeshMetric policy used:
```yaml
type: MeshMetric
mesh: preprod
name: all-generated
spec:
  targetRef:
    kind: Mesh
  default:
    sidecar:
      includeUnused: false
      profiles:
        appendProfiles:
        - name: All
    backends:
    - type: Prometheus
      prometheus:
        clientId: default
        port: 5670
        path: "/metrics"
        tls:
          mode: "Disabled"
```
Mesh configuration:
```yaml
type: Mesh
name: dev
skipCreatingInitialPolicies: ['*']
routing:
   defaultForbidMeshExternalServiceAccess: true
mtls:
  enabledBackend: ca-1
  backends:
    - name: ca-1
      type: builtin
      dpCert:
        rotation:
          expiration: 1d
      conf:
        caCert:
          RSAbits: 2048
          expiration: 10y
networking:
  outbound:
    passthrough: true
meshServices:
  mode: ReachableBackends
```

### To Reproduce

Apply the above policies, and make the following request:
```sh
curl -X POST http://127.0.0.1:5676/v3/discovery:monitoringassignments?fetch-timeout=2m -H "Content-Type: application/json" -d {} 

```

### Expected behavior

When htting mads endpoint, it should return all dataplanes which can be hit.

### Additional context (optional)

Running in multi-zone universal mode with default `monitoringAssignmentServer` configuration in kuma-cp config.
Also, have experimental auto reachable backends enabled.
