### ISSUE TITLE
Proto `oneof` is incorrectly mapped to oapi definition

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#13772]
### Description

DataSource

```
message DataSource {

  oneof type {
    // Data source is a secret with given Secret key.
    string secret = 1;
    // Data source is a path to a file.
    // Deprecated, use other sources of a data.
    string file = 2;
    // Data source is inline bytes.
    google.protobuf.BytesValue inline = 3;
    // Data source is inline string
    string inlineString = 4;
  }
}
```

ends up as:

```
    ProvidedCertificateAuthorityConfig:
      properties:
        cert:
          properties:
            Type: true
          required:
            - Type
          type: object
        key:
          properties:
            Type: true
          required:
            - Type
          type: object
      type: object
```

Which is incorrect.
