### ISSUE TITLE
Missing envoy_cluster_name=~"localhost_.*" in multiple envoy metrics

### ISSUE THREAD

**Issue by Jdelachi** [kumahq/kuma#13789]
### Kuma Version

2.10

### Describe the bug

After installing the kuma observability, some Grafana dashboard are empty. After troubleshooting, it is cause by missing metrics for localhost services.

### Kuma Dataplane Latency dahboard example

For metrics such as `envoy_cluster_upstream_rq_time_bucket`, the only "envoy_cluster_name" populated are `kuma_readiness` and `_kuma_metrics_hijacker`. 

This issue causes the promql to return an empty value `sum(histogram_quantile(0.99, rate(envoy_cluster_upstream_rq_time_bucket{kuma_io_zone=~"$zone",mesh="$mesh",envoy_cluster_name=~"localhost_.*",dataplane="$dataplane"}[$__rate_interval])))`.

I enabled the MeshMetric with the profile `All` for the test:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
  labels:
    k8s.kuma.io/namespace: kuma-system
    k8slens-edit-resource-version: v1alpha1
    kuma.io/mesh: default
    kuma.io/policy-role: system
  name: metrics-default
  namespace: kuma-system
spec:
  default:
    backends:
      - prometheus:
          path: /metrics
          port: 5670
        type: Prometheus
    sidecar:
      includeUnused: true
      profiles:
        appendProfiles:
          - name: All
```

### To Reproduce

Run `kumactl install observability | kubectl apply -f -` and create the MeshMetric resource provided previously.

The Kuma Dataplane dashboard will not show the latency chart.

### Expected behavior

The Kuma Dataplane dashboard shows the latency chart with data.
