### ISSUE TITLE
Automate annotations for pods in the Mesh

### ISSUE THREAD

**Issue by nickolaev** [kumahq/kuma#1386]
### Summary

Today Kuma provides all the automation to expose the cp and do metrics to Prometheus but still leaves the application metrics to the user as specified in the [docs](https://kuma.io/docs/1.0.4/policies/traffic-metrics/#expose-metrics-from-applications)

To better the user experience, we can introduce an automated injection of:
```
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "1234"
        prometheus.io/path: "/non-standard-path"
```

One idea is to have a generic mechanism to inject arbitrary annotations to all pods in the mesh. But we can also have this done only for metrics and these specific annotations.

Proposed by @svenwal
