### ISSUE TITLE
Mesh creation wizard in UI generates wrong YAML

### ISSUE THREAD

**Issue by svenwal** [kumahq/kuma#1388]
### Summary

When using the wizard in the GUI to create a new Mesh and enabling one or more options (like mTLS, Logging, ...) the created YAML is wrong

### Steps To Reproduce

1. Use the wizard to create a mesh, choose at least one optional setting
2. Apply the generated YAML
3. Look at the created Mesh - it misses the options

When looking at the YAML you'll notice all the options are not (as they should be) underneith a "spec".

So it should be 

```
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
**spec:**
  mtls: 
    enabledBackend: ca-1
    backends: 
      - name: ca-1
        type: builtin
```

but instead see below the "spec" is missing in the generated YAML

### Additional Details & Logs

- Version: Kong Mesh 1.1.1
- Error logs
- Configuration

Generated YAML:

```
echo "apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata: 
  name: test
mtls: 
  enabledBackend: test
  backends: 
    - name: test
      type: builtin
  enabled: true
tracing: 
  defaultBackend: test
  backends: 
    - name: test
      type: zipkin
      conf: 
        sampling: 100
        url: 'http://test'
logging: 
  backends: 
    - name: test
      format: '{ "destination": "%KUMA_DESTINATION_SERVICE%", "destinationAddress": "%UPSTREAM_LOCAL_ADDRESS%", "source": "%KUMA_SOURCE_SERVICE%", "sourceAddress": "%KUMA_SOURCE_ADDRESS%", "bytesReceived": "%BYTES_RECEIVED%", "bytesSent": "%BYTES_SENT%"}'
      type: tcp
      conf: 
        address: '127.0.0.1:5000'
metrics: 
  enabledBackend: test
  backends: 
    - name: test
      type: prometheus
      conf: 
        port: 5670
        path: /metrics" | kubectl apply -f -
```

- Platform and Operating System
K3d / Kubernetes
