### ISSUE TITLE
DNS for overlapping `kuma.io/service` in different meshes

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#1450]
### Summary
It is not very clear in the doc but I believe that each mesh should be a view isolated from other meshes.

This doesn't seem to be very much the case with DNS in `Universal` mode as a user can resolve DNS names of services that run on a different Mesh.
This is ok in most cases but when trying to offer strong isolation it seems unreasonable to have service meshes leak from one mesh to another.

### Steps To Reproduce

1. start serviceA in mesh1
2. start serviceB in mesh2
3. resolve serviceB from serviceA

### Suggestion

Envoy now provides a [DNSFilter](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/listeners/dns_filter).
It's likely possible to add the domains/vips to the envoy configuration at the same time that outbounds are added for example.
To do this we'd likely need to pass the domains in the outbound resources to then be able add the filter with a generator.
 
Advantage:
- Envoy will act as DNS and the CP won't have to be running a DNS server anymore.
Drawback:
- This feature in envoy is not production ready yet.

**Comment by lahabana** [comment]
If you think this would be a workable solution I'd be happy to work on it soon-ish.

**Comment by jakubdyszkiewicz** [comment]
Let me start with a short introduction to how Transparent Proxy and Kuma DNS works.
Envoy exposes one real listener on port 15001 and virtual listeners for each service that does not bind to the port.
When iptables hijacks the outgoing request, Envoy will extract original IP:port, go through virtual listeners and see if there is any match, if so then it does load balancing to the proper instance.

Example: DNS resolves `serviceB.mesh` to the IP 240.0.0.1 and has two instances with real IP of 10.0.0.1, and 10.0.0.2.
When application in the same mesh as serviceB (mesh2) tries to consume B by `http://serviceB.mesh`, the app will resolve it to 240.0.0.1, make a request to this address, Envoy will know that there is a virtual listener with this IP and will do a load balancing to one of the instances.

Now, when we generate Envoy configuration we take into account only Dataplanes from the same mesh. Cross mesh traffic is not supported, because there is strong mesh isolation.
Following your example, if serviceA from mesh1 tries to consume serviceB from mesh2 what will happen is that `http://serviceB.mesh` will resolve to 240.0.0.1 BUT, the request will just fail because in serviceA from mesh1 there is no virtual listener to serviceB from mesh2.
Therefore even if we resolve the DNS to something, we won't even try to send a traffic to serviceB from mesh2.

Even if there is serviceB in two different meshes, that's fine because we will only pass traffic to the proper mesh.

We could have designed the DNS so you would have to explicitly pass the mesh name like this `serviceB.mesh2.mesh`, but we wanted Mesh topology to be transparent from the application perspective. You can move your app to a different Mesh without changing the app itself.

You are right that there is a new DNSFilter in Envoy so we can embed the DNS server in Envoy itself. I think there are a couple of great things about this approach:
* As you said, we don't have to run DNS server anymore in the CP
* DNS will be much faster since DNS request will be kept inside the VM
* You don't have to have stable Virtual IPs between Control Plane instances
* More High Availability! When CP is down, DNS on the machine will still work

Drawbacks:
* DNS story for users is already complicated. Having two options to deploy them will be confusing, but is an option to always point DNS to the localhost always possible?

@nickolaev how ECS would fit to such DNS deployment?

**Comment by nickolaev** [comment]
ECS won't be a problem at all IMHO.

I see only positives in the proposed approach, I think you both outlined them. I can only add that the experience of maintaining the DNS in the CP and forwarding the hosts to it is not necessarily the easiest one. I'd gladly drop the DNS in kuma-cp.
Saying this - I don't think the approach should be to have both options, I would prefer to just move to the Envoy DNS Filter. One thing - on K8s we probably would want to add Cluster IPs there so the resolution is really really fast, avoiding CoreDNS.

I am 100% about this approach, and speaking about production readiness - where was that stated?

**Comment by lahabana** [comment]
It's in the envoy docs:

> https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/udp_filters/dns_filter

Though I looked at Envoy issues and the only semi-serious issue I see is: https://github.com/envoyproxy/envoy/issues/12508

**Comment by lahabana** [comment]
Ok so I managed to hack around.
The trickiest part was to pass information from `dns.VIPOutbounds` and the generator created.
I think a suitable option would be to add some metadata to `mesh_proto.Outbound` do you think that's something we'd want? If not how do you see this?

Also there's a bunch of things to figure out with transparent proxying and UDP Listeners. I'll look at this more tomorrow.

**Comment by lahabana** [comment]
I'm going to POC this with cheating with Tags to pass this info. I'm not sure it's the right thing to do but it will make it possible to test things out

**Comment by lahabana** [comment]
So I've just wrote a POC for this: https://github.com/lahabana/kuma/commit/f27cd908d937d3acfa9f11b3c7e9d566001e89b4

I've made it work with our CNI-plugin so that the we route `169.254.53.53:53` to envoy passthrough port.
I believe the best thing to do to make this production grade is to introduce it as a Policy.

Something like

```yaml
type: Dns
name: default-dns
mesh: default
selectors:
- match:
    kuma.io/service: '*'
conf:
  upstreamResolvers: # A list of resolvers to use when we are resolving things not in the local domain
     - "8.8.8.8:53"
     - "4.4.4.4:53"
  address: "169.254.53.53" # Optional by default it uses 0.0.0.0
  port: 53 # Optional by default it uses the transparent outbound port or 53 if the port is not set
  domain: "mesh" # The top domain to use (Optional default to mesh)
  tag: "kuma.io/domain" # The tag to use to build the domain .i.e: "${this}.mesh" (Optional defaults to "kuma.io/service")
```

This enables us to also get rid of the usage of Vips as the DNSProxy will directly use Envoy clusters.

For example:

```
dig @192.168.0.53 hello-task_http.m

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> @192.168.0.53 hello-task_http.mesh
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62981
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;hello-task_http.mesh.		IN	A

;; ANSWER SECTION:
hello-task_http.mesh.	300	IN	A	10.1.0.6
hello-task_http.mesh.	300	IN	A	10.1.0.7

;; Query time: 3 msec
;; SERVER: 192.168.0.53#53(192.168.0.53)
;; WHEN: Mon Jan 25 13:13:04 UTC 2021
;; MSG SIZE  rcvd: 110
```

```
kumactl get dataplanes -oyaml
items:
- creationTime: "0001-01-01T00:00:00Z"
  mesh: default
  modificationTime: "0001-01-01T00:00:00Z"
  name: 66d20f73-9686-6998-e23c-ae51fc1543f2-hello-task-32eab634
  networking:
    address: 10.1.0.7
    inbound:
    - address: 10.1.0.7
      port: 80
      serviceAddress: 172.18.0.7
      tags:
        kuma.io/service: hello-task_http
    outbound:
    - address: 240.0.0.1
      port: 80
      tags:
        kuma.io/service: hello-task_http
    transparentProxying:
      redirectPortInbound: 19060
      redirectPortOutbound: 16564
  type: Dataplane
- creationTime: "0001-01-01T00:00:00Z"
  mesh: default
  modificationTime: "0001-01-01T00:00:00Z"
  name: dcf2b661-1d1e-1e3d-ec26-7d6000744018-hello-task-533823a6
  networking:
    address: 10.1.0.6
    inbound:
    - address: 10.1.0.6
      port: 80
      serviceAddress: 172.18.0.6
      tags:
        kuma.io/service: hello-task_http
    outbound:
    - address: 240.0.0.0
      port: 80
      tags:
        kuma.io/service: debug-task_http
    - address: 240.0.0.1
      port: 80
      tags:
        kuma.io/service: hello-task_http
    transparentProxying:
      redirectPortInbound: 18997
      redirectPortOutbound: 16248
  type: Dataplane
```

The envoy config from an instance:

```json
    {
     "name": "kuma:dns",
     "active_state": {
      "version_info": "15ea3805-db7a-4a46-b55c-dff37e532c76",
      "listener": {
       "@type": "type.googleapis.com/envoy.api.v2.Listener",
       "name": "kuma:dns",
       "address": {
        "socket_address": {
         "protocol": "UDP",
         "address": "0.0.0.0",
         "port_value": 16862
        }
       },
       "filter_chains": [
        {}
       ],
       "listener_filters": [
        {
         "name": "envoy.filters.udp.dns_filter",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.filters.udp.dns_filter.v3alpha.DnsFilterConfig",
          "stat_prefix": "dns_filter",
          "server_config": {
           "inline_dns_table": {
            "virtual_domains": [
             {
              "name": "hello-task_http.mesh",
              "endpoint": {
               "cluster_name": "hello-task_http"
              }
             }
            ],
            "known_suffixes": [
             {
              "suffix": "mesh"
             }
            ]
           }
          },
          "client_config": {
           "upstream_resolvers": [
            {
             "socket_address": {
              "address": "8.8.8.8",
              "port_value": 53
             }
            }
           ],
           "max_pending_lookups": "256"
          }
         }
        }
       ],
       "traffic_direction": "OUTBOUND",
       "reuse_port": true
      },
      "last_updated": "2021-01-25T13:21:44.264Z"
     }
```

I believe introducing this as a policy makes it easy to transition and pretty flexible to users.

Let me know what you think about it @jakubdyszkiewicz  and @nickolaev. If that sounds good I can do a good part of the work in the coming week.
