### ISSUE TITLE
On universal service insights subscription never close

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#1605]
We have a dataplane still registered in our CP 7 days after shutting down:
```
dataplaneInsight:
    subscriptions:
    - connectTime: "2021-02-16T09:49:24.276245793Z"
      controlPlaneInstanceId: kuma-cp-remote1-1-53b4
      id: e27921d0-e715-48a4-a5c7-c451ab984c60
      status:
        cds:
          responsesAcknowledged: "4"
          responsesSent: "3"
        eds:
          responsesAcknowledged: "6"
          responsesSent: "4"
        lastUpdateTime: "2021-02-16T09:51:46.285163628Z"
        lds:
          responsesAcknowledged: "4"
          responsesSent: "3"
        rds: {}
        total:
          responsesAcknowledged: "14"
          responsesSent: "10"
      version:
        envoy:
          build: 0717f49fef0dac3818cd7cdc52bf18e0ae1f7a2c/1.16.1/clean-getenvoy-486d4e2-envoy/RELEASE/BoringSSL
          version: 1.16.1
        kumaDp:
          buildDate: "2021-01-22T15:27:02Z"
          gitCommit: a18e53c511653d5f22dbc9974fc78d1fb0675ded
          gitTag: 1.0.6
          version: 1.0.6
  mesh: mesh1
  modificationTime: "0001-01-01T00:00:00Z"
  name: remote1.d52f6637-1f33-cf8c-ffd2-c3926ace8442-debug-task-d2bcc39c
  type: DataplaneOverview
```

This DP can't possibly be still running (the vm it was on was destroyed).

What I think is happening:

- `OnStreamClosed` is never called (Not sure why though)
- Because the client never reconnects the subscription is never opened or closed
- Because `OnStreamClosed` is never called the dataplane_lifecycle doesn't work either

The quick hack for this would be to add support for stalled subscriptions in the `gc.collector` but I'm not sure we can expect requests or responses to be sent if nothing changes on either side.
