### ISSUE TITLE
Unable to invoke a service through a transparent universal mesh that happens to be running locally

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1742]
### Summary

I have a universal transparent mode DPP and I have service2 deployed on that VM. service2 is exposed through that DPP. All good. But that envoy doesn’t get a listener for the IP of service2. CP DNS correctly resolves service2.mesh to 240.0.0.4 but the DP config has no inbound setting for 240.0.0.4. So I can’t call a service through the mesh that happens to be running locally.

### Steps To Reproduce

```
name: httpbin2-efhlko
mesh: default
type: DataplaneOverview
networking: 
  address: ip-172-31-32-130.us-east-2.compute.internal
  inbound: 
    - port: 9124
      servicePort: 8124
      serviceAddress: 127.0.0.1
      tags: 
        kuma.io/protocol: http
        kuma.io/service: service2
    - port: 8080
      servicePort: 5000
      serviceAddress: 127.0.0.1
      tags: 
        kuma.io/protocol: http
        kuma.io/service: httpbin2
  outbound: 
    - address: 240.0.0.1
      port: 80
      tags: 
        kuma.io/service: grpc
    - address: 240.0.0.0
      port: 80
      tags: 
        kuma.io/service: httpbin
    - address: 240.0.0.2
      port: 80
      tags: 
        kuma.io/service: httpbin2
    - address: 240.0.0.3
      port: 80
      tags: 
        kuma.io/service: service1
  transparentProxying: 
    redirectPortInbound: 15006
    redirectPortOutbound: 15001
metrics: 
  type: prometheus
  conf: 
    path: /metrics
    port: 5670
    skipMTLS: true
```

```
# dig service2.mesh
; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.amzn2.2 <<>> service2.mesh
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59502
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available
;; QUESTION SECTION:
;service2.mesh.			IN	A
;; ANSWER SECTION:
service2.mesh.		60	IN	A	240.0.0.4
;; Query time: 1 msec
;; SERVER: 172.31.32.87#53(172.31.32.87)
;; WHEN: Thu Mar 25 18:37:45 UTC 2021
;; MSG SIZE rcvd: 60
```

I can create an additional service that gets bound to 240.0.0.5 which shows up in the dataplane resource but 240.0.0.4 is just skipped
