### ISSUE TITLE
Helm Control Plane Annotations Template Invalid

### ISSUE THREAD

**Issue by nbrink91** [kumahq/kuma#1750]
### Summary

Helm chart template is generating invalid cp service template when modifying annotations.

### Steps To Reproduce

1. Add annotation to .Values.controlPlane.service.annotations
2. Generate the helm template `helm template --debug -n kuma-system kuma-system .`
3. Review the kuma/templates/cp-service.yaml output and you will see the additional incorrect formatting with an extra indent.
```yaml  
annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5680"
      somekey: "somevalue"
```
### Additional Details & Logs

- Version
1.1.1 of the Helm chart
- Error logs
Error: YAML parse error on kuma/templates/cp-service.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key.
- Configuration
```yaml
controlPlane:
  service:
    annotations:
      somekey: somevalue
```
- Platform and Operating System
Reproduced in MacOS and Windows
- Installation Method (Helm, kumactl, AWS CloudFormation, etc.)
Helm
