### ISSUE TITLE
EDS returning envoy IP not service IP for universal service

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1754]
### Summary

EDS is returning the envoy address instead of the service address. This causes traffic, including health checks, to go back through envoy instead of directly through the service. 

### Steps To Reproduce

Below, envoy should have `127.0.0.1:5000` not `172.31.29.90:8080` for the `echo-service_default_svc_8080` cluster

```
kuma-dp run \
      --name=internalhttpbin-52i8jq \
      --mesh=default \
      --cp-address=https://ip-172-31-20-18.us-east-2.compute.internal:5678/ \
      --dataplane="type: Dataplane
mesh: default
name: internalhttpbin-52i8jq
networking: 
  address: ip-172-31-29-90.us-east-2.compute.internal
  outbound:
    - port: 10000
      tags: 
        kuma.io/service: externalhttpbin
    - port: 10001
      tags: 
        kuma.io/service: postman-echo
    - port: 10002
      tags: 
        kuma.io/service: internalhttpbin
    - port: 10003
      tags:
        kuma.io/service: echo-service_default_svc_8080
  inbound: 
    - port: 8080
      servicePort: 5000
      serviceAddress: 127.0.0.1
      tags: 
        kuma.io/service: echo-service_default_svc_8080
        kuma.io/zone: universal
        kuma.io/protocol: http" \
      --dataplane-token-file=kuma-token-internalhttpbin-52i8jq
```

```
echo-service_default_svc_8080::default_priority::max_connections::1024
echo-service_default_svc_8080::default_priority::max_pending_requests::1024
echo-service_default_svc_8080::default_priority::max_requests::1024
echo-service_default_svc_8080::default_priority::max_retries::3
echo-service_default_svc_8080::high_priority::max_connections::1024
echo-service_default_svc_8080::high_priority::max_pending_requests::1024
echo-service_default_svc_8080::high_priority::max_requests::1024
echo-service_default_svc_8080::high_priority::max_retries::3
echo-service_default_svc_8080::added_via_api::true
echo-service_default_svc_8080::172.31.29.90:8080::cx_active::0
echo-service_default_svc_8080::172.31.29.90:8080::cx_connect_fail::0
echo-service_default_svc_8080::172.31.29.90:8080::cx_total::0
echo-service_default_svc_8080::172.31.29.90:8080::rq_active::0
echo-service_default_svc_8080::172.31.29.90:8080::rq_error::0
echo-service_default_svc_8080::172.31.29.90:8080::rq_success::0
echo-service_default_svc_8080::172.31.29.90:8080::rq_timeout::0
echo-service_default_svc_8080::172.31.29.90:8080::rq_total::0
echo-service_default_svc_8080::172.31.29.90:8080::hostname::
echo-service_default_svc_8080::172.31.29.90:8080::health_flags::/failed_active_hc
echo-service_default_svc_8080::172.31.29.90:8080::weight::2
echo-service_default_svc_8080::172.31.29.90:8080::region::
echo-service_default_svc_8080::172.31.29.90:8080::zone::universal
echo-service_default_svc_8080::172.31.29.90:8080::sub_zone::
echo-service_default_svc_8080::172.31.29.90:8080::canary::false
echo-service_default_svc_8080::172.31.29.90:8080::priority::0
echo-service_default_svc_8080::172.31.29.90:8080::success_rate::-1.0
echo-service_default_svc_8080::172.31.29.90:8080::local_origin_success_rate::-1.0
```
