### ISSUE TITLE
Feature Request: Filter Envoy Metrics

### ISSUE THREAD

**Issue by korabum** [kumahq/kuma#1755]
### Summary

The default metrics generated by envoy proxy is relatively big. In a kubernetes cluster with around 200 services inside the kuma mesh, a single call to `/metrics` resulted in around 7MB of metrics data. This requires a lot of resource from prometheus to scrape all of the envoy metrics on the cluster. It would be nice if we can have a way to filter only the metrics that we actually need from kuma, using this configuration for example:

```yaml
---
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  metrics:
    backends:
    - conf:
        path: /metrics
        port: 5670
        filter: 'envoy_cluster_*' # Only include metrics that matches this pattern
        tags:
          kuma.io/service: dataplane-metrics
      name: prometheus-1
      type: prometheus
    enabledBackend: prometheus-1
```

### Additional Details & Logs

- Version: 1.1.1
