### ISSUE TITLE
DataplaneOverview does not show metrics configuration

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1939]
### Summary

DataplaneOverview in the UI and resource do not show metrics configuration

### Steps To Reproduce

Run DPP with the following file: 
```
type: Dataplane
mesh: default
name: internalhttpbin-52i8jq
networking:
  address: ip-172-31-29-90.us-east-2.compute.internal
  transparentProxying:
    redirectPortInbound: 15006
    redirectPortOutbound: 15001
  inbound:
    - port: 8080
      servicePort: 5000
      serviceAddress: 127.0.0.1
      tags:
        kuma.io/service: echo-service_default_svc_8080
        kuma.io/protocol: http
  metrics:
    type: prometheus
    conf:
      skipMTLS: true
      port: 5670
      path: /metrics
```

Results in:
```
name: universal-1.internalhttpbin-52i8jq.default
mesh: default
type: DataplaneOverview
networking: 
  address: ip-172-31-29-90.us-east-2.compute.internal
  inbound: 
    - port: 8080
      servicePort: 5000
      serviceAddress: 127.0.0.1
      tags: 
        kuma.io/protocol: http
        kuma.io/service: echo-service_default_svc_8080
        kuma.io/zone: universal-1
  outbound: 
    - address: 240.0.0.0
      port: 80
      tags: 
        kuma.io/service: backend_kuma-demo_svc_3001
    - address: 240.0.0.1
      port: 80
      tags: 
        kuma.io/service: echo-service_default_svc_8080
    - address: 240.0.0.2
      port: 5432
      tags: 
        kuma.io/service: externalpostgres
    - address: 240.0.0.2
      port: 80
      tags: 
        kuma.io/service: externalpostgres
    - address: 240.0.0.3
      port: 80
      tags: 
        kuma.io/service: frontend_kuma-demo_svc_8080
    - address: 240.0.0.4
      port: 80
      tags: 
        kuma.io/service: httpbin
    - address: 240.0.0.5
      port: 80
      tags: 
        kuma.io/service: postgres_kuma-demo_svc_5432
    - address: 240.0.0.6
      port: 80
      tags: 
        kuma.io/service: postman-echo
    - address: 240.0.0.7
      port: 80
      tags: 
        kuma.io/service: redis_kuma-demo_svc_6379
    - address: 240.0.0.8
      port: 80
      tags: 
        kuma.io/service: tcp_default_svc_1234
    - address: 240.0.0.9
      port: 80
      tags: 
        kuma.io/service: tools_default_svc
  transparentProxying: 
    redirectPortInbound: 15006
    redirectPortOutbound: 15001
```
