### ISSUE TITLE
Ingress dataplane on universal doesn't listen on public ip

### ISSUE THREAD

**Issue by gerardborst** [kumahq/kuma#2014]
### Summary
We are doing a POC of kuma in multi zone mode, at this moment with 1 zone in a k8s cluster in minikube and the other on ubuntu vm's in vagrant. 
It looks as if the ingress in the Universal zone doesn't listen on the correct public ip.

### Steps To Reproduce
We are using the Kuma Demo counter as a test app.

1. global and remote control plane with universal deployment on ubuntu machines. The remote control plane with 1 private ip
2. 1 vm with ingress with a public and a private ip.
```
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:6f:56:98 brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.11/24 brd 192.168.33.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe6f:5698/64 scope link 
       valid_lft forever preferred_lft forever
4: enp0s9: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:95:38:20 brd ff:ff:ff:ff:ff:ff
    inet 172.30.74.75/24 brd 172.30.74.255 scope global enp0s9
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe95:3820/64 scope link 
       valid_lft forever preferred_lft forever
```
3. the dataplane has the private ip as address and public ip as public ip
```
type: Dataplane
mesh: default
name: ingress-01
networking:
  address: 172.30.74.75
  ingress:
    publicAddress: 192.168.33.11
    publicPort: 10000
  inbound:
  - port: 10000
    tags:
      kuma.io/service: ingress
```

result:
```
root@ingress:~# netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      642/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      840/sshd            
tcp        0      0 172.30.74.75:10000      0.0.0.0:*               LISTEN      1333/envoy          
tcp        0      0 172.30.74.75:30001      0.0.0.0:*               LISTEN      1333/envoy          
tcp        0      0 127.0.0.1:30001         0.0.0.0:*               LISTEN      1333/envoy          
tcp6       0      0 :::22                   :::*                    LISTEN      840/sshd         
```

### Additional Details & Logs

- Version: 1.1.6
- Platform and Operating System: Ubuntu 18.04.5 LTS
- Installation Method: Universal on vagrant

If we use the following dataplane the ingress does work:
```
type: Dataplane
mesh: default
name: ingress-01
networking:
  address: 192.168.33.11
  ingress:
    publicAddress: 192.168.33.11
    publicPort: 10000
  inbound:
  - port: 10000
    tags:
      kuma.io/service: ingress
```
But I think this is not a valid solution in the life situation.

**Comment by thirdeyenick** [comment]
I actually had the same issue when testing this in universal mode. The kuma-dp doesn't actually bind to the address you set in `publicAddress`. It only announces to other ingress-dp's that traffic should be sent to this public address. I had to create some iptables rules on the VM which basically NAT the traffic coming in on the public IP to the private IP and port where the kuma-dp was listening. This is actually the same as kubernetes does it, but there you can use a service of type Loadbalancer or NodePort which will do the NAT for you.

**Comment by gerardborst** [comment]
I see now, but in k8s it's working out of the box so I think, IMHO, this should also be the case with Universal or if that is completely impossible it should at least be explained in the docs.

**Comment by gerardborst** [comment]
It is also possible to use
```
type: Dataplane
mesh: default
name: ingress-01
networking:
  address: 0.0.0.0
  ingress:
    publicAddress: 192.168.33.11
    publicPort: 10000
  inbound:
  - port: 10000
    tags:
      kuma.io/service: ingress
```

**Comment by jpeach** [comment]
ping @kumahq/kuma-maintainers

**Comment by gerardborst** [comment]
@jpeach as said in #2191 I had the biggest problem with determining what the ingress address should be.

In my environment I have an azure subscription with the global control plane in a kubernetes cluster and 3 vm's in another subscription with the zone control plane, the zone ingress and the redis backend.

The zone ingress has 2 nic's
```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0d:3a:be:ba:86 brd ff:ff:ff:ff:ff:ff
    inet 10.1.0.4/24 brd 10.1.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd00:db8:deca:deed::4/128 scope global dynamic noprefixroute 
       valid_lft 17279988sec preferred_lft 8639988sec
    inet6 fe80::20d:3aff:febe:ba86/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0d:3a:be:ba:d3 brd ff:ff:ff:ff:ff:ff
    inet 10.1.1.4/24 brd 10.1.1.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::20d:3aff:febe:bad3/64 scope link 
       valid_lft forever preferred_lft forever
```
The azure public ip address is attached to eth0. At first I choose 10.1.1.4 as "address", the ip address in the subnet of the zone control plane but that didn't work. After this I made the ZoneIngress as following and that did work:
```
type: ZoneIngress
name: ingress-01
networking:
  address: "10.1.0.4"
  port: 10000
  advertisedAddress: "x.x.x.x"
  advertisedPort: 10000
```
So the address is the address of the nic with the public ip address and this address is also routable within the private network.

In the documentation it is said "address: 127.0.0.1 # address that is routable within the zone". So it should be routable but at the same time it has an ip which isn't routable at all.

I would want to change the documentation but at the same time I don't know enough about the internals to know exactly what it should be.

At the same time this did cost me relatively a lot of time so it would have helped me if there was an example of a more realistic use case as this one.

If you point me where this should land and what cloud provider(s) you prefer I can try to make a first version of such a use case.
