### ISSUE TITLE
CI: add codecov Github App

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2058]
It would be nice to add the Github [coveralls action](https://github.com/marketplace/actions/coveralls-github-action) to the repository. This gives a visualization of the changes in code coverage for each PR, which I have found helpful in maintaining test coverage.

**Comment by austince** [comment]
+1 for this effort, but would suggest CodeCov over Coveralls, since its generally much better supported and feature-rich: https://github.com/codecov/codecov-action

**Comment by jpeach** [comment]
Yeh I think I must have meant codecov since that's what I used in a previous life :)

**Comment by jpeach** [comment]
I refreshed my memory on how to do this. Here's the steps:

* enable codecov for the kumahq organization, then it will show up in the app settings of each repository
* Add a test target that generates coverage to `coverage.out`
* Add a coverage upload target that does `bash <(curl -s https://codecov.io/bash)`
* Make sure the git checkout uses `depth 0`

Example YAML for Github actions:
```
name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -cover -coverprofile=coverage.out -v ./...

    - name: Coverage
      if: ${{ success() }}
      run: "bash <(curl -s https://codecov.io/bash)"


```
