### ISSUE TITLE
Use layered runtime to max out the regex program size

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2103]
### Summary

Even though the RE2 program size check is deprecated in envoy, it is still present [here](https://github.com/envoyproxy/envoy/blob/main/source/common/common/regex.cc#L82-L90).

Kuma should set a high runtime value for the `re2.max_program_size.error_level` so that configuration changes don't fail due to unexpected regex behavior.

xref https://github.com/kumahq/kuma/pull/2072#discussion_r643560505

**Comment by jpeach** [comment]
Confirmed that this is a real problem:

```yaml
apiVersion: kuma.io/v1alpha1    
kind: TrafficRoute      
mesh: default           
metadata:               
  name: route-all-default    
  namespace: test-server    
spec:                   
  sources:              
  - match:                      
      kuma.io/service: '*'    
  destinations:         
  - match:                      
      kuma.io/service: '*'    
  conf:                 
    http:               
    - match:            
        path:           
          prefix: /     
      modify:           
        path:           
          regex:        
            pattern: /static/[a-zA-Z0-9._-]{0,200}/[a-zA-Z0-9._-]{0,200}    
            substitution: /foo    
      split:            
      - weight: 100     
        destination:    
          kuma.io/service: '*'    
```

This generates an envoy error

```
[2021-06-09 22:56:17.908][18][warning][config] [source/common/config/grpc_subscription_impl.cc:107] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) outbound:240.0.0.0:80: regex '/static/[a-zA-Z0-9._-]{0,200}/[a-zA-Z0-9._-]{0,200}' RE2 program size of 2013 > max program size of 100 set for the error level threshold. Increase configured max program size if necessary.
outbound:10.96.149.99:10080: regex '/static/[a-zA-Z0-9._-]{0,200}/[a-zA-Z0-9._-]{0,200}' RE2 program size of 2013 > max program size of 100 set for the error level threshold. Increase configured max program size if necessary.
```
