### ISSUE TITLE
Fix Kubernetes CRD generation

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2130]
### Summary

From `pkg/plugins/resources/k8s/native/Makefile`:

```
# TODO(yskopets): CRD generation is broken since introduction of .proto definitions
```

and this comment is, in fact, true:

```
$ make manifests
/home/jpeach/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./api/...;./controllers/..." output:crd:artifacts:config=config/crd/bases
panic: interface conversion: types.Type is *types.Map, not *types.Named

goroutine 1 [running]:
sigs.k8s.io/controller-tools/pkg/crd.localNamedToSchema(0xc001693260, 0xc000c27720, 0x30)
	/home/jpeach/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/crd/schema.go:214 +0x5cb
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc001693260, 0xd9ccd0, 0xc000c27720, 0x1f)
	/home/jpeach/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/crd/schema.go:154 +0x8b
sigs.k8s.io/controller-tools/pkg/crd.structToSchema(0xc0014fcad0, 0xc000b26858, 0x0)
	/home/jpeach/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/crd/schema.go:375 +0x472
sigs.k8s.io/controller-tools/pkg/crd.typeToSchema(0xc0014fcad0, 0xd9d000, 0xc000b26858, 0x0)
	/home/jpeach/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/crd/schema.go:164 +0x36e
sigs.k8s.io/controller-tools/pkg/crd.infoToSchema(...)
	/home/jpeach/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/crd/schema.go:107
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedSchemaFor(0xc00014a140, 0xc000155a60, 0xc000b64450, 0xe)
	/home/jpeach/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/crd/parser.go:174 +0x308
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedFlattenedSchemaFor(0xc00014a140, 0xc000155a60, 0xc000b64450, 0xe)
	/home/jpeach/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/crd/parser.go:186 +0xde
sigs.k8s.io/controller-tools/pkg/crd.(*Parser).NeedCRDFor(0xc00014a140, 0xc000c3809e, 0x7, 0xc000b64450, 0xe, 0x0)
	/home/jpeach/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/crd/spec.go:85 +0x62c
sigs.k8s.io/controller-tools/pkg/crd.Generator.Generate(0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00014a0f0, 0xc00046c000, 0x0)
	/home/jpeach/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/crd/gen.go:108 +0x36f
sigs.k8s.io/controller-tools/pkg/genall.(*Runtime).Run(0xc000b86600, 0xc00014bd10)
	/home/jpeach/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/pkg/genall/genall.go:171 +0x165
main.main.func1(0xc0001afb80, 0xc00014bd10, 0x5, 0x5, 0x0, 0x0)
	/home/jpeach/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/cmd/controller-gen/main.go:176 +0xba
github.com/spf13/cobra.(*Command).execute(0xc0001afb80, 0xc000140130, 0x5, 0x5, 0xc0001afb80, 0xc000140130)
	/home/jpeach/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001afb80, 0xc0001288a0, 0x4, 0x0)
	/home/jpeach/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/home/jpeach/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/jpeach/go/pkg/mod/sigs.k8s.io/controller-tools@v0.3.0/cmd/controller-gen/main.go:200 +0x346
make: *** [Makefile:63: manifests] Error 2
```

It seems like we need CRD generation to work if we want to address #2107 or #1366.

**Comment by jpeach** [comment]
And DeepCopy generating is broken too. This seems more fundamental, because controller-gen doesn't like the fact that the spec field is `map[string]interface{}`. Perhaps we could address this with `runtime.RawExtension`, but overall, changing this seems like a substantial effort.

```
jpeach@greenling:~/upstream/konghq/kuma/pkg/plugins/resources/k8s/native$ make generate
go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=./hack/boilerplate.go.txt paths=./api/...
github.com/kumahq/kuma/pkg/plugins/resources/k8s/native/api/v1alpha1:-: name requested for invalid type: interface{}
github.com/kumahq/kuma/pkg/plugins/resources/k8s/native/api/v1alpha1:-: invalid map value type: interface{}
Error: not all generators ran successfully
run `controller-gen object:headerFile=./hack/boilerplate.go.txt paths=./api/... -w` to see all available markers, or `controller-gen object:headerFile=./hack/boilerplate.go.txt paths=./api/... -h` for usage
exit status 1
make: *** [Makefile:75: generate] Error 1
```

**Comment by jpeach** [comment]
Per https://github.com/kubernetes-sigs/controller-tools/issues/294, we should be able to use [json.RawMessage](https://golang.org/pkg/encoding/json/#RawMessage) as the type for fields that contain a JSON-marshaled protobuf.

I verified that this does generate a CRD that looks pretty consistent with what we are doing manually:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.6.1
  creationTimestamp: null
  name: meshes.kuma.io
spec:
  group: kuma.io
  names:
    kind: Mesh
    listKind: MeshList
    plural: meshes
    singular: mesh
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Mesh is the Schema for the Mesh API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: RawMessage is a carrier for an untyped JSON payload.
            #  XXX(jpeach) note this is missing "type: object" and "x-kubernetes-preserve-unknown-fields: true"
            # so we will need to verify compatibility and that this does what we want
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
```

It looks like the DeepCopy changes to a byte-wise copy:
```Go
// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
 func (in *Mesh) DeepCopyInto(out *Mesh) {
        *out = *in
        out.TypeMeta = in.TypeMeta
        in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
-       out.Spec = in.Spec.DeepCopy()
+       if in.Spec != nil {
+               in, out := &in.Spec, &out.Spec
+               *out = make(model.RawMessage, len(*in))
+               copy(*out, *in)
+       }
 }
```

Since this is a bigger semantic change than #2222, I'll need to discuss with the maintainers. Perhaps we should land #2222 and then transition to this? Or maybe just take a bit of extra time and go straight to `json.RawMessage`?

Any thoughts @nickolaev, @jakubdyszkiewicz, @lobkovilya, @parkanzky, @bartsmykla?
