### ISSUE TITLE
Outbound port connection issue

### ISSUE THREAD

**Issue by sumeshsg** [kumahq/kuma#2144]
### Summary

- Single AWS Ec2 Machine
- One control-plane
- Two data plane (one for Postgres service another for API service)

### Steps To Reproduce

1. Running Kuma-cp : **kuma-cp run**
2. Creating dataplane for postgresql (dp_postgresql.yaml)
```
          type: Dataplane
          mesh: default
          name: postgresql
          networking:
            address: 'IP address of AWS machine' 
            inbound:
            - port: 60001
              servicePort: 5433
              tags:
                kuma.io/service: postgresql
```

3. Creating data plane for APIservice (dp_design.yaml)
```
          type: Dataplane
          mesh: default
          name: design
          networking:
            address: 'IP address of AWS machine'
            inbound:
            - port: 40001
              servicePort: 8008
              tags:
                kuma.io/service: design
            outbound:
            - port: 50001
              tags:
                kuma.io/service: postgresql
```

4. Generate tokens for Postgresql and API service

        ./kumactl generate dataplane-token \
          --name postgresql \
          --mesh default \
          --tag kuma.io/service=postgresql > /tmp/kuma-dp-postgresql-token
          
        ./kumactl generate dataplane-token \
          --name design \
          --mesh default \
          --tag kuma.io/service=design > /tmp/kuma-dp-design-token

5. Run Dataplane:

./kuma-dp run --cp-address=https://127.0.0.1:5678 --dataplane-file=/opt/data-plane/dp_postgresql.yaml --dataplane-token-file=/tmp/kuma-dp-postgresql-token

./kuma-dp run --cp-address=https://127.0.0.1:5678 --dataplane-file=/opt/data-plane/dp_design.yaml --dataplane-token-file=/tmp/kuma-dp-design-token

6. Configuration of Postgres in the API service (Codebase)

```
"POSTGRES": {
    "username": "username",
    "password": "password",
    "host": "127.0.0.1" or <IP address of AWS machine > (tried both) ,
    "port": "50001",
    "data_base": "ABCD",
    "schema": "abcd"
  }
```

**Issue:** Getting below error while access Postgres database from API codebase with above configuration (Point No 5)

_Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 50001?_

### Additional Details & Logs

**Note:** Both inbound ports (postgresql:60001 and  api:40001) specified in the data plane of service is working fine.
