### ISSUE TITLE
Builtin DNS clash with multiple external services defined with the same host and different ports

### ISSUE THREAD

**Issue by phclark** [kumahq/kuma#2176]
### Summary

When using transparent proxying with built in DNS, multiple external services defined with the same host but different ports clash in their VIP definition, resulting in only one of the services being reachable by their full url:port combination. Using the .mesh domain, all services are reachable. Requests to all but one service result in either Empty reply from server or Connection reset by peer errors.

### Steps To Reproduce

1. Enable transparent proxying according to https://kuma.io/docs/1.1.6/networking/transparent-proxying/#transparent-proxying-2 and built in DNS with command:
```
sudo /usr/local/bin/kumactl install transparent-proxy \
  --kuma-dp-user kuma-dp \
  --exclude-inbound-ports 22,443,1433,80 \
  --exclude-outbound-ports 22,443,1433,80 \
  --skip-resolv-conf \
  --redirect-dns \
  --verbose \
  --kuma-cp-ip "${cp_ip_address}"
```
  
  and start kuma-dp:
```
  /usr/local/bin/kuma-dp run \
--cp-address "${cp_address}" \
--dataplane-file /etc/kuma-dp.yaml \
--dataplane-var address="${ip_address}" \
--dataplane-token "${token}" \
--dns-enabled
```
2. Define external services in control plane:
```
---
type: ExternalService
mesh: default
name: myservice-admin
tags:
  kuma.io/service: myservice-admin
  kuma.io/protocol: http
networking:
  address: 'myservice.com:8000'
  tls:
    enabled: false
---
type: ExternalService
mesh: default
name: myservice-api
tags:
  kuma.io/service: myservice-api
  kuma.io/protocol: http
networking:
  address: 'myservice.com:8001'
  tls:
    enabled: false
```
3. Verify configuration by connecting using .mesh domain:
`curl myservice-admin.mesh:8000`
`curl myservice-api.mesh:8001`

4. Try connect to services:
`curl myservice.com:8000`
`curl myservice.com:8001`

### Additional Details & Logs
Kuma-dp running on Amazon Linux 2, with kuma version 1.1.6 and envoy version 1.17.1
