### ISSUE TITLE
Use lifecycle type sidecar on kuma-sidecar container

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#2203]
### Summary

add `lifecycle.type=Sidecar`
```
  - name: kuma-sidecar
    image: docker.io/kumahq/kuma-dp:1.2.0
    lifecycle:
      type: Sidecar
```
conditionally when we are injecting Kuma DP on Kubernetes 1.18+

This way Kuma DP will start as a first container.
