### ISSUE TITLE
Option to use internal cert key pair for external services

### ISSUE THREAD

**Issue by skaravad** [kumahq/kuma#2248]
### Summary

As per https://kuma.io/docs/1.2.0/policies/external-services/#usage we can specify key pair + ca when communicating with external services which require TLS /mTLS , it would be great if the sidecar can use the key pair which it already uses for internal services , for instance if we provide managed CA for the Mesh or Use Vault, external services can have identities signed by the same CA.
```
    tls: 
      enabled: true
       use_Internal_Identity: true (something like that)
      allowRenegotiation: false
      caCert:
        secret: (if required , as external services can include CA of the Mesh for mTLS but not the other way around)
````
How it helps ?

The intent here is not to store /provision any kubernetes secrets given that these are static in nature and kubernetes secrets are no so secrets anyways. Given that kuma sidecar has the identity in-memory and auto rotation is in-built it enhances the security.

This is a enhancement request vs bug/issue.
