### ISSUE TITLE
TrafficPermissions can shadow one another if the match the same destination

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#2417]
@cpu601 pointed out that: 
- with 3 service a, b and c.
- an existing policy:
```
apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  name: allow-b-to-a
spec:
  sources:
    - match:
        kuma.io/service: b
  destinations:
    - match:
        kuma.io/service: a
```
- add a policy:
```
apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  name: allow-c-to-a
spec:
  sources:
    - match:
        kuma.io/service: c
  destinations:
    - match:
        kuma.io/service: a
```

The second will take over the first one resulting in service `b` not able to communicate with service `a` anymore.

This has 2 issues:

1) There's a massive risk of users shooting themselves in the foot (create a new policy that breaks existing connections when they seem unrelated)
2) Shouldn't it be possible to have multiple policies for the same service?

If the answer to 2 is no and we decide that only 1 destination matcher set (.i.e: the map at `spec.destinations.match`) should be possible we should introduce validation at creation/modification time to not process this policy at all and avoid the shadowing explained here.

**Comment by jpeach** [comment]
An inbound gets exactly 1 best-match TrafficPermission policy applied to it. So you can't apply both of these policies to same destination service at once (since it's inbound can only have 1 policy).

**Comment by lahabana** [comment]
Right, just to reword my question and the idea behind this ticket:

1) Is really a limitation we want to keep?
2) If yes shouldn't the oldest permission have priority (rather than the newest like it is now) in order to avoid shooting yourself in the foot?
3) Could we add validation to reject policies that already have the same exact destination matcher?


I'm not opposed to the single destination restriction, it just seems we might be able to improve the UX

**Comment by lobkovilya** [comment]
Will this work?
```yaml
apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  name: allow-b-c-to-a
spec:
  sources:
    - match:
        kuma.io/service: b
    - match:
        kuma.io/service: c
  destinations:
    - match:
        kuma.io/service: a
```
Anyway, I think validation is a good idea. We have to provide more visibility of what policies were applied between Service A and Service B. Ideally it should be `kumactl inspect --src=service-a --dst=service-b --policy=TrafficPermission`or something like this, but that's for the future
