### ISSUE TITLE
[summary] Weird behaviour of muiltizone on Azure EKS (upstream timeouts)

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#2509]
### Summary

This is the summary of my and @jakubdyszkiewicz week+ long investigation of very weird issue with multizone kuma on Azure EKS.

About a week ago, we received information than kuma behaves weirdly on Azure EKS.

#### Environment:

1. Azure EKS clusters with kuma installed:

   * kuma-global
   * kuma-zone-1
   * kuma-zone-2
 
2. Installed services

   * zone-1:

      * curlbox
      * service-a
      * service-b

   * zone-2:

      * curlbox
      * service-a
      * service-b

3. `mtls` turned on
4. both zones had zone-ingresses installed with `LoadBalancer` type

##### Services description

* **curlbox** is a simple container with `curl` installed which will be used to test connectivity to other services
* **service-a** is an http server with `/hello` endpoint, which called will send a request to `service-b` and then return a response from this service
* **service-b** is jest an http server which responds with data sent to it

#### Problem

When sending requests from the **curlbox** to **service-a** at the beginning everything was going well and we would receive expected responses all the time. After some time (at the beginning we thought it was about 10 minutes) some requests started timeouting with `upstream request timeout`

After lot of investigation and digging through `tcpdump` we figured out that after 4 minutes our zone-ingress stopped responding, which occured to be normal behaviour as Azure Load Balancers by default have set the `idle timeout` to 4 minutes. They also by default are sending packets with `RST` when this timeout will happen.

What was unexpected was the fact that even after receiving the `RST`, the connection was still marked as `ESTABILISHED` and envoy was trying to reuse it.

The first surprising behaviour is that when envoy tries to send the data to this connection there is completely no response from load balancer, and packets are being re-transmitted till the system timeout happen. My understanding of the TCP would suggest that if we are trying to send a request to a connection which is closed we should have again receive packet with `RST`.

It bothered me a lot, to the point I started to have dreams with TCP packets in them (not joking!). I couldn't figure out why this connection is still being mark as `ESTABILISHED` so I started to read RFCs in regards to understand what should be the correct behaviour, and according to [rfc5961](https://datatracker.ietf.org/doc/html/rfc5961#section-3.2):

> 1) If the RST bit is set and the sequence number is outside the current receive window, silently drop the segment.
> 
> 2) If the RST bit is set and the sequence number exactly matches the next expected sequence number (RCV.NXT), then TCP MUST reset connection.
> 
> 3) If the RST bit is set and the sequence number does not exactly
>      match the next expected sequence value, yet is within the current
>      receive window (RCV.NXT < SEG.SEQ < RCV.NXT+RCV.WND), TCP MUST
>      send an acknowledgment (challenge ACK):
>
>      <SEQ=SND.NXT><ACK=RCV.NXT><CTL=ACK>
>
>      After sending the challenge ACK, TCP MUST drop the unacceptable
>      segment and stop processing the incoming packet further.  Further
>      segments destined to this connection will be processed as normal.

so I started looking more deeply into the sequence numbers and then I found this:

![image](https://user-images.githubusercontent.com/11655498/128488340-140fc058-c67c-4b1c-a7e3-44bae596bbe7.png)

the `RST` packet from Azure Load Balancer comes with exactly the same `seq` and `ack` numbers

![image](https://user-images.githubusercontent.com/11655498/128488613-f4df5f84-2fd4-4cf9-a4ff-c61e3d2ec363.png)

 which in one host would be challenged (point 2 from rfc) as `ack` WAS right an visible in current TCP stream, but was not equal the last `seq`

![image](https://user-images.githubusercontent.com/11655498/128488857-910035a7-0463-401e-a4c9-2e2b6c156501.png)

and dropped in second as the `ack` is completely wrong:

![image](https://user-images.githubusercontent.com/11655498/128488956-a7677172-8f11-44d5-850a-ae0f9e065590.png)

### Steps To Reproduce

1. Create Azure EKS clusters:

   ```fish
   set -gx AZURE_RESOURCE_GROUP [...]
   set -gx AZURE_LOCATION [...]
   set -gx AZURE_SUBSCRIPTION [...]
   set -gx AZURE_SP [...]
   set -gx AZURE_SP_PASSWORD [...]
   set -gx SSH_KEY_PATH [...]
   set -gx ADMIN_USERNAME [...]
   
   for name in global zone-1 zone-2;
     az aks create \
       --name kuma-test-$name \
       --resource-group $AZURE_RESOURCE_GROUP \
       --location $AZURE_LOCATION \
       --subscription $AZURE_SUBSCRIPTION \
       --service-principal $AZURE_SP \
       --client-secret $AZURE_SP_PASSWORD \
       --node-count 1 \
       --node-vm-size Standard_DS2_v2 \
       --kubernetes-version 1.20.7 \
       --network-plugin azure \
       --network-policy calico \
       --ssh-key-value $SSH_KEY_PATH \
       --admin-username $ADMIN_USERNAME \
       --enable-node-public-ip \
       &
   end
   
   wait
   
   for name in global zone-1 zone-2;
     az aks get-credentials --resource-group $AZURE_RESOURCE_GROUP \
      --name kuma-test-$name \
      --file $HOME/.kube/kuma-$name-azure-aks-config.yaml \
      --overwrite-existing \
      &
   end
   
   wait

2. Install `kuma-global` and port-forward api endpoint

   ```fish
   kumactl install control-plane --control-plane-registry=bartsmykla --control-plane-version=1.2.3-debug --mode=global | kubectl apply --kubeconfig $HOME/.kube/kuma-global-azure-aks-config.yaml -f -
   kubectl port-forward svc/kuma-control-plane -n kuma-system 5681:5681 --kubeconfig $HOME/.kube/kuma-global-azure-aks-config.yaml
   ```

3. Install kuma on zone-1

   ```fish
   set -gx KDS_ADDRESS (kubectl get service kuma-global-zone-sync -n kuma-system --kubeconfig $HOME/.kube/kuma-global-azure-aks-config.yaml -o template --template="{{(index .status.loadBalancer.ingress 0).ip}}")
   kumactl install control-plane --mode=zone --zone=zone-1 --ingress-enabled --control-plane-registry=bartsmykla --control-plane-version=1.2.3-debug --kds-global-address grpcs://$KDS_ADDRESS:5685 | kubectl apply --kubeconfig $HOME/.kube/kuma-zone-1-azure-aks-config.yaml -f -
   ```

4. Install kuma on zone-2

   ```fish
   set -gx KDS_ADDRESS (kubectl get service kuma-global-zone-sync -n kuma-system -o template --template="{{(index .status.loadBalancer.ingress 0).ip}}" --kubeconfig $HOME/.kube/kuma-global-azure-aks-config.yaml)
   kumactl install control-plane --mode=zone --zone=zone-2 --ingress-enabled --control-plane-registry=bartsmykla --control-plane-version=1.2.3-debug --kds-global-address grpcs://$KDS_ADDRESS:5685 | kubectl apply --kubeconfig $HOME/.kube/kuma-zone-2-azure-aks-config.yaml -f -
   ```

5. Turn on mtls

   ```fish
   echo "apiVersion: kuma.io/v1alpha1
   kind: Mesh
   metadata:
     name: default
   spec:
     mtls:
       enabledBackend: ca-1
       backends:
         - name: ca-1
           type: builtin
           dpCert:
             rotation:
               expiration: 1d
           conf:
             caCert:
               RSAbits: 2048
               expiration: 10y" | kubectl apply --kubeconfig $HOME/.kube/kuma-global-azure-aks-config.yaml -f -
   ```

6. Create and annotate namespaces for workloads in zone-1 and zone-2

   ```fish
   kubectl create ns meshdev --kubeconfig $HOME/.kube/kuma-zone-1-azure-aks-config.yaml
   kubectl annotate namespace meshdev kuma.io/sidecar-injection=enabled --kubeconfig $HOME/.kube/kuma-zone-1-azure-aks-config.yaml
   kubectl create ns meshdev --kubeconfig $HOME/.kube/kuma-zone-2-azure-aks-config.yaml
   kubectl annotate namespace meshdev kuma.io/sidecar-injection=enabled --kubeconfig $HOME/.kube/kuma-zone-2-azure-aks-config.yaml
   ```

7. Deploy curlbox service on zone-1

   ```yaml
   ---
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: curlbox
     namespace: meshdev
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: curlbox
     template:
       metadata:
         labels:
           app: curlbox
         name: curlbox
       spec:
         containers:
         - args:
           - sh
           - -c
           - tail -f /dev/null
           image: bartsmykla/kuma-universal
           name: curlbox
           securityContext:
             capabilities:
               add:
               - "NET_ADMIN"
   ---
   apiVersion: v1
   kind: Service
   metadata:
     annotations:
       80.service.kuma.io/protocol: http
     name: curlbox
     namespace: meshdev
   spec:
     ports:
     - port: 80
       protocol: TCP
       targetPort: 3000
     selector:
       app: curlbox
   ```

8. Deploy service-a and service-b on zone-2

   ```yaml
   ---
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: service-a-v1
     namespace: meshdev
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: service-a
         version: v1
     template:
       metadata:
         annotations:
           kuma.io/protocol: http
         labels:
           app: service-a
           version: v1
         name: service-a
       spec:
         containers:
         - env:
           - name: VERSION
             value: cluster-b-1
           - name: SERVICE_B_URL
             value: http://service-b.meshdev/hello
           - name: OTEL_COLLECTOR_ADDRESS
             value: http://otel-collector.otel:4317
           image: bartsmykla/service-a:v1
           name: service-a
           ports:
           - containerPort: 8081
             name: http
             protocol: TCP
           resources:
             limits:
               cpu: 256m
               memory: 256Mi
             requests:
               cpu: 100m
               memory: 128Mi
   ---
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: service-b-v1
     namespace: meshdev
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: service-b
         version: v1
     template:
       metadata:
         labels:
           app: service-b
           version: v1
         name: service-b
       spec:
         containers:
         - env:
           - name: VERSION
             value: cluster-b-1
           - name: OTEL_COLLECTOR_ADDRESS
             value: http://otel-collector.otel:4317
           image: bartsmykla/service-b:v2
           name: service-b
           ports:
           - containerPort: 8080
             name: http
             protocol: TCP
           resources:
             limits:
               cpu: 256m
               memory: 256Mi
             requests:
               cpu: 100m
               memory: 128Mi
   ---
   apiVersion: v1
   kind: Service
   metadata:
     annotations:
       80.service.kuma.io/protocol: http
     name: service-a
     namespace: meshdev
   spec:
     ports:
     - port: 80
       protocol: TCP
       targetPort: http
     selector:
       app: service-a
   ---
   apiVersion: v1
   kind: Service
   metadata:
     annotations:
       80.service.kuma.io/protocol: http
     name: service-b
     namespace: meshdev
   spec:
     ports:
     - port: 80
       protocol: TCP
       targetPort: http
     selector:
       app: service-b
   ```

9. Start shell on the `curlbox` container in `zone-1`

   ```fish
   set -gx CURLBOX (kubectl get pod -n meshdev -l app=curlbox -o template --template "{{(index .items 0).metadata.name}}" --kubeconfig $HOME/.kube/kuma-zone-1-azure-aks-config.yaml)
   kubectl exec --kubeconfig $HOME/.kube/kuma-zone-1-azure-aks-config.yaml -n meshdev -ti pod/$CURLBOX -- bash
   ```

10. `Call service-a` few times from the `curlbox`

   ```fish
   for i in (seq 1 10); do curl service-a.meshdev.svc.80.mesh/hello; echo ""; sleep 0.5; done
   ```

11. Wait 4-5 minutes

12. Call `service-a` again

   ```fish
   for i in (seq 1 10); do curl service-a.meshdev.svc.80.mesh/hello; echo ""; sleep 0.5; done
   ```

### Additional Details & Logs

- Version: 1.2.2
- Error logs

   ```fish
   root@curlbox-7f4b9cd9dd-xcwlv:/# while true; do curl service-a.meshdev.svc.80.mesh/hello; echo ""; sleep 0.5; done
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   upstream request timeout
   {"service":"service-a","message":{"service":"service-b","message":"Hello ","version":"cluster-b-2"},"version":"cluster-b-1"}
   {"service":"service-a","message":{"service":"service-b","message":"Hello ","version":"cluster-b-1"},"version":"cluster-b-1"}
   upstream request timeout
   {"service":"service-a","message":{"service":"service-b","message":"Hello ","version":"cluster-b-2"},"version":"cluster-b-1"}
   {"service":"service-a","message":{"service":"service-b","message":"Hello ","version":"cluster-b-1"},"version":"cluster-b-1"}
   {"service":"service-a","message":{"service":"service-b","message":"Hello ","version":"cluster-b-2"},"version":"cluster-b-1"}
   upstream request timeout
   {"service":"service-a","message":{"service":"service-b","message":"Hello ","version":"cluster-b-1"},"version":"cluster-b-1"}
   {"service":"service-a","message":{"service":"service-b","message":"Hello ","version":"cluster-b-2"},"version":"cluster-b-1"}
   {"service":"service-a","message":{"service":"service-b","message":"Hello ","version":"cluster-b-1"},"version":"cluster-b-1"}
   {"service":"service-a","message":{"service":"service-b","message":"Hello ","version":"cluster-b-2"},"version":"cluster-b-1"}
   {"service":"service-a","message":{"service":"service-b","message":"Hello ","version":"cluster-b-1"},"version":"cluster-b-1"}
   {"service":"service-a","message":{"service":"service-b","message":"Hello ","version":"cluster-b-2"},"version":"cluster-b-1"}
   {"service":"service-a","message":{"service":"service-b","message":"Hello ","version":"cluster-b-1"},"version":"cluster-b-1"}
   ^C
   ```

- [packets-zone-1.pcapng.gz](https://github.com/kumahq/kuma/files/6944427/packets-zone-1.pcapng.gz)
- [packets-zone-2.pcapng.gz](https://github.com/kumahq/kuma/files/6944428/packets-zone-2.pcapng.gz)
