### ISSUE TITLE
take dns server into account in /ready endpoint of kuma-dp

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#2571]
### Summary

When working on confirmation that kuma works with websockets I faced an issue when my simple websocket client tried to connect to the server using our dns names (`server.default.svc.80.mesh`) and it was failing till I added some retries.
I then realized that kuma-dp's dns server (`coredns`) needs some time to start, so it should be taken into account.

For kubernetes [it looks like](https://github.com/kumahq/kuma/blob/2e3ace030eb9d663655d5bf4fc63cc149ac7cd39/pkg/plugins/runtime/k8s/webhooks/injector/injector.go#L235-L242) we are injecting `kuma-sidecar` and pointing to envoy's `/ready` endpoint, so I assume we should introduce our own `/ready` endpoint as a part of kuma-dp which would ask `envoy` and `coredns` for readiness.

For `coredns` we could use this plugin: https://coredns.io/plugins/ready/ 

### Steps To Reproduce

1. Deploy `kuma`

   ```shell
   kumactl install control-plane | kubectl apply -f -
   ```

2. Wait for `kuma` to be deployed

3. Annotate `default` namespace to automatically inject `kuma-dp`s

   ```shell
   kubectl annotate namespace default kuma.io/sidecar-injection=enabled
   ```

4. Deploy my simple websocket server

   ```yaml
   ---
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: server
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: server
     template:
       metadata:
         labels:
           app: server
         name: server
       spec:
         containers:
           - name: server
             image: bartsmykla/websockets-test-server:v2-0.1.1
             ports:
               - containerPort: 8080
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: server
   spec:
     ports:
       - port: 80
         protocol: TCP
         targetPort: 8080
     selector:
       app: server
   ```

5. Deploy my simple websocket client

   ```yaml
   ---
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: client
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: client
     template:
       metadata:
         labels:
           app: client
         name: client
       spec:
         containers:
           - name: client
             image: bartsmykla/websockets-test-client:v2-0.1.3
             ports:
               - containerPort: 8081
             command:
             - /client
             args:
             - --ws-server-addr
             - ws://server.default.svc.80.mesh/ws
             - --addr
             - localhost:8081
   ---
   apiVersion: v1
   kind: Service
   metadata:
     name: client
   spec:
     ports:
       - port: 80
         protocol: TCP
         targetPort: 8081
     selector:
       app: client
   ```

6. That's it, you can look into logs of the clent now

### Additional Details & Logs

- Version

any version with kuma-dp dns server

- Error logs
   ```shell
   connecting to ws://server.default.svc.80.mesh/ws
   try: 1
   ws dial response <nil>
   dial error: dial tcp: lookup server.default.svc.80.mesh on 10.43.0.10:53: read udp 10.42.0.12:54793->10.43.0.10:53: read: connection refused
   try: 2
   ws dial response <nil>
   dial error: dial tcp: lookup server.default.svc.80.mesh on 10.43.0.10:53: read udp 10.42.0.12:58566->10.43.0.10:53: read: connection refused
   try: 3
   ws dial response <nil>
   dial error: dial tcp: lookup server.default.svc.80.mesh on 10.43.0.10:53: no such host
   try: 4
   ws dial response <nil>
   dial error: dial tcp: lookup server.default.svc.80.mesh on 10.43.0.10:53: no such host
   try: 5
   ws dial response &{101 Switching Protocols 101 HTTP/1.1 1 1 map[Connection:[Upgrade] Sec-Websocket-Accept:[ZSTFTSTBiZV9PnU+0uPgjtvSh5k=] Upgrade:[websocket]] {0xc00021b2f0} 0 [] false false map[] 0xc0000a8700 <nil>}
   ```
- Configuration
- Platform and Operating System
- Installation Method (Helm, kumactl, AWS CloudFormation, etc.)
