### ISSUE TITLE
Improve protobuf test matcher

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2583]
### Summary

There is a gomega matcher for protobuf comparisons in `pkg/test/matchers`. This issue captures a couple of options for making it easier to see the differences between large protobuf values.

1. Compare the YAML:

```
  Expected
      <string>: http:
      - match:
          headers:
            bar:
              exact: foo
            baz:
              exact: foo
            foo:
              exact: foo
          path:
            exact: /api
      - match:
          headers:
            bar:
              exact: foo
            foo:
              exact: foo
          path:
            exact: /api
      - match:
          headers:
            foo:
              exact: foo
          path:
            exact: /api
      
  to equal
      <string>: http:
      - match:
          headers:
            bar:
              exact: foo
            baz:
              exact: foo
            foo:
              exact: foo
          path:
            exact: /api
      - match:
          path:
            exact: /api
      - match:
          headers:
            foo:
              exact: foo
          path:
            exact: /api
      
  Differences:
    (
    	"""
    	... // 10 identical lines
    	      exact: /api
    	- match:
  - 	    headers:
  - 	      bar:
  - 	        exact: foo
  - 	      foo:
  - 	        exact: foo
    	    path:
    	      exact: /api
    	... // 7 identical lines
    	"""
    )
  

```
```Go
func (p *ProtoMatcher) FailureMessage(actual interface{}) (message string) {
	actualYAML, expectedYAML, err := p.yamls(actual)
	if err != nil {
		return err.Error()
	}
	differences := cmp.Diff(actualYAML, expectedYAML)
	return fmt.Sprintf("%s\nDifferences:\n%s\n",
		format.Message(actualYAML, "to equal", expectedYAML),
		differences)
}
```

2. Compare the protobufs

```
  Expected matching protobuf message:
    (*v1alpha1.TrafficRoute_Conf)(Inverse(protocmp.Transform, protocmp.Message{
    	"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Conf",
    	"http": []protocmp.Message{
    		{"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Http", "match": protocmp.Message{"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Http.Match", "headers": map[string]protocmp.Message{"bar": {"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Http.Match.StringMatcher", "exact": string("foo")}, "baz": {"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Http.Match.StringMatcher", "exact": string("foo")}, "foo": {"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Http.Match.StringMatcher", "exact": string("foo")}}, "path": protocmp.Message{"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Http.Match.StringMatcher", "exact": string("/api")}}},
    		{
    			"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Http",
    			"match": protocmp.Message{
    				"@type":   s"kuma.mesh.v1alpha1.TrafficRoute.Http.Match",
  + 				"headers": map[string]protocmp.Message{"bar": s`{exact:"foo"}`, "foo": s`{exact:"foo"}`},
    				"path":    protocmp.Message{"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Http.Match.StringMatcher", "exact": string("/api")},
    			},
    		},
    		{"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Http", "match": protocmp.Message{"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Http.Match", "headers": map[string]protocmp.Message{"foo": {"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Http.Match.StringMatcher", "exact": string("foo")}}, "path": protocmp.Message{"@type": s"kuma.mesh.v1alpha1.TrafficRoute.Http.Match.StringMatcher", "exact": string("/api")}}},
    	},
    }))
  
```
```Go
func (p *ProtoMatcher) FailureMessage(actual interface{}) (message string) {
	differences := cmp.Diff(p.Expected, actual, protocmp.Transform())
	return "Expected matching protobuf message:\n" + differences
}
```
