### ISSUE TITLE
Traffic Logging proposal

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#271]
# Traffic Logging proposal

## Problem

We want to log the requests between services and report it to a given logging backend like ELK stack or even simple file.

## Solution

We introduce the TrafficLogging policy

```
mesh: default
name: web1-to-backend1
rules:
- destinations:
    - match:
        env: dev
        service: backend1
  sources:
    - match:
        service: web1
        version: "1.0"
  conf:
    backend: access-file
```

In Mesh entity there is a list of backends
```
type: Mesh
name: default
loggin:
  backend:
  - name: access-file
    file:
      path: "/tmp/access.log"
  - name: kibana
    tcp:
      address: kibana.srv:9000
```

In this case, we want to log traffic to file between service backend1 on dev environment to web1 service with version 1.0.

## Implementation

In Envoy, access logs are placed either on TCP Proxy filter or HTTP Connection Manager filter on the listener. Given the dataplane we generate inbound listeners where we know all the tags
and we generate outbound listeners for which we only know the service name.

## L4 - TCP Proxy

We can place access logs definitions on outbound listeners but we only know about a service, so we can match every source tag but only service tag in the destination.

We cannot place access log definitions on inbound listeners because we do not know the source of the traffic.
I can't see any built-in option to carry metadata about tags with TCP traffic. The only info we've got is the source IP and info from cert when mTLS is on (we cannot assume it is on).

There is one idea how to carry tags with L4. In Envoy, there is a concept of dynamic metadata. We could have the custom filter before TCP Proxy which will fetch the Mesh topology (dataplanes)
from the Control Plane and given the source IP:PORT it could match the dataplane and put tags in dynamic metadata. Then we would write custom filter on access logs 
https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/accesslog/v2/accesslog.proto#config-filter-accesslog-v2-extensionfilter
which would only run when it matches proper tags in metadata.
This would only work if Envoys communicates directly. If there is any hop that changes the IP:PORT address it will break.

## L7 - HTTP Connection Manager

In this case we can carry tags as a HTTP headers. Then, we can place access log definition on inbound listener and use the HeaderFilter in access log definition
https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/accesslog/v2/accesslog.proto#config-filter-accesslog-v2-headerfilter
to filter proper incoming traffic.

## Matching multiple rules

For simplicity, let's assume that we are on L7 so we can match all tags and we've got following policy
```
mesh: default
name: web1-to-backend1
rules:
- destinations:
    - match:
        service: *
  sources:
    - match:
        service: *
  conf:
    backend: kibana
- destinations:
    - match:
        env: dev
        service: backend1
  sources:
    - match:
        service: web1
        version: "1.0"
  conf:
    backend: access-file
```

Given traffic from a dataplane with tags `env: dev` and `service: backend1` to another dataplane with tags `service: web1` and `version: "1.0"`, we can interpret this in two ways

### Apply all matching policies

Logs will be sent to kibana and stored in the file.
From the implementation perspective - we generate access log filter for every matching rule.

### Apply the most relevant policy for source-destination pair

Logs will be stored in the file, because the second rule matches more tags.
From the implementation perspective - we cannot set one access log definition on inbound for the most matching rule, because when building Envoy resource in Control Plane we don't know yet the source of traffic. We could generate access log definitions in proper order and only run the first one matching, but there is no such mechanism in Envoy itself.
