### ISSUE TITLE
clash of Headless Service + Regular Service

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#2799]
### Summary

It's possible in Kubernetes to define regular Service and Headless Service for exact same port.

The result is this

```
apiVersion: kuma.io/v1alpha1
kind: DataplaneOverview
mesh: default
metadata: 
  name: mysql-0
  namespace: mysql
spec: 
  networking: 
    address: 10.244.0.7
    inbound: 
      - port: 3306
        tags: 
          app.kubernetes.io/component: primary
          app.kubernetes.io/instance: mysql
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: mysql
          controller-revision-hash: mysql-9d64cf8c6
          helm.sh/chart: mysql-8.8.1
          kuma.io/protocol: tcp
          kuma.io/service: mysql_mysql_svc_3306
          statefulset.kubernetes.io/pod-name: mysql-0
        health: 
          ready: true
      - port: 3306
        tags: 
          app.kubernetes.io/component: primary
          app.kubernetes.io/instance: mysql
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: mysql
          controller-revision-hash: mysql-9d64cf8c6
          helm.sh/chart: mysql-8.8.1
          kuma.io/instance: mysql-0
          kuma.io/protocol: tcp
          kuma.io/service: mysql-headless_mysql_svc_3306
          statefulset.kubernetes.io/pod-name: mysql-0
        health: 
          ready: true
    outbound: 
      - address: 240.0.0.0
        port: 80
        tags: 
          kuma.io/service: mysql-headless_mysql_svc_3306
      - address: 240.0.0.1
        port: 80
        tags: 
          kuma.io/service: mysql_mysql_svc_3306
      - address: 10.96.113.198
        port: 3306
        tags: 
          kuma.io/service: mysql_mysql_svc_3306
    transparentProxying: 
      redirectPortInbound: 15006
      redirectPortOutbound: 15001
      redirectPortInboundV6: 15010
  probes: 
    port: 9000
```

Why would anyone do this? You may want to access the service by Service hostname (ClusterIP) and by individual PodIP.

What we can do about this
1) Add validators that you cannot have 2 inbounds with a same port (I thought we had this?). This won't be obvious for users on Kubernetes what is going on.
2) Not allow a Dataplane to be selected by more than one service or resolve the conflict with annotation `kuma.io/primary-service: "true"` 

It's not the first time that I see two services overlapping (but not yet in this way). I think it would be worth it to check what are the use cases to select a Pod with two Services. It would simplify our life a lot to have 1 DP = 1 Service. 

### Steps To Reproduce

`helm install -n mysql mysql bitnami/mysql`
