### ISSUE TITLE
Configure max connection and connect/idle timeouts on passthrough clusters

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#2905]
### Summary

Right now passthrough clusters have a default limit of connections

```
outbound:passthrough:ipv4::observability_name::outbound_passthrough_ipv4
outbound:passthrough:ipv4::default_priority::max_connections::1024
outbound:passthrough:ipv4::default_priority::max_pending_requests::1024
outbound:passthrough:ipv4::default_priority::max_requests::1024
outbound:passthrough:ipv4::default_priority::max_retries::3
outbound:passthrough:ipv4::high_priority::max_connections::1024
outbound:passthrough:ipv4::high_priority::max_pending_requests::1024
outbound:passthrough:ipv4::high_priority::max_requests::1024
outbound:passthrough:ipv4::high_priority::max_retries::3
```

This limit may not be enough with a high number of connections to destinations outside of the mesh. We can reconfigure this using ProxyTemplate
```
type: ProxyTemplate
mesh: default
name: custom-template-1
selectors:
  - match:
      kuma.io/service: "*"
conf:
  imports:
    - default-proxy
  modifications:
    - cluster:
        operation: patch
        match:
          name: "outbound:passthrough:ipv4"
        value: |
          circuit_breakers: {
            thresholds: [
              {
                max_connections: 2048,
                max_pending_requests: 2048,
                max_requests: 2048,
                max_retries: 3
              }
            ]
          }
```

We should provide a native way of configuring it.

Options that I see right now:
* Configure it via Kuma CP configuration. Not ideal in a multicluster scenario since you need to go and configure Zone CP with it.
* Configure it via Mesh object. Not ideal since Mesh object is already pretty big. Also, we may want to increase the limit only for one data plane proxy.
* Configure it via CircuitBreaker. We would need to introduce some special matching in destination for this to work.

**Comment by lahabana** [comment]
I believe this is now fixed with having `From` in `MeshCircuitBreaker` @lobkovilya can you please confirm?

**Comment by lobkovilya** [comment]
Yes, it's fixed with a new `MeshCircuitBreaker` policy.

**Comment by yukha-dw** [comment]
If I simply want to define `thresholds` without adding any detector, is there any default value in CircuitBreaker that I have to aware of?
```
apiVersion: kuma.io/v1alpha1
kind: CircuitBreaker
mesh: default
metadata:
  name: circuit-breaker-example
spec:
  sources:
  - match:
      kuma.io/service: web_default_svc_80
  destinations:
  - match:
      kuma.io/service: backend_default_svc_80
  conf:
    thresholds:
      maxConnections: 2048
      maxPendingRequests: 2048
      maxRequests: 2048
      maxRetries: 5
```
