### ISSUE TITLE
Kuma init container requires NET_ADMIN priviledge which AWS EKS Fargate does not provide

### ISSUE THREAD

**Issue by Hunter-Thompson** [kumahq/kuma#2920]
### Summary

The Kuma Init container for the dataplane proxy requires NET_ADMIN privilege, which AWS EKS Fargate does not allow.

```
initContainers:
    - args:
        - '--redirect-outbound-port'
        - '15001'
        - '--redirect-inbound=true'
        - '--redirect-inbound-port'
        - '15006'
        - '--redirect-inbound-port-v6'
        - '15010'
        - '--kuma-dp-uid'
        - '5678'
        - '--exclude-inbound-ports'
        - ''
        - '--exclude-outbound-ports'
        - ''
        - '--verbose'
        - '--skip-resolv-conf'
        - '--redirect-all-dns-traffic'
        - '--redirect-dns-port'
        - '15053'
      command:
        - /usr/bin/kumactl
        - install
        - transparent-proxy
      image: 'docker.io/kumahq/kuma-init:1.3.0'
      imagePullPolicy: IfNotPresent
      name: kuma-init
      resources:
        limits:
          cpu: 100m
          memory: 50M
        requests:
          cpu: 10m
          memory: 10M
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  ``` 

### Steps To Reproduce
1. Create EKS Cluster
2. Setup Kuma CP
3. Create Fargate Profile for namespce
4. Create a Pod with Kuma sidecar injected inside the Fargate enabled namespace

### Additional Details & Logs

- Version
`v1.3.0`
- Error logs
```
Pod not supported on Fargate: invalid SecurityContext fields: Capabilities added: NET_ADMIN
```
- Configuration
Default configuration.

Similar issue:

https://github.com/aws/containers-roadmap/issues/682

---

Is there a workaround to using the Init container? People say that using a CNI might help, but since Daemonsets are not allowed, having a custom CNI becomes harder.
