### ISSUE TITLE
Tools for visibility

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#3074]
## Context

Today Kuma doesn't provide good utilities for debugging the final configuration on proxies. Values that were propagated on proxy could be observed using Envoy Admin API `/config_dump`. That's okay for local debugging, but could be challenging to do in production environments and also requires knowledges of how Kuma policies are converted to Envoy config.

The idea is to create Kuma API endpoints, that will bring more visibility. Such endpoints could be used for debugging, e2e-testing and for implementing migration tools related to the new policy matching.

### Observe matched policies

**GET :5681/config/${mesh}/${dataplane}/${policy}** 

returns effective policy that was sent to `${dataplane}`. For example:

```yaml
type: Timeout
mesh: default
name: base
sources:
  - match:
      kuma.io/service: '*'
destinations:
  - match:
      kuma.io/service: '*'
conf:
  http:
    requestTimeout: 10s
    idleTimeout: 1h
---
type: Timeout
mesh: default
name: base
sources:
  - match:
      kuma.io/service: 'backend'
destinations:
  - match:
      kuma.io/service: 'web'
conf:
  http:
    requestTimeout: 5s
    idleTimeout: 30m
```

```
$ curl kuma-cp:5681/config/default/backend-1/timeout
backend-1 -> web
http:
  requestTimeout: 5s
  idleTimeout: 30m
---
backend-1 -> '*'
http:
  requestTimeout: 10s
  idleTimeout: 1h
```
_note: output from endpoints will be strictly formatted in json, this is just for the example_ 

### Dry-run apply

Instead of real apply of the policy we can return the list of changes that will happen in configuration after the policy will be applied for real.

**POST :5681/dry-run/${policy} (+json body with policy)**

Example:
**timeout.json:**
```json
{
  "apiVersion": "kuma.io/v1alpha1",
  "kind": "Timeout",
  "mesh": "default",
  "metadata": {
    "name": "timeouts-backend"
  },
  "spec": {
    "sources": [
      {
        "match": {
          "kuma.io/service": "*"
        }
      }
    ],
    "destinations": [
      {
        "match": {
          "kuma.io/service": "backend"
        }
      }
    ],
    "conf": {
      "connectTimeout": "10s",
      "tcp": {
        "idleTimeout": "1h"
      },
      "http": {
        "requestTimeout": "5s",
        "idleTimeout": "1h"
      },
      "grpc": {
        "streamIdleTimeout": "5m",
        "maxStreamDuration": "30m"
      }
    }
  }
}
```

```
$ curl -H "Content-Type: application/json" --data @timeout.json http://kuma-cp:5681/dry-run/timeout
web-1 -> backend: 
+ tcp.idleTimeout: 1h
+ http.requestTimeout: 5s
---------------------
- tcp.idleTimeout: 50s
- http.requestTimeout: 3s
```
_note: output from endpoints will be strictly formatted in json, this is just for the example_
