### ISSUE TITLE
external services with different hostnames will not route to specific hosts

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3097]
### Summary

It might make sens to have multiple services with the same `kuma.io/service` (For example migrating to the mesh and adding temporary old services).
In this case you differentiate these services by name. However, it looks like currently the tags are not taken into account and the routing might be surprising (see steps to reproduce).

### Steps To Reproduce

1. Create 2 externalServices:
```yaml
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata:
  namespace: default
  name: external1
spec:
  tags:
    kuma.io/service: external
    kuma.io/protocol: http
    type: facebook
  networking:
    address: graph.facebook.com:443
    tls:
      enabled: true
---
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata:
  namespace: default
  name: external2
spec:
  tags:
    kuma.io/service: external
    kuma.io/protocol: http
    type: github
  networking:
    address: api.github.com:443
    tls:
      enabled: true
```
2. add a deployment for testing:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kuma-test
  name: "external-service-play"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "external-service-play"
  template:
    metadata:
      labels:
        app: "external-service-play"
      annotations:
        kuma.io/mesh: default
    spec:
      containers:
        - name: client
          image: nicolaka/netshoot
          command: ["/bin/bash"]
          args: ["-c", "while true; do echo calling; curl -s http://external.mesh; echo fb; curl -s http://facebook.external; echo github; curl -s http://github.external; sleep 2; done"]
          resources:
            limits:
              memory: "32Mi"
              cpu: "200m"
---
```
3. In the container: `kubectl exec -it deployment.apps/external-service-play -n kuma-test /bin/bash`
We can see that `curl http://external.mesh` roundrobins between both fb and github: 
4. Unfortunately `curl http://api.github.com` and `curl http://api.graph.facebook.com` roundrobin too.

This is because all 3 hostnames resolve to the same IP. In practice they should and should match to a more specific vip.

### Additional Details & Logs

- Version 1.3.x

**Comment by lahabana** [comment]
IS this still the case with the new API?

**Comment by slonka** [comment]
Added `needs-reproducing` to reproduce on `targetRef` policies.

**Comment by Automaat** [comment]
I reproduced it locally and this is still the problem when using new policies

**Comment by lahabana** [comment]
@slonka or @lukidzi this is no longer a problem with MeshExternalService right?

**Comment by slonka** [comment]
We use hostname generator and a name so it shouldn't collide in any way. I'll try to manually set `kuma.io/service` to verify.

**Comment by slonka** [comment]
tested with: 

```
apiVersion: kuma.io/v1alpha1
kind: MeshExternalService
metadata:
  name: bin-org
  namespace: kuma-system
  labels:
    kuma.io/service: example
spec:
  match:
    type: HostnameGenerator
    port: 80
    protocol: http
  endpoints:
    - address: httpbin.org
      port: 80
---
apiVersion: kuma.io/v1alpha1
kind: MeshExternalService
metadata:
  name: bin-dev
  namespace: kuma-system
  labels:
    kuma.io/service: example
spec:
  match:
    type: HostnameGenerator
    port: 80
    protocol: http
  endpoints:
    - address: httpbin.dev
      port: 80
```

no weird routing
