### ISSUE TITLE
Ability to override kuma.io/service in a pod

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3238]
### Description

Nothing happens when doing:

```yaml
metadata:
  labels:
    app: demo-app
    kuma.io/service: demo-app
```

This has some security implications that should be considered (you can now impersonate another DP).
