### ISSUE TITLE
logging config uses `defaultBackend` in mesh config when we use `enabledBackend` in other policies

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3242]
### What happened?

For example:
```yaml
type: Mesh
name: default
logging:
  defaultBackend: file
  backends:
    - name: logstash
```

We usually use `enabledBackend`
