### ISSUE TITLE
Custom tags in tracing

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3275]
### Description

Envoy tracing policy allows to add extra tracing info from headers we could support this.

https://www.envoyproxy.io/docs/envoy/latest/api-v3/type/tracing/v3/custom_tag.proto#envoy-v3-api-msg-type-tracing-v3-customtag

**Comment by lahabana** [comment]
Workaround with ProxyTemplates:

```yaml
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: custom-tracing
spec:
  selectors:
    - match:
        kuma.io/service: '*'
  conf:
    imports:
      - default-proxy # apply modifications on top of resources generated by Kuma
    modifications:
      - networkFilter:
          operation: patch
          match:
            name: envoy.filters.network.http_connection_manager
          value: |
            name: envoy.filters.network.http_connection_manager
            typedConfig:
              '@type': type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
              tracing:
                custom_tags:
                - tag: "order-id"
                  requestHeader:
                    name: "order-id"
                    defaultValue: "unknown"
```
