### ISSUE TITLE
Better error when running `kumactl apply` against a Control Plane running on `k8s`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3283]
### What happened?

1) Run kuma Control Plane on k8s
2) Try to create a Dataplane using kumactl

```
echo "
type: Dataplane
mesh: default
name: backend-1
networking:
  inbound:
  - interface: 127.0.0.1:8000:8080
    tags:
      service: backend
  outbound:
  - interface: :3000
    service: myservice.kuma-demo.svc
" | kumactl apply -f
```

3) We get an internal server error.
