### ISSUE TITLE
Replaze zone ingress exec projes with HTTP probes

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3298]
### Description

The YAML that kumactl generates to install a zone ingress deployment execs wget for its probes:
```
          livenessProbe:
            exec:
              command:
                - wget
                - -qO-
                - http://127.0.0.1:9901
            failureThreshold: 12
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            exec:
              command:
                - wget
                - -qO-
                - http://127.0.0.1:9901
            failureThreshold: 12
            initialDelaySeconds: 1
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3

```

We don't need to depend on wget being installed, since we can use a HTTP probe instead.
