### ISSUE TITLE
Use scoped routing in Gateway

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3299]
### Description

Gateway needs to be able to configure policies for virtual hosts (i.e. on the route configuration). To get a new route configuration per-host, we probably need to use Envoy scoped routing based on the `:authority` key.

This should work fine for regular hosts, but wildcard hosts might be a problem because the scoped routing key matched can't match a wildcard. I think that the way to address might be to split the key builder on the `.` character and then alter the number of fragments we match in the scoped route. As long as we can get the key ti match the correct routing table, the virtualhost match will deal with any ambiguity.

**Comment by jpeach** [comment]
I think we will need to carry a patch for scoped route consistency checking https://github.com/envoyproxy/go-control-plane/issues/517

**Comment by jpeach** [comment]
I have scoped routes working for fully qualified hostnames, but I don't think that it can work for wildcard hosts. Discussing in https://github.com/envoyproxy/envoy/issues/19098.

**Comment by jpeach** [comment]
I found another problem with scoped routing. The scoped route configuration xDS resources are global to an Envoy instance, which means that the scope key builder in any Envoy listener can match any scoped route configuration key, *even if that route configuration is intended for a different listener*.

Let's take the following Kuma config:
```yaml
#! /usr/bin/env bash

set -o errexit

readonly SERVICENAME=${SERVICENAME:-edge-gateway}

echo Creating external service
kumactl apply -f <(
cat <<EOF
type: ExternalService
mesh: default
name: httpbin
tags:
  kuma.io/service: httpbin
  kuma.io/protocol: http
networking:
  address: httpbin.org:443
  tls:
    enabled: true
    sni: httpbin.org
EOF
)

echo Creating gateway
kumactl apply -f <(
cat <<EOF
type: Gateway
mesh: default
name: httpbin-gateway
selectors:
- match:
    kuma.io/service: ${SERVICENAME}
conf:
  listeners:
  - port: 8080
    protocol: HTTP
    hostname: 'zero.example.com'
    tags:
      name: example.com
  - port: 8081
    protocol: HTTP
    hostname: 'one.example.com'
    tags:
      name: example.com

EOF
)


echo Creating routes
kumactl apply -f <(
cat <<EOF
type: GatewayRoute
mesh: default
name: httpbin-routes
selectors:
- match:
    kuma.io/service: ${SERVICENAME}
conf:
  http:
    rules:
    - matches:
      - path:
          match: PREFIX
          value: /
      backends:
      - destination:
          kuma.io/service: httpbin
EOF
)

```

In this configuration, envoy should be listening on two ports, and each port should only accept one hostname. However, what appears to happen is that it builds a global scoped route configuration table and tries all the keys. This means that any set of routes would be accessible from any listener, defeating any filter policies that we configure. This would not be acceptable for the behavior we want to implement.

So with this behavior and the lack of support for wildcard routes, it seems to me as though scoped routing in its current form is not feasible for implementing per-host policy in Gateway.
