### ISSUE TITLE
Design `MeshProxy` as a successor to `Dataplane`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3339]
### Description

As in the docs: https://kuma.io/docs/1.3.0/documentation/dps-and-data-model/#dataplane-entity

- https://github.com/kumahq/kuma/issues/3832
- https://github.com/kumahq/kuma/issues/8225
- https://github.com/kumahq/kuma/issues/8915

It would be best to do this in a backward compatible way.

We talked about Dataplane not actually existing in Kubernetes as it's all info from the pod.

An idea:
A workload/proxy has a spiffeId rooted on a CA and metadata.
So we'd have a filter that gets the spiffeID and resolves the metadata associated with it.
This means that you'll be only able to metadata as granular as your spiffeIDs are. In k8s out of the box, that would be your SA, but if you were to use something that give out pod SpiffeIDs granular work would be good.

I guess such a client would need to lookup somewhere (DP?) the spiffeID to populate labels in the metadata which can then be used for matchers.

This would mean that the client verifying the server takes a list of spiffeIds behind a service?
We trust that the spiffeId is given out to the right workload (that's what spiffe is for).
So in the end the SANs would be each of the spiffe ids of the endpoint.
As we already configure the endpoints there's no extra work here (though when there's a lot of spiffe that's a lot of info).

If we have multiple trust_bundle we can use: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls_spiffe_validator_config.proto#extension-envoy-tls-cert-validator-spiffe
What's unfortunate is that this doesn't support SDS so each CA would be repeated for each service.

There's also https://github.com/envoyproxy/envoy/pull/32586 (lua StringMatcher).

For things that fall into metrics etc you want an "identifying" label to figure that these are just replicas of the same deployment.

So I think some things we need:

- name
- spiffeId
- labels
- labelForStat

**Comment by lahabana** [comment]
This probably should go in v2.
It's still tricky to do even with versions as this would make the type different as well.

**Comment by jakubdyszkiewicz** [comment]
A note about V2 after the docs rewrite of V1 https://github.com/kumahq/kuma/pull/5219

It's very hard to describe inbound sections with regard to transparent proxy and not a transparent proxy.
I think what we should do in a model is when transparent proxying is defined the inbound should only define `serviceAddress` and `servicePort` because Envoy is not binding to `port` or `address`.

**Comment by lahabana** [comment]
Some random thoughts @lobkovilya and I had today:

```yaml
type: DataplaneProxy
mesh: default
spec:
  identity: # Comes from the pod in k8s
    deployment-hash: deadbeef
    version: v2
    k8s.kuma.io/deployment: foo
    k8s.kuma.io/namespace: bar
    k8s.kuma.io/pod: foo-argewg
    k8s.kuma.io/serviceAccountName: foo
    kuma.io/client-id: zone-bar-foo-argewg
  inbounds: # Comes from services in k8s
    - port: 5000
      servicePort: 6000
      serviceAddress: 127.0.0.2
      address: 127.0.0.1
      tags:
        kuma.io/service: my-other-svc
      health:
        ready: true
      serviceProbes:
        ...
    - port: 8000
      servicePort: 6000
      serviceAddress: 127.0.0.2
      address: 127.0.0.1
      tags:
        kuma.io/service: my-other-svc
      health:
        ready: true
      serviceProbes:
        ...
  network:
    address: 127.0.0.1 # Is this needed (just a default for inbound address)?
    advertisedAddress: 240.0.0.2
    adminPort: 9901
    probes:
      port: 5000
      endpoints:
        - inPort: 5000
          inPath: /health
          outPath: /5000/health
```
