### ISSUE TITLE
Figure out how services and builtin gateway dataplanes interact in Kubernetes 

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3427]
### What happened?

When we create a pod annotated with `kuma.io/gateway: builtin`, kuma-cp will try to create a builtin gateway dataplane to represent that (per #3294). This attempt will only succeed if there is already a matching Kubernetes service (matching is defined as `util_k8s.FindServices`.

There are 2 problems we need to solve here:

1. The proxy in the builtin dataplane isn't listening on any ports until someone binds a `Gateway` to it. This means that we can't create a sensible Service yet, because we don't know what ports to expose, and ports are a required Service field. worse than that, the listening ports on a `Gateway` can change, at which point we would want the Service ports to change as well.

2. When we create the Kubernetes service this generates a builtin gateway tag similar to `kuma.io/service: edge-gateway-dataplane_kuma-system_svc`. This makes it really hard to interoperate with Universal, where service names are arbitrary strings. For example, it should be totally OK to create a Universal service and then supply builtin dataplanes for it in a Kubernetes zone.

**Comment by jpeach** [comment]
Sample builtin dataplane deployment:

```yaml
# Everything needs to be in the kuma-system namespace so that
# we can get to kuma-cp TLS CA secrets.

--- 

# kuma-cp will authorize any DP that connects with a service account.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuma-gateway-account
  namespace: kuma-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-gateway-dataplane
  namespace: kuma-system
  labels:
    app: edge-gateway-dataplane
  annotations: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-gateway-dataplane
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: edge-gateway-dataplane
      annotations:
        kuma.io/gateway: builtin
        kuma.io/sidecar-injection: disabled
    spec:
      serviceAccountName: kuma-gateway-account
      volumes:
        - name: kuma-tls-cert
          secret:
            secretName: kuma-tls-cert
      containers:
      - name: kuma-dp
        image: docker.io/kumahq/kuma-dp
        imagePullPolicy: IfNotPresent
        args:
        - run
        - --log-level=debug
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KUMA_CONTROL_PLANE_URL
          value: https://kuma-control-plane.kuma-system:5678
        - name: KUMA_CONTROL_PLANE_CA_CERT_FILE
          value: /var/run/secrets/kuma.io/tls-cert/ca.crt
        - name: KUMA_DATAPLANE_NAME
          value: $(POD_NAME).$(POD_NAMESPACE)
        - name: KUMA_DATAPLANE_MESH
          value: default
        - name: KUMA_DATAPLANE_ADMIN_PORT
          value: "9901"
        - name: KUMA_DATAPLANE_DRAIN_TIME
          value: 30s
        - name: KUMA_DATAPLANE_RUNTIME_TOKEN_PATH
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: KUMA_DATAPLANE_PROXY_TYPE
          value: dataplane
        volumeMounts:
          - name: kuma-tls-cert
            mountPath: /var/run/secrets/kuma.io/tls-cert
            readOnly: true

---

apiVersion: v1
kind: Service
metadata:
  name: edge-gateway-dataplane
  namespace: kuma-system
  labels:
    app: edge-gateway-dataplane
  annotations:
spec:
  selector:
    app: edge-gateway-dataplane
  ports:
  - port: 80
    targetPort: 80
```

And kuma-cp generates this dataplane:
```yaml
apiVersion: kuma.io/v1alpha1
kind: Dataplane
mesh: default
metadata:
  creationTimestamp: "2021-12-06T04:01:03Z"
  generation: 1
  name: edge-gateway-dataplane-67d678476d-js7bh
  namespace: kuma-system
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Pod
    name: edge-gateway-dataplane-67d678476d-js7bh
    uid: 36f189cb-f10f-4a3d-8c99-9df2c78f7527
  resourceVersion: "26586"
  uid: c2b4d9ff-065d-458b-924d-5f52cb9741b9
spec:
  networking:
    address: 10.244.0.10
    gateway:
      tags:
        kuma.io/service: edge-gateway-dataplane_kuma-system_svc
      type: BUILTIN
```
