### ISSUE TITLE
Add possibility to restrict which mesh a pod can use

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3458]
### Description

Currently a user can start a pod and have it join any mesh. We should be able to restrict this.
The most likely level is `namespace` which is usually the level at which access control is done in K8s.

One option is adding new fields in the mesh config:

```yaml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  kubernetes:
     allowNamespaceList: ["a", "b"]
     denyNamespaceList: ["c", "d"]
```

**Comment by jakubdyszkiewicz** [comment]
# Mesh Membership

## Context

Right now, on Kubernetes you can change Mesh of Dataplane with `kuma.io/mesh` annotation on Pod.
This raises a problem of how we can restrict service owners of changing mesh of their services.

## Requirements

* Mesh operator can define which Dataplanes (Pods) can join defined Mesh
* Mesh operator can define Namespaces in which Pods can join defined Mesh
* Service owner can switch a Pod between two allowed Meshes (in case of migration)

## Configuration

Since last release, we autogenerate `k8s.kuma.io/namespace` tag. Therefore, we can implement this functionality with just tags in environment agnostic way.

```yaml
type: Mesh
name: demo
mtls:
  ...
dataplaneProxyMembership:
  allowed:
  - tags:
      k8s.kuma.io/namespace: ns-1
  - tags:
      k8s.kuma.io/namespace: ns-2
      kuma.io/zone: east
  - tags:
      k8s.kuma.io/namespace: ns-3
      xyz: abc
  denied: ... # same format as allowed
```

This means that:
* all data plane proxies in Namespace `ns-1` can join the `demo` Mesh.
* all data plane proxies in Namespace `ns-2` in zone east can join the `demo` Mesh.
  This way we can prevent `ns-2` from other zones to join.
* all data plane proxies with labels `xyz: abc` in namespace `ns-2` can also join the `demo` Mesh.

This mechanism can then be potentially reused in other context than Kubernetes. For example:
* Other orchestrators in which we would autogenerate Dataplane proxies (ECS).
* This could be a way to standardize mesh deployment and force service owners to define common tags.
  When `team: *` is defined, only data plane proxies with defined `team` tag can join.

The only problem here is what if we have Mesh that spans across Kubernetes and Universal cluster.
Let's say we have a zone `vms-1` and `vms-2` that are Universal.
The configuration above requires `k8s.kuma.io/namespace` which is not present on Universal clusters.

To support this case we could list them explicitly
```yaml
allowed:
  - tags:
      kuma.io/zone: vms-1
  - tags:
      kuma.io/zone: vms-2
  - tags:
      k8s.kuma.io/namespace: ns-1
  - tags:
      k8s.kuma.io/namespace: ns-2
      kuma.io/zone: east
  - tags:
      k8s.kuma.io/namespace: ns-3
      xyz: abc
```

Alternatively, we could autogenerate tag `kuma.io/environment` with values `kubernetes` or `universal`.
This way we don't have to explicitly list universal zones
```yaml
allowed:
  - tags:
      kuma.io/environment: universal
  - tags:
      k8s.kuma.io/namespace: ns-1
  - tags:
      k8s.kuma.io/namespace: ns-2
      kuma.io/zone: east
  - tags:
      k8s.kuma.io/namespace: ns-3
      xyz: abc
```

`kuma.io/environment` can be also used in other cases like putting `ProxyTemplate` only on universal proxies etc.
To not "pollute" the set of tags, we can only generate it with multizone deployments.
After all, in standalone mode you can only run one type of the environment.

`denied` section is useful for excluding only a couple of tags values (allow all namespaces but `ns-4`) and as a tool to remove compromised or bad behaving data plane proxies.

## Backwards compatibility

This feature is backwards compatible. If no `allowed` is specified on the Mesh, any data plane proxy can join.

## Multizone

In Multizone, this is configured on Global CP and synced to Zone CP as a part of Mesh object.
You can select zones with `kuma.io/zone` tags.
