### ISSUE TITLE
Add kuma.io/service tag to k8s services

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#3603]
### Description

Would be a good UX improvement to annotate k8s services with the `kuma.io/service` name so it was more transparent about which services are selected by policies (rather than having to go and look at the dataplane objects).

**Comment by jakubdyszkiewicz** [comment]
Hey, could you provide an example?

Let's say I have a Dataplane and two services
```
kind: Service
metadata:
  namespace: ns1
  name: service1
spec:
  ports:
  - port: 8080
    targetPort: 8080
  - port: 8081
    targetPort: 8081
---
kind: Service
metadata:
  namespace: ns1
  name: service2
spec:
  ports:
  - port: 7070
    targetPort: 7070
```

`Dataplane` object will have 3 `inbounds` with individual `kuma.io/service` tags:

```
kuma.io/service: service1_ns1_svc_8080
kuma.io/service: service1_ns1_svc_8081
kuma.io/service: service2_ns1_svc_7070
```

What do we want to put in Service objects then?
