### ISSUE TITLE
Install a Kuma GatewayClass as part of the controller install

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3612]
### Description

When the Kuma Gateway API controller is installed. it should create a GatewayClass referring to itself.

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: kuma
spec:
  controllerName: gateways.kuma.io/controller
```
