### ISSUE TITLE
provide an example how to run Kuma (universal mode) and demo app in Docker Compose

### ISSUE THREAD

**Issue by yskopets** [kumahq/kuma#367]
### Summary

* provide an example how to run `Kuma` and demo app in `Docker Compose`

**Comment by yskopets** [comment]
Apparently, it's possible to achieve sidecar-like behaviour in `Docker Compose`.

Here is a proof-of-concept example (test on `Docker for Mac`):

docker-compose,yaml
```
version: "2"

services:
  app:
    image: busybox
    command: top
  sidecar:
    image: busybox
    command: top
    network_mode: "service:app"
```

Demo script:
```
# start 1 instance of `app` and `sidecar` and then scale up to 2
# WARN: when I tried to start 2 instances of each from the beginning, networking configuration was wrong
docker-compose up --detach
docker-compose up --detach --scale app=2 --scale sidecar=2
docker-compose ps

# start HTTP server in each pair of `app + sidecar`
docker-compose exec --detach --index=1 app nc -lk -p 1234 -e echo -e "HTTP/1.1 200 OK\r\nContent-Length: 0\r\n\r\n"
docker-compose exec --detach --index=2 sidecar nc -lk -p 2345 -e echo -e "HTTP/1.1 404 OK\r\nContent-Length: 0\r\n\r\n"

# verify that each `app + sidecar` pair shares its own networking namespace 
docker-compose exec --index=1 app netstat -tlpn
docker-compose exec --index=1 sidecar netstat -tlpn
docker-compose exec --index=2 app netstat -tlpn
docker-compose exec --index=2 sidecar netstat -tlpn

# do sample requests: 1) from inside `app + sidecar` pair 2) from another `app + sidecar` pair
docker-compose exec --index=1 sidecar wget -SO- http://localhost:1234
docker-compose exec --index=2 sidecar wget -SO- http://localhost:1234
docker-compose exec --index=1 sidecar wget -SO- http://localhost:2345
docker-compose exec --index=2 sidecar wget -SO- http://localhost:2345

# verify that both containers inside `app + sidecar` pair have the same `eth0` config
docker-compose exec --index=1 app ifconfig eth0
docker-compose exec --index=2 app ifconfig eth0
docker-compose exec --index=1 sidecar ifconfig eth0
docker-compose exec --index=2 sidecar ifconfig eth0

# cleanup
docker-compose down
```

**Comment by rucciva** [comment]
hi @yskopets , in this docker-compose mode, if we would like to expose the dataplane to outside of the docker network, how would the configuration be?

is this correct? (for example if `app` listen to 80 and the host's IP is 192.168.1.1 )

- `docker-compose.yml`

```
version: "2"

services:
  app:
    image: busybox
    command: top
    ports:
        - 192.168.1.1:1080:1080
  sidecar:
    image: kong-docker-kuma-docker.bintray.io/kuma-dp:0.2.2
    command: run
    network_mode: "service:app"
    environment: 
        # kuma_dp required environments 
```

- `dataplane.yml`

```
---
type: Dataplane
mesh: default
name: app-1
networking:
  inbound:
  - interface: 192.168.1.1:1080:80
    tags:
      service: app
```

i'm a bit confused about how the other dataplane will find the IP to connect to this dataplane

**Comment by yskopets** [comment]
@rucciva Hey!

>  in this docker-compose mode, if we would like to expose the dataplane to outside of the docker network, how would the configuration be?

I'm using `Docker Compose` on my Mac.

In my case, the following 2 configurations are equivalent:

```
services:
  app:
    image: busybox
    command: top
    ports:
    - "1080:80"
```

and 

```
services:
  app:
    image: busybox
    command: top
    ports:
    - "0.0.0.0:1080:80" # notice "0.0.0.0:"
```

In both cases `Docker Compose` makes the `app` available on `0.0.0.0:1080` of my host machine.

Given that host IP is `192.168.1.1`, the `app` (deployed inside `Docker Compose`) can be accessed from outside as `192.168.1.1:1080`

> i'm a bit confused about how the other dataplane will find the IP to connect to this dataplane

In essence, Control Plane connects clients to servers based on `service` tag on `inbound` and `outbound` connections in the `Dataplane` resource. 

Every dataplane must announce its own IP address to the Control Plane as part of `Dataplane` resources, e.g.

```
type: Dataplane
mesh: default
name: app-1
networking:
  inbound:
  - interface: 192.168.0.5:1080:80 # dataplane's IP address is 192.168.0.5
    tags:
      service: app
```

Then, when configuring a dataplane for the client, you need to define `outbound` connections and refer to dependent services by their `service` tag, e.g.:

```
type: Dataplane
mesh: default
name: client-1
networking:
  inbound:
  - interface: 192.168.0.6:3000:3000 # dataplane's IP address is 192.168.0.6
    tags:
      service: client
  outbound:
  - interface: :4000
    service: app # reference to the `app` service
```

After that, when your `client` application needs to call the `app`, it should make requests to `127.0.0.1:4000`.

`client-1` dataplane will be configured by the Control Plane to balance requests received on `127.0.0.1:4000` to `192.168.0.5:1080`

---

By the way, we've prepared an example `Docker Compose` setup in #383.

It's still undergoing code review, but it's already functional on Mac and Linux.

---

Thanks again for your interest in Kuma !

**Comment by rucciva** [comment]
I see, so *regardless of the ip address given by docker daemon to the container*, the ip configured to dataplane should be the one reachable by other dataplane right?

so if i have 2 hosts, 192.168.0.2 and 192.168.0.3, and the app listen to port 80
the docker-compose and dataplane would be like this?

- host 1
```
version: "2"

services:
  app:
    image: busybox
    command: serve --port 80
    ports:
        - 1080:1080
  sidecar:
    image: kong-docker-kuma-docker.bintray.io/kuma-dp:0.2.2
    command: run
    network_mode: "service:app"
    environment: 
        # kuma_dp required environments 
```

```
type: Dataplane
mesh: default
name: app-1
networking:
  inbound:
  - interface: 192.168.0.2:1080:80
    tags:
      service: app
```

- host 2
```
version: "2"

services:
  client:
    image: busybox
    command: curl 127.0.0.1:4000
  sidecar:
    image: kong-docker-kuma-docker.bintray.io/kuma-dp:0.2.2
    command: run
    network_mode: "service:client"
    environment: 
        # kuma_dp required environments 
```

```
type: Dataplane
mesh: default
name: client-1
networking:
  inbound:
  - interface: 192.168.0.3:1080:80
    tags:
      service: client
  outbound:
  - interface: :4000
    service: app
```
