### ISSUE TITLE
Store envoy admin port in data plane proxy resource

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#3717]
### Description

Issue https://github.com/kumahq/kuma/issues/3488 implies implementation using calls to envoy admin API endpoint `/config_dump`. In order to do so, we need to know the envoy admin port. We have this information in dataplaneMetadata, but it's available on the Kuma CP instance that DPP is connected to. 

The final DPP resource may look like:
```yaml
networking:
  inbound: ...
  outbound: ...
  admin:
    port: 9901  
```
