### ISSUE TITLE
Ingress of kuma-global-zone-sync not working

### ISSUE THREAD

**Issue by cloudcafetech** [kumahq/kuma#3724]
### What happened?

We create a global zone in K8S cluster and create a ingress of **kuma-global-zone-sync** service on port **5685** as follows ..

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: kuma
  namespace: kuma-system
spec:
  rules:
  - host: kuma.172.25.32.171.nip.io
    http:
      paths:
      - backend:
          service:
            name: kuma-global-zone-sync
            port:
              number: 5685
        path: /
        pathType: Prefix
```

Now when creating remote zone on different K8S cluster the Control plane POD log showing error.

- Command1

```
kumactl install control-plane   --mode=zone   --zone=prod   --ingress-enabled   --kds-global-address grpcs://kuma.172.25.32.171.nip.io | kubectl apply -f -
```

- POD Logs of above command

```
kds-zone.kds-mux-client component terminated with an error {"generationID": 11, "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: address kuma.172.25.32.171.nip.io: missing port in address\""}
```

- Command2 (with port 80)

```
kumactl install control-plane   --mode=zone   --zone=prod   --ingress-enabled   --kds-global-address grpcs://kuma.172.25.32.171.nip.io:80 | kubectl apply -f -
```

- POD Logs of above command

```
 ERROR   kds-zone.kds-mux-client component terminated with an error {"generationID": 23, "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: first record does not look like a TLS handshake\""}
```

- Command3 (with port 443)

```
kumactl install control-plane   --mode=zone   --zone=prod   --ingress-enabled   --kds-global-address grpcs://kuma.172.25.32.171.nip.io:443 | kubectl apply -f -
```

- POD Logs of above command

```
kds-zone.kds-mux-client component terminated with an error {"generationID": 2, "error": "rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR"}
```

- Command4 (with port 5685) - though not valid for ingress endpoint

```
kumactl install control-plane   --mode=zone   --zone=prod   --ingress-enabled   --kds-global-address grpcs://kuma.172.25.32.171.nip.io:5685 | kubectl apply -f -
```

- POD Logs of above command

```
kds-zone.kds-mux-client component terminated with an error {"generationID": 17, "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.25.32.171:5685: connect: connection refused\""}
```

We running in on-prem Vanilla K8S where I cant use Load balancer as well as Nodeport (due to company security policy).
