### ISSUE TITLE
ability to use hostIp as datadog agent url.

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3732]
### Description

This came up with someone trying to use an environment variable as a parameter in their tracing backend.

They are doing:
```
env:
- name: DOGSTATSD_HOST_IP
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
```

And would like to use this to set the address of the backend.
One possibility would be to enable config to use metadata from the dpp this should maybe exposed in the dataplane configuration.
