### ISSUE TITLE
Way to reduce configuration policy by explicitly stating which Services a DP talks to

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3779]
### Description

Configuration grows linearly with the number of services because all services can theoretically talk to any other service.
It's easy for a service owner to know which services he's talking to (it's harder the other way round).
We should be able to leverage this to drastically reduce the configuration size and make performance easier to control.

This issue covers design and discussion, follow up issues will be opened for implementation

**Comment by jakubdyszkiewicz** [comment]
xref #3350

**Comment by parkanzky** [comment]
So far, we have discussed -

* Dynamic / automatic detection. This does not seem feasible.
* Explicit annotations to specify which dataplanes talk to which services.
* Changing the way we use dataplane outbounds.

**Comment by parkanzky** [comment]
One concern I would have with explicit annotations is introducing Kuma to a large legacy system. It might not be easy to extract all the services that each DP needs to talk to.

**Comment by jakubdyszkiewicz** [comment]
Here are the notes from the meeting

# Specifing outbound

## Kubernetes

```yaml
kind: Deployment
spec:
  template:
    ...
    metadata:
      annotations:
        kuma.io/explicit-outbounds: "redis_kuma-test_svc_80,elastic_kuma-test_svc_80"
```

## Universal

### Reusing outbound

```yaml
type: Dataplane
mesh: default
name: dp-1
networking:
  address: 192.168.0.1
  inbound:
  - port: 8000
    servicePort: 80
    tags:
      kuma.io/service: backend
      kuma.io/protocol: http
  outbound:
  - service: redis_kuma-test_svc_80
  - service: elastic_kuma-test_svc_80
  transparentProxy: ...
```

### Explicit outbound

```yaml
type: Dataplane
mesh: default
name: dp-1
networking:
  address: 192.168.0.1
  inbound:
  - port: 8000
    servicePort: 80
    tags:
      kuma.io/service: backend
      kuma.io/protocol: http
  explicitOutbound:
  - service: redis_kuma-test_svc_80
  - service: elastic_kuma-test_svc_80
  transparentProxy: ...
```

# Enforcing specyfing the outbound

```yaml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  constraints:
    dataplaneProxy:
      requirements:
      - explicitOutbounds: true
      - explicitOutbounds: false
        tags:
          kuma.io/service: pub-sub
```

**Comment by lahabana** [comment]
Open questions that are left out:

1. Should the value of: `kuma.io/explicit-outbounds` be a json array? If yes what does this bring?
2. Is there a better name than: `spec.constraints.dataplaneProxy`  (the dataplaneProxy bit is the most controversial)?
3. Is it confusing for users to reuse Outbounds in this case (which is why there's a second proposal for new fields)?
4. Shall we revive `service` instead of `tags: {"kuma.io/service"}` ?
5. There's a difference in behaviour between K8s and Universal when calling a non existent explicit-outbound. In K8s there's just no configuration in the generated DPP resource. In Universal there is but there's just no Envoy configuration generated for it. Is this a usability issue?

**Comment by lobkovilya** [comment]
I'm slightly concerned about the fact user has to configure a list of services through the annotation. I guess the user will have a Deployment with `template` section for Pod template. Is it even possible to update the annotation without restarting Pods? In my experience, DeploymentController always restarts the Pods. If so, it won't be possible to introduce a new service to the mesh without restarting every deployment that consumes it. 
Also, imagine you want to generate a list of services based on Open API (or other artifacts that company may have to manage APIs) I think it's not really handy to generate content and put it as an annotation value for deployment. 

What I'm saying is maybe we should not through away an idea to introduce another resource for that purpose. We already have `VirtualOutbound` policy, maybe we can do `Outbound`, or maybe we can give another thought to ServiceProfile. I think it is worth at least exploring this direction.

**Comment by jakubdyszkiewicz** [comment]
My opinions

1. The counterargument of the Array is that now it's harder to type because you need all the `{`,`}`,`"` in proper places. The only value I can see that if we have a structured format like this `[{"service":"redis_kuma-test_svc_80"},{"service":"elastic_kuma-test_svc_80"}]`, which makes this even more complicated. We can always migrate to JSON if we want.
2. I'm ok with dataplaneProxy
3. I'm on the fence about reusing the field. Below I present one more alternative
4. I think we should. First of all, with new policy matching we want to have `service` explicit instead of `kuma.io/service`. Second of all, once we have tags, users will try to do stuff like `k8s.kuma.io/ns: ns-1` or they may think that they need to specify every instance like `kuma.io/service+kuma.io/zone:east`,`kuma.io/service+kuma.io/zone:west`
5. I think the Envoy configuration will be the same. If on Universal you specify outbound that we don't have a VIP for it then you won't see the listener.
6. The annotation still applies. I read `constraints.requirements.dataplaneProxy.explicitOutbounds: true` as "explicit outbounds are required for dataplane proxy".  `constraints.requirements.dataplaneProxy.explicitOutbounds: false` as "explicit outbounds are not required for dataplane proxy, but does not mean not allowed or that they are not taken into account".  `constraints.restrictions.dataplaneProxy.explicitOutbounds: true` means that we cannot use explicit outbounds.

Here is one more alternative approach that we can adopt
```
type: Dataplane
mesh: default
name: dp-1
networking:
  address: 192.168.0.1
  inbound:
  - port: 8000
    servicePort: 80
    tags:
      kuma.io/service: backend
      kuma.io/protocol: http
  transparentProxying:
    redirectPortOutbound: 15001
    redirectPortInbound: 15003
    outbound:
    - service: redis_kuma-test_svc_80
    - service: elastic_kuma-test_svc_80
```
Advantages
* More reasonable name than `explicitOutbounds`. The annotation becomes `kuma.io/transparent-proxying-outbound`. Constraint becomes `enforceTransparentProxyingOutbound`.
* Different type than `networking#outbound` so we can just put a `service` for now or just put things connected to `transparentProxying` there


> I'm slightly concerned about the fact user has to configure a list of services through the annotation. I guess the user will have a Deployment with template section for Pod template. Is it even possible to update the annotation without restarting Pods? In my experience, DeploymentController always restarts the Pods. If so it won't be possible to introduce a new service to the mesh without restarting every deployment that consumes it

You can annotate the Pod in runtime if you want, but changing annotation in Deployment means restart of the Pod.
Can you describe a use case that we need to cover with this?
If you want to consume a new service in the mesh, you need to implement code that consumes this service in your application, so you need to deploy a new version of the consumer anyways.

 > Also, imagine you want to generate a list of services based on Open API (or other artifacts that company may have to manage APIs) I think it's not really handy to generate content and put it as an annotation value for deployment.

How is the OpenAPI spec connected with consumed services by the application?

> What I'm saying is maybe we should not through away an idea to introduce another resource for that purpose. We already have VirtualOutbound policy, maybe we can do Outbound, or maybe we can give another thought to ServiceProfile. I think it is worth at least exploring this direction.

Could you draft some examples?

**Comment by bartsmykla** [comment]
I like the approach with placing outbounds in transparent proxying section the most. To be honest I feel uncomfortable knowing that there was some other meaning assigned to `service` property in networking.outbound item, even knowing it was deprecated a long time ago, but I don't have that strong opinion about it to block our efforts if we'll decide going this route.

**Comment by michaelbeaumont** [comment]
1. No super strong opinion on this except that not using JSON makes it marginally more difficult for any tools to programmatically manipulate this value.
2. It's fine
3. What's different enough about this use case that justifies complicating the configuration? What is conceptually different about these outbounds on the service mesh level (not Envoy configuration level)?
4. Yes. I'm not sure why it was ever deprecated.
5. What configuration is missing exactly and what would this be a usability issue?
6. I think by virtue of the fact that it's under a `requirements` key the meaning is relatively clear and we explicitly have the `restrictions` key for disallowing something. Anything else is noise IMO.

**Comment by lobkovilya** [comment]
> You can annotate the Pod in runtime if you want, but changing annotation in Deployment means restart of the Pod.
Can you describe a use case that we need to cover with this?

If you're using GitOps approach I don't think it's convenient to override the annotation for every Pod. About the use case, it could be something like Gateway, when an application dynamically through some external configurations receives the list of services it should consume. Also, you could make a mistake and deploy a new version of the application without updating `kuma.io/explicit-outbounds`. Instead of a simple update of a single resource, you have to now restart the whole deployment. Anyway, it's something that will work on Universal, but won't work on Kubernetes (at least there is no easy way). 

> How is the OpenAPI spec connected with consumed services by the application?

Yeah right, OpenAPI about how to consume your application. But imagine inside the company you already have an artifact in some format that describes what services are consumed by your application. I think it is just more complicated to maintain stuff inside the annotation, it will be poorly formated, imagine how changes in a pull request will look like. 

> Could you draft some examples?

It could be something like this. Just a list of outbounds, but separated from the Dataplane resource.  
```yaml
type: Outbound
mesh: default
name: backend-outbounds
selectors:
  - match:
      kuma.io/service: "backend"
consumes:
  - service: redis_kuma-test_svc_80
  - service: elastic_kuma-test_svc_80
```

**Comment by jakubdyszkiewicz** [comment]
The design that we came up on the call

## Universal

```
type: Dataplane
mesh: default
name: {{ name }}
networking:
  address: {{ address }}
  inbound:
  - port: 8000
    servicePort: 80
    tags:
      kuma.io/service: backend
      kuma.io/protocol: http
  transparentProxying:
    reachableServices:
    - redis_kuma-test_svc_80
    - elastic_kuma-test_svc_80
```

## Kubernetes

```
kuma.io/reachable-services: redis_kuma-test_svc_80,elastic_kuma-test_svc_80
```

which will filter list of outbound that we currently provide for backwards compatibility and at the same time put `reachableServices` in the `transparentProxying`

```
type: Dataplane
mesh: default
name: {{ name }}
networking:
  address: {{ address }}
  inbound:
  - port: 8000
    servicePort: 80
    tags:
      kuma.io/service: backend
      kuma.io/protocol: http
  outbound: # real outbound still stays as is for now
    - port: 1234
      address: 192.17...
      tags:
        kuma.io/service: redis_kuma-test_svc_80
  transparentProxying:
    reachableServices:
    - redis_kuma-test_svc_80
```
