### ISSUE TITLE
After enable MTLS application not accessable.

### ISSUE THREAD

**Issue by cloudcafetech** [kumahq/kuma#3793]
Multi  cluster 2 zone with 1 global zone.

Then install Bookinfo app deployed in two clusters as follows.

- Deployed productpage and details services and version v1 of the reviews service in Cluster1

- Deployed ratings service and version v2 and v3 of the reviews service in Cluster2

Using standard Nginx Ingress Controller I can access Productpage, I can see version v1 but **not v2 & v3**.

once I enable MTLS

```
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  mtls:
    enabledBackend: ca-1
    backends:
      - name: ca-1
        type: builtin
        dpCert:
          rotation:
            expiration: 1d
        conf:
          caCert:
            RSAbits: 2048
            expiration: 10y
```

Not ablet to productpage :(
