### ISSUE TITLE
Traffic routing with headers not working

### ISSUE THREAD

**Issue by cloudcafetech** [kumahq/kuma#3806]
### What happened?

I have installed bookinfo application across two clusters as follows ,,

![image](https://user-images.githubusercontent.com/68260844/153221005-26f547c8-fad8-41d5-833a-845c74ee6a34.png)

Now I want if user login as **pkar** then productpage should shows **review V2 & V3** which running on **Stage** cluster.

For other user or blank user, productpage should shows **review V1** only which is running on **Dev** cluster.

Tried as follows with [Ref](https://kuma.io/docs/1.4.x/policies/traffic-route/#l7-traffic-split) but no luck

```
echo "apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata: 
  name: productpage-review
spec: 
  sources: 
    - match: 
        kuma.io/service: '*'
  destinations: 
    - match: 
        kuma.io/service: reviews_sample_svc_9080
  conf: 
    loadBalancer: 
      roundRobin: 
    split: 
    - weight: 100
      destination: 
        kuma.io/service: reviews_sample_svc_9080
        kuma.io/zone: dev
        version: v1
    http: 
      - match: 
          headers: 
            some-header: 
              regex: "^pkar$"
        split: 
          - weight: 50
            destination: 
              kuma.io/service: reviews_sample_svc_9080
              kuma.io/zone: stage
              version: v3
          - weight: 50
            destination: 
              kuma.io/service: reviews_sample_svc_9080
              kuma.io/zone: stage
              version: v2 " | kubectl apply -f -
```

- Routes status

```
$kumactl get traffic-routes

MESH      NAME                 AGE
default   productpage-review   24m
default   route-all-default    16m
```

**Comment by lobkovilya** [comment]
Hi @cloudcafetech, sorry for the long response. What header are you using for carrying the user name? I see in your example that you didn't update the header's name, it's still `some-header`

**Comment by cloudcafetech** [comment]
What I want as follows...

If user login as pkar then productpage should shows review V2 & V3 which running on Stage cluster.

Now help me to create trafficroute.

**Comment by lobkovilya** [comment]
Could you please tell me what header are you using for the user's name?

**Comment by cloudcafetech** [comment]
I am not a developer, just as infra guy.

similarly I did it for istio and works.

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - reviews
  http:
  - match:
    - headers:
        end-user:
          exact: pkar
    route:
    - destination:
        host: reviews
        subset: v2
      weight: 50
    - destination:
        host: reviews
        subset: v3
      weight: 50
  - route:
    - destination:
        host: reviews
        subset: v1
```

**Comment by lobkovilya** [comment]
Try that:
```
echo "apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata: 
  name: productpage-review
spec: 
  sources: 
    - match: 
        kuma.io/service: '*'
  destinations: 
    - match: 
        kuma.io/service: reviews_sample_svc_9080
  conf: 
    loadBalancer: 
      roundRobin: 
    split: 
    - weight: 100
      destination: 
        kuma.io/service: reviews_sample_svc_9080
        kuma.io/zone: dev
        version: v1
    http: 
      - match: 
          headers: 
            end-user: 
              regex: "^pkar$"
        split: 
          - weight: 50
            destination: 
              kuma.io/service: reviews_sample_svc_9080
              kuma.io/zone: stage
              version: v3
          - weight: 50
            destination: 
              kuma.io/service: reviews_sample_svc_9080
              kuma.io/zone: stage
              version: v2 " | kubectl apply -f -
```
