### ISSUE TITLE
Review inbounds to simplify identity

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3832]
### Description

With the current setup where each inbound is identified separately with their own kuma.io/service and tags it created the following issues:

- The cert has multiple names which is not very SPIFFE compliant
- Outside traffic is identified by internal ports (Metrics can be a little strange in this context)
- Applying policies is not straight forward

This has a huge impact as it's changing our data-model significantly and we should think about this as some things will likely break.

**Comment by lahabana** [comment]
One option could be to have the possibility to mark an inbound as `primary`.

.e.g:

```yaml
inbounds:
   - port: 8080
      tags:
        kuma.io/service: my_svc
        v: 2
   - port: 8081
      primary: true
      tags:
        kuma.io/service: my_svc2
```

If primary is never true we do what we do now.
If primary is true we use this as unique spiffe id and therefore all from matching on `targetRef.kind: MeshService`.

In k8s that'd be an extra annotation.

The other option is to really have a separate id when acting as a client:

```yaml
networking:
   client_identity:
      kuma.io/service: whatever (maybe even a serviceAccount in k8s?)
      tags:
         v: 2
   inbounds:
   - port: 8080
      tags:
        kuma.io/service: my_svc
        v: 2
   - port: 8081
      tags:
        kuma.io/service: my_svc2
```

In that case the spiffe would be what's in client_identity and there's likely a new `targetRef.kind`, this also makes serviceless pods a lot less ambiguous.
