### ISSUE TITLE
ProxyTemplate match on the individual listener

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#3835]
### Description

Proxy Templates enables you to modify Envoy resources that were already generated by Kuma.

Modifications on the listener can be targeted using `origin` to apply them for example on all inbound or all outbound listeners. On top of that, you can match by individual listener name. However, inbound listeners name contains IP (PodIP in case of Kubernetes) and port which can change and it's not stable between different instances of the same services. Outbound listeners contains VIP or ClusterIP which can also change.

We can add kuma.io/service tag (and potentially all tags) to `Listener#metadata` and expose a new way of matching
```
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: custom-template-1
spec:
  selectors:
    - match:
        kuma.io/service: backend_default_svc_80
  conf:
    imports:
      - default-proxy
    modifications:
      - listener:
          operation: patch
          match:
            listenerMetadata:
              kuma.io/service: backend
            origin: inbound
          value: |
            continueOnListenerFiltersTimeout: true
```
