### ISSUE TITLE
inbound timeout are set to nil 

### ISSUE THREAD

**Issue by skaravad** [kumahq/kuma#3934]
### What happened?

Many of our services take more than 15 secs to complete the request, though we applied the timeout policy, it applies only for outbound connection, however this is more like a timeout between kuma-sidecar -> service connection (upstream timeout). Ideally this should be configurable.

As of today it appears to be set as `nil` and defaults to envoy timeout 15s , thanks to @lobkovilya who identified the issue and provided a workaround, but this workaround should be applied to each service, which can be painful.

Here the workaround:
```
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: backend-template
spec:
  selectors:
    - match:
        kuma.io/service: backend_svc_80
  conf:
    imports:
      - default-proxy
    modifications:
      - virtualHost:
          operation: remove
          match:
            origin: inbound
            name:  backend_svc_80
            routeConfigurationName: inbound:backend_svc_80
      - virtualHost:
          operation: add
          match:
            origin: inbound
            routeConfigurationName: inbound:backend_svc_80
          value: | 
            name: backend_svc_80
            domains:
            - "*"
            routes:
            - match:
                prefix: /
              route:
                cluster: "localhost:8080"
                timeout: "9000s"
                idle_timeout: "9000s"
``` 
On a side note, the timeout policy is not getting applied properly as well,  the client closes connection in 5 mins which is again default envoy timeout, we applied a proxy template and it is working, but it looks like this needs to be addressed too.

Here is the template (it may not be accurate for all protocols but at least works for HTTP)
```
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: downstream-timeout
spec:
  selectors:
    - match:
        kuma.io/service: '*'
  conf:
    imports:
      - default-proxy
    modifications:
      - networkFilter:
          operation: patch
          match:
            name: envoy.filters.network.http_connection_manager
          value: |
            name: envoy.filters.network.http_connection_manager
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              commonHttpProtocolOptions:
                idleTimeout: 3600s
              http2ProtocolOptions:
                max_concurrent_streams: 100
                initial_stream_window_size: 65536
                initial_connection_window_size: 1048576
              stream_idle_timeout: 1800s
              request_timeout: 1800s
```
