### ISSUE TITLE
Importing `gateway-proxy` in `ProxyTemplates` manifest results in error

### ISSUE THREAD

**Issue by marcoferrer** [kumahq/kuma#3935]
### What happened?

kuma versions
```
Client: Kuma 1.5.0
Server: Kuma 1.5.0
```

This documentation leads me to believe that when writing a `ProxyTemplate` for a new built in gateway I should import `gateway-proxy`

https://kuma.io/docs/dev/policies/proxy-template/#builtin-gateway-support

But doing so results in the following error message
```
The ProxyTemplate "edge-gateway" is invalid: spec.conf.imports[0]: profile not found. Available profiles: default-proxy
```

This can be reproduced by applying the following manifest
```yaml
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: edge-gateway
spec:
  selectors:
    - match:
        kuma.io/service: edge-gateway
  conf:
    imports:
      - gateway-proxy
    modifications:
      - cluster:
          operation: add
          value: |
            name: test-cluster
            connectTimeout: 5s
            type: STATIC
```
