### ISSUE TITLE
Configuring listener of type tcp in `MeshGateway` results in error

### ISSUE THREAD

**Issue by marcoferrer** [kumahq/kuma#3936]
### What happened?

kuma versions
```
Client: Kuma 1.5.0
Server: Kuma 1.5.0
```
The following manifest results in an error
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
mesh: default
metadata:
  name: edge-gateway
spec:
  selectors:
    - match:
        kuma.io/service: edge-gateway
  conf:
    listeners:
      - port: 8080
        protocol: TCP
        tags:
          port: tcp/8080
```

Error message
```
The MeshGateway "edge-gateway" is invalid: spec.conf.listeners[0].protocol: protocol type is not supported
```
