### ISSUE TITLE
ExternalService with wrong address leads to the lack of listeners in DPP

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#3980]
### What happened?

I was writing an e2e test and ran into weird issue. 

1. Checkout changes from the branch [bug/no-listeners-on-dpp](https://github.com/kumahq/kuma/compare/bug/no-listeners-on-dpp?expand=1)
2. Change `PIt` to `FIt`
3. Run `E2E_PKG_LIST=test/e2e/faultinjection/universal/... make test/e2e/debug-universal`
4. Run `docker exec -ti kuma-4_dp-demo-client /bin/bash`
5. Run `curl localhost:9901/listeners`

Expected: list of listeners
Actual: empty response

If change external service address to the real one (like `httpbin.org:80`), then listeners will be synced correctly.

**Comment by lahabana** [comment]
Triage: This is with ZoneEgress

**Comment by lahabana** [comment]
This issue only seems to be reproducible on docker for mac.

**Comment by jakubdyszkiewicz** [comment]
I think this may be caused by cluster warm on init.
I saw a similar issue here in test, but it was ready after 1 minute. Fixed with proxy template https://github.com/kumahq/kuma/pull/4813

**Comment by slonka** [comment]
@lobkovilya is this still the case?

**Comment by lukidzi** [comment]
I've tried to reproduce this by creating ExternalService with no existing domain name but there was no error/cluster in k8s and listeners were available 

```yaml
echo 'apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata:
  name: httpbin
spec:
  tags:
    kuma.io/service: httpbin
    kuma.io/protocol: http # optional, one of http, http2, tcp, grpc, kafka
  networking:
    address: hnajdfnak.org:80
' | kubectl apply -f -
```
@lobkovilya was is the case with an incorrect address or something different?
