### ISSUE TITLE
Mesh gateway svc - support for additional annotations and loadBalancerIp

### ISSUE THREAD

**Issue by wjrbetts** [kumahq/kuma#4075]
### Description

So that a user can have more control over how a cloud load balancer is created for a mesh gateway service, they should be able to specify a loadBalancerIp and additional annotations. These would then get included in the mesh gateway service that is created.

Perhaps something like:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: edge-gateway
spec:
  replicas: 1
  serviceType: LoadBalancer
  loadBalancerIp: 1.2.3.4
  additionalAnnotations:
    annotation1Name: annotation1Value
    annotation2Name: annotation2Value
  tags:
    kuma.io/service: edge-gateway
```
