### ISSUE TITLE
Mesh gateway instance unable to create listener when hostname is omitted/a wildcard

### ISSUE THREAD

**Issue by wjrbetts** [kumahq/kuma#4091]
### What happened?

When I set hostname to be '*' or leave hostname out of the MeshGateway config, the MeshGatewayInstances I have running get the following error:

`[2022-03-31 08:33:51.627][24][warning][config] [source/common/config/grpc_subscription_impl.cc:126] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) mesh-gateway:HTTPS:8443: error adding listener '10.117.1.32:8443': partial wildcards are not supported in "server_names"`

When I set it to a non-wildcard value the listener is created successfully.

Here is my MeshGateway config:
```yaml
type: MeshGateway
mesh: default
name: mesh-gateway
conf:
  listeners:
    - port: 8443
      protocol: HTTPS
      tls:
        certificates:
          - inline: <redacted>
        mode: TERMINATE
selectors:
  - match:
      kuma.io/service: mesh-gateway
```

Here is my MeshGatewayInstance config:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: mesh-gateway
  namespace: kuma-system
spec:
  replicas: 3
  serviceType: ClusterIP
  tags:
    kuma.io/service: mesh-gateway
```

One thing to note about my setup is that I have created an additional service manually to get functionality requested in https://github.com/kumahq/kuma/issues/4075 and https://github.com/kumahq/kuma/issues/4084. I can't see why that would cause this issue, but here is the config for that service in case this is a  relevant detail:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: mesh-gateway-workaround
  namespace: kuma-system
  labels:
    app: mesh-gateway-workaround
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: xxxxxxx
spec:
  type: LoadBalancer
  loadBalancerIP: x.x.x.x
  ports:
    - name: httpsport
      protocol: TCP
      targetPort: 8443
      port: 443
  selector:
    app: mesh-gateway
```
