### ISSUE TITLE
Test resource builders

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4133]
### Description

We need test resource builders, we end up with such code right now
```
	dp := func(idx int) string {
		return fmt.Sprintf(`
type: Dataplane
mesh: hc-panic
name: dp-echo-%d
networking:
  address: 192.168.0.%d
  inbound:
  - port: 8080
    servicePort: 80
    tags:
      kuma.io/service: test-server
      kuma.io/protocol: http`, idx, idx)
	}

```
in multiple places. The majority of time we don't even care about the content of fields, we just want a valid resource.

There is a WIP done by me on `resource-builder` branch
