### ISSUE TITLE
Support configuration of Envoy's OAuth plugin (for MeshGateway and Gateway)

### ISSUE THREAD

**Issue by zd9KgA** [kumahq/kuma#4172]
### Description

Hello!

I'd like to leverage Envoy's support for OAuth2-based authentication either on the mesh gateway or (just now) the api gateway. I'm currently deploying an extra Envoy in front of the Kuma Mesh, which allows me to leverage the following configuration (with some env-style variable names instead of their values and a URL structure suited for Otka).

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  name: envoyproxy-config
  namespace: ${NAMESPACE}
data:
  envoy.yaml: |
    ---
    admin:
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 9901
    static_resources:
      secrets:
        - name: token
          generic_secret:
            secret:
              inline_string: ${OAUTH2_CLIENT_SECRET}
        - name: hmac
          generic_secret:
            secret:
              inline_string: ${OAUTH2_HMAC_SECRET}
      listeners:
        - address:
            socket_address:
              address: 0.0.0.0
              port_value: 10000
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    codec_type: AUTO
                    stat_prefix: ingress_http
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: upstream
                          domains:
                            - "*"
                          routes:
                            - match:
                                prefix: /
                              route:
                                cluster: upstream-service
                    http_filters:
                      - name: envoy.filters.http.oauth2
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.oauth2.v3.OAuth2
                          config:
                            token_endpoint:
                              cluster: oauth
                              uri: "https://${OAUTH2_SERVER}/oauth2/${OAUTH2_API_AS}/v1/token"
                              timeout: 5s
                            authorization_endpoint: "https://${OAUTH2_SERVER}/oauth2/${OAUTH2_API_AS}/v1/authorize"
                            redirect_uri: "%REQ(:scheme)%://%REQ(:authority)%/callback"
                            redirect_path_matcher:
                              path:
                                exact: /callback
                            signout_path:
                              path:
                                exact: /logout
                            forward_bearer_token: true
                            credentials:
                              client_id: ${OAUTH2_CLIENT_ID}
                              token_secret:
                                name: token
                              hmac_secret:
                                name: hmac
                            auth_scopes:
                              - email
                              - openid
                              # - user
                      - name: envoy.filters.http.csrf
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.csrf.v3.CsrfPolicy
                          filter_enabled:
                            default_value:
                              numerator: 100
                      - name: envoy.filters.http.router
                        typed_config: {}
      clusters:
        - name: upstream-service
          connect_timeout: 2s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: upstream-service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: ${GATEWAY_SERVICE:-edge-gateway}
                          port_value: 8080
        - name: oauth
          connect_timeout: 2s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: oauth
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: ${OAUTH2_SERVER}
                          port_value: 443
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              sni: ${OAUTH2_SERVER}
```

Using `ProxyTemplate`, I manage to configure the parts for the listener as well as for the clusters. But I lack support for specifying the static resource:

```yaml
    static_resources:
      secrets:
        - name: token
          generic_secret:
            secret:
              inline_string: ${OAUTH2_CLIENT_SECRET}
        - name: hmac
          generic_secret:
            secret:
              inline_string: ${OAUTH2_HMAC_SECRET}
```
Would it be an option to extend the use of Kuma `Secret` for purposes like this?
