### ISSUE TITLE
Design MeshTrafficPermission

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#4222]
### Description

As https://github.com/kumahq/kuma/pull/4197 is merged, we can try to implement a new policy MeshTrafficPermission using policy-gen.

### Example

```yaml
---
# Universal
---
type: MeshTrafficPermission
mesh: default
name: default-tp
spec: # move everything under `.spec` to look similar with k8s
  selectors:
    service: ‘backend’
    tags:
      version: v2
  conf:
    rules:
    - service: malicious
      tags: {} # map of other tags
      action: deny
      http: … # potential new section that enables L7 TrafficPermission
    defaultAction: allow
    mode: strict
---
# Kubernetes
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
mesh: default
metadata:
  name: mtp-1
spec:
  selectors:
    service: ‘backend’
    tags:
      version: v2
  conf:
    rules:
    - service: malicious
      tags: {} # map of other tags
      action: deny
      http: … # potential new section that enables L7 TrafficPermission
    defaultAction: allow
    mode: strict
```

ref: [Policy matching V2](https://docs.google.com/document/d/1FM72PCThcTD6kg920g8LTw7oeBgSZ-0HaRi6D6TrcrU/edit?usp=sharing)

**Comment by lahabana** [comment]
What is the `mode`?

**Comment by lobkovilya** [comment]
> Didn't we discuss about moving everything except name/type/mesh in a spec so that the universal and k8s look a lot similar?

Yep, I unconsciously copied example from the doc, you're right, I added `.spec`. 
> What is the mode?

Ability to override STRICT/PERMISSIVE mTLS mode that's set on Mesh. Probably we should rename it to `mTLSMode`?

**Comment by lahabana** [comment]
Yes sounds like the mode is not specific enough.

**Comment by michaelbeaumont** [comment]
@lobkovilya Can you include the intended semantics of this policy?

```
spec:
  selectors:
    service: ‘backend’
    tags:
      version: v2
  conf:
    rules:
    - service: malicious
      tags: {} # map of other tags
      action: deny
      http: … # potential new section that enables L7 TrafficPermission
```

would this this deny traffic from `malicious` to `backend,v2`?

**Comment by jakubdyszkiewicz** [comment]
I'm not sure if permissive/strict mTLS can be applied on the traffic from specific source. Can you check that?

I have a feeling that for permissive/strict we may need to have a separate `MeshMTLS` policy that defines backend and mode.

**Comment by michaelbeaumont** [comment]
@lobkovilya @jakubdyszkiewicz 
What I meant was that I think traffic comes to a proxy and then goes to a route, independent of where it comes from. And so for HTTP rules, we would mix entries with different `routeName`s. Their ordering relative to each other is as far as I can tell meaningless but for the same `routeName` the order is important.

For example

```
routeRules:
- service: A
  action: allow
  routeName: app1-routes
- service: A
  routeName: app2-routes
- service: A
  tags:
    foo: bar
  action: deny
  routeName: app1-routes
```

has the same semantics as

```
routeRules:
- service: A
  action: allow
  routeName: app1-routes
- service: A
  tags:
    foo: bar
  action: deny
  routeName: app1-routes
- service: A
  routeName: app2-routes
```


So instead maybe

```
routeRules:
- routeName: app1-routes
  rules:
  - service: A
    action: allow
  - service: A
    tags:
      foo: bar
    action: deny
- routeName: app2-routes
  rules:
  - service: A
    action: allow
```

where the ordering of the outer list is entirely meaningless and is equivalent to

```
rulesByRouteName:
  app1-routes:
    rules: [..]
  app2-routes:
    rules: [..]
```

but most k8s APIs don't typically have this structure since it's perhaps less obvious what the keys refer to.

Does that make sense?

**Comment by lobkovilya** [comment]
@michaelbeaumont I think it's better to be closer to envoy configuration when you have `principal` (service + tags) and `permission` (routeName). For each `principal` we have a list of `permissions`. So I'd better allow several route names for each rule item to have more compact policy:
```
routeRules:
- service: A
  action: allow
  routeNames: 
  - app1-routes
  - app2-routes
- service: A
  tags:
    foo: bar
  action: deny
  routeNames: 
  - app1-routes
```

**Comment by michaelbeaumont** [comment]
> I think it's better to be closer to envoy configuration when you have principal (service + tags) and permission (routeName).

Why? We're building an abstraction on top of Envoy. It should be an implementation detail in most cases.

I personally think refining like:

```
dataplane (or gateway) > route > who can access it?
```

is more intuitive because I think `dataplane/gateway + route` is the self-contained unit being protected.

I don't think it's as natural to think

```
dataplane (or gateway) > who's accessing it > which routes can they use?
```

because the `dataplane/gateway` isn't enough information to know what information you're protecting, you need to have the context of the `route` in question.

For compactness I could imagine:

```
routeRules:
- routeNames:
  - app1-routes
  - app2-routes
  rules:
  - service: A
    action: allow
  - service: A
    tags:
      foo: bar
    action: deny
```

I suspect that the issue here is that we need to be able to attach permissions directly to routes. IMO once you have routes, attaching to tags alone is no longer enough, at least for `MeshGateway`. [This is the issue that Gateway APIs policy attachment solves.](https://gateway-api.sigs.k8s.io/v1alpha2/references/policy-attachment/#policy-attachment-for-ingress)
