### ISSUE TITLE
With CNI, the network-attachment-definition is only created when the kuma annotations are on the namespace

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#4224]
### What happened?

If you have mesh deployed with CNI enabled and you add the kuma annotations to the deployment then the kuma-cni `network-attachment-definition` is not created and it fails with:

` Warning NoNetworkFound     106s         multus       cannot find a network-attachment-definition (kuma-cni) in namespace (openshift-ingress): [network-attachment-definitions.k8s.cni.cncf.io](http://network-attachment-definitions.k8s.cni.cncf.io/) "kuma-cni" not found`. If you add the kuma annotations to the namespace then it works fine as the network-attachment-definition is created`

**Comment by lahabana** [comment]
My suspicion is that the deployment is annotated and not the pod.

This won't work:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: kuma-example
  labels:
    # BAD THE POD NEEDS TO BE LABELED NOT THE DEPLOYMENT
    kuma.io/sidecar-injection: disabled
spec:
  ...
  template:
    metadata:
      ...
    spec:
      containers:
      ...
```

This will work:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: kuma-example
spec:
  ...
  template:
    metadata:
      ...
      labels:
        # indicate to Kuma that this Pod doesn't need a sidecar
        kuma.io/sidecar-injection: disabled
    spec:
      containers:
        ...
```
