### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#4256]
### Description

Currently our documented solution for websockets support is to designate the service as `tcp`: https://kuma.io/docs/1.6.x/policies/protocol-support-in-kuma/#websocket-support. However this discounts services that may provide websocket and regular services (requiring an `http` designation for various policies / functionality to work). 

Is there a way we could provide websocket support with an `http` service leveraging Envoy's `upgrade_config`?

Sample ProxyTemplate to achieve this below:

```yaml
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: ws-upgrade-out
spec:
  selectors:
    - match:
        kuma.io/service: '*'
  conf:
    imports:
      - default-proxy
    modifications:
      - networkFilter:
          operation: patch
          match:
            name: envoy.filters.network.http_connection_manager
          value: |
            name: envoy.filters.network.http_connection_manager
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              upgrade_configs:
                - upgrade_type: websocket
              http2_protocol_options:
                allow_connect: true
```

This is slightly simplified (the `http2_protocol_options` really only need to be on the `inbound` HCMs). Also there are two options w.r.t. protocol options. Because HTTP2 doesn't support websocket upgrade, you either need to set the outbound cluster to `http_protocol_options` (to force HTTP1.1) or set `allow_connect` on the `http2_protocol_options` to allow HTTP2 between Envoy's but allow it to use CONNECT protocol to essentially tunnel it through to the eventual upstream. Depends on the use case / requirements as to which you'd use I guess :shrug:
