### ISSUE TITLE
MeshGateway CRD's installation issue with batch job

### ISSUE THREAD

**Issue by ravish-kumar-maersk** [kumahq/kuma#4258]
### What happened?

Summary - 
Kuma uses the batch job "kuma-install-missing-crds" to install the meshgateway crd's. The batch job does not have any resources defined in it and the "[pre-upgrade-job](https://github.com/kumahq/kuma/blob/1.6.0/deployments/charts/kuma/templates/pre-upgrade-install-missing-crds-job.yaml#L122)" container dies with OOM. 
CPU - 30m
Memory - 64Mi

The second iteration with CPU 60m and Memory 128Mi was successful. 

I am using LimitRange to define resources at namespace level. 

Can the CPU and memory for the batch job be defined in the chart itself as default? 

Steps - 
1). Create Helm repo 

```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kuma
  namespace: kuma-system
spec:
  interval: 5m
  url: https://kumahq.github.io/charts
```

2). Install kuma
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuma
  namespace: kuma-system
spec:
  releaseName: kuma
  interval: 5m
  chart:
    spec:
      chart: kuma
      version: "=1.6.0"
      sourceRef:
        kind: HelmRepository
        name: kuma
  values:
    experimental:
      # -- If true, it installs experimental built-in Gateway support
      meshGateway: true
```

Error Log - 

```
kubectl describe pod kuma-install-missing-crds-dfbw7 -n kuma-system

Name:         kuma-install-missing-crds-dfbw7
Namespace:    kuma-system
Priority:     0
Node:         xxxx-xxx
Start Time:   Thu, 05 May 2022 17:34:46 +0530
Labels:       app.kubernetes.io/instance=kuma
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=kuma
              app.kubernetes.io/version=1.6.0
              controller-uid=e049e551-3b07-49de-999b-5cb8ba299227
              helm.sh/chart=kuma-1.6.0
              job-name=kuma-install-missing-crds
Annotations:  kubernetes.io/limit-ranger:
                LimitRanger plugin set: cpu, memory request for container pre-upgrade-job; cpu, memory limit for container pre-upgrade-job; cpu, memory re...
Status:       Running
IP:           10.1.1.115
IPs:
  IP:           10.1.1.115
Controlled By:  Job/kuma-install-missing-crds
Init Containers:
  pre-upgrade-job-init:
    Container ID:  containerd://a78a5e5c870ccbfaf4fd9a82373f24b2345de674057267c6c58021735129e6ba
    Image:         docker.io/kumahq/kumactl:1.6.0
    Image ID:      docker.io/kumahq/kumactl@sha256:4910d8960b6d17b709a34ec99030c450588301836af6f25bfd2b2b72000d2723
    Port:          <none>
    Host Port:     <none>
    Command:
      /kuma/scripts/save_missing_crds.sh
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 05 May 2022 17:34:49 +0530
      Finished:     Thu, 05 May 2022 17:34:55 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     30m
      memory:  64Mi
    Requests:
      cpu:        30m
      memory:     64Mi
    Environment:  <none>
    Mounts:
      /kuma/missing from missing-crds (rw)
      /kuma/scripts from scripts (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-npp46 (ro)
Containers:
  pre-upgrade-job:
    Container ID:  containerd://b4ab7e0acbb45b2e41a502c4b46bd3161030579178b4f798f29d4565f2e81ec9
    Image:         bitnami/kubectl:1.20
    Image ID:      docker.io/bitnami/kubectl@sha256:45dddaa9b519329a688366e2b6119214a42cac569529ccacb0989c43355f0255
    Port:          <none>
    Host Port:     <none>
    Command:
      /kuma/scripts/install_missing_crds.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Thu, 05 May 2022 17:38:14 +0530
      Finished:     Thu, 05 May 2022 17:38:18 +0530
    Ready:          False
    Restart Count:  5
    Limits:
      cpu:     30m
      memory:  64Mi
    Requests:
      cpu:        30m
      memory:     64Mi
    Environment:  <none>
    Mounts:
      /kuma/missing from missing-crds (ro)
      /kuma/scripts from scripts (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-npp46 (ro)
```
