### ISSUE TITLE
TrafficRoute resource with headers doesn't work

### ISSUE THREAD

**Issue by ralls0** [kumahq/kuma#4307]
### What happened?

I have deployed the bookinfo application provided by Istio on a cluster.

Now I want to replicate the behavior of its tutorial with the Kuma Service Mesh so that all traffic from a user named Jason will be routed to the service reviews:v2.
As mentioned [here](https://istio.io/latest/docs/tasks/traffic-management/request-routing/#route-based-on-user-identity) the productpage service adds a custom end-user header to all outbound HTTP requests to the reviews service.

I tried to replicate this behavior using `TrafficRoute` resource following the [Kuma docs](https://kuma.io/docs/1.4.x/policies/traffic-route/#l7-traffic-split), as it is shown here:

```yaml
apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata: 
  name: split-traffic-reviews
  namespace: kuma-system
spec:
  sources: 
    - match: 
       kuma.io/service: "*"
  destinations: 
    - match: 
        kuma.io/service: reviews_bookinfo-kuma_svc_9080
  conf:
    destination:
      kuma.io/service: reviews_bookinfo-kuma_svc_9080
      version: v1
    http: 
      - match: 
          headers: 
            end-user: 
              regex: "^jason$" # or exact: jason
        destination:
          kuma.io/service: reviews_bookinfo-kuma_svc_9080
          version: v2
```

The problem is that this rule doesn't work. Either Jason user or others, when I reload the page I get both versions with a random load balancing.
