### ISSUE TITLE
Request help: the service of `kuma-demo` unreachable

### ISSUE THREAD

**Issue by mangoGoForward** [kumahq/kuma#4336]
## Summary
Hi,

I'm first experience with Kuma, and follow the guide of [Multi-zone deployment](https://kuma.io/docs/1.6.x/deployments/multi-zone). When I consume the example service in k8s cp node with `curl`, I got the error of `Could not resolve host: demo-app; Unknown error`

```shell
$ curl http://demo-app:5000
curl: (6) Could not resolve host: demo-app; Unknown error
```

Thanks for your help in advance!

## Steps To Reproduce

1. Set up the global control plane
```
 kumactl install control-plane --mode=global | kubectl apply -f -
```
`NodePort` to expose `kuma-global-zone-sync` service
```
kubectl get services -n kuma-system
NAME                    TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                              AGE
kuma-control-plane      ClusterIP   10.233.37.223   <none>        5680/TCP,5681/TCP,5682/TCP,443/TCP   20m
kuma-global-zone-sync   NodePort    10.233.27.223   <none>        5685:32184/TCP                       20m
```
2. Set up the zone control planes on Kubernetes
```
kumactl install control-plane \
> --mode=zone \
> --zone=k8s111 \
> --ingress-enabled \
> --egress-enabled \
> --kds-global-address grpcs://{global-node-outer-ip}:32184 | kubectl apply -f -
```
Create data plane proxy
```
kubectl apply -f https://bit.ly/3Kh2Try
```
View the list of service names available for cross-zone communication
```
kubectl get dataplanes -n kuma-demo -o yaml | grep kuma.io/service
          k8s.kuma.io/service-name: demo-app
          k8s.kuma.io/service-port: "5000"
          kuma.io/service: demo-app_kuma-demo_svc_5000
          kuma.io/service: demo-app_kuma-demo_svc_5000
          kuma.io/service: redis_kuma-demo_svc_6379
          k8s.kuma.io/service-name: redis
          k8s.kuma.io/service-port: "6379"
          kuma.io/service: redis_kuma-demo_svc_6379
          kuma.io/service: demo-app_kuma-demo_svc_5000
          kuma.io/service: redis_kuma-demo_svc_6379
```
3. Set up the zone control planes on universal
```
kuma-dp run --proxy-type=ingress --cp-address=https://{vm-node-outer-ip}:5678 --dataplane-token-file=/tmp/ingress-token --dataplane-file=ingress-dp.yaml
```
and the contents of `ingress-dp.yaml`:
```yaml
type: ZoneIngress
name: ingress-01
networking:
  address: 127.0.0.1 # address that is routable within the zone
  port: 10000
  advertisedAddress: 10.0.0.1 # an address which other zones can use to consume this zone-ingress
  advertisedPort: 10000 # a port which other zones can use to consume this zone-ingress
```
4. Enable mTLS in global control plane
```yaml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  mtls:
    enabledBackend: ca-1
    backends:
      - name: ca-1
        type: builtin
        dpCert:
          rotation:
            expiration: 1d
        conf:
          caCert:
            RSAbits: 2048
            expiration: 10y
```
Then apply the configuration.

Get secret:
```shell
kubectl get secrets     -n kuma-system     --field-selector='type=system.kuma.io/secret'
NAME                                    TYPE                    DATA   AGE
dataplane-token-signing-key-default-1   system.kuma.io/secret   1      4h48m
default.ca-builtin-cert-ca-1            system.kuma.io/secret   1      6m36s
default.ca-builtin-key-ca-1             system.kuma.io/secret   1      6m36s
```

Finally, I consume the example service with `Curl`
```shell
 curl http://demo-app:5000
curl: (6) Could not resolve host: demo-app; Unknown error
```

## Additional Details & Logs
Version: Kuma v1.1.6 on Kubernetes and vm
Error logs: Message see above
Platform and Operating System:  Linux version 5.4.180-1.el7.elrepo.x86_64
Installation Method: kumactl
