### ISSUE TITLE
timeoutConfigurer is overriden for ExternalServices

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#4475]
### What happened?

When Kuma builds a cluster for external service it sets timeouts [properly](https://github.com/kumahq/kuma/blob/master/pkg/xds/generator/outbound_proxy_generator.go#L199):
```go
edsClusterBuilder := envoy_clusters.NewClusterBuilder(proxy.APIVersion).
	Configure(envoy_clusters.Timeout(cluster.Timeout(), protocol)).
```
But then overrides TimeoutConfigure with an empty value in [ProvidedEndpointCluster](https://github.com/kumahq/kuma/blob/master/pkg/xds/envoy/clusters/configurers.go#L89):
```go
// ProvidedEndpointCluster sets the cluster with the defined endpoints, this is useful when endpoints are not discovered using EDS, so we don't use EdsCluster
func ProvidedEndpointCluster(name string, hasIPv6 bool, endpoints ...core_xds.Endpoint) ClusterBuilderOpt {
	return ClusterBuilderOptFunc(func(config *ClusterBuilderConfig) {
		config.AddV3(&v3.ProvidedEndpointClusterConfigurer{
			Name:      name,
			Endpoints: endpoints,
			HasIPv6:   hasIPv6,
		})
		config.AddV3(&v3.AltStatNameConfigurer{})
		config.AddV3(&v3.TimeoutConfigurer{})
	})
}
```

### Workaround

ProxyTemplate to set 'connectTimeout' value for ExternalServices:
```yaml
type: ProxyTemplate
mesh: default
name: fix-connect-timeout
selectors:
  - match:
      kuma.io/service: "*"
conf:
  imports:
    - default-proxy
  modifications:
    - cluster:
        operation: patch
        match: 
          name: httpbin 
          origin: outbound
        value: | 
          connectTimeout: 3s
```
