### ISSUE TITLE
Kuma Injector failing using ContainerPatch

### ISSUE THREAD

**Issue by coreywagehoft** [kumahq/kuma#4516]
### What happened?

I was trying to use `ContainerPatch` to changes some values in the sidecar and got an error after attempting to deploy a workload that would use the container patch.

Example Container Patch:
```yaml
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: container-patch
  namespace: kuma-system
spec:
  sidecarPatch:
    - op: remove
      path: /resources/requests/cpu
    - op: remove
      path: /resources/limits/cpu
    - op: add
      path: /resources/requests/cpu
      value: "500m"
    - op: add
      path: /resources/limits/cpu
      value: "500m"
```

Another example I tried:
```yaml
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: container-kong-dp
  namespace: {{ .Release.Namespace }}
spec:
  sidecarPatch:
    - op: replace
      path: /resources/requests/cpu
      value: "500m"
    - op: replace
      path: /resources/limits/cpu
      value: "500m"
```

I got the following error from the Admission Webhook:
```
Error creating: admission webhook "pods-kuma-injector.kuma.io" denied the request: could not apply patches ["container-patch"]: json: error calling MarshalJSON for type *jsonpatch.lazyNode: json: error calling MarshalJSON for type *jsonpatch.lazyNode: json: error calling MarshalJSON for type *jsonpatch.lazyNode: json: error calling MarshalJSON for type *json.RawMessage: invalid character 'm' after top-level value   FailedCreate
```

This is running Kuma 1.7.0

**Comment by bartsmykla** [comment]
@coreywagehoft can you try:

```yaml
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: container-patch
  namespace: kuma-system
spec:
  sidecarPatch:
    - op: remove
      path: /resources/requests/cpu
    - op: remove
      path: /resources/limits/cpu
    - op: add
      path: /resources/requests/cpu
      value: '"500m"'
    - op: add
      path: /resources/limits/cpu
      value: '"500m"'
```

or:

```yaml
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: container-patch
  namespace: kuma-system
spec:
  sidecarPatch:
    - op: replace
      path: /resources/requests/cpu
      value: '"500m"'
    - op: replace
      path: /resources/limits/cpu
      value: '"500m"'
```

according to jsonpatch documentation, values needs to be a properly formatted as a json values, so my assumption is it's trying to build json like:
```json
{
  "resources": {
    "limits": {
      "cpu": 500m
    }
  }
}
```
instead of:
```json
{
  "resources": {
    "limits": {
      "cpu": "500m"
    }
  }
}
```
