### ISSUE TITLE
Add `ZoneEgress` configuration in `MeshLoadBalancingStrategy`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4547]
### Description

Currently ZoneEgress is all or nothing: https://kuma.io/docs/2.6.x/production/cp-deployment/zoneegress/#zone-egress

It would be nice if we could set these per zone. For example say we use ZoneEgress only in zone A.

Suggestion:

```yaml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  routing:
    zoneEgress:
       zones: ["a", "b"]
  mtls: # mTLS is required to use ZoneEgress
     enabled: true
```

ZoneEgress is especially useful in cases where the network has constrained (route all external traffic through a set of dedicated hosts), it's great but it has a cost and you might not want to pay the cost for every zone.

This would be a breaking change. Maybe there's a nicer way to go about this.

Should ZoneEgress live in [MeshLoadBalancingStrategy](https://kuma.io/docs/2.2.x/policies/meshloadbalancingstrategy/)?

After all this would enable to specify zoneEgress from the entire mesh all the way down to a service.

**Comment by lahabana** [comment]
Added some context back to triage

**Comment by mmorel-35** [comment]
As it is a per zone configuration,  would you consider this configuration:
```yaml
apiVersion: kuma.io/v1alpha1
kind: Zone
metadata:
  name: a
spec: 
  routing:
    zoneEgress: true
---
apiVersion: kuma.io/v1alpha1
kind: Zone
metadata:
  name: b
spec: 
  routing:
    zoneEgress: true
```
What would be the default configuration?  If not defined for the zone, the zone uses the present egress if there is no egress in the zone it just doesn't even try to use one. On the contrary,  if the zone is expecting an egress,  there must be an error to say it.
