### ISSUE TITLE
[Kong Mesh 1.8, ARM64] gateway api demo doesn't work

### ISSUE THREAD

**Issue by gAmUssA** [kumahq/kuma#4559]
### What happened?

I'm following https://kuma.io/docs/1.7.x/explore/gateway-api/#usage

- installed demo into `kuma-demo` namespace
- running 

```
echo "apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: kuma
spec:
  controllerName: gateways.kuma.io/controller
" | kubectl apply -f -
```

getting error

```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "validate.gateway.networking.k8s.io": the server could not find the requested resource
```

gateway crds installed via 

```
kubectl apply -k "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.4.3"
```

```
❱ kumactl version
Client: Kong Mesh 1.8.0-amd64
Server: Kong Mesh 1.8.0-arm64
```

Thanks
