### ISSUE TITLE
Design MeshTLS policy

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4622]
### Description

We need a way to configure TLS version between DP proxies. Same for permissive/strict TLS.

**Comment by slonka** [comment]
Isn't this solved by https://github.com/kumahq/kuma/pull/5186 ?

**Comment by jakubdyszkiewicz** [comment]
> Triage: 5186 solved TLS version on CP servers. This issue is about TLS version between DPPs. We also agreed that we don't want to squeeze this into MeshTrafficPermission. It will be a separate policy (MeshMTLS?)

**Comment by lahabana** [comment]
xref:

- https://github.com/kumahq/kuma/issues/4400

**Comment by lahabana** [comment]
Starting to think that defining which CA issues certs is likely only possible targetRef: Mesh. However, other things should be possible on a per service basis (.e.g Permissiveness)

**Comment by lahabana** [comment]
I think it would make sense to separate backend from TLS configuration.

Maybe 1 resource would be `IdentityBackend` which would have an idea and a way to issue cert and get access to a CA (potentially one of these could Spirre which bypasses completely our CP....).
The 2 resource would be an MTLS policy. With from and to that reference `IdentityBackends` to validate respectively clients and servers. In this same resource we'd be able to set TLS specific configuration (versions, cyphers...)

**Comment by lahabana** [comment]
Some other mesh options:

Istio:
https://istio.io/latest/docs/concepts/security/#authentication-policies
https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings

Linkerd:
https://linkerd.io/2.15/reference/authorization-policy/
https://linkerd.io/2.15/features/automatic-mtls/

I think it would make sense to have a `TLSProvider/IdentityBackend` resource which would look like:

```yaml
type: TLSBackend
name: my-stuff
spec:
  type: Builtin|Provided|Extension|CAOnly # CAOnly can be used to be used only for validating client.
  spiffeDomain: "foo/bar/baz"
  extension:
     ...
  builtin:
     rotation: 2d
     identity: ServiceAccount|Labels...
```

Then have a TLSConfig policy:

```yaml
type: TLSConfig
name: foo
spec:
   targetRef:
      kind: Mesh
   to:
     - targetRef:
           kind: Mesh
        tlsVersions: [2.2, 2.3]
        serverTlsBackends:
           - type: Standard
              targetRef:
                  kind: TLSBackend
                  name: a
          - type: Spiffe
             targetRef:
                 kind: TLSBackend
                 name: foo
   from:
     - targetRef:
           kind: Mesh
        default:
           tlsVersion: [2.3, 2.2]
           tlsCiphers: ...
           serverTlsBackend:
           - targetRef:
                  kind: TLSBackend
                  name: a
           clientTlsBackends:
           - targetRef:
                  kind: TLSBackend
                  name: a
           - targetRef:
                 kind: TLSBackend
                 name: foo
           - type:  None
```

The config in from and to are likely very similar but we'd have the ability to diverge. Also in most cases only 1 backend would exist. How things are validated and certificate issued is all up to the backend which is something I find quite nice as easy to extend.

`clientTlsBackend.type: None` is what makes permissive possible.

Also I like what linkerd does which is to write certs to the system namespace.
Another observation is that all these only allow serviceAccount to be the level of identity for a cert. I think it may make sense to do the same (that greatly reduces the number of certs at the cost of less granularity in MTP).
It may make sense in the short term to only support MTP with serviceAccounts or serviceName.
