### ISSUE TITLE
New TrafficLog design (new name: MeshLogging)

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4733]
### Description

Rebuild traffic log to have it work with the new selectors.

Open questions:

- should the backends be inlined in the policy? This would make it easier to have per zone backends.
- We should support inbound and outbound logs.
- https://github.com/kumahq/kuma/issues/3324
- https://github.com/kumahq/kuma/issues/3242

**Comment by lahabana** [comment]
xref https://github.com/kumahq/kuma/issues/3324

**Comment by slonka** [comment]
@lahabana - could you explain how 

> should the backends be inlined in the policy? This would make it easier to have per zone backends.

inlining would make it easier to have per zone backends?

FYI @lobkovilya

**Comment by lahabana** [comment]
Because you define a policy:

```
name: log-zone-a
spec:
   targetRef:
      type: proxySubset
      tags:
        kuma.io/zone: foo
    to:
       - targetRef:
            type: mesh
          default:
             backend: my-zone-specific-backend

**Comment by slonka** [comment]
I'm still not sure. It's this:

```yaml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  logging:
    backends:
      - name: logstash-zone-a
        type: tcp
        conf:
          address: 127.0.0.1:5000
      - name: logstash-zone-b
        type: tcp
        conf:
          address: 127.0.0.2:5000
---
type: MeshLogging
mesh: default
name: log-zone-a
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/zone: zone-a
  from:
    - targetRef:
        kind: Mesh
        name: default
      default:
        backends:
          - logstash-zone-a
---
type: MeshLogging
mesh: default
name: log-zone-b
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/zone: zone-b
  from:
    - targetRef:
        kind: Mesh
        name: default
      default:
        backends:
          - logstash-zone-b
```

vs this:

```yaml
type: MeshLogging
mesh: default
name: log-zone-a
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/zone: zone-a
  from:
    - targetRef:
        kind: Mesh
        name: default
      default:
        backends:
          - name: logstash-zone-a
            type: tcp
            conf:
              address: 127.0.0.1:5000
---
type: MeshLogging
mesh: default
name: log-zone-b
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/zone: zone-b
  from:
    - targetRef:
        kind: Mesh
        name: default
      default:
        backends:
          - name: logstash-zone-b
            type: tcp
            conf:
              address: 127.0.0.2:5000
```

how is one easier than the other? or, is my example wrong?
