### ISSUE TITLE
New `VirtualOutbound` design

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4741]
### Description

With new matchers

Some current shortcomings:

- vob are not real clusters (they are a subset of existing cluster). This means you can't for example match a policy a Vob
- vob are not bindable from inside the pod (for example if you use bind <vob>) it won't work as the 240.x.x.x ip doesn't exists.
- vob and services have a weird relationship...

Is there something we could do that would work better and be close to services. Is it just a way we define a services?

**Comment by lahabana** [comment]
Some existing use cases for vob:

- custom default DNS (1 kuma.io/service is respected)
- host:port with tags ( 1 host:port name/port for each version, 1 DNS name per zone...)
- reachable instances ( each instance have their own DNS name for example statefulset in k8s) probably don't want to create 1 resource per instance).

**Comment by lahabana** [comment]
Some random chat with @lobkovilya got us to build this draft:

```yaml
type: MeshServiceGenerator
name: k8sDefault
spec:
  selectors:
    kuma.io/service: "*"
    port: "*"
    k8s.namespace: "*"
    k8s.serviceName: "*"
  templateMappings:
    kuma.io/service: svc
    k8s.namespace: ns
    k8s.serviceName: "k8ss"
  addresses:
        - "{{svc}}.mesh:80"
        - "{{k8ss}}.{{ns}}.{{port}}"
  urlTemplate: "{{svc}}.mesh" 
  portTemplate: "80"

--- 
type: MeshServiceGenerator
name: k8sDefault
targetRef:
  kind: MeshSubset
  tags:
    app: labels
spec:
  selectors:
    my-company.app/service: "*"
    port: "*"
    k8s.namespace: "*"
    k8s.serviceName: "*"
  templateMappings:
    my-company.app/service: svc
    k8s.namespace: ns
    k8s.serviceName: "k8ss"
  nameTemplate: "{{svc}}
  svctags:
     k: v
  addresses:
        - "{{svc}}.mesh:80"
        - "{{k8ss}}.{{ns}}.{{port}}"
  urlTemplate: "{{svc}}.mesh" 
  portTemplate: "80"
```

There's lots of gaps here.
Some things we thought that was quite problematic:

- Can we group multiple different `kuma.io/service` in the same actual Service (Is there a case for this?! - Same service in universal and k8s) (if that's the case certificate id is problematic).
- headless services. Handle by default?
