### ISSUE TITLE
DaemonSet with HostPort - is not created kuma service

### ISSUE THREAD

**Issue by istar2metal** [kumahq/kuma#4747]
### What happened?

In k8s-cluster working ingress-nginx DaemonSet with HostPort as deligated gateway in kuma mesh:
```...
spec:
  template:
    metadata:
      annotations:
        kuma.io/gateway: enabled
    spec:
      containers:
        name: ingress-nginx-controller
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          name: https
          protocol: TCP
        - containerPort: 10254
          hostPort: 10254
          name: metrics
          protocol: TCP
...
```
It has no kubernetes Service (only for ingress-metrics, no for ingress port):
```
kubectl -n ingress-nginx get svc
NAME                               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)     AGE
ingress-nginx-controller-metrics   ClusterIP   10.233.53.14   <none>        10254/TCP   223d
```
As expected, kuma-dataplanes have been created for this minor service ingress-nginx-controller-metrics:
```
...
kind: Dataplane
...
spec:
  networking:
...
    gateway:
      tags:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/part-of: ingress-nginx
        k8s.kuma.io/namespace: ingress-nginx
        k8s.kuma.io/service-name: ingress-nginx-controller-metrics
        k8s.kuma.io/service-port: "10254"
        kuma.io/protocol: tcp
        kuma.io/service: ingress-nginx-controller-metrics_ingress-nginx_svc_10254
        kuma.io/zone: hcloud
...
```
Since there is no kuma-service for general ingress http ports, mTLS (in strict mode) does not work.
@Krzys
