### ISSUE TITLE
External Service easily misconfigured in an insecure way

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#4758]
### Description

The below External Service policy is valid despite the fact that `networking.tls.caCert` is not set. When this is not set Envoy does not have a trusted_ca configured for the upstream TLS. In this situation Envoy does not verify server certificates so communication to the external service is not secure.

```yaml
type: ExternalService
mesh: default
name: 'some-name'
tags:
  kuma.io/service: 'some-name'
  kuma.io/protocol: http
networking:
  address: 'example.com:443'
  tls:
    enabled: true
    allowRenegotiation: false
```

Many people might assume that by default a system CA bundle will be used to verify server certificates seeing as this is not a mandatory field.

If TLS is enabled for an External Service then caCert should be mandatory to avoid insecure misconfiguration.

ref: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/tls.proto#extensions-transport-sockets-tls-v3-upstreamtlscontext
