### ISSUE TITLE
gateway: XDS error if a TCP route attaches to an HTTP listener 

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#4775]
### What happened?

```
2022-08-05T17:57:20.357Z	ERROR	xds-server.dataplane-sync-watchdog	OnTick() failed	{"dataplaneKey": {"Mesh":"gateway-resources","Name":"resources-edge-gateway-58d8f6646c-p6rpv.gateway-resources"}, "error": "invalid resource \"resources-edge-gateway:HTTP:8080\": invalid RouteConfiguration.VirtualHosts[0]: embedded message failed validation | caused by: invalid VirtualHost.Routes[0]: embedded message failed validation | caused by: invalid Route.Match: embedded message failed validation | caused by: invalid RouteMatch.PathSpecifier: value is required", "errorVerbose": "invalid RouteConfiguration.VirtualHosts[0]: embedded message failed validation | caused by: invalid VirtualHost.Routes[0]: embedded message failed validation | caused by: invalid Route.Match: embedded message failed validation | caused by: invalid RouteMatch.PathSpecifier: value is required\ninvalid resource \"resources-edge-gateway:HTTP:8080\"\ngithub.com/kumahq/kuma/pkg/xds/server/v3.(*reconciler).Reconcile\n\t/home/mike/projects/kuma/pkg/xds/server/v3/reconcile.go:83\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncDataplane\n\t/home/mike/projects/kuma/pkg/xds/sync/dataplane_watchdog.go:128\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).Sync\n\t/home/mike/projects/kuma/pkg/xds/sync/dataplane_watchdog.go:65\ngithub.com/kumahq/kuma/pkg/xds/sync.(*dataplaneWatchdogFactory).New.func2\n\t/home/mike/projects/kuma/pkg/xds/sync/dataplane_watchdog_factory.go:45\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start\n\t/home/mike/projects/kuma/pkg/util/watchdog/watchdog.go:25\nruntime.goexit\n\t/usr/lib/go/src/runtime/asm_amd64.s:1594"}

```

```
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
metadata:
  name: gateway
mesh: gateway
spec:
  selectors:
  - match:
      kuma.io/service: gateway
  conf:
    listeners:
    - port: 8080
      protocol: HTTP
---
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayRoute
metadata:
  name: gateway
mesh: default
spec:
  selectors:
  - match:
      kuma.io/service: gateway
  conf:
    tcp:
      rules:
      - backends:
        - destination:
            kuma.io/service: service
```
