### ISSUE TITLE
support Upstream/DownstreamTLSContext in ProxyTemplate

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4948]
### Description

Currently such ProxyTemplate

```
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: custom-template-1
spec:
  selectors:
    - match:
        kuma.io/service: demo-app_kuma-demo_svc_5000
  conf:
    imports:
      - default-proxy
    modifications:
      - cluster:
          operation: patch # <- patch, add adds a new cluster
          match:
            origin: outbound
          value: |
            transport_socket:
              name: envoy.transport_sockets.tls
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
                common_tls_context:
                  tls_params:
                    tls_minimum_protocol_version: TLSv1_2
                    tls_maximum_protocol_version: TLSv1_2
```

replaces the whole UpstreamTlsContext. There is no way to patch only part of the TLS Context
