### ISSUE TITLE
targetRef as a group of other targetRefs

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#4972]
### Description

Prelude: this issue results from a question during `MeshAccessLog` meeting.

After further question we decided that it was likely better to have a targetRef kind that groups other targetRefs together .e.g:

```yaml
spec:
   targetRef:
      kind: Alias
      name: myAlias
```

And in this alias we'd have:

```yaml
kind: Alias
name: myAlias
spec:
  targetRef:
  - kind: MeshService
    name: backend
  - kind: MeshService
    name: cart
```

There's a lot of outstanding things to figure especially when it comes to validating such a targetRef.

Original content:

>
> Right now `targetRef` is a single field:
>
> 
> ```yaml
> spec:
>   targetRef:
>     kind: MeshService
>     name: backend
> ```
> 
>  but to simplify configuring multiple things, this could be a list:
> 
> ```yaml
> spec:
>   targetRef:
>     - kind: MeshService
>       name: backend
>     - kind: MeshService
>       name: frontend
>     - kind: MeshService
>       name: cart
> ```
