### ISSUE TITLE
ProxyTemplate native Envoy resource is not valid: could not resolve Any message type

### ISSUE THREAD

**Issue by danielc-salt** [kumahq/kuma#5018]
### What happened?

I am trying to apply a ProxyTemplate to modify a filter chain on the side-car envoy of my pods.

I am using ProxyTemplate but when I apply the template I get this error:

`The ProxyTemplate "edge-aggregator" is invalid: spec.conf.modifications[0].httpFilter.value: native Envoy resource is not valid: could not resolve Any message type: type.googleapis.com/udpa.type.v1.TypedStruct`

I tried the direct reference with no success:

`The ProxyTemplate "edge-aggregator" is invalid: spec.conf.modifications[0].httpFilter.value: native Envoy resource is not valid: could not resolve Any message type: type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor`

My template looks like this:

> apiVersion: kuma.io/v1alpha1
> kind: ProxyTemplate
> mesh: default
> metadata:
>   name: salt-edge-aggregator
> spec:
>   selectors:
>     - match:
>         security/capture: "true"
>         kuma.io/service: '*'
>   conf:
>     imports:
>       - ingress-proxy
>       - gateway-proxy
>     modifications:
>       - httpFilter:
>           operation: addFirst
>           match:
>             name: envoy.filters.http.router 
>             listenerTags: # optional: if absent, filter will be patched within all listeners regardless of listener tags
>               salt.security/capture: "true"
>           value: | # you can specify only part of filter definition that will be merged into existing filter
>             name: envoy.filters.http.ext_proc
>             typed_config:
>               "@type": type.googleapis.com/udpa.type.v1.TypedStruct
>               type_url: "type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor"
> 

According to documentation this particular filter should be supported, or am I doing something wrong?

Thanks.

**Comment by danielc-salt** [comment]
I have verified further:
Kuma version is 1.18
Envoy version is 1.22.1
The extension is loaded into envoy: 
```
{
       "name": "envoy.filters.http.ext_proc",
       "category": "envoy.filters.http"
      }
```

I have tested other templates that use other filters in the http group and they work, but this filter seems to not pass parsing: my current template is:
```
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: edge-aggregator
spec:
  selectors:
    - match:
        security/capture: "true"
        kuma.io/service: '*'
  conf:
    imports:
      - default-proxy
    modifications:
      - httpFilter:
          operation: addFirst
          match:
            name: envoy.filters.http.router 
            listenerTags: # optional: if absent, filter will be patched within all listeners regardless of listener tags
              security/capture: "true"
          value: | # you can specify only part of filter definition that will be merged into existing filter
            name: envoy.filters.http.ext_proc
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3alpha.ExternalProcessor
              value:
                failure_mode_allow: true
                message_timeout: 1s
                processing_mode:
                  request_header_mode: "SEND"
                  response_header_mode: "SEND"
                  request_body_mode: "BUFFERED"
                  response_body_mode: "BUFFERED"
                  request_trailer_mode: "SKIP"
                  response_trailer_mode: "SKIP"
                grpc_service:
                  timeout: 1s
                  envoy_grpc:
                    cluster_name: "outbound|5001||edge-aggregator.istio-collector.svc.cluster.local"
                    authority: edge-aggregator.collector.svc.cluster.local

```

With same error:
```
danielc@MacBook edge-aggregator % kube apply -f envoy-filter-proxy.yaml
The ProxyTemplate "edge-aggregator" is invalid: spec.conf.modifications[0].httpFilter.value: native Envoy resource is not valid: could not resolve Any message type: type.googleapis.com/envoy.extensions.filters.http.ext_proc.v3.ExternalProcessor
```
