### ISSUE TITLE
Hard limit on `BuildRules` output

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#5028]
### Description

The function `BuildRules` generates rules for all possible subsets of `clients/destinations`. We should think about the case when policy contains many distinct keys, because the complexity is `O(2^N)`

**Comment by jakubdyszkiewicz** [comment]
We could optimize the algo further. For example this set of rules
```
type: MeshTrafficPermission
name: mtp-2
mesh: default
spec:
 targetRef:
   kind: MeshService
   name: backend
 from:
   - targetRef:
       kind: MeshService
       name: demo-client-2
     default:
       action: DENY


type: MeshTrafficPermission
name: mtp-1
mesh: default
spec:
 targetRef:
   kind: MeshService
   name: backend
 from:
   - targetRef:
       kind: MeshService
       name: demo-client
     default:
       action: ALLOW


type: MeshTrafficPermission
name: mtp-3
mesh: default
spec:
 targetRef:
   kind: MeshService
   name: backend
 from:
   - targetRef:
       kind: MeshServiceSubset
       name: demo-client
       tags:
         kuma.io/zone: east
     default:
       action: DENY
```

produces such rules

```
{
 "total": 4,
 "items": [
  {
   "type": "clientSubset",
   "policyType": "MeshTrafficPermission",
   "subset": {
    "kuma.io/service": "demo-client-2",
    "kuma.io/zone": "east"
   },
   "conf": {
    "action": "DENY"
   },
   "origins": null
  },
  {
   "type": "clientSubset",
   "policyType": "MeshTrafficPermission",
   "subset": {
    "kuma.io/service": "demo-client",
    "kuma.io/zone": "east"
   },
   "conf": {
    "action": "DENY"
   },
   "origins": null
  },
  {
   "type": "clientSubset",
   "policyType": "MeshTrafficPermission",
   "subset": {
    "kuma.io/service": "demo-client-2",
    "kuma.io/zone": "!east"
   },
   "conf": {
    "action": "DENY"
   },
   "origins": null
  },
  {
   "type": "clientSubset",
   "policyType": "MeshTrafficPermission",
   "subset": {
    "kuma.io/service": "demo-client",
    "kuma.io/zone": "!east"
   },
   "conf": {
    "action": "ALLOW"
   },
   "origins": null
  }
 ]
}
```

where `demo-client-2` has nothing to do with `kuma.io/zone`
