### ISSUE TITLE
metrics_hijacker creates unsupported format by prometheus

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5055]
### Description

I have a simple service:

```go
func serveContent(listener net.Listener, meter metric.Meter, cfg Config) {
	mux := http.NewServeMux()
	calledIt2 := promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "called_it2",
	}, []string{"method"})

	mux.HandleFunc("/", func(writer http.ResponseWriter, request *http.Request) {
		defer func() {
			_ = request.Body.Close()
		}()
		calledIt2.WithLabelValues(request.Method).Inc()
		data, err := ioutil.ReadAll(request.Body)
		if err != nil {
			writer.WriteHeader(http.StatusInternalServerError)
			_, _ = writer.Write([]byte(fmt.Sprintf("Failed with %+v", err)))
		}
		writer.WriteHeader(http.StatusOK)
		writer.Header().Set("Content-Type", "application/json")
		if err := json.NewEncoder(writer).Encode(Response{
			Data:    string(data),
			Method:  request.Method,
			Message: "hello!",
		}); err != nil {
			writer.WriteHeader(http.StatusInternalServerError)
			_, _ = writer.Write([]byte(fmt.Sprintf("Failed with %+v", err)))
		}
	})

	err := http.Serve(listener, mux)
	if err != nil {
		fmt.Printf("error on listener end: %v", err)
	}

}


func serveMetrics(listener net.Listener, collector prometheus.Collector) {
	registry := prometheus.NewRegistry()
	err := registry.Register(collector)
	if err != nil {
		fmt.Printf("error registering collector: %v", err)
		return
	}

	mux := http.NewServeMux()
	mux.Handle("/metrics", promhttp.Handler())
	err = http.Serve(listener, mux)
	if err != nil {
		fmt.Printf("error on listener end: %v", err)
	}
}

```

I then add this to the scraping with: `prometheus.metrics.kuma.io/aggregate-app-port: "5000"`
The scraper fails with: `ts=2022-09-23T14:46:57.907Z caller=scrape.go:1309 level=debug component="scrape manager" scrape_pool=kuma-dataplanes target=http://10.42.0.27:5670/metrics msg="Append failed" err="\"INVALID\" is not a valid start token"`

I've tried to move to a minimal set and even excluded all envoy metrics:

```yaml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  metrics:
    backends:
    - conf:
        envoy:
          filterRegex: fewfew
          usedOnly: true
        path: /metrics
        port: 5670
        tags:
          kuma.io/service: dataplane-metrics
      name: prometheus-1
      type: prometheus
    enabledBackend: prometheus-1
  mtls:
    backends:
    - name: ca-1
      type: builtin
    enabledBackend: ca-1
```

(note the filter that matches nothing)
This still fails with the same error.

Some data:
[envoy.txt](https://github.com/kumahq/kuma/files/9634715/envoy.txt)
[out.txt](https://github.com/kumahq/kuma/files/9634716/out.txt)
[out2.txt](https://github.com/kumahq/kuma/files/9634717/out2.txt)
[out3.txt](https://github.com/kumahq/kuma/files/9634718/out3.txt)

envoy is by calling `:9901/envoy?format=prometheus` the 3 are with `:5670/metrics` with different filters on envoy metrics.

My gut feeling:

1) We don't support `# HELP`
2) The double end line at the end of the file is not something supported in the prometheus exposition format

I think 2 is more likely
