### ISSUE TITLE
Access to mTLS service from Ingress resources

### ISSUE THREAD

**Issue by manju-rn** [kumahq/kuma#5087]
### What happened?

Here is simple setup I have:
1. Kuma version: 1.8, standalone installation
2. Platform: Kubernetes - k3s .  This is configured with inbuilt Traefik as ingress and Calico as CNI.  Single Node cluster
3. In Kuma,   2 mesh are created.  ha-mesh and test-mesh.  ha-mesh is configured for mTLS with built in option of certificates
4.  A simple UI based container image is installed - adminer : latest   (from `https://hub.docker.com/_/adminer`)

**Problem Statement:**
1. When I inject the namespace hosting this adminer in test-mesh (which has no mTLS ), then the adminer UI is accessible from the ingress that is created for adminer
2. However, when I inject the namespace hosting adminer in ha-mesh ( which has the mTLS enabled), then the adminer UI is not accessible, it results in 502 error.  None of the adminer pods show any error log.

So **How can mTLS pods be accessed from Ingress?** I am guessing that since the traffic is coming via ingress it is not mTLS encapsulated and hence not authorizing.  **How and where can I check the kuma logs?** Since none of the pods / containers show any error in their logs

**Comment by manju-rn** [comment]
> > Triage: Can you check if both adminer and ingress have sidecar containers and are both in the same mesh?
> > Also please check https://kuma.io/docs/1.8.x/explore/gateway/#delegated do you set `kuma.io/gateway: enabled` on your ingress?

Can you please elaborate on the "ingress" side container?  I have a namespace adminer-ns in which both the adminer deployment and the ingress manifest are hosted.  The ingress itself does not have the pod - unless you are referring to the Traefik (default in k3s) that provides the ingress implementation.

I will check on the gateway - so is my assumption correct that for the mTLS hosted mesh, this delegated gateway is required for the ingress to route traffic to meshed services / pods?   

Also, where can I see the logs - I have checked the pods in the kuma-system and they do not report any error. I was under the impression that some of the logs would say "unauthenticated ..."  something like that.

![image](https://user-images.githubusercontent.com/26291847/193701935-cbc3809a-ad7a-4bf1-8727-cb19c7f07ea5.png)
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adminer-ingress
  namespace: adminer-ns
spec:
  rules:
  - http:
      paths:
        - path: /adminer
          pathType: Prefix
          backend:
            service:
              name: adminer-svc
              port:
                number: 9090
```
