### ISSUE TITLE
builtin gateway is not getting all retry policy config

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5089]
### Description

With:

```yaml
apiVersion: kuma.io/v1alpha1
kind: Retry
mesh: default
metadata:
  name: test-retry-policy
spec:
  sources:
  - match:
      kuma.io/service: '*'
  destinations:
  - match:
      kuma.io/service: '*'
  conf:
    http:
      numRetries: 5
      perTryTimeout: 16s
      backOff:
        baseInterval: 0.025s
        maxInterval: 0.025s
      retryOn:
        - all_5xx
        - gateway_error
        - reset
        - connect_failure
        - refused_stream
        - http3_post_connect_failure
    tcp:
      maxConnectAttempts: 5
    grpc:
      numRetries: 5
      perTryTimeout: 16s
      backOff:
        baseInterval: 0.025s
        maxInterval: 0.025s
```

The retryOn values are not applied to the gateway envoy config which just has a default value: `"retry_policy": { "retry_on": "gateway-error,connect-failure,refused-stream", "num_retries": 5, "per_try_timeout": "16s", "retry_back_off": { "base_interval": "0.025s", "max_interval": "0.250s" } }`

Probably something specific was forgotten when implementing the extra config.
