### ISSUE TITLE
Allow serviceAddress to accept dns record

### ISSUE THREAD

**Issue by Tahvok** [kumahq/kuma#5127]
### Description

This is for kuma universal.
When using kuma-dp inside a **user-defined docker network bridge**, each container listens on its own ip.
Therefore, you must set `serviceAddress` inside `inbound`, like so:
```yaml
type: Dataplane
mesh: default
name: {{ name }}
networking:
  address: kuma-dp
  advertisedAddress: {{ host_address }}
  inbound:
    - port: 1337
      servicePort: 80
      serviceAddress: 172.18.0.5
      tags:
        kuma.io/service: my-service
```

However, the service container ip might change, for example recreation of a container will assign a new ip to the new container (even if same name is used).

This leads to an issue where each time the service container changes, you need to adjust the kuma-dp serviceAddress to the new address.

However, docker itself provides a solution, where you can communicate directly with each service inside same docker network bridge, by exposing a special dns service, where each container can communicate with each other using the container name.
You can read more about it [here](https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge) and [here](https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge).

This feature request is asking to add the capability to allow setting `serviceAddress` to a dns name and not only ip address. This will allow kuma to discover the ip address of the service container name, and the configuration of kuma-dp can be greatly simplified.

~~DNS discovery is partly supported already. kuma-dp is allowing to set networking.address to be DNS name, and essentially you can set it to be the name of the container `kuma-dp` as in this example. This work was done in pr #965 .~~
It appears to me that although networking.address does accept a dns record, and it does not fail to startup, it does not able to load the listener (no errors are thrown). I could not manage to debug why that is happening.

In the end, I want to be able to set the configuration as follows:
```yaml
type: Dataplane
mesh: default
name: {{ name }}
networking:
  address: kuma-dp
  advertisedAddress: {{ host_address }}
  inbound:
    - port: 1337
      servicePort: 80
      serviceAddress: my-service
      tags:
        kuma.io/service: service-name
```
