### ISSUE TITLE
Proxy is not emitting metrics as expected/documented in Traffic Metrics

### ISSUE THREAD

**Issue by gdasson** [kumahq/kuma#5180]
## Expected Behavior 
As documented in https://kuma.io/docs/1.8.x/policies/traffic-metrics/#expose-metrics-from-data-plane-proxies:

* Proxy in the mesh should expose an HTTP endpoint with Prometheus metrics on port 5670(by default) and URI path /metrics(by default)
* If overridden by annotations, proxy in the mesh should expose an HTTP endpoint with Prometheus metrics on port specified by "prometheus.metrics.kuma.io/port" annotation and URI path specified by "prometheus.metrics.kuma.io/path" annotation

## Current Behavior
Proxy is not emitting metrics on the port and URI path

## Steps to Reproduce

Step 1: Configure mesh resource as documented here: https://kuma.io/docs/1.8.x/policies/traffic-metrics/#expose-metrics-from-data-plane-proxies:
Step 2: Deploy a pod with sidecar injected
Step 3: port-forward pod's port 5670 (k port-forward pod_name -n namespace 5670:5670)
Step 4: curl http://localhost:5670/metrics
Step 5: The curl command will error out citing an EOF error (curl: (35) Encountered end of file)
Step 6: port-forward will error out citing that the port is not available

## Context (Environment)
Mesh Resource:
```
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: example-mesh
spec:
  mtls:
    backends:
    - conf:
        caCert:
          RSAbits: 2048
          expiration: 10y
      dpCert:
        rotation:
          expiration: 1d
      name: ca-1
      type: builtin
    enabledBackend: ca-1 #just testing with inbuilt CA
  metrics:
    enabledBackend: prometheus-1
    backends:
    - name: prometheus-1
      type: prometheus
      conf:
        skipMTLS: true
        port: 5670
        path: /metrics
```
Deployment:
```
# Deployment manifest for helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: helloworld-yaml
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        kuma.io/sidecar-injection: enabled
      annotations:
        kuma.io/mesh: example-mesh
        kuma.io/container-patches: sc-container-patch
    spec:
      automountServiceAccountToken: true
      serviceAccountName: helloworld
      securityContext:
        fsGroup: 1000 # Any volumes created below and any processes in this container will be part of this Group.
      imagePullSecrets:
      - name: reg-ro
      containers:
      - name: httpd
        image: <our_container_registry>/httpd:2.4.51
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsUser: 1000
        volumeMounts:
        # Bring in our own custom httpd.conf
        - mountPath: "/usr/local/apache2/conf/httpd.conf"
          name: configs
          subPath: httpd.conf
        # Custom index page
        - mountPath: "/usr/local/apache2/htdocs/index.html"
          name: configs
          subPath: index.html
        # Creating this volume mount so that Apache has a place to create it's PID file.
        - name: storage
          mountPath: /usr/local/apache2/logs
      volumes:
      - name: configs
        configMap:
          name: helloworld
      - name: storage
        emptyDir: {}
```

PodMonitor definition(We expect PodMonitor custom resource to do its magic so we could scrape metrics off of the metrics endpoint from pod):
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kong-mesh-dp
  namespace: helloworld-yaml
spec:
  selector:
    matchLabels:
      kuma.io/sidecar-injection: enabled
  namespaceSelector:
    #any: true #For now we are using matchNames on specific namespace to test. Eventually we expect to use any: true. That would mean that any pod with the label "kuma.io/sidecar-injection: enabled" would be scraped.
    matchNames:
      - helloworld-yaml
  podMetricsEndpoints:
    - targetPort: 5670
      path: /metrics
      scrapeTimeout: 10s
```

**Comment by jakubdyszkiewicz** [comment]
> Triage: Is it still a problem? I think @johnharris85 had a chance to explain why we cannot access the listener on localhost

**Comment by lukidzi** [comment]
@gdasson Have you got a chance to look if the problem still exists?

**Comment by jakubdyszkiewicz** [comment]
@debianmaster 

Are you trying to fetch them with `localhost:5670` (port forward) or with `POD_IP:5670`?

**Comment by slonka** [comment]
@debianmaster - any updates on the issue?

**Comment by gdasson** [comment]
So I was able to make things work. Documented below are the issues and the fixes:

**Issue**:

- PodMonitor's podMetricsEndpoints.targetPort setting is deprecated. They recommend to use: podMetricsEndpoints.port instead. Essentially, the recommended option is to use a "named port" instead of a "port number". Supplying a port number is deprecated.
   
**Fixes**:

1. We applied a **ContainerPatch** to expose 5670 as a named port from a proxy-injected pod
2. We updated the PodMonitor configuration to use the named port.

### **An example of the ContainerPatch we applied:**
```
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: sc-container-patch
  namespace: kong-mesh-system
spec:
  sidecarPatch:
    - op: add
      path: /ports
      value:  '[{ "containerPort": 5670, "name":"metrics", "protocol":"TCP"}]'
```
Please note that your pod should be annotated with below annotation for this to work:

- kuma.io/container-patches: <container_patch_name>

More about container patches here: https://kuma.io/docs/2.0.x/explore/dpp-on-kubernetes/#custom-container-configuration

### **An example of the new PodMonitor:**
```
#This PodMonitor will create scrape configs for all proxies in this cluster. 
#The condition is that all pods that want prometheus scraping from kong mesh proxy should have a label:  kuma-dp-prometheus-scrape: enabled
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kong-mesh-dp
  namespace: prometheus-stack
spec:
  selector:
    matchLabels:
      kuma-dp-prometheus-scrape: enabled #This is an example of the label that we will use in all pods that will have a kuma proxy injected. you could name it the way you want.
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      scrapeTimeout: 10s
```

After doing these settings, we were able to see dataplane metrics scraped by our prometheus server
