### ISSUE TITLE
Match protocol on outbound listeners in MeshProxyPatch modification

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#5209]
### Description

Use case: replace `statsForAllMethods` to false in `envoy.filters.http.grpc_stats` filter.

For some reason, we cannot do a simple patch because of how proto works with BoolWrapper.

We can however remove the filter and add it again
```
---
type: ProxyTemplate
mesh: default
name: grpc-modification
selectors:
- match:
    kuma.io/service: "*"
conf:
  imports:
  - default-proxy
  modifications:
  - httpFilter:
      operation: remove
      match:
        name: envoy.filters.http.grpc_stats
        listenerTags:
          kuma.io/protocol: grpc
  - httpFilter:
      operation: addBefore
      match:
        name: envoy.filters.http.router
        listenerTags:
          kuma.io/protocol: grpc
      value: |
        name: envoy.filters.http.grpc_stats
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.http.grpc_stats.v3.FilterConfig
          emitFilterState: true
          statsForAllMethods: false
```

This works, but only for inbound listeners. We cannot do such a thing for outbound listeners.
We should either add new field in match called `protocl` or add `kuma.io/protocol` to `listenerTags` for outbound listeners.
