### ISSUE TITLE
MeshGateway TLS listener doesn't validate

### ISSUE THREAD

**Issue by conman2305** [kumahq/kuma#5254]
### What happened?

Trying to create a MeshGateway with a TLS listener using the following configuration:

```
---
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
mesh: dev
metadata:
  name: dsr-gateway
spec:
  conf:
    listeners:
    - port: 8181
      protocol: HTTPS
      tls:
        mode: TERMINATE
        certificate:
          secret: dsr-cert
  selectors:
  - match:
      kuma.io/service: dsr-gateway
---
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayRoute
mesh: dev
metadata:
  name: dsr-gateway-route
spec:
  selectors:
    - match:
        kuma.io/service: dsr-gateway
  conf:
    http:
      rules:
        - matches:
            - path:
                match: PREFIX
                value: /
          backends:
            - destination:
                kuma.io/service: demo-service-rust_test_svc_8181
```

and I'm getting the following error during apply:

`The MeshGateway "dsr-gateway" is invalid: spec.conf.listeners[0].tls.certificates: cannot be empty in TLS termination mode`

I'm following the documentation here: https://kuma.io/docs/1.8.x/policies/mesh-gateway/#tls-termination

Kuma version: 1.8.1

This is a multi-zone and multi-mesh deployment, if that changes anything.

Thank you!
