### ISSUE TITLE
Add possibility to expose metrics endpoints with TLS

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5368]
### Description

From @mmorel-35 

We deploy our prometheus outside of the mesh as the second option here ([Observability](https://kuma.io/docs/1.8.x/explore/observability/#configuring-prometheus)) is recommended, so we have skipMTLS: true

Prometheus then retrieves HTTP URL for the dataplanes metrics endpoints which is not allowed in our company.

The option skipMTLS disables the mtls provided by the mesh but I would like to be able to provide my own server certificate so the metrics endpoint is secured when it is accessed outside of the mesh.
In my opinion, the tls configuration shall be provided at the level of the dataplane config file and not at the level of the metrics policy.

This way, the metrics endpoint will be secured but you'll also need to ensure that the mads service of the control plane retrieves now HTTPS URL if the dataplane has TLS config while HTTP when it didn't.

**Comment by lahabana** [comment]
@mmorel-35 some random thoughts:

Wouldn't it be easier to reference a cert in the Kuma secrets in the metrics definition? We could then provide this cert to all dataplanes and it would make cert rotation a little easier, I guess SAN verification would be tricky here.

Is it also imaginable to use a provided CA and expose the endpoint through TLS (but not mTLS) so the cert would be rooted on the provided CA and prometheus would be able to verify it?

**Comment by mmorel-35** [comment]
It is completely imaginable that the tls config could be at the level of the metrics definition, for example, there could be something like that definition in the dataplane config file : 
```yaml
metrics:
  name: 
  type: ‘prometheus’
  conf:
  tls:
    enabled: true
    certFile:  ""
    keyFile: ""
    minVersion: "TLSv1_2"
    cipherSuites: []
```

So when mtls is disabled, the dataplane exposes it's metrics in a secured way and also the mesh is not responsible of the certificate rotation.


At the level of the mesh, I'm not sure if how it could look like ?  And the first could be done without this :

```yaml 
metrics: 
  enabledBackend: prometheus
  backends: 
    - name: prometheus
      type: prometheus
      conf: 
        path: /metrics
        port: 5670
        skipMTLS: true
        tls:
          ca: "" # Root CA ?
        tags: 
          kuma.io/service: dataplane-metrics
````

**Comment by jakubdyszkiewicz** [comment]
Hey, 2 questions from me
1) How will Prometheus verify the cert used to protect the metrics endpoint? I'm talking about SAN verification. What is the expected SAN from this cert?
2) Do you have control over what CA Prometheus will use to verify the metrics endpoint? Can CP distribute those certs or is the assumption that CP does not have an access to the CA?

**Comment by mmorel-35** [comment]
As it is a service discovery, there will be an url like https://myservice.mydomain:5670/metric for each dataplane
where the dataplane address is myservice.mydomain (this needs to be a dns name and not an IP I think) 

So the DNS name provided in the server certificate of the Dataplane will be
DNS Name=myservice.mydomain

In Prometheus [scrape_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config),
It is possible to provide a [tls client config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tls_config) 

So the Prometheus service discovery can be provided with a client certificate so il can call https URL from mydomain 

I don't think that the CP needs to distribute the dataplane's metrics as it won't consume it .

**Comment by jakubdyszkiewicz** [comment]
Hey, I still would like to know more about the first question.

Ping me on Kuma Slack, I think it would be easier to discuss it live :) Thanks

**Comment by jakubdyszkiewicz** [comment]
Here are my thoughts about potential deployments

For all examples below, this setting is always available
```
tls:
    minVersion: TLSv1_2
    maxVersion: TLSv1_3
    cipherSuites: []
```

## Metrics without TLS

Should be the most common case.

```
type: prometheus
confg: {}
```

## Metrics with mTLS when Prometheus is in the Mesh

This is the case that we support right now. MADS needs to deliver endpoints with `http://` because Prometheus' Envoy is handling TLS. Metrics Endpoint however is configured with TLS.

```
type: prometheus
conf:
  schema: "http"
  tls:
    enabled: true
    cert:
      activeMTLSBackend: true
    clientCertVerification:
      enabled: true
      caBundle:
        activeMTLSBackend: true
```

We could infer schema by default whether tls is enabled or not and for the case when Prometheus is in the mesh, we can override it to `http`

## Metrics when Prom is outside of the Mesh and certs are provided by user

This scenario is useful if there is already mechanism to distribute certs (this is what @mmorel-35 is describing above)

```
type: prometheus
conf:
  tls:
    enabled: true
    cert:
      certFile: "/tmp/cert.pem"
      keyFile: "/tmp/key.pem"
    clientCertVerification:
      enabled: true
      caBundle: # optional, if empty then default system CA bundle is used
        file: "/tmp/ca.pem"
      san: "prometheus.acme.org" # optional, if empty then just CA is verified
```

Client cert verification is optional (if you disable it, you still have TLS, just not mTLS)

## Metrics when Prom is outside of the Mesh and certs are provided by the CP

Another option is that CP could distribute cert from the CA that was provided by the user, but it's different CA than mTLS.

```
type: prometheus
conf:
  tls:
    enabled: true
    cert:
      providedCA:
        cert: # type: DataSource
          secret: "ca-cert"
        key:
          secret: "ca-key"
    clientCertVerification:
      enabled: true
      caBundle:
        secret: "ca-cert"
```

Certs generated this way would have `Dataplane#networking.address` in the cert SANs.
