### ISSUE TITLE
Default / autogenerated validator of `targetRef` policies allows empty `to` array

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#5443]
### What happened?

Default / autogenerated validator or target ref policies allows empty `to` (and probably `from` as well) arrays

AC:
- this [test](https://github.com/kumahq/kuma/blob/1a8d4330316f9ff6d8a6960370166e714ba6d72a/pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator_test.go#L107) should pass

xref https://github.com/kumahq/kuma/pull/5415

**Comment by lahabana** [comment]
What's wrong with an empty `to`?

**Comment by slonka** [comment]
> I feel we need to support this in cases where we have both a from and a to

What does it mean to have `to: []`? Is it the same as `to: nil`? To me it's ok to omit `to` or `from` but having `to: []` or `from: []` explicitly does not make sense e.g.:

```
type: MeshTrafficPermission
mesh: mesh-1
name: mtp-1
spec:
  targetRef:
    kind: Mesh
  from: []
```

it has no effect, why would we want to store that?
