### ISSUE TITLE
External service is not working in Kuma v2.0.0

### ISSUE THREAD

**Issue by brunda-bs** [kumahq/kuma#5450]
### What happened?

Hi Team,

External service policy is not working in the v2.0.0 Kuma release. The same was working fine in the v1.6.2 Kuma release. Post upgrade we see that it is failing.  

External service yaml:
```
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata:
  name: alpine-frontend
spec:
  tags:
    kuma.io/service: frontend_kuma-frontend_svc_8080
    kuma.io/protocol: http
  networking:
    address: dl-cdn.alpinelinux.org:80
    tls: # optional
      enabled: false
```
Container exec:
<img width="1302" alt="Screenshot 2022-12-07 at 1 04 04 PM" src="https://user-images.githubusercontent.com/97163498/206116724-7405e02c-7034-464a-b446-61194b8a45dd.png">

We observe that external service will not be able to view from the GUI. When both internal and external service is present, the Service tab is showing as partially degraded.
<img width="1387" alt="Screenshot 2022-12-07 at 1 02 45 PM" src="https://user-images.githubusercontent.com/97163498/206116963-2d5a1f00-280b-4e1a-a234-0041daa27871.png">
