### ISSUE TITLE
Incorrect traffic routing when using multiple inbounds

### ISSUE THREAD

**Issue by vermdeep** [kumahq/kuma#5476]
### What happened?

In version 1.8.1 of Kuma, I encountered an issue where my service had two inbounds: one for HTTP traffic, and one for gRPC traffic. After the containers got restarted, the downstream services began sending gRPC traffic on the HTTP port, and HTTP traffic on the gRPC port. We could see an increase in 4xx errors on the HTTP listener and 5xx errors on the gRPC listener.

The problem was fixed by force deploying the downstream service, which corrected the inbound discovery issue and restored correct routing of traffic. It was working fine before that.

Dataplane config I am using:
```yml
name: prod.wms-service-v2
mesh: prod
type: Dataplane
networking:
  address: 10.209.37.118
  inbound:
    - port: 16011
      servicePort: 5005
      tags:
        application: wms-service-v2
        kuma.io/protocol: http
        kuma.io/service: wms-service-http
        kuma.io/zone: prod
    - port: 16010
      servicePort: 5006
      tags:
        application: wms-service-v2
        kuma.io/protocol: grpc
        kuma.io/service: wms-service-v2
        kuma.io/zone: prod
  admin:
    port: 9902
```

**Comment by slonka** [comment]
I [have a branch](https://github.com/kumahq/kuma/compare/master...slonka:kuma:fix-multiple-inbounds-mixup?expand=1) - still needs some work to reproduce this. Not sure if I'll have time to work on it, or the next on-duty will pick this up.

**Comment by slonka** [comment]
Tried reproducing this (on 2.6.0) using python and `http.server` like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: kuma-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: python:3.11.4
        command: ["/bin/bash", "-c", "(python -m http.server 8080 --directory bin &) && python -m http.server 8081 --directory boot"]
        ports:
        - containerPort: 8080
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: kuma-demo
spec:
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http1
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: http2
```

and a loop to wget one of the ports:

```bash
while true; do wget -O - http://echo_kuma-demo_svc_8081.mesh && date && sleep 1; done
```

and another loop to restart the deployment (I also did manual force delete):

```bash
while true; do kubectl rollout restart deployment echo -n kuma-demo && sleep 20; done
```

and couldn't reproduce this.

@vermdeep have you seen this again? Have you upgraded to a newer version?
