### ISSUE TITLE
Dynamic lifecycle of Universal mesh nodes 

### ISSUE THREAD

**Issue by p0pr0ck5** [kumahq/kuma#554]
### Summary

Currently, running a universal mesh requires that every individual data plane be registered via the HTTP API. This is untenable in environments where application instances are dynamically provisioned (eg orchestration systems like Nomad, Mesos, or Swarm, or VM environments that actively scale, such as metrics-based auto scaling groups), for a few reasons:

- Additional orchestration has to go into creating _and deleting_ the dataplane instance from the control plane 
- Running multiple instances of a service requires registering data planes with essentially duplicate information, which is smelly
- Policies are applied directly to dataplane nodes which leads to duplication and relationship spaghetti in complex environments

I can envision a model where policies are applied to an abstract `service`, which would only need to be defined once in the lifecycle of an infrastructure, and then data plane processes run and _assume_ a service, eg:

`kuma-dp —role=web ...`

In such a case, when the dataplane starts it registers itself with the control plane (assuming it is authorized to do so for the given role, see below). This provides automatic discovery of services within the mesh, without need to manually configure instance IP and port definitions. 

The existing dataplane token model would serve well in this case to provide an authorization model for a dataplane instance (eg tokens can be issued to a VM or tool that will spawn the dp process based on existing identity/authentication mechanisms like IAM).

**Comment by jakubdyszkiewicz** [comment]
Hey @p0pr0ck5 

Lets assume we've got Nomad environment with dynamically allocated ports and 2 Dataplanes
```
type: Dataplane
mesh: default
name: backend-1
networking:
  inbound:
  - interface: 192.168.0.1:1234:1235
    tags:
      service: backend
  outbound:
  - interface: :1236
    service: redis
```
```
type: Dataplane
mesh: default
name: backend-2
networking:
  inbound:
  - interface: 192.168.0.1:1244:1245
    tags:
      service: backend
  outbound:
  - interface: :1246
    service: redis
```
How would you define abstract `service` here and how would you pass IPs and ports which are not common information for the dataplanes?

> This provides automatic discovery of services within the mesh, without need to manually configure instance IP and port definitions.

Can you elaborate on this?

*Inbound* - You still have to pass <IP, port of application and port of Envoy> for every for every port of application
*Outbound* - sure, instead of manually specifying services we can open outbound port for every service in a mesh, but lets say we've got 1000 services.
1) Every dataplane would have to open 1000 ports. Nomad would have to assign 1000 extra ports.
2) Envoy has to know about every service in the mesh which will reduce performance (Envoy has to follow instances of services that it does not use, Envoy has to store metrics for services it does not use).
