### ISSUE TITLE
Path based Traffic-Route is not working 

### ISSUE THREAD

**Issue by adarsh-padhi** [kumahq/kuma#5543]
### What happened?

**Usecase:**

I want to route with versions  depending upon the path . 

E.g. `www.xyz.com` will route `version V1` &  `www.xyz.com/new` will route `version V2` . 

- There are 2 pods i,e, `version-v1` , `version-v2` ( both labelled with version tag and running on same port )
- Added the appProtocol in the backend service

I followed the documentation [L7 traffic split](https://kuma.io/docs/2.0.x/policies/traffic-route/#l7-traffic-split) & found it to be not working for me.

here is the **code** for the traffic route

```
apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
metadata:
  name: path-split
mesh: default
spec:
  sources:
  - match:
      kuma.io/service: frontend_default_svc_80
      kuma.io/zone : dev
  destinations:
  - match:
      kuma.io/service: backend_default_svc_80
  conf:
    loadBalancer:
      roundRobin: {}
    http:
      - match:
          path:
            prefix: "/new"
        modify:
          path:
            regex:
              pattern: "\/new$"
              substitution: ""
        destination:
          kuma.io/service: backend_default_svc_80
          kuma.io/zone: dev
          kuma.io/protocol: http
          version: v2
    destination: 
      kuma.io/service: backend_default_svc_80
      kuma.io/zone: dev
      kuma.io/protocol: http
      version: v1
```
