### ISSUE TITLE
`MeshTimeout` incorrectly configures inbound `MeshGateway` listeners

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#5555]
### What happened?

The policy:
```yaml
kind: MeshTimeout
apiVersion: kuma.io/v1alpha1
metadata:
  namespace: kuma-system
  name: eg
spec:
  targetRef:
    kind: MeshService
    name: edge-gateway
  to:
    - targetRef:
        kind: MeshService
        name: frontend_kuma-demo_svc_8080
      default:
        http:
          streamIdleTimeout: 32s
```

sets `streamIdleTimeout` for the edge gateway listener. This listener is shared across all destination services so it's not correct to set it this way.
