### ISSUE TITLE
RateLimitedBackOff set to 8 seconds retries after ~11 seconds

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#5707]
### What happened?

We're setting "x-retry-after" to 8 seconds but the delay is longer.

<img width="1723" alt="image" src="https://user-images.githubusercontent.com/2753650/212664309-f9df97f0-705a-4e12-9f40-8e10a65b4ee0.png">

Also, request time was quite small so not sure what happened there:
![image](https://user-images.githubusercontent.com/2753650/212663762-3de9ef4c-fa9a-4a77-9e14-eacc11ea9b6a.png)

**Comment by lobkovilya** [comment]
ProxyTemplate to add response header:
```yaml
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: custom-template-1
spec:
  selectors:
    - match:
        kuma.io/service: backend_kuma-demo_svc_3001
  conf:
    imports:
      - default-proxy
    modifications:
      - virtualHost:
          operation: remove
          match:
            name: "backend_kuma-demo_svc_3001"
      - virtualHost:
          operation: add
          match:
            routeConfigurationName: "inbound:backend_kuma-demo_svc_3001"
          value: |
            name: "backend_kuma-demo_svc_3001"
            domains:
            - "*"
            routes:
            - match:
                prefix: /
              route:
                cluster: "localhost:3001"
                timeout: "0s"
              responseHeadersToAdd:
                - header:
                    key: "x-retry-after-header"
                    value: "8"
```

**Comment by slonka** [comment]
Same thing happens on k3d locally (1st retry triggered after ~11 seconds):

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/2753650/213995364-35f0ec16-67ef-4d0a-ab8c-125adecf39ca.png">

<img width="1688" alt="image" src="https://user-images.githubusercontent.com/2753650/213995567-731b6d46-f646-4979-ad08-f4e3d8b93c4f.png">

Fault injection:

```yaml
apiVersion: kuma.io/v1alpha1
kind: FaultInjection
mesh: default
metadata:
  name: fi1
spec:
  sources:
    - match:
        kuma.io/service: frontend_kuma-demo_svc_8080
        kuma.io/protocol: http
  destinations:
    - match:
        kuma.io/protocol: http
        kuma.io/service: backend_kuma-demo_svc_3001
  conf:        
    abort:
      httpStatus: 500
      percentage: 80
```

MeshRetry:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshRetry
metadata:
  name: mesh-retry
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: Mesh
      default:
        http: 
          numRetries: 5
          retryOn:
            - 5xx
          rateLimitedBackOff:
            resetHeaders:
              - name: "x-retry-after-header"
                format: "Seconds"
```

MeshTrace:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTrace
metadata:
  name: default
  namespace: kuma-system
  labels:
    kuma.io/mesh: default # optional, defaults to `default` if unset
spec:
  targetRef:
    kind: Mesh
  default:
    backends:
      - zipkin:
          url: http://jaeger-collector.mesh-observability:9411/api/v2/spans
```

Default request timeout (`timeout-all-default`) changed to:

```yaml
      requestTimeout: 120s
```
