### ISSUE TITLE
Apply new policies to clusters generated by the traffic split

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#5828]
### Description

Clusters generated by TrafficRoute or MeshHTTPRoute should get configurations for new outbound policies (MeshCircuitBreaker, MeshHealthCheck, MeshTimeouts, etc).

**Comment by lahabana** [comment]
Can you please give an example of what actually doesn't work?

**Comment by lobkovilya** [comment]
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshHealthCheck
metadata:
  name: web-to-backend-check
  namespace: kong-mesh-system
spec:
  targetRef:
    kind: MeshService
    name: frontend_kuma-demo_svc_8080
  to:
    - targetRef:
        kind: MeshService
        name: backend_kuma-demo_svc_3001
      default:
        interval: 10s
        timeout: 2s
        unhealthyThreshold: 3
        healthyThreshold: 1
        http:
          path: /health
          expectedStatuses: [200, 201]
```

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
mesh: default
metadata: 
  name: http-route-1
  namespace: kong-mesh-system
spec: 
  spec: 
    targetRef: 
      kind: MeshService
      name: frontend_kuma-demo_svc_8080
    to: 
      - targetRef: 
          kind: MeshService
          name: backend_kuma-demo_svc_3001
        rules: 
          - matches: 
              - path: 
                  value: /
                  type: Prefix
            default: 
              backendRefs: 
                - kind: MeshServiceSubset
                  name: backend_kuma-demo_svc_3001
                  tags: 
                    version: v0
                  weight: 50
                - kind: MeshServiceSubset
                  name: backend_kuma-demo_svc_3001
                  tags: 
                    version: v1
                  weight: 50
```  
Health checks won't be generated for `backend_kuma-demo_svc_3001-_0_` and `backend_kuma-demo_svc_3001-_1_`
