### ISSUE TITLE
Add Backends resource for grouping observability metadata

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5868]
### Description

As described: https://github.com/kumahq/kuma/blob/master/docs/madr/decisions/009-tracing-policy.md#backends

This should enable us to reference some common configuration:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTraceBackend
metadata:
 name: jaeger
spec:
  zipkin:
    url: http://jaeger-collector.mesh-observability:9411/api/v2/spans
```

Should these be quite generic? For example `MeshObservability` so that if you are using a tool doing metrics, logs and tracing you don't need to repeat things 3 times?
