### ISSUE TITLE
Warnings and errors should bubble up to GUI the when applied policy is incorrect for the targeted DPP

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#5870]
### Description

There are cases when the policy is correct from the schema perspective, but it doesn't make sense (or is wrong) after merging with other policies or after applying to a particular DPP. For example, when a user configures HTTP values for TCP proxy. 

We can print a warning in CP, but a better UX is to show such warnings/errors in the GUI. 

From the implementation perspective, we can use the `.status` field in CRD (but we need to implement something similar in Universal). Alternatively, we can use DataplaneInsight for such types of errors. 

### Use cases:
* Zone Egress enabled but Zone Egress is not deployed
* Using a feature that requires mTLS when mTLS is not enabled

**Comment by slonka** [comment]
Bumping this and voting 👍 because we just spent some time with @bartsmykla trying to figure out outbound naming mistake.

**Comment by lobkovilya** [comment]
Check https://gateway-api.sigs.k8s.io/geps/gep-713/#conditions when writing MADR

**Comment by lahabana** [comment]
There are now warnings in the rules api: https://github.com/kumahq/kuma/blob/4d008ffd12fd1f0b5346529681d546a9532cb570/api/openapi/specs/common/resource.yaml#L79-L84

Is there something more we should add on the backend side or this is now only something to display in the frontend?

**Comment by bartsmykla** [comment]
> API is there, but we want to populate warnings in plugins matching when present

The idea was to do it here: https://github.com/kumahq/kuma/blob/a61a9885fe57e53b4c5b7d49f2887242973f2368/pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin.go#L45-L47
> we have all resources, so we can say - "you are trying to apply some policy on a mesh with mtls enabled etc."

**Comment by lobkovilya** [comment]
Warnings on InspectRule are useful, but what I initially meant in the issue is to bubble up errors from the [Apply](https://github.com/kumahq/kuma/blob/e6b0f060d4b80d9073bdf2285610b4708f0ed671/pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go#L37) methods. Today if we're failing to build a snapshot for Envoy we print errors to CP logs or silently ignore policies (like when you try to apply HTTP timeout on the TCP service).

I think a good place for these types of warnings is DataplaneInsight (as well as ZoneIngressInsight/ZoneEgressInsight).

**Comment by lahabana** [comment]
Aren't errors in the Apply just bugs in the end?

**Comment by lobkovilya** [comment]
No, the same example with MeshTimeouts and protocols applies. You're allowed to create:
```yaml
type: MeshTimeout
name: timeout-global
mesh: default
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: Mesh
    default:
      idleTimeout: 20s
      connectionTimeout: 2s
      http:
        requestTimeout: 2s
```
but `requestTimeout` won't be set if there is no HTTPConnectionManager

**Comment by lahabana** [comment]
Do you actually want to show a warning? You are likely just writing a policy that works for all protocols, this is going to spam with warnings right?

**Comment by lobkovilya** [comment]
> this is going to spam with warnings right?

Depends on the implem really, if we put 1 warning on the dataplane insight `policy "mt-1" attempts to configure HTTP on TCP proxy` should be fine. 

But probably MeshTimeout is not the best example. What if there is a MeshLoadBalancingStrategy:
```yaml
type: MeshLoadBalancingStrategy
name: ring-hash
mesh: mesh-1
spec:
  targetRef:
    kind: MeshService
    name: web
  to:
    - targetRef:
        kind: MeshService
        name: backend
      default:
        loadBalancer:
          type: RingHash
          ringHash:
            hashPolicies:
              - type: Header
                header:
                  name: x-header
```
and RingHash works only if there is an HTTPConnectionManager
