### ISSUE TITLE
Prometheus aggregator does not handle Accept-Encoding correctly

### ISSUE THREAD

**Issue by LisaParrattBJSS** [kumahq/kuma#5892]
### What happened?

I first noticed this problem when ingesting prometheus metrics from a pod within a mesh, utilising metrics aggregation:

> prometheus ts=2023-01-31T12:23:47.968Z caller=scrape.go:1358 level=debug component="scrape manager" scrape_pool=mesh target=http://10.0.0.1:5670/metrics msg="Append failed" err="\"INVALID\" is not a valid start token"

After some forum reading, I think I isolated the problem pulling from the endpoint:

> curl --compressed -v http://10.0.0.1:5670/metrics --output -
> \*   Trying 10.0.129.175:5670...
> \* Connected to 10.0.0.1 (10.0.0.1) port 5670 (#0)
> \> GET /metrics HTTP/1.1
> \> Host: 10.0.129.175:5670
> \> User-Agent: curl/7.74.0
> \> Accept: */*
> \> Accept-Encoding: deflate, gzip, br
> \>
> \* Mark bundle as not supporting multiuse
> < HTTP/1.1 200 OK
> < content-type: text/plain; version=0.0.4; charset=utf-8
> < date: Tue, 31 Jan 2023 12:17:15 GMT
> < x-envoy-upstream-service-time: 56
> < server: envoy
> < transfer-encoding: chunked
> <
> 
> **Gzipped binary noise**
> **Plain text metrics from envoy**
> 
> \* Connection #0 to host 10.0.0.1 left intact

If I don't specify "--compressed" I get a correct looking response.

Judging by the lack of "Content-Encoding" header in the response, I would presume it shouldn't be returning any gzipped data?

If I had to hazard a guess, it appears the aggregator is passing along the "Accept-Encoding" header when it scrapes the aggregated containers, but is then not uncompressing the data before passing it back.

**Comment by LisaParrattBJSS** [comment]
The following egregious hack makes metrics work, supporting the theory it is related to compression:

```
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: scrub-prometheus
spec:
  selectors:
    - match:
        kuma.io/service: '*'
  conf:
    imports:
      - default-proxy
    modifications:
      - httpFilter:
          operation: addFirst
          match:
            listenerName: 'kuma:metrics:prometheus'
          value: |
            name: envoy.filters.http.lua
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  request_handle:headers():remove("Accept-Encoding")
                end
```
