### ISSUE TITLE
ability to install universal control-plane on Kubernetes

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5907]
### Description

It's useful for people to be able to run universal control-plane on Kubernetes.
In that case they usually back it with postgres

I think we should add a `controlPlane.environment` with a default of `kubernetes`.

In that case you likely want to add to the CP startup env vars:

```yaml
- name: KUMA_ENVIRONMENT
  value: "universal"
- name: KUMA_STORE_TYPE
  value: "postgres"
- name: KUMA_STORE_POSTGRES_HOST
  value: {{ .Values.postgres.host }}
- name: KUMA_STORE_POSTGRES_PORT
  value: "{{ .Values.postgres.port }}"
- name: KUMA_STORE_POSTGRES_USER
  value: "{{ .Values.postgres.user }}"
- name: KUMA_STORE_POSTGRES_DB_NAME
  value: "{{ .Values.postgres.db }}"
```

And then you'll want to guard installing the webhooks and the crd with `controlPlane.environment==kubernetes`.
