### ISSUE TITLE
MeshHTTPRoute make default `weight` value greater than 0

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#5921]
### Description

It could be not very obvious that the following route doesn't work:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: http-route-1
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshService
    name: frontend_kuma-demo_svc_8080
  to:
    - targetRef:
        kind: MeshService
        name: backend_kuma-demo_svc_3001
      rules:
        - matches:
            - path:
                type: Exact
                value: /exact
          default:
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /new
            backendRefs:
              - kind: MeshService
                name: backend_kuma-demo_svc_3001
```
because `backendRefs[0].Weight` is not set (and equal 0 by default)
