### ISSUE TITLE
MeshHTTPRoute validate prefix-based filter when non-prefix match is used

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#5922]
### Description

Kuma silently avoids configuring prefix-based filters when a non-prefix match is used:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: http-route-1
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshService
    name: frontend_kuma-demo_svc_8080
  to:
    - targetRef:
        kind: MeshService
        name: backend_kuma-demo_svc_3001
      rules:
        - matches:
            - path:
                type: Exact
                value: /hello
          default:
            filters:
              - type: URLRewrite # this filter won't end up in Envoy because `Exact` match is used
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /nneww 
            backendRefs:
              - kind: MeshService
                weight: 1
                name: backend_kuma-demo_svc_3001
```
Probably we can validate this during the policy creation
