### ISSUE TITLE
Apps cannot be consumed using delegated gateway with CNI v2 and IPV6

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#6017]
### Description

A user reported an issue on slack that the app can be consumed via regular dataplane proxy, but not via delegated gateway.

The setup is EKS 1.23, Kuma CNI v2 (because of ARM images), IPV6 only.

Double-check if this really an issue.

YAML resources
```
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: sample-mesh
  namespace: kuma-system
spec:
  mtls:
    enabledBackend: ca-10
    backends:
      - name: ca-10
        type: builtin
        dpCert:
          rotation:
            expiration: 1d
        conf:
          caCert:
            RSAbits: 4096
            expiration: 10y
---
apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: sample-mesh
metadata:
  name: allow-all-sample-mesh
  namespace: kuma-system
spec:
  sources:
    - match:
        kuma.io/service: '*'
  destinations:
    - match:
        kuma.io/service: '*'
---
kind: Namespace
apiVersion: v1
metadata:
  name: testing-2
  labels:
    kuma.io/sidecar-injection: enabled
  annotations:
    kuma.io/mesh: sample-mesh
---
# target
kind: Pod
apiVersion: v1
metadata:
  name: adminer
  labels:
    app: adminer
    landscape: admin
  namespace: testing-2
spec:
    containers:
    - name: adminer
      image: adminer:latest
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8080
        protocol: TCP
      resources:
        limits:
            cpu: 100m
            memory: 128Mi
        requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: testing-2
spec:
  selector:
    app: adminer
  ports:
    - protocol: TCP
      port: 750
      targetPort: 8080
---
kind: Pod
apiVersion: v1
metadata:
  name: alpine
  labels:
    app: alpine
  namespace: testing-2
spec:
  containers:
    - name: alpine
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command: ["/usr/bin/tail", "-F" ]
      stdin: true
      tty: true
---
kind: Pod
apiVersion: v1
metadata:
  name: alpine-gateway
  labels:
    app: alpine-gateway
  namespace: testing-2
  annotations:
    kuma.io/gateway: enabled
spec:
  containers:
    - name: alpine-gateway
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command: ["/usr/bin/tail", "-F" ]
      stdin: true
      tty: true

```

context: https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1676360879019199
