### ISSUE TITLE
External Service that points to CNAME

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#6041]
### What happened?

Create ExternalService with DNS that returns CNAME to another name. Our DNS returns both A and CNAME record which is not a valid response.

If you set ExternalService to name returned from CNAME, the traffic works.

**Comment by slonka** [comment]
I remember trying to reproduce this and not being able to do so:

```
dig www4.slonka.net

; <<>> DiG 9.10.6 <<>> www4.slonka.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61159
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;www4.slonka.net.               IN      A

;; ANSWER SECTION:
www4.slonka.net.        297     IN      CNAME   slonka.github.io.
slonka.github.io.       3597    IN      A       185.199.110.153
slonka.github.io.       3597    IN      A       185.199.111.153
slonka.github.io.       3597    IN      A       185.199.108.153
slonka.github.io.       3597    IN      A       185.199.109.153

;; Query time: 9 msec
;; SERVER: 192.168.100.1#53(192.168.100.1)
;; WHEN: Tue Jun 18 08:15:29 CEST 2024
;; MSG SIZE  rcvd: 138
```

notice the `www4.slonka.net.        297     IN      CNAME   slonka.github.io.`.

Then with this ES: 

```
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata:
  name: slonka4
spec:
  tags:
    kuma.io/service: slonka4
    kuma.io/protocol: http # optional, one of http, http2, tcp, grpc, kafka
  networking:
    address: www4.slonka.net:80
```

I'm getting the same 404 through ES and directly:

```
~ # curl -I slonka4.mesh
HTTP/1.1 404 Not Found
```

```
curl -I www4.slonka.net:80
HTTP/1.1 404 Not Found
```
