### ISSUE TITLE
Policy merging discrepancy between Kubernetes and Universal with defaults

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#6070]
### What happened?

We use the `kubebuilder:default` annotation to generate an OpenAPI spec describing our resources. When we create our CRDs with these OpenAPI specs, Kubernetes then _sets_ the value of omitted fields to the default. On Universal, we don't do the same, this part of the spec serves only as documentation

This means:
* Merging won't work as intended. Given a `kubebuilder:default=30s` for `interval`:
```
---
targetRef:
kind: Mesh
to:
  - default:
      interval: 100s
      timeout: 200s
---
targetRef:
  kind: MeshService
  name: backend
to:
  - default:
      timeout: 300s
```
on Universal we get `{interval: 100s, timeout: 300s}` but on Kubernetes we get `{interval: 30s, timeout: 300s}` because the API server sets `interval: 30s` on the second resource.

* when writing policy implementations, we have to duplicate the default everywhere we use the fields for the universal case, even though on Kubernetes they'll always be set
