### ISSUE TITLE
MeshLoadBalancingStrategy implement localityAwareness

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#6305]
### Description

https://github.com/kumahq/kuma/pull/6202 implements a load balancer functionality, this issue tracks the implementation of:
```yaml
default:
  localityAwareness:
    disabled: true
```
