### ISSUE TITLE
design new external service resource

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6330]
### Description

For #1496 we need to move external service to be namespace based. It's a good time to rethink this resource and improve it.

Rough design from a thinking session:
```yaml
type: externalService
metadata:
  namespace: kuma-system
  name: my-service
spec:
  hostname: my-service.foo.bar
  kuma.io/service: my-service
  protocol: http
  port: 443
  instances:
     - address: east-1
       port: 334
       tags:
          region: east-1
       tls:
         enabled: true
     - address: west-1
       port: 335
       tags:
          region: west-1
```

Each instance of a resource is an envoy cluster.
Is each instance inside the resource a different envoy endpoint? If yes can we have different TLS config for example (seems like it)?

Should we disallow having an internal and an external service with the same name? --> Probably

There are a few issues around ES that we should take into consideration for this:

- https://github.com/kumahq/kuma/issues/6180
- https://github.com/kumahq/kuma/issues/6041
- https://github.com/kumahq/kuma/issues/5474
- https://github.com/kumahq/kuma/issues/4758
- https://github.com/kumahq/kuma/issues/4400
- https://github.com/kumahq/kuma/issues/3980
- https://github.com/kumahq/kuma/issues/3097
- https://github.com/kumahq/kuma/issues/2248
- https://github.com/kumahq/kuma/issues/6352
- https://github.com/kumahq/kuma/issues/6391
- https://github.com/kumahq/kuma-website/issues/727
- https://github.com/kumahq/kuma/issues/7121
- https://github.com/kumahq/kuma/issues/7200
- https://github.com/kumahq/kuma/issues/8721
- ExternalService support for SRV record (if possible)
- https://github.com/kumahq/kuma-gui/issues/2471
