### ISSUE TITLE
design `MeshService` as a replacement for ServiceInsights

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6331]
### Description

ServiceInsights has limitations:

- It's not namespace scoped (blocking: #1496)
- It only contains the number of dataplanes
- There's one for the entire Mesh (potentially problematic at scale).
- It's hard to figure if a label affects all the DPPs with a common kuma.io/service.
- Is this a path forward to fix: #2780 (just having MeshAdmin control the creation of Services).
- How much is this common with #4741 ?
- Should permissive TLS be part of this?

Can users edit MeshService or is it purely managed by the CP?
How does this work in Universal?

Can we get rid of the job to compute ServiceInsights and instead reconcile MeshService when a DPP of a specific Service changes?

Example:

```yaml
type: MeshService
metadata:
   namespace: kuma-system
   name: my-service
spec:
   type: internal|external
   dataplanes: 30
   kuma.io/service: foo_svc_80
   tags:
     kuma.io/protocol: http
```

Many questions come up here :)

**Comment by lahabana** [comment]
Probably interesting to watch while working on this: https://www.youtube.com/watch?v=Oslwx3hj2Eg

**Comment by lahabana** [comment]
An idea:

```yaml
type: MeshService
metadata:
  namespace: foo
  name: my-svc
spec:
   port: 8080
   hostnames: [ ...]
   groups:
     - tags:
          kuma.io/protocol: http
       endpoints:
           - a:9090
           - b:9090
           - c:9090
     - tags:
          version: v0
          kuma.io/protocol: http
       endpoints:
           - a:9090
     - tags:
           version: v1
           kuma.io/protocol: http
       endpoints:
           - b:9090
           - c:9090
```

These would exist per zone and we could easily pass them from one to the other thus removing the need for `availableServices` in ZoneIngress.

This sort of format makes it easy to have a CLA cache and we wouldn't need to look at dataplanes for generating outbounds.

A later version of this could populate VIPs and hostnames with something like virtualOutbounds
