### ISSUE TITLE
Merging of policies results in not applying policy on some outbound

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#6426]
### What happened?

Reported by Brent Yarger. Apparently when applied this policy
```
apiVersion: kuma.io/v1alpha1
kind: MeshRetry
metadata:
  name: retry-all
  namespace: kong-mesh-system
  labels:
    kuma.io/mesh: default 
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: Mesh
      default:
        http:
          numRetries: 1
          backOff:
            baseInterval: 5s
            maxInterval: 1m
          retryOn:
            - "5xx"
```
and
```
apiVersion: kuma.io/v1alpha1
kind: MeshRetry
metadata:
  name: retry-echo-to-mockserver
  namespace: kong-mesh-system
  labels:
    kuma.io/mesh: default # optional, defaults to `default` if unset
spec:
  targetRef:
    kind: MeshService
    name: echo-service_default_svc_8080
  to:
    - targetRef:
        kind: MeshService
        name: mockserver_mockserver_svc_1080
      default:
        http:
          numRetries: 5
          backOff:
            baseInterval: 10s
          retryOn:
            - "5xx"
```
results in the other upstreams in the echo service sidecar get retry config removed.
