### ISSUE TITLE
MeshRetry does not support targetRef kind Mesh

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#6432]
### What happened?

According [the docs](https://kuma.io/docs/2.1.x/policies/meshretry/#targetref-support-matrix), `MeshRetry` supports a `to` `targetRef` of `Mesh`, although when applying a policy with a `Mesh` `to` selector, I get:

`The MeshRetry "retry-test" is invalid: spec.spec.to[0].targetRef.name: using name with kind Mesh is not yet supported`

Policy:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshRetry
metadata:
  name: retry-test
  namespace: kuma-system
  labels:
    kuma.io/mesh: default # optional, defaults to `default` if unset
spec:
  targetRef:
    kind: MeshService
    name: demo-app_kuma-demo_svc_5000
  to:
    - targetRef:
        kind: Mesh
        name: default
      default:
        http:
          numRetries: 10
          backOff:
            baseInterval: 15s
            maxInterval: 20m
          retryOn:
            - "5xx"
```
