### ISSUE TITLE
MeshTrace doesn't work with MeshGatewayRoute / clarify behavior?

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#6497]
### What happened?

We document that MeshTrace works with MeshGatewayRoute but it doesn't appear to:

```yaml
echo "
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: edge-gateway
  namespace: default
spec:
  replicas: 1
  serviceType: LoadBalancer
  tags:
    kuma.io/service: edge-gateway
---
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
mesh: default
metadata:
  name: edge-gateway
spec:
  selectors:
  - match:
      kuma.io/service: edge-gateway
  conf:
    listeners:
      - port: 8080
        protocol: HTTP
        hostname: foo.example.com
        tags:
          port: http/8080
      - port: 8080
        protocol: HTTP
        hostname: bar.example.com
        tags:
          port: http/bar
---
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayRoute
mesh: default
metadata:
  name: edge-gateway-route2
spec:
  selectors:
    - match:
        kuma.io/service: edge-gateway
        port: http/bar
  conf:
    http:
      rules:
        - matches:
            - path:
                match: PREFIX
                value: /
          backends:
            - destination:
                kuma.io/service: backend_kuma-demo_svc_3001
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrace
metadata:
  name: default
  namespace: kong-mesh-system
spec:
  targetRef:
    kind: MeshGatewayRoute
    name: edge-gateway-route2
  default:
    backends:
      - zipkin:
          url: http://jaeger-collector.mesh-observability:9411/api/v2/spans
" | kubectl apply -f -
```

Although like https://github.com/kumahq/kuma/issues/5864 it seems to work when using `MeshService` and the gateway svc name?
