### ISSUE TITLE
Configure control plane to reach ingress proxy via advertisedAddress

### ISSUE THREAD

**Issue by albertpx** [kumahq/kuma#6543]
### Description

For communication of control plane with ingress proxy, the `address` configuration is used.
For example, given this configuration:
```yaml
type: ZoneIngress
name: {{ name }}
networking:
  port: 10001
  address: {{ address }}
  advertisedPort: 10001
  advertisedAddress: {{ address }}
```
Unlike in a regular configuration of a dataplane, in this case, `advertisedAddress` can be used for configuring a different address, such as a load balancer address, but the control plane will continue using the `address` to communicate with it.

In a regular dataplane proxy, the `advertisedAddress` is used to tell control plane on what address to communicate with it.

Such config as in a regular dataplane, is also desirable for an ingress proxy. For example, when the proxy is running behind a docker bridge, so the address would be an internal docker bridge address, but it should have the ability to tell the control plane to communicate with it over advertisedAddress.

The most configurable option would be to introduce another configuration, such as `addressForControlPlane` or similar, to tell the control plane what is the address to communicate with it.
