### ISSUE TITLE
Ingress proxy does not respect the configured advertisedAddress of a dataplane

### ISSUE THREAD

**Issue by albertpx** [kumahq/kuma#6545]
### What happened?

When running a dataplane with a different `advertisedAddress` than `address`. For example dataplane is running with the following config:
```
type: Dataplane
mesh: default
name: {{ name }}
networking:
  address: {{ container_address }}
  advertisedAddress: {{ address }}
  inbound:
    - port: 5555
      servicePort: 6666
      tags:
        kuma.io/service: kuma-test-inbound
        kuma.io/protocol: http
```

The `container_address` was for example `172.18.0.2`, and the `address` was `10.0.0.5`.

We noticed that only same-zone traffic is working. Dataplane in one zone was able to reach another in the same zone with no issues.

However, cross-zone communication was not working.
After investigating the ingress proxy of the destination zone, we have noticed the following in its config_dump:
```
kuma-test-inbound::172.18.0.2:5555::cx_active::0
```
The ingress proxy is trying to reach the dataplane over its `address` and not `advertisedAddress`.
