### ISSUE TITLE
Unable to use custom tags of dataplane for cross-zone communication

### ISSUE THREAD

**Issue by albertpx** [kumahq/kuma#6546]
### What happened?

On universal cross-zone cluster, if you configure custom tags on inbound dataplane, for example with `custom/foo: bar` tag:
```yaml
type: Dataplane
mesh: default
name: {{ name }}
networking:
  address: {{ address }}
  inbound:
    - port: 5555
      servicePort: 6666
      tags:
        kuma.io/service: kuma-test-inbound
        kuma.io/protocol: http
        custom/foo: bar
```

Then you can use that custom tag in the outbound dataplane, for example:
```yaml
type: Dataplane
mesh: common
name: {{ name }}
networking:
  address: {{ address }}
  gateway:
    tags:
      kuma.io/service: kuma-test-outbound
  outbound:
    - port: 1337
      address: {{ container_address }}
      tags:
        kuma.io/service: kuma-test-inbound
        custom/foo: bar
```

If the inbound and outbound are in the same zone control plane, then communication between the two services works properly.
However, it is not working if the services reside in different zones.
Removing the custom tag in the outbound service, discovers the inbound service without any issue. It is only when setting the additional custom tag on the outbound service when the communication stops working.
