### ISSUE TITLE
`ExternalService`s shouldn't rely on the existence of a `TrafficPermission`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6589]
### Description

When delete default TrafficPermission then ExternalServices don't work at all. Kuma generates outbounds for ES based on the TrafficPermission policy (no permission -> no outbound).

Can we just have a RBAC filter on the external service listener? What happens with Egress?

- [x] https://github.com/kumahq/kuma/issues/8468

**Comment by lahabana** [comment]
Should we close this now? @lukidzi ?

**Comment by slonka** [comment]
This is still a problem, we shouldn't close this ☝️

**Comment by cbugneac-nex** [comment]
I'm on Kuma version 2.4.3 and decided to migrate to `MeshTrafficPermission` from `TrafficPermission`. Created default allow all initially to not break working things:
```yaml
---
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  namespace: kuma-system
  name: allow-all-default
  labels:
    kuma.io/mesh: default
spec:
  from:
  - default:
      action: AllowWithShadowDeny
    targetRef:
      kind: Mesh
  targetRef:
    kind: Mesh
```
And now access to `ExternalServices` doesn't work even if I add explicit `MeshTrafficPermissions` for `ExternalServices`.
