### ISSUE TITLE
"stream timeout" from MeshGatewayInstance 

### ISSUE THREAD

**Issue by conman2305** [kumahq/kuma#6620]
### What happened?

Some of our web services have endpoints that take a while to return. When these endpoints take more than 5 or so seconds to return, the Envoy MeshGatewayInstance is returning a 504 with a `stream timeout` error. I rigged up a quick little Rust service that reproduces this issue 100% by just having it sleep for 6s before returning a 200 status code:

```
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 504
< date: Tue, 25 Apr 2023 20:53:09 GMT
< content-type: text/plain
< content-length: 14
< strict-transport-security: max-age=31536000; includeSubDomains
< server: Kuma Gateway
<
* Connection #0 to host <redacted> left intact
stream timeout%
```

I've configured a Timeout policy for the mesh:

```
spec:
  conf:
    connectTimeout: 3600s
    http:
      idleTimeout: 3600s
      requestTimeout: 3600s
      streamIdleTimeout: 7200s
    tcp:
      idleTimeout: 3600s
  destinations:
    - match:
        kuma.io/service: '*'
  sources:
    - match:
        kuma.io/service: '*'
```

As well as used a ProxyTemplate to bump up the idle timeout of the Gateway:

```
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: custom-template-1
spec:
  selectors:
    - match:
        kuma.io/service: '*'
  conf:
    imports:
      - gateway-proxy # default configuration for MeshGateway
    modifications:
      - networkFilter:
          operation: patch
          match:
            name: envoy.filters.network.http_connection_manager
            origin: gateway # you can also specify the name of the listener
          value: |
            name: envoy.filters.network.http_connection_manager
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              streamIdleTimeout: 15s
```

I confirmed this is an issue with the Gateway by running an ubuntu container and hitting the same endpoint using the Kuma service mesh DNS name and never saw the issue. Any ideas?
