### ISSUE TITLE
Duplicated fault filter in envoy config with two MeshFaultInjection policies targeting MeshGateway

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#6630]
### What happened?

I deployed two `MeshFaultInjection` policies:

<details>
<summary>First: <code>targetRef: MeshService#demo-app_gateway</code> + <code>from.targetRef: Mesh</code> / percentage: <code>55</code></summary>

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshFaultInjection
metadata:
  name: mfi
  namespace: kuma-system
spec:
  targetRef:
    kind: MeshService
    name: demo-app_gateway
  from:
    - targetRef:
        kind: Mesh
      default:
        http:
          - abort:
              httpStatus: 500
              percentage: 55
```
</details>
<details>
<summary>Second: <code>targetRef: Mesh</code> + <code>from.targetRef: MeshService#demo-app_gateway</code> / percentage: <code>77</code></summary>

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshFaultInjection
metadata:
  name: mfi-2
  namespace: kuma-system
spec:
  targetRef:
    kind: Mesh
  from:
    - targetRef:
        kind: MeshService
        name: demo-app_gateway
      default:
        http:
          - abort:
              httpStatus: 500
              percentage: 77
```
</details>

and when looking at config dump we have (this is just an excerpt of the listener with less important fields removed, for clarity):
```json
{
  "name": "demo-app:HTTP:80",
  "activeState": {
    "listener": {
      "@type": "type.googleapis.com/envoy.config.listener.v3.Listener",
      "name": "demo-app:HTTP:80",
      "address": {
        "socketAddress": {
          "address": "10.42.0.9",
          "portValue": 80
        }
      },
      "filterChains": [
        {
          "filters": [
            {
              "name": "envoy.filters.network.http_connection_manager",
              "typedConfig": {
                "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                "statPrefix": "demo-app_gateway",
                "rds": {
                  "routeConfigName": "demo-app:HTTP:80"
                },
                "httpFilters": [
                  {
                    "name": "envoy.filters.http.fault",
                    "typedConfig": {
                      "@type": "type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault",
                      "abort": {
                        "httpStatus": 500,
                        "percentage": {
                          "numerator": 55
                        }
                      },
                      "headers": [
                        {
                          "name": "x-kuma-tags",
                          "safeRegexMatch": {
                            "googleRe2": {},
                            "regex": ".*&kuma.io/service=[^&]*demo-app_gateway[,&].*"
                          }
                        }
                      ]
                    }
                  },
                  {
                    "name": "envoy.filters.http.fault",
                    "typedConfig": {
                      "@type": "type.googleapis.com/envoy.extensions.filters.http.fault.v3.HTTPFault",
                      "abort": {
                        "httpStatus": 500,
                        "percentage": {
                          "numerator": 55
                        }
                      },
                      "headers": [
                        {
                          "name": "x-kuma-tags",
                          "safeRegexMatch": {
                            "googleRe2": {},
                            "regex": ".*&kuma.io/service=[^&]*demo-app_gateway[,&].*"
                          }
                        }
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
      ],
      "trafficDirection": "INBOUND"
    }
  }
}
```
