### ISSUE TITLE
IdleTimeout on httpConnectionManager is set from Timeout policy even though MeshTimeout is defined

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#6644]
### What happened?

IdleTimeout for HTTP traffic could be configured in 2 places in Envoy:
1. https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-common-http-protocol-options
2. https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-common-http-protocol-options

The old Timeout policy is using 1, but the new MeshTimeout is using 2. 

When applying MeshTimeout:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
metadata:
  name: mt-1
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshService
    name: frontend_kuma-demo_svc_8080
  to:
    - targetRef:
        kind: MeshService
        name: backend_kuma-demo_svc_3001
      default:
        idleTimeout: 3s
        connectionTimeout: 3s
        http:
          requestTimeout: 3s
          streamIdleTimeout: 3s
          maxStreamDuration: 3s
          maxConnectionDuration: 3s
```
and there is still old Timeout `timeout-all-default` then

ACTUAL: `httpConnectionManager.commonHttpProtocolOptopns.idleTimeout: 3600s`
EXPECTED: `httpConnectionManager.commonHttpProtocolOptopns.idleTimeout: 0s`
