### ISSUE TITLE
Set minimum set of capabilities for sidecar container

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6714]
### Description

Here's a matching container patch:

```yaml
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: default-container-patch
  namespace: kong-mesh-system
spec:
  sidecarPatch:
    - op: add
      path: /securityContext/capabilities
      value: '{
        "add": [
            "NET_BIND_SERVICE",
            "SETGID",
            "SETUID",
            "FSETID"
        ],
        "drop" : [
        "ALL"
        ]
      }'
```

This is for example required to work on openShift. It feels like this is likely good to always be the default when using the CNI.
Any good reason to have this security context the default?
