### ISSUE TITLE
MeshHTTPRoute empty `matches` array behaves unexpectedly 

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#6757]
### What happened?

When apply:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: reviews-to-v1
  namespace: kuma-system
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: MeshService
        name: reviews_default_svc_9080
      rules:
        - matches: [] # EMTPY
          default:
            backendRefs:
              - kind: MeshServiceSubset
                name: reviews_default_svc_9080
                tags:
                  version: v1
```
then Envoy has a split cluster `reviews_default_svc_9080_-0-` but listener points to non-split cluster `reviews_default_svc_9080`.
