### ISSUE TITLE
MeshHTTPRoute configuration fails in Envoy

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#6758]
### What happened?

When apply

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: jason-to-v2
  namespace: kuma-system
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: MeshService
        name: reviews_default_svc_9080
      rules:
        - matches:
          - headers:
            - type: Exact
              name: end-user
              value: jason
          default:
            backendRefs:
              - kind: MeshServiceSubset
                name: reviews_default_svc_9080
                tags:
                  version: v2
```
then there is an error in Envoy that `matches.path` is required. 

We can either add an extra validation or assume that path is always `prefix: /`
