### ISSUE TITLE
MeshTimeout + MeshGateway wrong result

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#6761]
`MeshTimeout` can't be applied in a coherent way at the moment in some cases with `MeshGateway`

The solution for now is to only apply `targetRef.kind: Mesh` scoped `MeshTimeout`s in these cases.

Todo:

- [ ] https://github.com/kumahq/kuma/pull/6744: invalidate the use of route-level configuration (like `requestTimeout`) with `spec.targetRef.kind: MeshGateway` and `to.targetRef.kind: MeshService`. Instead only allow `to.targetRef.kind: Mesh`
- [ ] https://github.com/kumahq/kuma/issues/6923: Enable setting more specific timeouts with `targetRef.kind: MeshGatewayRoute`

### What happened?

Apply the following MeshGatewayRoute and MeshTimeout:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayRoute
mesh: default
metadata:
  name: demo-app
spec:
  selectors:
    - match:
        kuma.io/service: demo-app_gateway
  conf:
    http:
      rules:
        - matches:
            - path:
                match: PREFIX
                value: /
          backends:
            - weight: 1
              destination:
                kuma.io/service: backend_kuma-demo_svc_3001
            - weight: 1
              destination:
                kuma.io/service: demo-app_kuma-demo_svc_5000
```
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTimeout
mesh: default
metadata:
  name: mt-1
  namespace: kuma-system
spec:
  spec:
    targetRef:
      kind: MeshService
      name: demo-app_gateway
    to:
      - targetRef:
          kind: MeshService
          name: backend_kuma-demo_svc_3001
        default:
          http:
            requestTimeout: 31s
      - targetRef:
          kind: MeshService
          name: demo-app_kuma-demo_svc_5000
        default:
          http:
            requestTimeout: 11s
```
Only `11s` will be set in Envoy route:

```json
{
 "route_config": {
  "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
  "name": "demo-app:HTTP:80",
  "virtual_hosts": [
   {
    "name": "*",
    "domains": [
     "*"
    ],
    "routes": [
     {
      "match": {
       "prefix": "/"
      },
      "route": {
       "weighted_clusters": {
        "clusters": [
         {
          "name": "backend_kuma-demo_svc_3001-7533776aed72e82a",
          "weight": 1,
          "request_headers_to_add": [
           {
            "header": {
             "key": "x-kuma-tags",
             "value": "&kuma.io/service=demo-app_gateway&"
            }
           }
          ]
         },
         {
          "name": "demo-app_kuma-demo_svc_5000-41c96d8c484e3ae3",
          "weight": 1,
          "request_headers_to_add": [
           {
            "header": {
             "key": "x-kuma-tags",
             "value": "&kuma.io/service=demo-app_gateway&"
            }
           }
          ]
         }
        ]
       },
       "timeout": "11s", <--- HERE
       "retry_policy": {
        "retry_on": "gateway-error,connect-failure,refused-stream",
        "num_retries": 5,
        "per_try_timeout": "16s",
        "retry_back_off": {
         "base_interval": "0.025s",
         "max_interval": "0.250s"
        }
       },
       "cluster_not_found_response_code": "INTERNAL_SERVER_ERROR"
      }
     }
    ]
   }
  ],
  "validate_clusters": false,
  "request_headers_to_remove": [
   "x-kuma-tags"
  ]
 }
}
```
The problem is we're allowing to specify `requestTimeout` per destination, but this is a route-level parameter and route in envoy can have multiple destinations.
