### ISSUE TITLE
Metric hijacker is not honouring application content-type

### ISSUE THREAD

**Issue by AyushSenapati** [kumahq/kuma#6782]
**Kuma Version:** 2.1.1

### What happened?

As per the latest prom scraper, it sends the following `Accept` header
```
Accept: "application/openmetrics-text;version=1.0.0,application/openmetrics-text;version=0.0.1;q=0.75,text/plain;version=0.0.4;q=0.5,*/*;q=0.1"
```
Ref: https://github.com/prometheus/prometheus/blob/main/scrape/scrape.go#L799

Currently the metric hijacker allows following headers and send them as it's from the scraper to the target applications: `"accept", "accept-encoding", "user-agent", "x-prometheus-scrape-timeout-seconds"`
If the application supports `openmetrics`, it will return metrics in that format. But after aggregating the metrics from the target apps, the hijacker sets the `Content-Type` to `text/plain`. Now that the metrics are in openmetrics format but the type is set to plain text, the scraper is failing to parse the content.

Application is returning following metrics content, which is in openmetrics-text format.
```
...
http_server_requests_seconds_bucket{error="none",exception="none",method="GET",outcome="SUCCESS",status="200",uri="/prometheus",le="0.003495251"} 0.0
http_server_requests_seconds_bucket{error="none",exception="none",method="GET",outcome="SUCCESS",status="200",uri="/prometheus",le="0.003844776"} 25.0 # {span_id="3ae5e7138b7c3549",trace_id="64622fefa9afd2325cd5b908b67d7a6a"} 0.003788807 1684157749.966
...
...
```
But as the hijacker overrides the Content-Type with text/plain, the prom scraper complains:
```
"lastError": "expected timestamp or new record, got \"#\" (\"INVALID\") while parsing: \"http_server_requests_seconds_bucket{error=\\\"none\\\",exception=\\\"none\\\",method=\\\"GET\\\",outcome=\\\"SUCCESS\\\",status=\\\"200\\\",uri=\\\"/prometheus\\\",le=\\\"0.003844776\\\"} 25.0 #\""
```

### What do I expect?
Even if openmetrics-text 1.0.0 is the superset of all other types, Instead of hard cording it, the metric hijacker should honour the highest content-type negotiated between the prom scraper and the applications.

**Comment by AyushSenapati** [comment]
The below hack made the metrics work. Till the fix is released, any one facing the same issue can give it a try:

```yaml
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: prom-metrics-fix
spec:
  selectors:
    - match:
        kuma.io/service: '*'
  conf:
    imports:
      - default-proxy
    modifications:
      - httpFilter:
          operation: addFirst
          match:
            name: envoy.filters.http.router
            listenerName: 'kuma:metrics:prometheus'
          value: |
            name: envoy.filters.http.lua
            typedConfig:
              '@type': type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
              inline_code: |
                function envoy_on_request(request_handle)
                  request_handle:headers():replace("accept", "text/plain; version=0.0.4; charset=utf-8")
                end
```

`NOTE`: The match name and listenerName are important, else it would replace accept header of all the requests, which may lead to many potential issues.
