### ISSUE TITLE
YAML fields order

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#679]
### Summary

kumactl produces such YAMLs

```
conf:
  abort:
    httpStatus: 500
    percentage: 50
  delay:
    percentage: 50
    value: 5s
  responseBandwidth:
    limit: 50 mbps
    percentage: 50
creationTime: 2018-07-17T16:05:36.995Z
destinations:
  - match:
      service: backend
mesh: default
modificationTime: 2018-07-17T16:05:36.995Z
name: fi1
sources:
  - match:
      service: frontend
      version: "0.1"
type: FaultInjection
```
(including creationTime/modifciationTime soon to be merged https://github.com/Kong/kuma/pull/677/files PR)

We want to see it like this
```
type: FaultInjection
name: fi1
mesh: default
creationTime: 2018-07-17T16:05:36.995Z
modificationTime: 2018-07-17T16:05:36.995Z
sources:
  - match:
      service: frontend
      version: "0.1"
destinations:
  - match:
      service: backend
conf:
  abort:
    httpStatus: 500
    percentage: 50
  delay:
    percentage: 50
    value: 5s
  responseBandwidth:
    limit: 50 mbps
    percentage: 50
```

This is fixed in JSON. Some time ago I did a quick check if this can be fixed and the conclusion was that the library for producing YAML first convert object to JSON then to map and then to YAML. Since map is unordered, the fields order is not preserved.

Current YAML library works on `json` tags on object. If we want to switch to different library we would need to add also `yaml` tags to objects generated from protobuf files.
