### ISSUE TITLE
TrafficMirror Policy

### ISSUE THREAD

**Issue by subnetmarco** [kumahq/kuma#680]
```yaml
type: TrafficMirror
name: mirror-1
mesh: default
sources:
  - match:
      service: backend
      version: 1
destinations:
  - match:
      service: redis
      version: 5
conf:
  - amount: 25
    destination:
      service: redis
      version: 6
  - amount: 10
    destination:
      service: redis
      version: 2
```
