### ISSUE TITLE
Mixed tcp and http protocol result in protocol errors

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#6825]
### What happened?

Steps to reproduce
1. Deploy kuma marketplace demo
2. Add second service
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    3001.service.kuma.io/protocol: tcp # <- notice that the first service has http here
  name: backend-v2
  namespace: kuma-demo
spec:
  ports:
  - name: api
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: kuma-demo-backend
```
3. Exec to container and execute requests
```
❯❯❯ kubectl exec -n kuma-demo kuma-demo-app-6787b4f7f5-qxjzz -ti -- sh
/ # while curl backend:3001; do echo "" && sleep 0.1; done
```
see that some of them fails with protocol error
```
Hello World! Marketplace with sales and reviews made with <3 by the OCTO team at Kong Inc.
Hello World! Marketplace with sales and reviews made with <3 by the OCTO team at Kong Inc.
upstream connect error or disconnect/reset before headers. reset reason: protocol error
upstream connect error or disconnect/reset before headers. reset reason: protocol error
Hello World! Marketplace with sales and reviews made with <3 by the OCTO team at Kong Inc.
upstream connect error or disconnect/reset before headers. reset reason: protocol error
Hello World! Marketplace with sales and reviews made with <3 by the OCTO team at Kong Inc.
Hello World! Marketplace with sales and reviews made with <3 by the OCTO team at Kong Inc.
```

**Comment by lukidzi** [comment]
@michaelbeaumont mentioned that configuring the protocol isn't straightforward. When multiple services point to the same address but with different protocols, the last one takes precedence. It seems odd to find the highest common protocol on the inbound side because the outbound configuration still relies on the protocol defined by the specific cluster. Not sure what is the best solution here. So far we are not doing any infer protocol on inbounds.

**Comment by lahabana** [comment]
> When multiple services point to the same address but with different protocols, the last one takes precedence.
@lukidzi could you show an example?

**Comment by lukidzi** [comment]
```
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: kuma-demo
  annotations:
    3001.service.kuma.io/protocol: "http"
spec:
  selector:
    app: kuma-demo-backend
  ports:
  - name: api
    port: 3001
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    3001.service.kuma.io/protocol: tcp # <- notice that the first service has http here
  name: backend-v2
  namespace: kuma-demo
spec:
  ports:
  - name: api
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: kuma-demo-backend
```
2nd service is going to be used.
