### ISSUE TITLE
TrafficRoute Default destination removal

### ISSUE THREAD

**Issue by adarsh-padhi** [kumahq/kuma#6858]
### Description

how to route to a service with a matching path .. I mean I just want the matching destination not the default destination
## scenario :
I want to route to service A if the matching path has some keywords , that's it
No default destination is required ..
Is it possible in trafficRoute policy ?
## for e.g.
```
apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  name: demo.kuma.svc.8000
spec:
  sources:
    - match:
        kuma.io/service: demo-app4_kuma-backend_svc_8083
  destinations:
    - match:
        kuma.io/service: demo_kuma_svc_8000
  conf:
    http:
      - match:
          path:
            regex: "robot"
        destination:
          kuma.io/service: something_default_svc_8000
    destination:
        kuma.io/service: demo_kuma_svc_8000
```
I don't want the last 2 lines of the code

**Comment by jakubdyszkiewicz** [comment]
> Triage: Have you tried MeshHTTPRoute https://kuma.io/docs/2.2.x/policies/meshhttproute/ ?

**Comment by adarsh-padhi** [comment]
does it will work with the external services ?

**Comment by adarsh-padhi** [comment]
so let me tell you my use case : 
I want to open GitHub.com as an external service and access 1 particular repository using it. so is this policy will help ? I tried with the meshHTTPRoute , I am getting some TLS error like

`
fatal: unable to access 'https://github.com/usr1/demo.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
`

**Comment by michaelbeaumont** [comment]
Like you mentioned on slack, you'd like the traffic to fail if it doesn't match the rule, correct? One way to do this I think is to set a non existent service as the default destination.

**Comment by michaelbeaumont** [comment]
@adarsh-padhi can you please include the ExternalService, the TrafficRoute and MeshHTTPRoute resources you're using?

**Comment by adarsh-padhi** [comment]
#### External service

```yaml
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata:
  name: github-com-443
spec:
  tags:
    kuma.io/service: github-com-443
    kuma.io/protocol: tcp
  networking:
    address: github.com:443
    tls: # optional
      enabled: false
```

#### TrafficRoute.yaml

``` yaml
apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  name: github.com.443.ext
spec:
  sources:
    - match:
        kuma.io/service: demo-app4_kuma-backend_svc_8083
  destinations:
    - match:
        kuma.io/service: github-com-443
  conf:
    http:
      - match:
          path:
            regex: "^((?!hello).)*$"
        destination:
          kuma.io/service: dummy_service_svc_8000
    destination:
        kuma.io/service: github-com-443
```

#### meshHTTPRoute.yaml


```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: github.com.443.ext
  namespace: kuma-system
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: MeshService
    name: demo-app4_kuma-backend_svc_8083
  to:
    - targetRef:
        kind: MeshService
        name: github-com-443
      rules:
        - matches:
            - path:
                type: Prefix
                value: /hello
          default:
            backendRefs:
              - kind: MeshService
                name: github-com-443
```

NOTE : The trafficRoute option is working for me . The regex which I used is to check `the repo doesn't contain hello word in the GitHub URL`

**Comment by michaelbeaumont** [comment]
OK, I'll close this issue then and also sure MeshHTTPRoute is working for ExternalService as well.

**Comment by adarsh-padhi** [comment]
No , MeshHTTPRoute is not working . Can you check the above policy if I have missed something

**Comment by michaelbeaumont** [comment]
@adarsh-padhi Hmm I can't get it to work with either route resource and this ExternalService. Are you sure your `/hello` requests are being blocked with `TrafficRoute`?  The reason it "shouldn't" work is that you seem to be consuming `github.com` over TLS (you're using `https://github.com` from your application) and so the mesh has no visibility into the content and can't do routing.

I think you'll need to [let Envoy handle TLS](https://kuma.io/docs/2.2.x/policies/external-services/#accessing-the-external-service):

```
---
apiVersion: kuma.io/v1alpha1
kind: ExternalService
metadata:
  name: github-com
mesh: default
spec:
  tags:
    kuma.io/service: github-com
    kuma.io/protocol: http
  networking:
    address: github.com:443
    tls:
      enabled: true

```

and consume using `http://`
