### ISSUE TITLE
Confusion with MeshHTTPRoute configuring listeners with httpConnectionManager for every outbound

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#6860]
### What happened?

I'm confused. Maybe it's not a bug, but a feature, but it makes my life harder trying to understand it.

There is this assumption which I couldn't find documented under any of extisting MADRs, that for the new policies (route-related ones), traffic as opposite of now, flow by default (currently, there has to be a `TrafficRoute` policy for the traffic to flow, for the new policies, there is expectation that it will flow, even when there is no policy). I think it comes from the GAMMA:
> When no HTTPRoute resources or AuthZ configuration are defined, all traffic should implicitly work - this is just how Kubernetes functions. When you create an HTTPRoute targeting a service as a parentRef you are replacing that implicit logic - not adding to it. Therefore, you may be reshaping or restricting traffic via an HTTPRoute configuration (which should be noted is distinct from disallowing traffic by AuthZ).
>
> ref. https://gateway-api.sigs.k8s.io/geps/gep-1426/#omitting-backendrefs

Our current behaviour is kinda odd though. Let's say for example we have 4 services:
```
internal{http}: client
internal{http}: server
internal{tcp}:  server2
external{http}: external-server
external{tcp}:  something-else
```
When the default `TrafficRoute` policy exists, but there is no `MeshHTTPRoute`s, `client`s xds listener configuration would look similar to (simplified):
```yaml
outbound:240.0.0.0:80{client}:
  filter: httpConnectionManager
outbound:240.0.0.1:80{server}:
  filter: httpConnectionManager
outbound:240.0.0.2:80{server2}:
  filter: tcpProxy
outbound:240.0.0.3:80{external-server}:
  filter: httpConnectionManager
outbound:240.0.0.4:80{something-else}:
  filter: tcpProxy
```
That's expected, right?
Now let's assume we want to redirect http traffic going from `client` to `server` to `external-server`, so we'll add `MeshHTTPRoute` similar to:
```yaml
type: MeshHTTPRoute
name: mhttpr
mesh: default
spec:
  targetRef:
    kind: MeshService
    name: client
  to:
  - targetRef:
      kind: MeshService
      name: server
    rules:
    - matches:
      - path:
          type: PathPrefix
          value: "/"
      default:
        backendRefs:
        - kind: MeshService
          name: external-server
```
So how our config changed?
```yaml
outbound:240.0.0.0:80{client}:
  filter: httpConnectionManager
outbound:240.0.0.1:80{server}:
  filter: httpConnectionManager
outbound:240.0.0.2:80{server2}:
  filter: httpConnectionManager
outbound:240.0.0.3:80{external-server}:
  filter: httpConnectionManager
outbound:240.0.0.4:80{something-else}:
  filter: httpConnectionManager
```
It looks like we bumped services `server2` and `something-else` from `tcp` to `http`, even if our policy didn't even touch them at all.
So what would happen if we would remove the default `TrafficRoute` now you might ask. The answer is: nothing. The config stays the same.

It makes my life with introducing `MeshTCPRoute` much harder.
