### ISSUE TITLE
cross zone meshTCPRoute doesn't work

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6989]
### What happened?

```
type: MeshTCPRoute
name: tcp-route-1
mesh: default
spec:
  targetRef:
    kind: MeshService
    name: demo-app_kuma-demo_svc_5000
  to:
    - targetRef:
        kind: MeshService
        name: redis_kuma-demo_svc_6379
      rules:
        - default:
            backendRefs:
              - kind: MeshServiceSubset
                name: redis_kuma-demo_svc_6379
                tags:
                  kuma.io/zone: east
                weight: 90
              - kind: MeshServiceSubset
                name: redis_kuma-demo_svc_6379
                tags:
                  kuma.io/zone: west
                weight: 10
```

- deploy MeshGatewayRoute

```
type: MeshGateway
mesh: default
name: edge-gateway
selectors:
  - match:
      kuma.io/service: edge-gateway
conf:
  listeners:
    - port: 8080
      protocol: HTTP
      tags:
        port: http/8080

type: MeshGatewayRoute
mesh: default
name: edge-gateway-route
selectors:
  - match:
      kuma.io/service: edge-gateway
      port: http/8080
conf:
  http:
    rules:
      - matches:
          - path:
              match: PREFIX
              value: /
        backends:
          - destination:
              kuma.io/service: demo-app_kuma-demo_svc_5000
```
