### ISSUE TITLE
ExternalServices don't seem to work when MTLS mode is set to PERMISSIVE

### ISSUE THREAD

**Issue by brentos** [kumahq/kuma#7140]
### What happened?

With the following ExternalService
```
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata:
  name: httpbin
spec:
  tags:
    kuma.io/service: httpbin
    kuma.io/protocol: http
  networking:
    address: httpbin.org:443
    tls: # optional
      enabled: true
```

with Zone Egress enabled and STRICT MTLS mode, I can successfully curl httpbin.mesh

with Zone Egress enabled and PERMISSIVE MTLS mode, curl fails as follows:
```
curl http://httpbin.mesh/anything
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection termination
```

I would expect ExternalServices to function with PERMISSIVE mode enabled + Zone Egress

**Comment by lahabana** [comment]
Can you show your mesh resource with each mTLS version?

**Comment by brentos** [comment]
only change between these is the MTLS mode:

```
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  mtls:
    enabledBackend: ca-1
    backends:
      - name: ca-1
        type: builtin
        dpCert:
          rotation:
            expiration: 1d
        conf:
          caCert:
            RSAbits: 2048
            expiration: 10y
        mode: PERMISSIVE
  metrics:
    enabledBackend: prometheus-1
    backends:
      - name: prometheus-1
        type: prometheus
        conf:
          path: /metrics
          port: 5670
          skipMTLS: true
          tags:
            kuma.io/service: dataplane-metrics
  networking:
    outbound:
      passthrough: false
  routing:
    zoneEgress: true
```

```
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  mtls:
    enabledBackend: ca-1
    backends:
      - name: ca-1
        type: builtin
        dpCert:
          rotation:
            expiration: 1d
        conf:
          caCert:
            RSAbits: 2048
            expiration: 10y
        mode: STRICT
  metrics:
    enabledBackend: prometheus-1
    backends:
      - name: prometheus-1
        type: prometheus
        conf:
          path: /metrics
          port: 5670
          skipMTLS: true
          tags:
            kuma.io/service: dataplane-metrics
  networking:
    outbound:
      passthrough: false
  routing:
    zoneEgress: true
```
