### ISSUE TITLE
Remove 'mesh' from Universal resource's primary key

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#7166]
### Description

Primary keys are different for resources on Universal and Kubernetes:
* Universal: (name, namespace, mesh, type)
* Kubernetes: (name, namespace, kind)

Potentially this can result in inconsistent state when Global on Universal and Zone on k8s:

* Global(Universal):
```yaml
type: MeshTrafficPermission
name: allow-all
mesh: mesh-1
spec: {}
---
type: MeshTrafficPermission
name: allow-all
mesh: mesh-2
spec: {}
```

* Zone(Kubernetes):
```yaml
kind: MeshTrafficPermission
metadata:
  name: allow-all
  namespace: kuma-system
  labels:
    kuma.io/mesh: mesh-1
spec: {}
```
MeshTrafficPermission from mesh-2 is not synced to Zone because there is already MeshTrafficPermission with a key `(allow-all, kuma-system, MeshTrafficPermission)`.

One of the solutions is to remove `mesh` from Universal's primary key and force users to have unique policy names across all meshes. It's not ideal, but at least Universal and Kubernetes will be consistent.
