### ISSUE TITLE
Allow configuring envoy's application log format for better integration with observability tooling

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#7214]
### Description

It would be beneficial to allow configuring envoy application logging format (probably json would be enough), which would allow better integration with observability tooling (like Datadog) 

---

ref. https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/application_logging#printing-logs-in-json-format
```yaml
application_log_config:
  log_format:
    json_format:
      Timestamp: "%Y-%m-%dT%T.%F"
      ThreadId: "%t"
      SourceLine: "%s:%#"
      Level: "%l"
      Message: "%j"
      FixedValue: "SomeFixedValue"
```
