### ISSUE TITLE
Implement Mirror part of MeshHTTPRoute

### ISSUE THREAD

**Issue by subnetmarco** [kumahq/kuma#724]
Mirror is part of request modification in the MeshTrafficRoute MADR: https://github.com/kumahq/kuma/blob/master/docs/madr/decisions/011-mesh-traffic-route.md#request-modification

This issue covers the implementation

### Old description

There is already an open issue https://github.com/Kong/kuma/issues/680 for TrafficMirror policy that allows to replicate traffic across multiple destinations, this is an alternative implementation that only allows one destination in the policy:

```yaml
apiVersion: kuma.io/v1alpha1
kind: TrafficMirror
mesh: default
metadata:
  namespace: default
  name: mirror-1
spec:
  sources:
    - match:
        service: backend
        version: 1
  destinations:
    - match:
        service: redis
        version: 2
  conf:
     percentage: 40
     destination:
       service: redis
       version: 3
```

And similar on Universal. Thoughts?
