### ISSUE TITLE
Specify Mesh via label on K8S

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#738]
### Summary

Right now all Kuma entities has explicit field called `mesh`. Here is an example of `TrafficPermission`
```
apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default # <- here
metadata:
  namespace: default
  name: permission-1
spec:
  sources:
    - match:
        service: backend
  destinations:
    - match:
        service: redis
        version: '5.0'
```

I'd like to start a discussion to change it so we specify mesh with label
```
apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
metadata:
  namespace: default
  name: permission-1
  labels:
    kuma.io/mesh: default
spec:
  sources:
    - match:
        service: backend
  destinations:
    - match:
        service: redis
        version: '5.0'

```

## Motivation
* Kubernetes for now does not support filtering for CRD fields. Right now we do a filtering in memory which causes problems with pagination and is a performance hit
* If you want to list resources by mesh, you cannot do it on K8S right now. With label, you would be able to do it
* It will be consistent across all the resources, even the ones that are not owned by Kuma. For example, we do it right now for K8S Secrets and if you want to change the mesh on your Pod.
* Slightly shorter syntax if we go with implicit `default` mesh when the label is not specified. On the other hand, slightly longer syntax if you want to explicitly specify the mesh.
* Possibility to run `kubectl delete trafficpermissions -l kuma.io/mesh=demo`

## Open questions
* Can mesh label be really implicit? If we want to list all resources that belong to a default mesh can we specify label selector like: `label does not exist OR it has value default`

This is a pretty big breaking change to our model therefore please keep the discussion and do not implement it until we reach an agreement.
