### ISSUE TITLE
MeshTrafficPermission: prometheus listener doesn't allow traffic with allow-all policy

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#7412]
### What happened?

When kuma uses the default `MeshTrafficPermission` that allows all the traffic, changes for RBAC are not applied to the `kuma:metrics:prometheus` listener. In this case, traffic from the scraper cannot reach the services endpoint.

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  namespace: kuma-system
  name: allow-all
spec:
  targetRef:
    kind: Mesh
  from:
    - targetRef:
        kind: Mesh
      default:
        action: Allow
```
`config_dump` of rbac `kuma:metrics:prometheus` listener when using `MeshTrafficPermission`
```yaml
        {
           "name": "envoy.filters.network.rbac",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC",
            "rules": {},
            "stat_prefix": "kuma_metrics_prometheus."
           }
          },
```

When we switch to `TrafficPermisson` traffic works. 
```yaml
apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  name: allow-all-traffic
spec:
  sources:
    - match:
        kuma.io/service: '*'
  destinations:
    - match:
        kuma.io/service: '*'
```

`config_dump` of rbac `kuma:metrics:prometheus` listener when using `TrafficPermission`

```yaml
        {
           "name": "envoy.filters.network.rbac",
           "typed_config": {
            "@type": "type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC",
            "rules": {
             "policies": {
              "allow-all-traffic": {
               "permissions": [
                {
                 "any": true
                }
               ],
               "principals": [
                {
                 "any": true
                }
               ]
              }
             }
            },
            "stat_prefix": "kuma_metrics_prometheus."
           }
          },
```
