### ISSUE TITLE
Add helm directory to dependabot updates

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#7657]
### Description

We depend on a few 3rd party images (.e.g: https://github.com/kumahq/kuma/pull/7656).

Dependabot supports updating versions in [helm charts](https://github.blog/changelog/2022-11-16-dependabot-version-updates-for-docker-image-tags-in-kubernetes-manifests/). It would be good to make sure this works for us.

A few things to check:

1. Do dependabot work with docker images in `values.yaml`.
2. If 1 is no what can we do?

**Comment by slonka** [comment]
according to https://github.com/dependabot/dependabot-core/pull/5738 - it should work with 

```yaml
foo:
  image:
    repository: sql/sql
    tag: 1.2.3
    registry: docker.io
```

or alternatively:

```yaml
foo:
  image:
    repository: sql/sql
    version: 1.2.3
```
