### ISSUE TITLE
validation on name for `targetRef` is too weak

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#7912]
### What happened?

In:

https://github.com/kumahq/kuma/blob/29d7e8159a76b258020f6c61a3f88328aaa3102e/pkg/plugins/policies/core/matchers/validators/validator.go#L26-L44

There's no validation on the value of name, tags, mesh.

For example someone did:

```yaml
targetRef:
  kind: MeshService
  name: '*'
```

because they were used to old policies.
