### ISSUE TITLE
TrafficRoute doesn't set LB type to LeastRequest when `choiceCount` is not specified

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#7932]
### What happened?

The following policy doesn't change the LB type to `LEAST_REQUEST` and there are neither validation errors or errors in logs:
```yaml
type: TrafficRoute
name: route-1
mesh: mesh-1
sources:
  - match:
      kuma.io/service: 'svc-a'
destinations:
  - match:
      kuma.io/service: 'svc-b'
conf:
  loadBalancer:
    leastRequest: {}
  destination:
    kuma.io/service: 'svc-b'
```

But if `choiceCount` is specified then it works:

```yaml
type: TrafficRoute
name: route-1
mesh: mesh-1
sources:
  - match:
      kuma.io/service: 'svc-a'
destinations:
  - match:
      kuma.io/service: 'svc-b'
conf:
  loadBalancer:
    leastRequest:
      choiceCount: 2
  destination:
    kuma.io/service: 'svc-b'
```

The behavior is diverging from the docs:
> The number of random healthy hosts from which the host with the fewest active requests will be chosen. **Defaults to 2** so that we perform two-choice selection if the field is not set.
