### ISSUE TITLE
Support probes on Kubernetes

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#795]
### Summary

When mTLS on, we assume that all the traffic to service has to be encrypted so it breaks any readinessProbe and livenessProbe for the application.

Ideas:
* With L7 TrafficPermission we can enable `/health` endpoints
* But TCP probes are still valid use case that we need to support. It depends on which parts of K8S sends healthchecks, but we may be able to filter by source IP+Port (similar thing what we've done with Prometheus mTLS endpoint)

### Acceptance criteria
I can deploy application in mTLS Mesh with `readinessProbe` and `livenessProbe`

**Comment by carlosjgp** [comment]
Kubernetes uses an easy to identify user agent that could be ignored
https://github.com/kubernetes/kubernetes/pull/47729/files#diff-ca8ccba349ee7f2f0cddbb8305fc86a1R78

**Comment by nickolaev** [comment]
> Kubernetes uses an easy to identify user agent that could be ignored
> https://github.com/kubernetes/kubernetes/pull/47729/files#diff-ca8ccba349ee7f2f0cddbb8305fc86a1R78

But mTLS is on the TCP socket level, one can't get to the headers before decrypting the message.

**Comment by nickolaev** [comment]
Possible workaround:
Using `liveness command`: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command

**Comment by jakubdyszkiewicz** [comment]
L7 Traffic permissions probably won't solve the problem because mTLS is applied on L4 even before RBAC is applied.

Another option would be to enrich Dataplane model with health check definition, then open extra port without mTLS that serves only this endpoint (it's similar to prometheus endpoint that exposes only one endpoint from Admin API). Then we can override healthcheck in pod to this port.

Additional advantage that @nickolaev pointed out is that we can reuse it on universal.

**Comment by jakubdyszkiewicz** [comment]
# Proposal

Given a dataplane

```
spec:
  networking:
    address: 192.168.0.1
    inbound:
      - port: 8080
        tags:
          app: example
          kuma.io/protocol: tcp
          kuma.io/service: example_demo_svc_80
      - port: 8081
        tags:
          app: example
          kuma.io/protocol: http
          kuma.io/service: example_demo_svc_81
```

and a liveness probe

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    image: k8s.gcr.io/liveness
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
```

We can enrich dataplane model with `healthChecks`

```
spec:
  networking:
    address: 192.168.0.1
    inbound:
      - port: 8080
        tags:
          app: example
          kuma.io/protocol: tcp
          kuma.io/service: example_demo_svc_80
      - port: 8081
        tags:
          app: example
          kuma.io/protocol: http
          kuma.io/service: example_demo_svc_81
  healthChecks:
    port: 9000
    endpoints:
    - inboundPort: 8080
      path: /healthz
    - inboundPort: 8081
      path: /healthz
```

As a result, we open a new inbound listener on `192.168.0.1:9000` that can handle two endpoints:
* `192.168.0.1:9000/8080/healthz` which forwards a request to inbound with port 8080 on path `/healthz`
* `192.168.0.1:9000/8081/healthz` which forwards a request to inbound with port 8081 on path `/healthz`

`192.168.0.1:9000` does not require mTLS even when mTLS is on.

Of course, on K8S we autogenerate `Dataplane` model from Pod so we can scan through containers and their `livenessProbes` to generate `healthChecks` part.
When we inject Kuma DP to the container we can override `livenessProbes` on the Pod with our endpoints.

What do you think?
