### ISSUE TITLE
CrossMesh MeshGateway listener does not work when MeshGatewayRoute hostnames are set

### ISSUE THREAD

**Issue by ttreptow** [kumahq/kuma#8076]
### What happened?

I have a MeshGateway with a listener set up with no hostname set (defaults to '*') and crossMesh enabled. I'm trying to add MeshGatewayRoutes that have hostnames specified.

When the below configuration is set, the gateway proxy throws errors like

> [2023-10-19 21:15:58.269][26][warning][config] [source/extensions/config_subscription/grpc/grpc_subscription_impl.cc:128] gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) vault:HTTP:8080: error adding listener '10.200.12.80:8080': filter chain '' has the same matching rules defined as ''

Looking at the generated Envoy config, I see that it is trying to set two identical filter chains for that listener.

Digging into the code, I think what is happening is that [RedistributeWildcardRoutes](https://github.com/kumahq/kuma/blob/6f86847aee5d50fd912aeaaa8f5470427f127676/pkg/plugins/runtime/gateway/generator.go#L429) is creating two host name configs, one for the route's host name (assuming you have one route with one hostname set) and one for the wildcard. 
The problem with having multiple hosts is that crossMesh enabled sets the protocol to HTTPS with no TLS mode set, then in [configureTls](https://github.com/kumahq/kuma/blob/6f86847aee5d50fd912aeaaa8f5470427f127676/pkg/plugins/runtime/gateway/filter_chain_generator.go#L439C33-L439C33) the switch block never sets `envoy_listeners.MatchServerNames(hostnames...),` as it does for other https modes.

The net effect is that the filter chains have identical matching blocks (since they are missing hostname matching) which causes the error.

MeshGateway:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
mesh: mesh1
metadata:
  name: cross-mesh
  namespace: kuma
spec:
  conf:
    listeners:
      - crossMesh: true
        port: 8080
        protocol: HTTP
        tags:
          some: tag
```

Note that the hostname is not set and crossMesh is `true`

MeshGatewayRoute:
```yaml
piVersion: kuma.io/v1alpha1
kind: MeshGatewayRoute
mesh: mesh1
metadata:
  name: test
  namespace: kuma
spec:
  conf:
    http:
      hostnames:
      - myservice.external.mesh
      rules:
      - backends:
        - destination:
            kuma.io/service: test_test_svc_8000
        matches:
        - path:
            match: PREFIX
            value: /
  selectors:
  - match:
      kuma.io/service: edge-gateway
      some: tag
```

MeshGatewayInstance:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: edge-gateway
  namespace: gateway
spec:
  replicas: 1
  serviceType: ClusterIP
  tags:
    kuma.io/service: edge-gateway
```

The namespace is tagged with `kuma.io/mesh: mesh1` and the gateway dataplace does seem to get the correct mesh
