### ISSUE TITLE
When setting a CircuitBreaker, it only applies on outbound cluster

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#8086]
### What happened?

Very similiar to https://github.com/kumahq/kuma/issues/3934 but for CircuitBreakers. When applying a circuitbreaker with a connection limit of e.g. 2000, it gets applied on the outbound cluster of the source, but the inbound localhost cluster on the destination remains unchanged (default), essentially capping at 1024 (for max connections, this likely also applies in other places / for other fields). Right now the fix is a proxy template (in the case below, it's a redis I'm patching):
```
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  name: redis-limit
spec:
  selectors:
    - match:
        kuma.io/service: '*'
  conf:
    imports:
      - default-proxy
    modifications:
      - cluster:
          operation: patch
          match:
            name: localhost:6379
            origin: inbound
          value: |
            circuitBreakers:
              thresholds:
                - maxConnections: 2000
                  maxPendingRequests: 2000
                  maxRequests: 2000
```
