### ISSUE TITLE
Prometheus app metrics discovery on Universal

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#809]
### Summary

On Kubernetes when a user wants to expose app metrics, they can use `prometheus.io/*` annotations on either Deployment on Service.

On Universal, Kuma is used instead of Service Discovery system, so it should help Prometheus discovery app metrics.

Idea:
```
metrics:
  backends:
  - name: prom-1
    type: prometheus
    conf:
      appMetrics:
        port: 5671 # 5671 by default
        path: /metrics # /metrics by default
        appPort: 8080
        appPath: /metrics # /metrics by default
```
This can be enabled on Mesh (if there is a convention that app on each VM is exposed in the same port) but also available to set on Dataplane.

This information can be then propagated to `kuma-prometheus-sd`
