### ISSUE TITLE
Using policy name with "." causes hash to be inserted in the wrong place on the zone

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#8167]
### What happened?

When creating a policy like this:

```
type: MeshAccessLog
name: valid.name
mesh: default
spec:
  targetRef:
    kind: MeshServiceSubset
    name: frontend
    tags:
      version: canary
  to:
    - targetRef:
        kind: MeshService
        name: backend
      default:
        backends:
          - type: File
            file:
              path: /tmp/access.log
```

causes the zone to get 

```
name: valid-bv979f8v7wfw4v54.name
```

which is not right
