### ISSUE TITLE
Add userDefinedVolumes and userDefinedVolumeMounts to kuma helm charts

### ISSUE THREAD

**Issue by ashman1984** [kumahq/kuma#8222]
### Description

The Kong Gateway helm chart supports [these](https://github.com/Kong/charts/blob/main/charts/kong/values.yaml#L50-L56) (userDefinedVolumes & userDefinedVolumeMounts) options and they would be handy if these were available to mount volumes to the CP in mesh.

This will enable the use of Secrets Store CSI Drivers for mounting (License) secrets from Azure Key Vault and the like.

I did some testing by adding the following to the cp-deployment.yaml file:

```
volumes:
{{- if .Values.userDefinedVolumes }}
{{- .Values.userDefinedVolumes | toYaml | nindent 8 }}
{{- end }}
```
and
```
volumeMounts:
{{- if .Values.userDefinedVolumeMounts }}
{{- .Values.userDefinedVolumeMounts | toYaml | nindent 12 }}
{{- end }}
```

Then defined the options at the root in my values file:
```
userDefinedVolumes:
  - name: secrets-store-kong-license
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "azure-kv-kong-license"

userDefinedVolumeMounts:
  - name: secrets-store-kong-license
    mountPath: "/mnt/secrets-store"
    readOnly: true
```

I did attempt to put them under `.Values.controlPlane.userDefinedVolumes` and `.Values.controlPlane.userDefinesVolumeMounts` however my knowledge of templating is minimal and this did not work as expected.

The solution as a whole did appear to work when deploying a standalone CP however I was not sure on how or where these options should sit in the values file or what standard should be followed.

Should userDefinedVolumeMounts for the kuma-sidecar be a consideration?
Does that take away from the containerpatches?

Thanks
