### ISSUE TITLE
MeshAccessLog with tcp reporting doesn't work with TrafficPermission but with MeshTrafficPermisson

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#8296]
### What happened?

The client reported that when creating MeshAccessLog to report logs to TCP backend it didn't work but a normal command from the container reported logs properly. Also, the user said that after removing TrafficPermisson and adding MeshTrafficPermisson it starts to work. There should be no correlation and we need more details.

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshAccessLog
metadata:
  annotations:
kubectl.kubernetes.io/last-applied-configuration: | ...
  labels:
    argocd.argoproj.io/instance: kuma-root
    kuma.io/mesh: default
  name: default
  namespace: kuma-system
spec:
  from:
  - default:
      backends:
      - tcp:
          address: datadog-kuma-tcp.datadog.svc.cluster.local:10518
          format:
            json:
            - key: date
              value: '%START_TIME%'
            - key: kuma_source_service
              value: '%KUMA_SOURCE_SERVICE%'
            - key: kuma_mesh
              value: '%KUMA_MESH%'
            - key: kuma_source_address_without_port
              value: '%KUMA_SOURCE_ADDRESS_WITHOUT_PORT%'
            - key: kuma_source_service
              value: '%KUMA_SOURCE_SERVICE%'
            - key: upstream_host
              value: '%UPSTREAM_HOST%'
            - key: kuma_destination_service
              value: '%KUMA_DESTINATION_SERVICE%'
            - key: duration
              value: '%DURATION%'
            - key: bytes_sent
              value: '%BYTES_SENT%'
            - key: bytes_received
              value: '%BYTES_RECEIVED%'
            - key: req.method
              value: '%REQ(:METHOD)%'
            - key: req.path
              value: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
            - key: protocol
              value: '%PROTOCOL%'
            - key: response.code
              value: '%RESPONSE_CODE%'
            - key: response.flags
              value: '%RESPONSE_FLAGS%'
            - key: upstream_servuce_time
              value: '%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%'
            - key: req.x_forwarded_for
              value: '%REQ(X-FORWARDED-FOR)%'
            - key: req.useragent
              value: '%REQ(USER-AGENT)%'
            - key: req.x_request_id
              value: '%REQ(X-REQUEST-ID)%'
            - key: kuma_traffic_direction
              value: '%KUMA_TRAFFIC_DIRECTION%'
            type: Json
        type: Tcp
    targetRef:
      kind: Mesh
  targetRef:
    kind: Mesh
  to:
  - default:
      backends:
      - tcp:
          address: datadog-kuma-tcp.datadog.svc.cluster.local:10518
          format:
            json:
            - key: date
              value: '%START_TIME%'
            - key: kuma_source_service
              value: '%KUMA_SOURCE_SERVICE%'
            - key: kuma_mesh
              value: '%KUMA_MESH%'
            - key: kuma_source_address_without_port
              value: '%KUMA_SOURCE_ADDRESS_WITHOUT_PORT%'
            - key: kuma_source_service
              value: '%KUMA_SOURCE_SERVICE%'
            - key: upstream_host
              value: '%UPSTREAM_HOST%'
            - key: kuma_destination_service
              value: '%KUMA_DESTINATION_SERVICE%'
            - key: duration
              value: '%DURATION%'
            - key: bytes_sent
              value: '%BYTES_SENT%'
            - key: bytes_received
              value: '%BYTES_RECEIVED%'
            - key: req.method
              value: '%REQ(:METHOD)%'
            - key: req.path
              value: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
            - key: protocol
              value: '%PROTOCOL%'
            - key: response.code
              value: '%RESPONSE_CODE%'
            - key: response.flags
              value: '%RESPONSE_FLAGS%'
            - key: upstream_servuce_time
              value: '%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%'
            - key: req.x_forwarded_for
              value: '%REQ(X-FORWARDED-FOR)%'
            - key: req.useragent
              value: '%REQ(USER-AGENT)%'
            - key: req.x_request_id
              value: '%REQ(X-REQUEST-ID)%'
            - key: kuma_traffic_direction
              value: '%KUMA_TRAFFIC_DIRECTION%'
            type: Json
        type: Tcp
    targetRef:
      kind: Mesh
```

Kuma 2.4.3
Datadog not defined as ExternalService
Datadog agent outside of the mesh

https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1699437083998349
