### ISSUE TITLE
Mesh Gateway is not taken into account with Locality aware mesh load balancing strategy

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#8303]
### What happened?

I connected 2 zones to Mink. I deployed counter demo in both clusters. I have a gateway in one zone. I applied this strategy
```
type: MeshLoadBalancingStrategy
name: mlb-1
mesh: default
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: Mesh
      default:
        localityAwareness:
          localZone:
            affinityTags: []
          crossZone:
            failover:
              - to:
                  type: Only
                  zones: ["gcp"]
            failoverThreshold:
              percentage: 50
```

and demo app from both zones have priority 0. I expect the request to stay in local zone.
