### ISSUE TITLE
Consider changing validation message “$field required in body”

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma#8316]
### Description

While applying policies, we’ve seen a "$field required in body" validation error message while forgetting to set a field in an object:

```yaml
field:
  type: value
  # `zones: []` was missing here
```

This message is a little weird when it occurs in this context. Can we somehow change this to be more clear?
