### ISSUE TITLE
Improve `AllowWithShadowDeny` (or/and RBAC in general)

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#8459]
### Description

Right now `AllowWithShadowDeny` is not very useful due to the following:
- ~RBAC filter being applied on the L4 level means that counter is only bumped on new connections, it's a bit hard to correlate a policy change to stats~
- we don't have docs on how to interpret `rbac.shadow_allowed` and we bump that metric
- no RBAC stats in our dashboards
- we don't use [access_log_hint](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/rbac/v3/rbac.proto) which could make it easier to inspect interesting requests

Is this scenario possible:
- I start with `AllowWithShadowDeny` on `Mesh` to see every service that consumes my API. After a week I add some of them to `Allow`. Can I exclude them from `AllowWithShadowDeny`? Something like:

```
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  name: allow-orders
  namespace: kuma-demo
  labels:
    kuma.io/mesh: default
spec:
  targetRef:
    kind: Dataplane
    labels:
      app: payments
  from:
  - targetRef:
      kind: MeshSubset
      tags:
        kuma.io/service: orders
    default:
      action: Allow
  - targetRef:
      kind: MeshSubset
      tags:
        kuma.io/service: !orders
    default:
      action: AllowWithShadowDeny
```
