### ISSUE TITLE
Rule merging alghoritm is not sorting lexographically on MeshTrafficPermission

### ISSUE THREAD

**Issue by samm-git** [kumahq/kuma#8484]
### What happened?

My intention is to create a `MeshTrafficPermission` set of rules that will allow connectivity from some services and ShadowDeny (or Deny) everything else. 

To achieve that i did a 2 `MeshTrafficPermission` objects, both on  `MeshSubset` targetRef level.

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  labels:
    kuma.io/mesh: default
  name: default-demo-app
  namespace: kuma-system
spec:
  targetRef:
    kind: MeshSubset
    tags:
      k8s.kuma.io/service-name: demo-app
  from:
    - default:
        action: Allow
      targetRef:
        kind: MeshSubset
        tags:
          app.kubernetes.io/name: ui
    - default:
        action: Allow
      targetRef:
        kind: MeshSubset
        tags:
          app.kubernetes.io/name: service-order
    - default:
        action: Allow
      targetRef:
        kind: MeshSubset
        tags:
          app.kubernetes.io/name: service-payment
---

apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  labels:
    kuma.io/mesh: default
  name: default-demo-app-b
  namespace: kuma-system
spec:
  targetRef:
    kind: MeshSubset
    tags:
      k8s.kuma.io/service-name: demo-app
  from:
    - default:
        action: Deny
      targetRef:
        kind: Mesh
```

This setup works fine if naming is like `myrule` for allow set and `myrule-a` for denyset. I see in UI that rules are applied in correct order:
<img width="1216" alt="Screenshot 2023-11-28 at 15 54 03" src="https://github.com/kumahq/kuma/assets/1388875/09bb4783-6c39-4c7c-9552-d70427fa6b13">

My tests also shows that traffic works as expected

However, when I try to use names like `rule-a` and `rule-b` order is opposite to expected and tests also failing.

<img width="1176" alt="Screenshot 2023-11-28 at 15 56 25" src="https://github.com/kumahq/kuma/assets/1388875/bc5e1f66-1112-4d0a-8c3a-425d778ec233">

I am not sure how sorting is working, but looks like that not according to doc which state that `2. At the same level we use lexicographic order on name`.

**Comment by lahabana** [comment]
I indeed see the same problem by writing a simple test.

I you want I made it work this way with a single policy:

```yaml
# The first entry in from is then overridden by the following ones
type: MeshTrafficPermission
mesh: default
name: default-demo-app
spec:
  targetRef:
    kind: MeshSubset
    tags:
      k8s.kuma.io/service-name: demo-app
  from:
    - default:
        action: Deny
      targetRef:
        kind: Mesh
    - default:
        action: Allow
      targetRef:
        kind: MeshSubset
        tags:
          app.kubernetes.io/name: ui
    - default:
        action: Allow
      targetRef:
        kind: MeshSubset
        tags:
          app.kubernetes.io/name: service-order
    - default:
        action: Allow
      targetRef:
        kind: MeshSubset
        tags:
          app.kubernetes.io/name: service-payment
```

Give me the rules:

```yaml
Rules:
  127.0.0.1:80:
    - Conf:
        action: Allow
      Origin:
        - mesh: default
          name: default-demo-app
          type: MeshTrafficPermission
      Subset:
        - Key: app.kubernetes.io/name
          Not: false
          Value: ui
    - Conf:
        action: Allow
      Origin:
        - mesh: default
          name: default-demo-app
          type: MeshTrafficPermission
      Subset:
        - Key: app.kubernetes.io/name
          Not: false
          Value: service-payment
    - Conf:
        action: Allow
      Origin:
        - mesh: default
          name: default-demo-app
          type: MeshTrafficPermission
      Subset:
        - Key: app.kubernetes.io/name
          Not: false
          Value: service-order
    - Conf:
        action: Deny
      Origin:
        - mesh: default
          name: default-demo-app
          type: MeshTrafficPermission
      Subset:
        - Key: app.kubernetes.io/name
          Not: true
          Value: service-order
        - Key: app.kubernetes.io/name
          Not: true
          Value: service-payment
        - Key: app.kubernetes.io/name
          Not: true
          Value: ui
```

I think this is what you are trying to do: "Deny everyone except these 3 apps"
