### ISSUE TITLE
Change of mesh in ExternalService doesn't change it's ownerReference 

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#8721]
### What happened?

1. Create `ExternalService` 
```yaml
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata:
  name: httpbin
spec:
  tags:
    kuma.io/service: httpbin
    kuma.io/protocol: http 
  networking:
    address: httpbin.org:443
```
2. Create other mesh with different name
3. Create the same `ExternalService` but for other mesh
```yaml
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: mesh-1
metadata:
  name: httpbin
spec:
  tags:
    kuma.io/service: httpbin
    kuma.io/protocol: http 
  networking:
    address: httpbin.org:443
```
4. Check the `ExternalService` object you can notice that ownerReference points to the old mesh
<img width="1060" alt="image" src="https://github.com/kumahq/kuma/assets/13002762/21c61964-9768-4127-8332-fe824eb2512d">
