### ISSUE TITLE
MeshAccessLog fails on MeshGateway

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#8875]
### What happened?

```
2024-01-16T18:06:45.739Z	ERROR	xds-server.dataplane-sync-watchdog	OnTick() failed	{"dataplaneKey": {"Mesh":"default","Name":"edge-gateway-c64564fdf-6cd46.microservice-mesh"}, "error": "runtime error: invalid memory address or nil pointer dereference", "errorVerbose": "runtime error: invalid memory address or nil pointer dereference\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick.func1\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/util/watchdog/watchdog.go:62\nruntime.gopanic\n\truntime/panic.go:914\nruntime.panicmem\n\truntime/panic.go:261\nruntime.sigpanic\n\truntime/signal_unix.go:861\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshaccesslog/plugin/v1alpha1.configureGatewayListener\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go:294\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshaccesslog/plugin/v1alpha1.applyToGateway\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go:194\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshaccesslog/plugin/v1alpha1.plugin.Apply\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go:58\ngithub.com/kumahq/kuma/pkg/plugins/policies/core/generator.generator.Generate\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/plugins/policies/core/generator/generator.go:23\ngithub.com/kumahq/kuma/pkg/xds/generator/core.CompositeResourceGenerator.Generate\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/xds/generator/core/resource_generator.go:22\ngithub.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateProfileSource).Generate\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/xds/generator/proxy_template.go:76\ngithub.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateGenerator).Generate\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/xds/generator/proxy_template.go:28\ngithub.com/kumahq/kuma/pkg/xds/server/v3.(*TemplateSnapshotGenerator).GenerateSnapshot\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/xds/server/v3/reconcile.go:168\ngithub.com/kumahq/kuma/pkg/xds/server/v3.(*reconciler).Reconcile\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/xds/server/v3/reconcile.go:55\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncDataplane\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/xds/sync/dataplane_watchdog.go:148\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).Sync\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/xds/sync/dataplane_watchdog.go:79\ngithub.com/kumahq/kuma/pkg/xds/sync.(*dataplaneWatchdogFactory).New.func2\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/xds/sync/dataplane_watchdog_factory.go:43\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/util/watchdog/watchdog.go:70\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start\n\tgithub.com/kumahq/kuma@v0.0.0-20240116073830-16213ffe9057/pkg/util/watchdog/watchdog.go:40\nruntime.goexit\n\truntime/asm_amd64.s:1650"}
```

Conf:

```
type: MeshAccessLog
name: otel
mesh: default
spec:
  targetRef:
    kind: Mesh
  from:
    - targetRef:
        kind: Mesh
      default:
        backends:
          - type: OpenTelemetry
            openTelemetry:
              endpoint: otel-collector.observability.svc:4317
```

```
type: MeshGateway
mesh: default
name: edge-gateway
selectors:
  - match:
      kuma.io/service: edge-gateway
conf:
  listeners:
    - port: 8080
      protocol: HTTP
```
