### ISSUE TITLE
Gateway cluster has a hash even though there's no subset

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#8876]
### What happened?

If I look at the clusters;

```
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::cx_active::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::cx_connect_fail::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::cx_total::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::rq_active::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::rq_error::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::rq_success::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::rq_timeout::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::rq_total::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::hostname::
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::health_flags::healthy
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::weight::2
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::region::
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::zone::europe-west
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::sub_zone::
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::canary::false
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::priority::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::success_rate::-1
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::local_origin_success_rate::-1
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::cx_active::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::cx_connect_fail::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::cx_total::1
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::rq_active::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::rq_error::1
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::rq_success::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::rq_timeout::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::rq_total::1
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::hostname::
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::health_flags::healthy
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::weight::2
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::region::
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::zone::us-east
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::sub_zone::
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::canary::false
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::priority::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::success_rate::-1
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::local_origin_success_rate::-1
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::cx_active::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::cx_connect_fail::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::cx_total::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::rq_active::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::rq_error::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::rq_success::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::rq_timeout::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::rq_total::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::hostname::
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::health_flags::healthy
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::weight::2
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::region::
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::zone::us-east
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::sub_zone::
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::canary::false
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::priority::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::success_rate::-1
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::local_origin_success_rate::-1
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::cx_active::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::cx_connect_fail::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::cx_total::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::rq_active::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::rq_error::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::rq_success::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::rq_timeout::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::rq_total::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::hostname::
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::health_flags::healthy
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::weight::2
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::region::
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::zone::us-west
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::sub_zone::
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::canary::false
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::priority::0
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::success_rate::-1
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::local_origin_success_rate::-1
```

With this conf:

```yaml
type: MeshHTTPRoute
mesh: default
name: api-play-000
spec:
  targetRef:
    kind: MeshGateway
    name: edge-gateway
  to:
    - targetRef:
        kind: Mesh
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          default:
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /api/dynamic/microservice_mesh/
            backendRefs:
              - kind: MeshService
                name: api-play-000_microservice-mesh_svc_8080
---
type: MeshHTTPRoute
mesh: default
name: api-play-004
spec:
  targetRef:
    kind: MeshGateway
    name: edge-gateway
  to:
    - targetRef:
        kind: Mesh
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /other
          default:
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /api/dynamic/microservice_mesh/
            backendRefs:
              - kind: MeshService
                name: api-play-004_microservice-mesh_svc_8080
```

If I look at a regular dataplane there's no suffix:

```
api-play-000_microservice-mesh_svc_8080::34.78.216.155:10001::cx_active::0
api-play-000_microservice-mesh_svc_8080::34.78.216.155:10001::cx_connect_fail::0
api-play-000_microservice-mesh_svc_8080::34.78.216.155:10001::cx_total::0
api-play-000_microservice-mesh_svc_8080::34.78.216.155:10001::rq_active::0
api-play-000_microservice-mesh_svc_8080::34.78.216.155:10001::rq_error::0
api-play-000_microservice-mesh_svc_8080::34.78.216.155:10001::rq_success::0
api-play-000_microservice-mesh_svc_8080::34.78.216.155:10001::rq_timeout::0
```

How come on gateways when no subset is selected the cluster name is not just: `api-play-000` ?
