### ISSUE TITLE
MeshLocalityAwareLoadBalancing doesn't seem to work on gateways

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#8877]
### What happened?

With config:

```yaml
type: MeshLoadBalancingStrategy
name: no-failover
mesh: default
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: Mesh
      default:
        localityAwareness:
          crossZone:
            failover:
              - to:
                  type: None # Disable locality aware load balancing
 ```
 
 On a regular dataplane we can see there are no ingress in the endpoints iof the cluster:
 
 ```
api-play-000_microservice-mesh_svc_8080::10.44.0.10:8080::zone::us-east
api-play-000_microservice-mesh_svc_8080::10.44.1.15:8080::zone::us-east
```

However for a gateway:

```
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.78.216.155:10001::zone::europe-west
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.0.10:8080::zone::us-east
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::10.44.1.15:8080::zone::us-east
api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e::34.145.71.108:10001::zone::us-west
```

Could it be related to: 

- #8876
