### ISSUE TITLE
Overlapping route path has 301 redirect behaviour

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#8878]
### What happened?

With:

```yaml
type: MeshHTTPRoute
mesh: default
name: api-play-000
spec:
  targetRef:
    kind: MeshGateway
    name: edge-gateway
  to:
    - targetRef:
        kind: Mesh
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          default:
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /api/dynamic/microservice_mesh
            backendRefs:
              - kind: MeshService
                name: api-play-000_microservice-mesh_svc_8080
---
type: MeshHTTPRoute
mesh: default
name: api-play-004
spec:
  targetRef:
    kind: MeshGateway
    name: edge-gateway
  to:
    - targetRef:
        kind: Mesh
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /other
          default:
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /api/dynamic/microservice_mesh
            backendRefs:
              - kind: MeshService
                name: api-play-004_microservice-mesh_svc_8080
```

I would expect this to work with `/other` being the first rule that matches.
It works for the `/other` rule but it doesn't with: `/` I get:

```
➜  mesh-localityaware git:(main) ✗ curl -v http://34.148.44.60:8080/
*   Trying 34.148.44.60:8080...
* Connected to 34.148.44.60 (34.148.44.60) port 8080
> GET / HTTP/1.1
> Host: 34.148.44.60:8080
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< content-type: text/html; charset=utf-8
< location: /api/dynamic/microservice_mesh
< date: Tue, 16 Jan 2024 21:31:13 GMT
< content-length: 65
< x-envoy-upstream-service-time: 373
< server: Kuma Gateway
< vary: Accept-Encoding
<
<a href="/api/dynamic/microservice_mesh">Moved Permanently</a>.
```

If I change `/` to `/main` (or even `/o`) it works

Here are the routes XDS config:

```json
{
      "dynamicRouteConfigs": [
        {
          "versionInfo": "8cc75c05-e32e-496a-b2eb-4691195f6a1c",
          "routeConfig": {
            "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
            "name": "edge-gateway-x7d7z4729b7688d4:HTTP:8080",
            "virtualHosts": [
              {
                "name": "*",
                "domains": [
                  "*"
                ],
                "routes": [
                  {
                    "match": {
                      "path": "/other"
                    },
                    "route": {
                      "weightedClusters": {
                        "clusters": [
                          {
                            "name": "api-play-004_microservice-mesh_svc_8080-68d84729aaa9cad5",
                            "weight": 1,
                            "requestHeadersToAdd": [
                              {
                                "header": {
                                  "key": "x-kuma-tags",
                                  "value": "&kuma.io/service=edge-gateway&&kuma.io/zone=us-east&"
                                }
                              }
                            ]
                          }
                        ]
                      },
                      "clusterNotFoundResponseCode": "INTERNAL_SERVER_ERROR",
                      "regexRewrite": {
                        "pattern": {
                          "regex": ".*"
                        },
                        "substitution": "/api/dynamic/microservice_mesh"
                      },
                      "idleTimeout": "5s"
                    }
                  },
                  {
                    "match": {
                      "prefix": "/other/"
                    },
                    "route": {
                      "weightedClusters": {
                        "clusters": [
                          {
                            "name": "api-play-004_microservice-mesh_svc_8080-68d84729aaa9cad5",
                            "weight": 1,
                            "requestHeadersToAdd": [
                              {
                                "header": {
                                  "key": "x-kuma-tags",
                                  "value": "&kuma.io/service=edge-gateway&&kuma.io/zone=us-east&"
                                }
                              }
                            ]
                          }
                        ]
                      },
                      "clusterNotFoundResponseCode": "INTERNAL_SERVER_ERROR",
                      "prefixRewrite": "/api/dynamic/microservice_mesh/",
                      "idleTimeout": "5s"
                    }
                  },
                  {
                    "match": {
                      "prefix": "/"
                    },
                    "route": {
                      "weightedClusters": {
                        "clusters": [
                          {
                            "name": "api-play-000_microservice-mesh_svc_8080-0eee2d145d492a4e",
                            "weight": 1,
                            "requestHeadersToAdd": [
                              {
                                "header": {
                                  "key": "x-kuma-tags",
                                  "value": "&kuma.io/service=edge-gateway&&kuma.io/zone=us-east&"
                                }
                              }
                            ]
                          }
                        ]
                      },
                      "clusterNotFoundResponseCode": "INTERNAL_SERVER_ERROR",
                      "prefixRewrite": "/api/dynamic/microservice_mesh/",
                      "idleTimeout": "5s"
                    }
                  }
                ]
              }
            ],
            "requestHeadersToRemove": [
              "x-kuma-tags"
            ],
            "validateClusters": false,
            "ignorePortInHostMatching": true
          }
}
```

**Comment by michaelbeaumont** [comment]
@lahabana curious if this works with MeshGatewayRoute

**Comment by lahabana** [comment]
I reproduced this with the following k8s manifest:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: microservice-mesh
  labels:
    kuma.io/sidecar-injection: enabled
spec: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-play-000
  name: api-play-000
  namespace: microservice-mesh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-play-000
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-play-000
      name: api-play-000
      namespace: microservice-mesh
    spec:
      containers:
        - args:
            - -config-file
            - /etc/config/config.yaml
          image: ghcr.io/lahabana/api-play:main
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
          name: app
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
          resources:
            limits:
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 32Mi
          volumeMounts:
            - mountPath: /etc/config
              name: config
      volumes:
        - configMap:
            name: api-play-000
          name: config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-play-000
  name: api-play-000
  namespace: microservice-mesh
spec:
  ports:
    - appProtocol: http
      name: api
      port: 8080
      targetPort: 8080
  selector:
    app: api-play-000
---
apiVersion: v1
data:
  config.yaml: |-
    {
      "apis": [
        {
          "conf": {
            "body": "I am Service 0 and I have 2 replicas",
            "call": [
              {
                "url": "http://api-play-001.microservice-mesh.svc.8080.mesh:80/api/dynamic/microservice_mesh"
              },
              {
                "url": "http://api-play-002.microservice-mesh.svc.8080.mesh:80/api/dynamic/microservice_mesh"
              }
            ]
          },
          "path": "microservice_mesh"
        }
      ]
    }
kind: ConfigMap
metadata:
  labels:
    app: api-play-000
  name: api-play-000
  namespace: microservice-mesh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-play-001
  name: api-play-001
  namespace: microservice-mesh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-play-001
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-play-001
      name: api-play-001
      namespace: microservice-mesh
    spec:
      containers:
        - args:
            - -config-file
            - /etc/config/config.yaml
          image: ghcr.io/lahabana/api-play:main
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
          name: app
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
          resources:
            limits:
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 32Mi
          volumeMounts:
            - mountPath: /etc/config
              name: config
      volumes:
        - configMap:
            name: api-play-001
          name: config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-play-001
  name: api-play-001
  namespace: microservice-mesh
spec:
  ports:
    - appProtocol: http
      name: api
      port: 8080
      targetPort: 8080
  selector:
    app: api-play-001
---
apiVersion: v1
data:
  config.yaml: |-
    {
      "apis": [
        {
          "conf": {
            "body": "I am Service 1 and I have 2 replicas",
            "call": []
          },
          "path": "microservice_mesh"
        }
      ]
    }
kind: ConfigMap
metadata:
  labels:
    app: api-play-001
  name: api-play-001
  namespace: microservice-mesh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-play-002
  name: api-play-002
  namespace: microservice-mesh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-play-002
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-play-002
      name: api-play-002
      namespace: microservice-mesh
    spec:
      containers:
        - args:
            - -config-file
            - /etc/config/config.yaml
          image: ghcr.io/lahabana/api-play:main
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
          name: app
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
          resources:
            limits:
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 32Mi
          volumeMounts:
            - mountPath: /etc/config
              name: config
      volumes:
        - configMap:
            name: api-play-002
          name: config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-play-002
  name: api-play-002
  namespace: microservice-mesh
spec:
  ports:
    - appProtocol: http
      name: api
      port: 8080
      targetPort: 8080
  selector:
    app: api-play-002
---
apiVersion: v1
data:
  config.yaml: |-
    {
      "apis": [
        {
          "conf": {
            "body": "I am Service 2 and I have 2 replicas",
            "call": [
              {
                "url": "http://api-play-003.microservice-mesh.svc.8080.mesh:80/api/dynamic/microservice_mesh"
              }
            ]
          },
          "path": "microservice_mesh"
        }
      ]
    }
kind: ConfigMap
metadata:
  labels:
    app: api-play-002
  name: api-play-002
  namespace: microservice-mesh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-play-003
  name: api-play-003
  namespace: microservice-mesh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-play-003
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-play-003
      name: api-play-003
      namespace: microservice-mesh
    spec:
      containers:
        - args:
            - -config-file
            - /etc/config/config.yaml
          image: ghcr.io/lahabana/api-play:main
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
          name: app
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
          resources:
            limits:
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 32Mi
          volumeMounts:
            - mountPath: /etc/config
              name: config
      volumes:
        - configMap:
            name: api-play-003
          name: config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-play-003
  name: api-play-003
  namespace: microservice-mesh
spec:
  ports:
    - appProtocol: http
      name: api
      port: 8080
      targetPort: 8080
  selector:
    app: api-play-003
---
apiVersion: v1
data:
  config.yaml: |-
    {
      "apis": [
        {
          "conf": {
            "body": "I am Service 3 and I have 2 replicas",
            "call": []
          },
          "path": "microservice_mesh"
        }
      ]
    }
kind: ConfigMap
metadata:
  labels:
    app: api-play-003
  name: api-play-003
  namespace: microservice-mesh
---
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: edge-gateway
  namespace: microservice-mesh
spec:
  replicas: 2
  serviceType: LoadBalancer
  tags:
    kuma.io/service: edge-gateway
---
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
metadata:
  name: edge-gateway
mesh: default
spec:
  selectors:
    - match:
        kuma.io/service: edge-gateway
  conf:
    listeners:
      - port: 80
        protocol: HTTP
---
apiVersion: kuma.io/v1alpha1
kind: MeshHTTPRoute
metadata:
  name: api-play-000
  namespace: kong-mesh-system
spec:
  targetRef:
    kind: MeshGateway
    name: edge-gateway
  to:
    - targetRef:
        kind: Mesh
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          default:
            filters:
              - type: URLRewrite
                urlRewrite:
                  path:
                    type: ReplacePrefixMatch
                    replacePrefixMatch: /api/dynamic/microservice_mesh
            backendRefs:
              - kind: MeshService
                name: api-play-000_microservice-mesh_svc_8080
```
