### ISSUE TITLE
Missing support for http2 in kuma-sidecar (envoy)

### ISSUE THREAD

**Issue by caribru** [kumahq/kuma#889]
### Summary

Looks like kuma dataplane is missing L7 support for http2/grpc upstream/envoy clusters.

Per the cncf proposal it looks like its coming. 
https://github.com/cncf/toc/issues/436 

Note: I was unable to create a work around with proxy-template + mtls which would be a blocker for us to go to production with kuma. 

### Steps To Reproduce

1. Default kuma mesh install with/without mtls
2. Create fe + be grpc application and deploy to default mesh, ensure side cars are created
3. Confirm dataplane autocreated and default protocol for your grpc port is "tcp"
4. Send traffic, should work.
5. Annotate service with 9080.service.kuma.io/protocol: http
6. Send traffic, should fail depending on your application. our case jvm + netty reports: io.netty.handler.codec.http2.Http2Exception: Unexpected HTTP/1.x request: POST /xxx.yyy/zzz

### Additional Details & Logs
- Tested on kuma 0.5.1 and 0.6.0
- By turning off mtls and adding the proxy-template below I can get L7 grpc loadbalancing working with mtls turned off. 

It looks like the inbound and outbound listeners need the alpn_protocols field set to h2 with mtls activated. I couldn't figure out a sustainable way to override the listeners (named with podIP).

```
apiVersion: kuma.io/v1alpha1
kind: ProxyTemplate
mesh: default
metadata:
  namespace: default
  name: grpc-services
spec:
  selectors:
    - match:
        service: '*'
  conf:
    imports:
      - default-proxy

    resources:
      - name: localhost:9080
        version: v1
        resource: |
          '@type': type.googleapis.com/envoy.api.v2.Cluster
          connectTimeout: 5s
          name: localhost:9080
          http2_protocol_options: {}
          loadAssignment:
            clusterName: localhost:9080
            endpoints:
            - lbEndpoints:
              - endpoint:
                  address:
                    socketAddress:
                      address: 127.0.0.1
                      portValue: 9080
          type: STATIC
      - name: backend_default_svc_9080
        version: v1
        resource: |
          '@type': type.googleapis.com/envoy.api.v2.Cluster
          connectTimeout: 5s
          name: backend_default_svc_9080
          http2_protocol_options: {}
          type: EDS
          eds_cluster_config:
            eds_config:
              ads: {}
      - name: frontend_default_svc_9080
        version: v1
        resource: |
          '@type': type.googleapis.com/envoy.api.v2.Cluster
          connectTimeout: 5s
          name: frontend_default_svc_9080
          http2_protocol_options: {}
          type: EDS
          eds_cluster_config:
            eds_config:
              ads: {}
```
