### ISSUE TITLE
Extend the dataplane model to allow for arbitrary service IP

### ISSUE THREAD

**Issue by nickolaev** [kumahq/kuma#891]
### Summary

When generating the Static cluster for the Inbound, we have ahardoced assumption that the service is available at `127.0.0.1` and a particular port specified in the Inbound `servicePort` field:

https://github.com/Kong/kuma/blob/master/pkg/xds/generator/inbound_proxy_generator.go#L33

```go
cluster, err := envoy_clusters.NewClusterBuilder().
	Configure(envoy_clusters.StaticCluster(localClusterName, "127.0.0.1", endpoint.WorkloadPort)).
	Build()
```

However, when the DP is used in Universal mode, there might be a case where the service and the DP run in different netns, containers, VMs, or even physical servers. In such cases, the assumption of `127.0.0.1` will not be true and is a limitation.

We can extend the data plane model for such use-cases, where more flexibility regarding the service address is needed with an optional field in the Inbound, e.g. `serviceIP`. The extended dataplane will look like this:

```yaml
type: Dataplane
mesh: default
name: redis-1
networking:
  address: 192.168.0.1
  inbound:
  - port: 9000
    servicePort: 6379
    serviceIP: 192.168.0.2
    tags:
      service: redis
```

NOTE: with envoy static clusters (which we create for the inbound listeners), we should use IP. DNS resolvable names are not supported.
