### ISSUE TITLE
Kubernetes YAML example for HealthCheck kind is invalid

### ISSUE THREAD

**Issue by arctiqjacob** [kumahq/kuma#893]
### Summary

When I tried to deploy a HealthCheck in my Kubernetes cluster with the following example [here](https://kuma.io/docs/0.6.0/policies/health-check/#usage), I get the following errors:
```
The HealthCheck "proxy-to-random-sports-team" is invalid: 
* spec.conf.interval: must have a positive value
* spec.conf.timeout: must have a positive value
* spec.conf.unhealthyThreshold: must have a positive value
* spec.conf.healthyThreshold: must have a positive value
```

I am not sure if I need to specify those features there as well plus in my `activeChecks` and `passiveChecks`. Also, in the docs, `mesh: default` is defined twice in the Kubernetes YAML.

### Steps To Reproduce

1. Apply the example health-check in the above documentation to a Kubernetes cluster
2. See error from Kubernetes

Here is the exact manifest I am using:
Not Working:
```YAML
apiVersion: kuma.io/v1alpha1
kind: HealthCheck
mesh: default
metadata:
  namespace: kuma-system
  name: proxy-to-random-sports-team
spec:
  sources:
  - match:
      service: kong-proxy
  destinations:
  - match:
      service: random-sports-team
  conf:
    activeChecks:
      interval: 10s
      timeout: 2s
      unhealthyThreshold: 3
      healthyThreshold: 1
    passiveChecks:
      unhealthyThreshold: 3
      penaltyInterval: 5s
```

Working:
```YAML
kubectl apply -f - <<EOF
apiVersion: kuma.io/v1alpha1
kind: HealthCheck
mesh: default
metadata:
  namespace: kuma-system
  name: proxy-to-random-sports-team
spec:
  sources:
  - match:
      service: kong-proxy
  destinations:
  - match:
      service: random-sports-team
  conf:
    interval: 10s
    timeout: 2s
    unhealthyThreshold: 3
    healthyThreshold: 1
EOF
```

### Additional Details & Logs

- Version: Kuma v0.6.0 running on kubernetes
- Error logs: Posted Above
- Configuration: Default Kubernetes 
- Platform and Operating System: GKE v1.16.8-gke.6
