### ISSUE TITLE
confusing composition of MeshLoadBalancingStrategy policies

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9077]
### What happened?

Here are my policies:

```
type: MeshLoadBalancingStrategy
mesh: default
name: allow-api-play-004
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: MeshService
        name: api-play-004_microservice-mesh_svc_8080
      default:
        localityAwareness:
          crossZone:
            failover:
              - to:
                  type: Any
---
type: MeshLoadBalancingStrategy
mesh: default
name: failover-gw
spec:
  targetRef:
    kind: MeshGateway
    name: edge-gateway
  to:
    - targetRef:
        kind: Mesh
      default:
        localityAwareness:
          crossZone:
            failover:
              - from:
                  zones:
                    - us-east
                    - us-west
                to:
                  type: Only
                  zones:
                    - us-east
                    - us-west
              - from:
                  zones:
                    - europe-west
                to:
                  type: Only
                  zones:
                    - europe-west
                    - us-east
            failoverThreshold:
              percentage: 99
---
type: MeshLoadBalancingStrategy
mesh: default
name: no-failover
spec:
  targetRef:
    kind: Mesh
  to:
    - targetRef:
        kind: Mesh
      default:
        localityAwareness:
          crossZone:
            failover:
              - to:
                  type: None
```

What I see in the rules api:

```json
   "toRules": [
    {
     "conf": {
      "localityAwareness": {
       "crossZone": {
        "failover": [
         {
          "from": {
           "zones": [
            "us-east",
            "us-west"
           ]
          },
          "to": {
           "type": "Only",
           "zones": [
            "us-east",
            "us-west"
           ]
          }
         },
         {
          "from": {
           "zones": [
            "europe-west"
           ]
          },
          "to": {
           "type": "Only",
           "zones": [
            "europe-west",
            "us-east"
           ]
          }
         }
        ],
        "failoverThreshold": {
         "percentage": 99
        }
       }
      }
     },
     "matchers": [
      {
       "key": "kuma.io/service",
       "not": false,
       "value": "api-play-004_microservice-mesh_svc_8080"
      }
     ],
     "origin": [
      {
       "mesh": "default",
       "name": "allow-api-play-004",
       "type": "MeshLoadBalancingStrategy"
      },
      {
       "mesh": "default",
       "name": "failover-gw",
       "type": "MeshLoadBalancingStrategy"
      },
      {
       "mesh": "default",
       "name": "no-failover",
       "type": "MeshLoadBalancingStrategy"
      }
     ]
    },
    {
     "conf": {
      "localityAwareness": {
       "crossZone": {
        "failover": [
         {
          "from": {
           "zones": [
            "us-east",
            "us-west"
           ]
          },
          "to": {
           "type": "Only",
           "zones": [
            "us-east",
            "us-west"
           ]
          }
         },
         {
          "from": {
           "zones": [
            "europe-west"
           ]
          },
          "to": {
           "type": "Only",
           "zones": [
            "europe-west",
            "us-east"
           ]
          }
         }
        ],
        "failoverThreshold": {
         "percentage": 99
        }
       }
      }
     },
     "matchers": [
      {
       "key": "kuma.io/service",
       "not": true,
       "value": "api-play-004_microservice-mesh_svc_8080"
      }
     ],
     "origin": [
      {
       "mesh": "default",
       "name": "failover-gw",
       "type": "MeshLoadBalancingStrategy"
      },
      {
       "mesh": "default",
       "name": "no-failover",
       "type": "MeshLoadBalancingStrategy"
      }
     ]
    }
   ],
   "type": "MeshLoadBalancingStrategy",
   "warnings": []
}
```

Or graphically rendered:
<img width="1586" alt="Screenshot 2024-01-30 at 16 40 04" src="https://github.com/kumahq/kuma/assets/702355/58fcd0d4-5199-40bb-96dd-5d1438ccfb6f">

I'd expect `kuma.io/service:api-play-004_microservice-mesh_svc_8080` to still have `type: Any` no?

**Comment by lahabana** [comment]
It works if I change `failover-gw` to use `proxyTypes` see: 
```yaml
type: MeshLoadBalancingStrategy
mesh: default
name: failover-gw
spec:
  targetRef:
    kind: Mesh
    proxyTypes:
      - Gateway
  to:
    - targetRef:
        kind: Mesh
      default:
        localityAwareness:
          crossZone:
            failover:
              - from:
                  zones:
                    - us-east
                    - us-west
                to:
                  type: Only
                  zones:
                    - us-east
                    - us-west
              - from:
                  zones:
                    - europe-west
                to:
                  type: Only
                  zones:
                    - europe-west
                    - us-east
            failoverThreshold:
              percentage: 99
```

My understanding is that `kind: MeshGateway` is more specific so it creates a more specific rule and the `to` in it is a very open targetRef (`kind: Mesh`).
