### ISSUE TITLE
Prometheus not able to scrape the data-plane metrics endpoints on Data Plane Proxies

### ISSUE THREAD

**Issue by gsadhani** [kumahq/kuma#9108]
### What happened?

Kuma version: v2.6.0
Prometheus version: v2.48.1

I enabled metrics for the mesh using the following configuration: 

```
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: platform
  namespace: kuma-system
spec:
  mtls:
    enabledBackend: ca-1
    backends:
      - name: ca-1
        type: builtin
  logging:
    defaultBackend: file
    backends:
    - name: file
      type: file
      conf:
        path: /dev/stdout
  metrics:
    backends:
    - conf:
        path: /metrics
        port: 5670
        tags:
          kuma.io/service: dataplane-metrics
        tls:
          mode: activeMTLSBackend
      name: prometheus-1
      type: prometheus
    enabledBackend: prometheus-1
```

The prometheus server is part of the same mesh and I configured a prometheus scrape job as follows:
```
      - job_name: 'kuma-dataplanes'
        scrape_interval: "1m"
        relabel_configs:
        - source_labels:
          - __meta_kuma_mesh
          regex: "(.*)"
          target_label: mesh
        - source_labels:
          - __meta_kuma_dataplane
          regex: "(.*)"
          target_label: dataplane
        - source_labels:
          - __meta_kuma_service
          regex: "(.*)"
          target_label: service
        - action: labelmap
          regex: __meta_kuma_label_(.+)
        - source_labels:
          - k8s_kuma_io_name
          regex: "(.*)"
          target_label: pod
        - source_labels:
          - k8s_kuma_io_namespace
          regex: "(.*)"
          target_label: namespace
        kuma_sd_configs:
        - server: http://kuma-control-plane.kuma-system.svc.cluster.local:5676
```

The job fails to scrape pods in the mesh with the following error: 
```
Get "http://100.64.209.56:5670/metrics": EOF
```

I checked the rbac on the prometheus listener and seems like there is no issues with traffic permissions: 
```
                    {
                      "name": "envoy.filters.network.rbac",
                      "typedConfig": {
                        "@type": "type.googleapis.com/envoy.extensions.filters.network.rbac.v3.RBAC",
                        "rules": {
                          "policies": {
                            "metrics-permissions": {
                              "permissions": [
                                {
                                  "any": true
                                }
                              ],
                              "principals": [
                                {
                                  "any": true
                                }
                              ]
                            }
                          }
                        },
                        "statPrefix": "kuma_metrics_prometheus."
                      }
                    },
```

Am I missing something? Any pointers will be super helpful!
