### ISSUE TITLE
Disabling IPv6 Annotation at Deployment Spec

### ISSUE THREAD

**Issue by ravish-kumar-maersk** [kumahq/kuma#9121]
### What happened?

We are using Kuma 2.4.1 in multi-zone deployment. 
Global CP is hosted in AKS.

A managed k8s is created using Azure VMs and added as a zone. It only uses IPv4. 

So per the [documentation](https://kuma.io/docs/2.4.x/production/dp-config/ipv6/#disabling-ipv6), need to disable IPv6 from DP config.

We are applying the below annotation at the "Deployment" level but it's **NOT** getting applied to Pod. 
`kuma.io/transparent-proxying-inbound-v6-port: "0"`

Need to add the annotation specifically at Pod Spec.  

Is this expected behavior?? 

Deployment Spec -- 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  namespace: kuma-demo
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      annotations:
        kuma.io/transparent-proxying-inbound-v6-port: "0"
      labels:
        app: app2
        kuma.io/sidecar-injection: enabled
    spec:
      containers:
      - name: demo
        image: xxxxxxxx.azurecr.io/demo
```
