### ISSUE TITLE
Default gateway meshtimeout is a MeshSubset

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9149]
### What happened?

```yaml
type: MeshTimeout
mesh: default
name: mesh-gateways-timeout-all-default
spec:
  targetRef:
    kind: MeshSubset
    proxyTypes:
      - Gateway
  to:
    - targetRef:
        kind: Mesh
      default:
        idleTimeout: 1h0m0s
        http:
          streamIdleTimeout: 5s
  from:
    - targetRef:
        kind: Mesh
      default:
        idleTimeout: 5m0s
        http:
          streamIdleTimeout: 5s
          requestHeadersTimeout: 500ms
```

I think it should be a Mesh as this makes this very hard to override with other policies...
