### ISSUE TITLE
Introduce `kind: Service` for k8s

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9150]
### Description

When using k8s we could create a fake kind which works for k8s:

```
targetRef:
  kind: Service
  name: my-svc
  port: 8080
  namespace: my-namespace
```

This can be directly expanded to: `kind: MeshService my-svc_my-namespace_svc_8080`
This would make the k8s UX even nicer.

Once question is when it comes to ordering, we could potentially consider this just a MeshService (it's just some sugar coating).

Also do we tolerate not setting a port and it works for all ports of a service?
