### ISSUE TITLE
odd behaviour with multiple policies with same top level targetRef

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9151]
### What happened?

I've created a branch with a test Case: https://github.com/lahabana/kuma/commit/62c17a5c0bc8a5c5ac9061c9f32738322edba538

The idea is to have multiple policies with the same top level targetRef but different `to` targetRefs.

One is at Mesh and the other is MeshService.
What happens is that we sort them by policy name and completely lose the `meshService` specific entry.

I believe this is not what a user would expect. At the same level we should sort lexicography but also by kind.

So instead of having an intermediary representation:

```yaml
    - targetRef: # from mesh-timeout-all-default
        kind: Mesh
      default:
        connectionTimeout: 5s
        idleTimeout: 1h0m0s
        http:
          requestTimeout: 15s
          streamIdleTimeout: 30m0s
    - targetRef: # from mesh-timeout-1
        kind: Mesh
      default:
        http:
          requestTimeout: 1s
    - targetRef: # from mesh-timeout-4
        kind: MeshService
        name: api-play-002_microservice-mesh_svc_8080
      default:
        http:
          requestTimeout: 3s
```

It should be:

```yaml
    - targetRef: # from mesh-timeout-4
        kind: MeshService
        name: api-play-002_microservice-mesh_svc_8080
      default:
        http:
          requestTimeout: 3s
    - targetRef: # from mesh-timeout-all-default
        kind: Mesh
      default:
        connectionTimeout: 5s
        idleTimeout: 1h0m0s
        http:
          requestTimeout: 15s
          streamIdleTimeout: 30m0s
    - targetRef: # from mesh-timeout-1
        kind: Mesh
      default:
        http:
          requestTimeout: 1s
```

I'm not sure if it's a bug or if we're diverging from the design we already thought about
