### ISSUE TITLE
MeshGateway error with MeshTCPRoute

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9154]
### What happened?

I'm hitting:

```
2024-02-06T19:43:16.748Z	ERROR	xds-server.dataplane-sync-watchdog	OnTick() failed	{"dataplaneKey": {"Mesh":"default","Name":"tcp-gateway-86b988965-kxbbr.microservice-mesh"}, "error": "interface conversion: interface {} is v1alpha1.Rule, not v1alpha1.RuleConf", "errorVerbose": "interface conversion: interface {} is v1alpha1.Rule, not v1alpha1.RuleConf\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick.func1\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/util/watchdog/watchdog.go:62\nruntime.gopanic\n\truntime/panic.go:914\nruntime.panicdottypeE\n\truntime/iface.go:263\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.GenerateEnvoyRouteEntries\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/gateway.go:79\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.sortRulesToHosts\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go:185\ngithub.com/kumahq/kuma/pkg/plugins/policies/core/xds/meshroute.CollectListenerInfos\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/core/xds/meshroute/gateway.go:98\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.ApplyToGateway\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go:122\ngithub.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.plugin.Apply\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go:58\ngithub.com/kumahq/kuma/pkg/plugins/policies/core/generator.generator.Generate\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/core/generator/generator.go:23\ngithub.com/kumahq/kuma/pkg/xds/generator/core.CompositeResourceGenerator.Generate\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/generator/core/resource_generator.go:22\ngithub.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateProfileSource).Generate\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/generator/proxy_template.go:76\ngithub.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateGenerator).Generate\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/generator/proxy_template.go:28\ngithub.com/kumahq/kuma/pkg/xds/server/v3.(*TemplateSnapshotGenerator).GenerateSnapshot\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/server/v3/reconcile.go:168\ngithub.com/kumahq/kuma/pkg/xds/server/v3.(*reconciler).Reconcile\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/server/v3/reconcile.go:55\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncDataplane\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/sync/dataplane_watchdog.go:148\ngithub.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).Sync\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/sync/dataplane_watchdog.go:79\ngithub.com/kumahq/kuma/pkg/xds/sync.(*dataplaneWatchdogFactory).New.func2\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/sync/dataplane_watchdog_factory.go:43\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/util/watchdog/watchdog.go:70\ngithub.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start\n\tgithub.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/util/watchdog/watchdog.go:40\nruntime.goexit\n\truntime/asm_amd64.s:1650"}
```

When applying:
```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: tcp-gateway
  namespace: microservice-mesh
  labels:
    kuma.io/origin: zone
spec:
  replicas: 1
  serviceType: LoadBalancer
  tags:
    kuma.io/service: tcp-gateway
---
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
metadata:
  name: tcp-gateway
  labels:
    kuma.io/origin: zone
mesh: default
spec:
  selectors:
    - match:
        kuma.io/service: tcp-gateway
  conf:
    listeners:
      - port: 90
        protocol: TCP
---
apiVersion: kuma.io/v1alpha1
kind: MeshTCPRoute
metadata:
  name: tcp-gateway
  namespace: kong-mesh-system
  labels:
    kuma.io/origin: zone
spec:
  targetRef:
    kind: MeshGateway
    name: tcp-gateway
  to:
    - targetRef:
        kind: Mesh
      rules:
        - default:
            backendRefs:
              - kind: MeshService
                name: api-play-001_microservice-mesh_svc_8080
```

Pretty print of the stacktrace;
```
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/util/watchdog/watchdog.go:62
runtime.gopanic
	runtime/panic.go:914
runtime.panicdottypeE
	runtime/iface.go:263
github.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.GenerateEnvoyRouteEntries
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/gateway.go:79
github.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.sortRulesToHosts
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go:185
github.com/kumahq/kuma/pkg/plugins/policies/core/xds/meshroute.CollectListenerInfos
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/core/xds/meshroute/gateway.go:98
github.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.ApplyToGateway
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go:122
github.com/kumahq/kuma/pkg/plugins/policies/meshtcproute/plugin/v1alpha1.plugin.Apply
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go:58
github.com/kumahq/kuma/pkg/plugins/policies/core/generator.generator.Generate
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/plugins/policies/core/generator/generator.go:23
github.com/kumahq/kuma/pkg/xds/generator/core.CompositeResourceGenerator.Generate
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/generator/core/resource_generator.go:22
github.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateProfileSource).Generate
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/generator/proxy_template.go:76
github.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateGenerator).Generate
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/generator/proxy_template.go:28
github.com/kumahq/kuma/pkg/xds/server/v3.(*TemplateSnapshotGenerator).GenerateSnapshot
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/server/v3/reconcile.go:168
github.com/kumahq/kuma/pkg/xds/server/v3.(*reconciler).Reconcile
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/server/v3/reconcile.go:55
github.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncDataplane
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/sync/dataplane_watchdog.go:148
github.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).Sync
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/sync/dataplane_watchdog.go:79
github.com/kumahq/kuma/pkg/xds/sync.(*dataplaneWatchdogFactory).New.func2
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/xds/sync/dataplane_watchdog_factory.go:43
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/util/watchdog/watchdog.go:70
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start
	github.com/kumahq/kuma@v0.0.0-20240201085611-d176c947ae41/pkg/util/watchdog/watchdog.go:40
runtime.goexit
	runtime/asm_amd64.s:1650
```
