### ISSUE TITLE
Gateway listener with multiple HTTP listener do not have different httpConnectionManager stat

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9155]
### What happened?

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
metadata:
  name: double-listener-gateway
  labels:
    kuma.io/origin: zone
mesh: default
spec:
  selectors:
    - match:
        kuma.io/service: double-listener-gateway
  conf:
    listeners:
      - port: 80
        protocol: HTTP
        tags:
          port: http-80
      - port: 81
        protocol: HTTP
        tags:
          port: http-81
```

Both have the same statPrefix:

```
              "filterChains": [
                {
                  "filters": [
                    {
                      "name": "envoy.filters.network.http_connection_manager",
                      "typedConfig": {
                        "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
                        "statPrefix": "double-listener-gateway",
```

Ideally these should have the port in the stat prefix for better stats as at the moment these get rolled up together which makes it impossible to differentiate listeners per port.
