### ISSUE TITLE
allow using envoy's zone aware routing

### ISSUE THREAD

**Issue by aniket-z** [kumahq/kuma#9161]
### Description

Our current setup has the following components:
- kuma-cp running in universal mode
- hundreds of ECS services across multiple AWS ECS clusters
- all kuma-dps configured with same zone (i.e. "kuma.io/zone" is same for all dataplanes)

Now, we want to use [envoy's zone aware routing feature](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/zone_aware) to reduce our inter-AZ network cost

We are aware that kuma supports [locality-aware-routing](https://github.com/kumahq/kuma/blob/master/docs/madr/decisions/031-locality-aware-load-balancing.md) but there it seems we are configuring routing using [envoy's priority based load balancing](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/priority) rather than using [envoy's zone aware routing feature](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/zone_aware).

Consider a scenario where source service calls destination service and source service has 4 tasks in zone A and 1 task in zone B but destination service has 1 task in zone A and 4 tasks in zone B. Here, if we use kuma's locality aware routing, from what I have understood, it seems that traffic on all tasks of destination service would not be same (and thus CPU % would not be same for all tasks) whereas if we were to use envoy's zone aware routing throughput per task of destination service (and thus the CPU%) would be same as it does routing taking zone level task count of both source & destination service in account. Please correct me if I have misunderstood envoys' zone aware routing or kuma's locality aware routing and if the problem I have described is not valid?

Is there any way we could use envoy's zone aware routing feature with kuma? We don't want to change kuma.io/zone as that would require us to setup kuma's zone ingress & egress and we don't want to introduce an extra hop (and thus extra cost & latency) and an extra component into our system. Please suggest how should we proceed here

**Comment by lukidzi** [comment]
Hi, I think the thing you want to achieve can be done with Kuma by using https://kuma.io/docs/2.6.x/policies/meshloadbalancingstrategy/#disable-cross-zone-traffic-and-prioritize-traffic-the-dataplanes-on-the-same-node-and-availability-zone

First you need to add a tag to your dataplane in the same availability zone. 

e.g: 
```yaml
type: Dataplane
mesh: default
name: { { name } }
networking:
  address: { { address } }
  inbound:
    - port: 8000
      servicePort: 80
      tags:
        kuma.io/service: backend
        kuma.io/protocol: HTTP
        kuma.io/availability-zone: zone1
```

this `kuma.io/availability-zone: az-1` is an example and you can add different one to the dataplanes in the same location.
When your dataplanes are tagged you need to create a policy:
```yaml
type: MeshLoadBalancingStrategy
name: local-zone-affinity-backend
mesh: mesh-1
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: MeshService
      name: backend
    default:
      localityAwareness:
        localZone:
          affinityTags:
          - key: kuma.io/availability-zone
             weight: 1000
  ```

in this case, most of the requests will be routed to the dataplanes with the same value of  `kuma.io/availability-zone` tag.

https://kuma.io/docs/2.6.x/policies/meshloadbalancingstrategy/#configuring-localityaware-load-balancing-for-traffic-within-the-same-zone
