### ISSUE TITLE
Support `from[].targetRef.kind: MeshGateway` in `MeshTrafficPermission`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9185]
### Description

Tried:

```shell
echo "
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  namespace: kuma-system
  name: demo-app
spec:
  targetRef:
    kind: MeshService
    name: demo-app_kuma-demo_svc_5000
  from:
    - targetRef:
        kind: MeshGateway
        name: my-gateway
      default:
        action: Allow
" | kubectl apply -f -
The MeshTrafficPermission "demo-app" is invalid: spec.from[0].targetRef.kind: value is not supported
```

So I had to use:

```shell
echo "
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  namespace: kuma-system
  name: demo-app
spec:
  targetRef:
    kind: MeshService
    name: demo-app_kuma-demo_svc_5000
  from:
    - targetRef:
        kind: MeshService
        name: edge-gateway
      default:
        action: Allow
" | kubectl apply -f -
meshtrafficpermission.kuma.io/demo-app created
```

MeshGateway is quite useful in this case and should likely be preferred.

**Comment by michaelbeaumont** [comment]
Wasn't this reverted? https://github.com/kumahq/kuma/pull/9359

**Comment by lahabana** [comment]
Why did we decide to not go with MeshGateway? Was it simply because we can't really tell which listener traffic is coming from?

**Comment by lukidzi** [comment]
`MeshGateway` allows you to select many different dataplanes. It's a bit strange that we can have different sets of dataplanes with different names matching the same listener.

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshGateway
mesh: default
metadata:
  name: edge-gateway
spec:
  selectors:
    - match:
        kuma.io/service: edge-gateway
    - match:
        kuma.io/service: other-gateway
        kuma.io/version: v2
  conf:
    listeners:
      - port: 8080
        protocol: HTTP
        hostname: foo.example.com
        tags:
          vhost: foo.example.com
      - port: 8080
        protocol: HTTP
        hostname: bar.example.com
        tags:
          vhost: bar.example.com
```
When we have a policy:

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
...
  from:
    - targetRef:
        kind: MeshGateway
        name: edge-gateway
```

we map the matching to RBAC rules which matches 

```
    - match:
        kuma.io/service: edge-gateway
    - match:
        kuma.io/service: other-gateway
        kuma.io/version: v2
```

I think we don't match the exact listener but we match a data plane identity based on tags
