### ISSUE TITLE
Charset for resources is too wide, validation is too weak for Mesh, MeshService and Zone

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#9246]
### What happened?

If you create a mesh with `.` in the name it will succeed but the DPs will fail to start.

**Comment by lahabana** [comment]
Doesn't look like it's done anywhere indeed: https://github.com/kumahq/kuma/blob/6858e83ea358fce6502ea7a05201294de50a0dae/pkg/core/resources/apis/mesh/meta_validator.go#L64-L75

**Comment by lahabana** [comment]
Ok it's broken for all resources on universal:

```yaml
 ./build/artifacts-darwin-arm64/kumactl/kumactl get meshtrafficpermission foo.dwqdw -oyaml
creationTime: "2024-02-19T15:49:31.32399Z"
mesh: default
modificationTime: "2024-02-19T15:49:31.32399Z"
name: foo.dwqdw
type: MeshTrafficPermission
from:
- default:
    action: Allow
  targetRef:
    kind: Mesh
targetRef:
  kind: Mesh
```
