### ISSUE TITLE
Service Health Probes not tracking kubernetes health probe properly, routes traffic to an unhealthy pod

### ISSUE THREAD

**Issue by NorbertGajda8** [kumahq/kuma#9289]
## Summary
Kuma-sidecar is properly running, but our app container is failing and Kuma routes traffic to this pod, even if this  container health probe (Readiness probe) is failing.

Tested on Kuma v2.3.3 and 2.5.2, same behavior. 

### Container configuration health probes
```yaml
    startupProbe:
      failureThreshold: 5
      httpGet:
        path: /health/startup
        port: 8080
      periodSeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 20
      successThreshold: 1
      tcpSocket:
        port: 8080
      timeoutSeconds: 5
    readinessProbe:
      failureThreshold: 2
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 3
```

### Pod events:
Warning  Unhealthy             11m (x2 over 11m)   kubelet                          Readiness probe failed: Get "http://10.25.12.143:9901/ready": dial tcp 10.25.12.143:9901: connect: connection refused
  Normal   UpdatedKumaDataplane  10m (x5 over 11m)   k8s.kuma.io/dataplane-generator  Updated Kuma Dataplane: xxxxxxx-v1-7d6d8f87c8-vq8cd
  Warning  Unhealthy             62s (x67 over 10m)  kubelet                          Readiness probe failed: HTTP probe failed with statuscode: 503

### Deployed pod's container configs:
Liveness:   tcp-socket :8080 delay=30s timeout=5s period=20s #success=1 #failure=3
Readiness:  http-get http://:9000/8080/ready delay=15s timeout=1s period=10s #success=3 #failure=2
Startup:    http-get http://:9000/8080/health/startup delay=0s timeout=5s period=15s #success=1 #failure=5

### Kuma applied config (health.ready is true, and no events triggered)
```yaml
❯ k describe dataplanes.kuma.io manufacturing-v1-7d6d8f87c8-vq8cd
...
API Version:  kuma.io/v1alpha1
Kind:         Dataplane
Mesh:         default
...
Spec:
  Networking:
    Address:  10.25.12.143
    Admin:
      Port:  9901
    Inbound:
      Health:
        Ready:  true
      Port:     50051
      Tags:
       ...
    Transparent Proxying:
      Redirect Port Inbound:   15006
      redirectPortInboundV6:   15010
      Redirect Port Outbound:  15001
  Probes:
    Endpoints:
      Inbound Path:  /health?plugins
      Inbound Port:  8282
      Path:          /8282/health?plugins
      Inbound Path:  /health?plugins
      Inbound Port:  8282
      Path:          /8282/health?plugins
      Inbound Path:  /ready
      Inbound Port:  8080
      Path:          /8080/ready
      Inbound Path:  /health/startup
      Inbound Port:  8080
      Path:          /8080/health/startup
    Port:            9000
Events:              <none>
```

If you need any more configuration parameter, I will gladly provide it.
