### ISSUE TITLE
having ca.crt inlined in a k8s secret doesn't work on helm instal.

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9324]
### What happened?

```
cat values.yaml
controlPlane:
  tls:
    general:
      secretName: foo
```
helm upgrade kuma kuma/kuma --create-namespace --namespace kuma-system --values values.yaml

Error: UPGRADE FAILED: execution error at (kuma/templates/cp-webhooks-and-secrets.yaml:2:5): You need to send both or neither of controlPlane.tls.general.caBundle and controlPlane.tls.general.secretName
