### ISSUE TITLE
Support for HTTP/HTTPS Otel Collector Endpoints in observability policies

### ISSUE THREAD

**Issue by codecontribu** [kumahq/kuma#9459]
### Description

When otel-collector is deployed with below receiver configuration and MeshTrace policy is configured to use grpc endpoint we can see spans in the otel collector logs and works fine. Would also like to have support for HTTP/HTTPS as well, right now when we use http endpoints we don't see any connection established as spans are not received.
 
```
  collector.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
    processors:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
```

Following works currently
```
type: MeshTrace
name: default
mesh: default
spec:
 targetRef:
   kind: Mesh
 default:
   backends:
     - type: OpenTelemetry
       openTelemetry:
         endpoint: opentelemetrycollector.otel.svc.cluster.local:4317
```

Would also like to have this working

```
type: MeshTrace
name: default
mesh: default
spec:
 targetRef:
   kind: Mesh
 default:
   backends:
     - type: OpenTelemetry
       openTelemetry:
         endpoint: http://opentelemetrycollector.otel.svc.cluster.local:4318/
```
