### ISSUE TITLE
Support single Prometheus to handle many Meshes with mTLS

### ISSUE THREAD

**Issue by nickolaev** [kumahq/kuma#946]
### Summary

Today this is possible in the following way.

Disable MTLs for kuma-dp metrics like this:

```yaml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
spec:
  metrics:
    enabledBackend: prometheus-1
    backends:
    - name: prometheus-1
      type: prometheus
      conf:
        skipMTLS: true
```
The `skipMTLS` filed ensures that mTLS is not used for the Prometheus Backend.

Change the default kuma-metrics namespace to have the annotation`kuma.io/sidecar-injection` to `disabled`:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: kuma-metrics
  annotations:
    kuma.io/sidecar-injection: disabled
```

Kill all the pods in kuma-metrics and let them restart.

We need to rethink how to handle this more elegantly.

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System
