### ISSUE TITLE
MeshTimeout doesn't fully override legacy Timeout

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#9484]
### What happened?

1. Create Timeout
```yaml
type: Timeout
mesh: default
name: timeout-to-backend
sources:
  - match:
      kuma.io/service: '*'
destinations:
  - match:
      kuma.io/service: 'backend_kuma-demo_svc_3001'
conf:
  connectTimeout: 31s
  tcp: 
    idleTimeout: 32s
  http:
    requestTimeout: 33s
    idleTimeout: 34s
    streamIdleTimeout: 35s
    maxStreamDuration: 36s
```
2. Create MeshTimeout
```yaml
type: MeshTimeout
name: timeout-global
mesh: default
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: Mesh
    default:
      connectionTimeout: 21s
      idleTimeout: 22s
      http:
        requestTimeout: 23s
        streamIdleTimeout: 25s
        maxStreamDuration: 26s
        maxConnectionDuration: 27s
```
3. Check config dump on demo-client

```json
{
  "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
  "name": "outbound:backend_kuma-demo_svc_3001",
  "virtualHosts": [
    {
      "name": "backend_kuma-demo_svc_3001",
      "domains": [
        "*"
      ],
      "routes": [
        {
          "match": {
            "prefix": "/"
          },
          "route": {
            "cluster": "backend_kuma-demo_svc_3001",
            "timeout": "33s",
            "retryPolicy": {
              "retryOn": "gateway-error,connect-failure,refused-stream",
              "numRetries": 5,
              "perTryTimeout": "16s",
              "retryBackOff": {
                "baseInterval": "0.025s",
                "maxInterval": "0.250s"
              }
            }
          }
        }
      ]
    }
  ]
}
```
```json
{
  "filters": [
    {
      "name": "envoy.filters.network.http_connection_manager",
      "typedConfig": {
        "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager",
        "statPrefix": "backend_kuma-demo_svc_3001",
        "routeConfig": {
          "name": "outbound:backend_kuma-demo_svc_3001",
          "virtualHosts": [
            {
              "name": "backend_kuma-demo_svc_3001",
              "domains": [
                "*"
              ],
              "routes": [
                {
                  "match": {
                    "prefix": "/"
                  },
                  "route": {
                    "cluster": "backend_kuma-demo_svc_3001",
                    "timeout": "23s",
                    "idleTimeout": "25s",
                    "retryPolicy": {
                      "retryOn": "gateway-error,connect-failure,refused-stream",
                      "numRetries": 5,
                      "perTryTimeout": "16s",
                      "retryBackOff": {
                        "baseInterval": "0.025s",
                        "maxInterval": "0.250s"
                      }
                    }
                  }
                }
              ]
            }
          ],
          "requestHeadersToAdd": [
            {
              "header": {
                "key": "x-kuma-tags",
                "value": "&app=kuma-demo-frontend&&env=prod&&k8s.kuma.io/namespace=kuma-demo&&k8s.kuma.io/service-name=frontend&&k8s.kuma.io/service-port=8080&&kuma.io/protocol=http&&kuma.io/service=frontend_kuma-demo_svc_8080&&kuma.io/zone=zone-1&&pod-template-hash=5f5f455864&&version=v8&"
              }
            }
          ],
          "validateClusters": false
        },
        "httpFilters": [
          {
            "name": "envoy.filters.http.router",
            "typedConfig": {
              "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
            }
          }
        ],
        "commonHttpProtocolOptions": {
          "idleTimeout": "0s"
        },
        "streamIdleTimeout": "35s",
        "requestHeadersTimeout": "0s"
      }
    }
  ]
}
```

Expected: no timeout values starting with `3`
Actual: there are `33s` and `35s` that correspond to `http.requestTimeout` and `http.streamIdleTimeout`.

**Comment by lukidzi** [comment]
I've tried to reproduce it but I saw only `http.streamIdleTimeout` not set on the listener. It is because we are setting it on the route 
```yaml
"routes": [
  {
    "match": {
      "prefix": "/"
    },
    "route": {
      "cluster": "backend_kuma-demo_svc_3001",
      "timeout": "23s",
      "idleTimeout": "25s",
      "retryPolicy": {
        "retryOn": "gateway-error,connect-failure,refused-stream",
        "numRetries": 5,
        "perTryTimeout": "16s",
        "retryBackOff": {
          "baseInterval": "0.025s",
          "maxInterval": "0.250s"
        }
      }
    }
  }
]

```

https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#route-timeouts

> The route [idle_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-idle-timeout) allows overriding of the HTTP connection manager [stream_idle_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-stream-idle-timeout) and does the same thing.
