### ISSUE TITLE
reducing touch points for a user in universal mode with global CP

### ISSUE THREAD

**Issue by sudeeptoroy** [kumahq/kuma#951]
### Summary
In large deployment scenario where many local CP connect with global CP, a user would be required to have three touch point. 
1> global CP 
2> local CP 
3> kuma-dp
This will increases the chance for misconfiguration. 
It would be great if we can configure everything from Global CP.  Global CP can then distribute only config to all connected local CPs. With local CP's XDS backed up behind a GLB kuma-cp can connect to the nearest local CP. This greatly reduces the touch points for a user. 
For Ops:
Adding new or removing local cps would be easier and seamless to the client. 
Additionally with this model requirement of database can also get limited to global CP where local CPs can be added in ephemeral mode. 

### Additional Details & Logs

- Version : 0.6 onwards

**Comment by jakubdyszkiewicz** [comment]
Can you describe a bit how do you manage your deployment process?

Right now you can apply Dataplanes on Remote and Policies on Global. You can read more about this in proposal https://github.com/kumahq/kuma/blob/master/docs/proposals/multicluster.md
The reasoning for this is true high availability deployment. If Global is down, you can still spin up and down new dataplanes and generate proper XDS (which is the most critical action for the CP).

What we had in mind is that Dataplane is applied by CI (ex. Jenkins), so when you develop an application, you put your Dataplane definition in the app repository (or infra definition for an app). Then when you deploy an app via CI, CI first takes Dataplane definition, apply it on a proper Kuma CP (CI should know which cluster to choose) and schedule application and kuma-dp to run. User should only provide Dataplane definition, to which cluster connect and on which cluster apply it seems for me like a job for CI.

## DB-less CP
It would be really challenging to get rid of the DB for the CP. We use it also for
* leader election - some tasks need to be executed only by one instance in the cluster (global/remote sync, DNS allocator etc.)
* sharing some data - dataplane insights, DNS VIP allocation, metadata of the cluster

## Potential solution that could help - DataplaneTemplate
So what we hear is that with Universal deployments sometimes it's challanging to manage `Dataplane` object, especially for dynamic environments.

As a potential solution we could introduce new object called `DataplaneTemplate`. So for example when you've got 5 instances of the same service, all Dataplanes definitions are different only by IP address. You apply one `DataplaneTemplate` (on Global, which is synced to the remotes) for all of them like this
```
type: DataplaneTemplate
name: web
mesh: default
networking:
  address: {{ address }}
  inbound:
    - port: 1234
      tags:
        kuma.io/service: web
  outbound:
    - port: 1234
      service: redis
```
and then when running `kuma-dp` you can execute it with
```
kuma-dp run --template web --name web-01 --mesh default --var address=192.168.0.1 --cp-address kuma-cp.lb.com --dataplane-token-file /var/kuma-dp
```
The result of this would be that when a dataplane connects to the remote control plane, it uses this template and creates a Dataplane object on the fly, and when it disconnects, it removes the object.

```
type: Dataplane
name: web-01
mesh: default
networking:
  address: 192.168.0.1
  inbound:
    - port: 1234
      tags:
        kuma.io/service: web
  outbound:
    - port: 1234
      service: redis
```

This way you need to define `DataplaneTemplate` only once for all of your service instances (in global CP) and then you can reuse it.

This could also help with environments like Marathon/Nomad where you don't have stable ports, so for example we could do this
```
type: DataplaneTemplate
name: web
mesh: default
networking:
  address: {{ address }}
  inbound:
    - port: {{ web-port }}
      tags:
        kuma.io/service: web
  outbound:
    - port: {{ redis-port }}
      service: redis
```

```
kuma-dp run --template web --name web-01 --mesh default --var address=192.168.0.1 --var web-port=1010 --var redis-port 2020 --cp-address kuma-cp.lb.com --dataplane-token-file /var/kuma-dp
```
->
```
type: Dataplane
name: web-01
mesh: default
networking:
  address: 192.168.0.1
  inbound:
    - port: 1010
      tags:
        kuma.io/service: web
  outbound:
    - port: 2020
      service: redis
```

What do you think @sudeeptoroy ?
