### ISSUE TITLE
MeshMetric: Policy without clientId applying to clients with explicit client IDs

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma#9628]
### What happened?

Policy without clientId applies to Prometheus servers with explicit clientId but it shouldn’t. It should only appear in the kuma-dataplanes-random, but it appears in kuma-dataplanes and kuma-dataplanes-two, too.

![image](https://github.com/kumahq/kuma/assets/5774638/c7946e81-ac5f-493d-a1ef-1c065efdec1e)

## YAMLs

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
 name: metrics-default
 namespace: kong-mesh-system
 labels:
   kuma.io/mesh: default
spec:
 targetRef:
   kind: Mesh
 default:
   backends:
   - type: Prometheus
     prometheus:
       clientId: prometheus-one
       port: 5670
       path: "/metrics"
---
apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
 name: metrics-demo-app
 namespace: kong-mesh-system
 labels:
   kuma.io/mesh: default
spec:
 targetRef:
   kind: MeshSubset
   tags:
     app: demo-app
 default:
   backends:
   - type: Prometheus
     prometheus:
       clientId: prometheus-two
       port: 5671
       path: "/metrics"
---
apiVersion: kuma.io/v1alpha1
kind: MeshMetric
metadata:
 name: metrics-redis
 namespace: kong-mesh-system
 labels:
   kuma.io/mesh: default
spec:
 targetRef:
   kind: MeshSubset
   tags:
     app: redis
 default:
   backends:
   - type: Prometheus
     prometheus:
       port: 5672
       path: "/metrics"
```
