### ISSUE TITLE
specifying dataplane network using docker container name (universal mode on docker)

### ISSUE THREAD

**Issue by ejacobhayes** [kumahq/kuma#971]
### Summary

Dataplanes must be specified with an IP address, and docker containers undergo frequent IP changes across restarts. Is it intended to recreate the dataplane each time?

If the dataplane could accept a docker name this would alleviate the need to reprovision dataplanes each time the namespace containers ip address changes

Perhaps a similar config to the following example is a use case for users with universal mode on docker.

### Steps To Reproduce
```
# cat kuma-dataplane.yml
```
```yaml
type: Dataplane
mesh: default
name: kuma-dataplane
networking:
  address: kuma-namespace
  inbound:
    - port: 9082
      servicePort: 8080
      tags:
        kuma.io/service: swagger
        kuma.io/protocol: tcp
    - port: 8181
      servicePort: 8081
      tags:
        kuma.io/service: cadvisor
        kuma.io/protocol: tcp
```

2. Provision dataplane using docker container name vs IP address
```
    # cat /srv/kuma/kuma-dataplane/kuma-dataplane.yml | kumactl apply -f -
        Error: Could not create a resource (Resource is not valid)
        * networking.address: address has to be valid IP address
```

### Additional Details & Logs

- Version: 0.7.0
- Error logs
- Configuration
- Platform and Operating System: Centos 7.7
