### ISSUE TITLE
UI is still generating Kubernetes labels instead of annotations 

### ISSUE THREAD

**Issue by arctiqjacob** [kumahq/kuma#972]
### Summary

In 0.7.x, we now have to use annotations to inject our sidecar/set the mesh to deploy into. The UI still generates the Kubernetes YAML with labels as shown below:

```YAML
echo "apiVersion: v1
kind: Namespace
metadata: 
  name: kuma-demo
  namespace: kuma-demo
  labels: 
    kuma.io/sidecar-injection: enabled
    kuma.io/mesh: default" | kubectl apply -f - && kubectl delete pod --all -n kuma-demo
```

### Steps To Reproduce

1. In the UI, create a new Dataplane and fill it out
2. The generated Kubernetes YAML has labels 

### Additional Details & Logs

- Version: 0.7.0
- Platform: GKE
