### ISSUE TITLE
Allow to reference `MeshService` in Gateway API's `HTTPRoute` as a backendRef

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#9894]
### Description

Currently we are allowing only to specify Kubernetes native services as backendRefs:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-app-1
spec:
  parentRefs:
  - name: my-gateway
  rules:
  - backendRefs:
    - name: my-service-1
      port: 8080
```
Issue is that it will allow to target only services present in the same k8s cluster as `HTTPRoute`. If you would like to allow targeting services present in different zones (in multi-zone deployments) we should allow targeting different resource types:
- We could go with [Multi Cluster Services](https://multicluster.sigs.k8s.io/concepts/multicluster-services-api/), but this effort seems dead and is experimental for the last 3 years
- We could allow targeting our `MeshService`s
  ```yaml
  apiVersion: gateway.networking.k8s.io/v1
  kind: HTTPRoute
  metadata:
    name: http-app-1
  spec:
    parentRefs:
    - name: my-gateway
    rules:
    - backendRefs:
      - group: kuma.io/v1alpha1
        kind: MeshService
        name: my-service-1
  ```
