### ISSUE TITLE
Dataplane Insights - responses acknowledge

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#994]
### Summary

Demo app with reconnection showed me this

```
  dataplaneInsight:
    mTLS:
      certificateExpirationTime: "2020-08-26T10:29:59Z"
      certificateRegenerations: 2
      lastCertificateRegeneration: "2020-08-25T10:30:00.156814200Z"
    subscriptions:
    - connectTime: "2020-08-25T09:42:32.011975300Z"
      controlPlaneInstanceId: 9b6124f3-53d1-490e-926f-a0d191187c4c
      id: 8666910a-54f9-4dfc-9ed4-a794173bc5e1
      status:
        cds:
          responsesAcknowledged: "7"
          responsesSent: "7"
        eds:
          responsesAcknowledged: "32"
          responsesSent: "16"
        lastUpdateTime: "2020-08-25T10:12:56.295622600Z"
        lds:
          responsesAcknowledged: "12"
          responsesRejected: "1"
          responsesSent: "13"
        rds:
          responsesAcknowledged: "3"
          responsesRejected: "3"
          responsesSent: "6"
        total:
          responsesAcknowledged: "54"
          responsesRejected: "4"
          responsesSent: "42"
    - connectTime: "2020-08-25T10:29:56.005928300Z"
      controlPlaneInstanceId: bb86b6ba-ff02-479b-b1ad-2c84b89cd5c1
      id: 4b9f76af-0a08-494d-b91c-8455d2785a83
      status:
        cds:
          responsesAcknowledged: "3"
          responsesSent: "2"
        eds:
          responsesAcknowledged: "28"
          responsesSent: "5"
        lastUpdateTime: "2020-08-25T10:32:03.853747400Z"
        lds:
          responsesAcknowledged: "3"
          responsesSent: "2"
        rds:
          responsesAcknowledged: "2"
          responsesSent: "1"
        total:
          responsesAcknowledged: "36"
          responsesSent: "10"
```

the
```
responsesAcknowledged: "36"
responsesSent: "10"
```
does not really make sense.

* Investigate if the version is empty after reconnection
* Investigate that we really ignoring initial DiscoveryRequest (I don't think checking ResponseNonce is enough)
