### ISSUE TITLE
Error when using HTTP/2 protocol on Inbound

### ISSUE THREAD

**Issue by nickolaev** [kumahq/kuma#997]
### Summary

An error `mismatched route reference and resource lengths: map[outbound:backend:true] != 0"` is seen in the dataplane when HTTP/2 protocol is used in the inbound.

### Steps To Reproduce

1. Start `kuma-cp` in standalone mode
2. Apply the supplied `dp-frontend.yaml` and `dp-backend.yaml`
3. Start a single `kuma-dp`
4. Observe the repeating error in the logs when envoy config is re-conciliated

### Additional Details & Logs

- Version 0.7.1
- Error logs
```
2020-08-28T11:24:13.264Z        ERROR   xds-server.reconcile    inconsistent snapshot   {"snapshot": {"Resources":[{"Version":"","Items":{"backend":{"cluster_name":"backend","endpoints":[{"lb_endpoints":[{"HostIdentifier":{"Endpoint":{"address":{"Address":{"SocketAddress":{"address":"10.128.0.54","PortSpecifier":{"PortValue":9000}}}}}},"metadata":{"filter_metadata":{"envoy.lb":{"fields":{"kuma.io/protocol":{"Kind":{"StringValue":"http2"}}}},"envoy.transport_socket_match":{"fields":{"kuma.io/protocol":{"Kind":{"StringValue":"http2"}}}}}},"load_balancing_weight":{"value":1}}]}]}}},{"Version":"","Items":{"backend":{"name":"backend","ClusterDiscoveryType":{"Type":3},"eds_cluster_config":{"eds_config":{"ConfigSourceSpecifier":{"Ads":{}}}},"connect_timeout":{"seconds":5},"http2_protocol_options":{},"LbConfig":null}}},{"Version":"","Items":{}},{"Version":"","Items":{"outbound:10.128.0.15:8000":{"name":"outbound:10.128.0.15:8000","address":{"Address":{"SocketAddress":{"address":"10.128.0.15","PortSpecifier":{"PortValue":8000}}}},"filter_chains":[{"filters":[{"name":"envoy.http_connection_manager","ConfigType":{"TypedConfig":{"type_url":"type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager","value":"EgNtaXAqDgoMZW52b3kucm91dGVyGhIKAhoAEgxvdXRib3VuZDptaXA="}}}]}],"traffic_direction":2}}},{"Version":"","Items":{}},{"Version":"","Items":null}]}, "proxyError": "json: unsupported type: xds.TrafficPermissionMap", "error": "mismatched route reference and resource lengths: map[outbound:backend:true] != 0"}
```
- Configuration
`dp-frontend.yaml`
```yaml
type: Dataplane
mesh: default
name: dp-frontend
networking:
  address: 127.0.0.1
  inbound:
  - port: 6000
    tags:
      kuma.io/service: frontend
      kuma.io/protocol: tcp
  outbound:
  - port: 9000
    address: 127.0.0.1
    tags:
      kuma.io/service: backend
```

`dp-backend.yaml`
```yaml
type: Dataplane
mesh: default
name: dp-backend
networking:
  address: 127.0.0.1
  inbound:
  - port: 9000
    servicePort: 9001
    tags:
      kuma.io/service: backend
      kuma.io/protocol: http2
```

- Platform and Operating System Linux/amd64

reported by @LukeCz
